betagouv/rdv-solidarites.fr

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_types.scss
app/assets/stylesheets/landing.scss

En attendant d'avoir un vrai design.

Switch to system fonts

---

Gemfile
Gemfile.lock
config/environments/development.rb

https://github.com/flyerhzm/bullet

Add bullet

---

app/controllers/pros_controller.rb
app/helpers/pros_helper.rb
app/views/layouts/_left_menu.html.slim
app/views/pros/_invited_pro.html.slim
app/views/pros/_pro.html.slim
app/views/pros/index.html.slim

Je n'ai pas modifié le nom du role `user`, il est toujours traduit en Utilisateur. Je sais pas si on devrait le renommer ici aussi.

Utilisateur => Professionnel

---

app/controllers/admin/evenement_types_controller.rb
app/dashboards/evenement_type_dashboard.rb
app/models/evenement_type.rb
app/views/evenement_types/index.html.slim
config/routes.rb
db/schema.rb

Evenement type dashboard

---

app/models/motif.rb
app/views/motifs/_form.html.slim
app/views/rdvs/_form.html.slim
app/views/rdvs/second_steps/new.html.slim

En fait ça n'avait pas de sens de dire que tu voulais pas plus de 0 users sur ton rdv

max_users_limit cannot be lower than 1

---

Gemfile
Gemfile.lock
app/controllers/agendas_controller.rb
app/helpers/plage_ouvertures_helper.rb
app/javascript/packs/components/calendar.js
app/models/plage_ouverture.rb
app/models/pro.rb
app/views/agendas/index.html.slim
app/views/plage_ouvertures/_form.html.slim
app/views/plage_ouvertures/index.html.slim
config/environments/development.rb
config/environments/production.rb
config/routes.rb

Par défaut une plage d'ouverture se répète toutes les semaines

Recurrence

---

Gemfile
Gemfile.lock
Procfile.dev
app/controllers/rdvs/first_steps_controller.rb
app/controllers/rdvs/second_steps_controller.rb
app/javascript/packs/components/calendar.js
app/javascript/routes.js.erb
app/views/agendas/index.html.slim
app/views/rdvs/first_steps/new.html.slim
app/views/rdvs/second_steps/new.html.slim
app/views/rdvs/third_steps/new.html.slim
config/routes.rb
package.json
yarn.lock

à merger après https://github.com/betagouv/lapin/pull/112

Workflow rdv pros

---

app/controllers/motifs_controller.rb
app/dashboards/motif_dashboard.rb
app/models/motif.rb
app/views/plage_ouvertures/_form.html.slim
app/views/rdvs/first_steps/new.html.slim
db/migrate/20190916114034_add_deleted_at_to_motifs.rb
db/migrate/20190917073101_add_index_to_deleted_at.rb
db/schema.rb
spec/factories/motif.rb
spec/models/motif_spec.rb

J'ai pas utilisé le default_scope parce que c'est de m...

Soft delete on motifs

---

app/controllers/welcome_controller.rb
app/models/creneau.rb
app/models/lieu.rb
app/models/plage_ouverture.rb
app/views/welcome/welcome_motif.html.slim
config/environments/test.rb
spec/models/creneau_spec.rb
spec/models/lieu_spec.rb
spec/models/plage_ouverture_spec.rb

User search with results 2

---

app/controllers/lieux_controller.rb
app/controllers/motifs_controller.rb
app/controllers/plage_ouvertures_controller.rb
app/javascript/packs/components/calendar.js
app/views/agendas/index.html.slim
app/views/layouts/_left_menu.html.slim
app/views/plage_ouvertures/_form.html.slim
app/views/plage_ouvertures/index.html.slim
config/brakeman.ignore
config/routes.rb
spec/controllers/lieux_controller_spec.rb
spec/controllers/motifs_controller_spec.rb
spec/controllers/plage_ouvertures_controller_spec.rb

Plage ouverture nested in organisations

---

app/controllers/absences_controller.rb
app/models/organisation.rb
app/views/absences/_form.html.slim
app/views/absences/edit.html.slim
app/views/absences/index.html.slim
app/views/agendas/index.html.slim
app/views/layouts/_left_menu.html.slim
config/routes.rb
spec/controllers/absences_controller_spec.rb

Absences nested in organisations

---

config/routes.rb

Remove unused routes for organisations

---

app/dashboards/user_dashboard.rb

fix: https://sentry.io/organizations/lapins/issues/1329274449/?project=1811205&query=is%3Aunresolved

fix Administrate users

---

app/controllers/agents/creneaux/agent_searches_controller.rb
app/controllers/agents/rdvs/third_steps_controller.rb
app/controllers/agents/rdvs_controller.rb
app/controllers/organisations_controller.rb
app/javascript/packs/components/calendar.js
app/models/rdv.rb
app/views/layouts/_left_menu.html.slim
app/views/organisations/show.html.slim
spec/controllers/agents/rdvs_controller_spec.rb
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb

à rebaser et merger après le merge de #190 
https://trello.com/c/ZIW8ISWL/160-agent-trouver-un-rdv
et 
https://trello.com/c/gk9tBjje/159-agent-consulter-son-agenda-left-menu-agenda

Fix rdv redirection

---

app/javascript/packs/application.js
app/javascript/packs/components/browser-detection.js
app/javascript/packs/landing.js
package.json
yarn.lock

https://trello.com/c/hsIkNZrr/158-ajouter-un-bandeau-navigateur-obsol%C3%A8te

add warning for old browsers

---

app/assets/stylesheets/components/_forms.scss
app/controllers/agents/users_controller.rb
app/models/user.rb
app/views/agents/users/_search.html.slim

[User] Add email in search for users

---

app/models/plage_ouverture.rb

``` js
plage_ouverture: {
end_time: 18:00, 
first_day: 2019-1201, 
lieu_id: 41, 
motif_ids: [237], 
recurrence: null, 
start_time: 09:00, 
title: Palm Beach
}
```
```ruby
start_time = Date.parse('2019-1201') # return Invalid Date --> nil
plage_ouverture.valid? == true
```
https://sentry.io/organizations/lapins/issues/1350411511/?environment=production&project=1811205&referrer=alert_email

[Sentry][Agent] Add validation on first_day presence

---

app/controllers/agents/users_controller.rb
app/policies/agent/organisation_policy.rb
app/policies/agent/user_policy.rb

@mmagn C'est vraiment ceinture bretelle car on le teste deja dans le initialize

[Agent] Link to user policy

---

app/controllers/agents/users_controller.rb
spec/controllers/agents/users_controller_spec.rb

& if user is not valid do not crash

[Agents] Create user with nil email

---

app/views/common/_header.html.slim

Suite à une remarque lors du point référent.

Corrige une faute d'orthographe sur la page d'accueil

---

app/javascript/packs/controllers/recurrence_controller.js
app/views/agents/plage_ouvertures/_form.html.slim
app/views/agents/plage_ouvertures/_recurrence.html.slim
config/environments/test.rb
spec/features/agents/agent_can_manage_recurrence_on_plage_ouverture.rb

On rollback le composant date qui introduisait un bug.
On ajoute des tests pour éviter que cela se reproduise.

[Agent][Plage Ouverture] Fix recurrence

---

app/views/agents/plage_ouvertures/index.html.slim

bug : quand on utilise back/next du navigateur la box select2 ne se met pas à jour

Fix navigation bug when Back button is used

---

app/controllers/agents/creneaux/agent_searches_controller.rb
app/models/creneau/agent_search.rb
app/views/agents/creneaux/agent_searches/_creneaux.html.slim
app/views/agents/creneaux/agent_searches/index.html.slim
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb

[Agent] [BONUS] Find creneau with multiple lieux

---

app/controllers/admin/agents_controller.rb
app/controllers/admin/application_controller.rb
app/controllers/admin/users_controller.rb
app/views/admin/agents/show.html.slim
app/views/admin/users/show.html.slim

[SuperAdmin] Virer le se logger en tant que pour le déploiement

---

config/spring.rb

https://github.com/bkeepers/dotenv/issues/316

[Dev] Fix .ENV not loaded in test and console

---

app/controllers/agents/users_controller.rb

https://sentry.io/organizations/lapins/issues/1394795896/?project=1811205&query=is%3Aunresolved

[Sentry] - [Agent][ThirdStep] Select2 ajax error on blank query 

---

app/controllers/users/rdvs_controller.rb
app/views/users/rdvs/new.html.slim
spec/controllers/users/rdvs_controller_spec.rb

En attendant de repasser sur les /lieux, voici un fix rapide

Fix old route after rollback

---

app/views/agents/agents/index.html.slim

Quick fix.
On pourrait aussi passer le service en Badge pour gagner un peu de place.

[Agent] Design pété sur le listing des agents

---

app/views/welcome/index.html.slim

Suite aux retours des référents.

[Usager][Home] Header Rend générique les services contactables dans la solution

---

public/404.html
public/500.html
public/maintenance.html

[Usager][Agent] Page 404

---

app/assets/stylesheets/components/_calendar.scss
app/javascript/packs/components/calendar.js
app/views/agents/plage_ouvertures/index.json.jbuilder
spec/controllers/agents/plage_ouvertures_controller_spec.rb

Les créneaux se chevauchent plus si les horaires ne se chevauchent pas.
Amélioration de la vue de l'événement au survol de la souris.

[Agent][Agenda] Les créneaux de RDV de 20 min se chevauchent

---

app/controllers/agents/rdvs_controller.rb
app/javascript/packs/components/calendar.js
app/views/agents/rdvs/status.js.erb

3 raffraichissements:
Changement de status
Modification du rdv
Toute les 30 secondes (pour les secretaires qui n'actualisent pas leur page)

[Agent] Rafraîchissement de l'agenda après modification d'un rdv

---

app/models/concerns/recurrence_concern.rb
app/models/plage_ouverture.rb
app/views/agents/plage_ouvertures/_form.html.slim
app/views/agents/plage_ouvertures/_recurrence.html.slim

Travail préparatoire pour simplifier la review

[Agent][Absences] Récurrence sur les absences (préparation)

---

app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/structure/_right_sidebar.scss
app/javascript/packs/components/calendar.js

[Social][Agent] Vue journée V2

---

app/controllers/agents/agents_controller.rb
app/helpers/rdvs_helper.rb
app/javascript/packs/application.js
app/views/agents/agents/show.html.slim

je suis pas fan de l'ui, qu'en pensez vous? J'ai peur d'avoir des retours : " Je ne comprends pas..."

[Agenda] Filtrer les RDV par statut

---

.env.sample
.gitignore
README.md
bin/setup

- Ajouté un `.env.sample` et modifié le `bin/setup` en conséquence.
- quelques modification de style sur le README.md
- ignore le keepass
- précise la version de ruby (?)

Readme update

---

app/controllers/sessions_controller.rb

Revert "If agent is trying to sign in as user, should be signed in as agent"
This reverts commit c0e8ce81a2c61a1aba2e847238202ce9515e7a61.

[BUG][Agent] Sign in du coté user (1/2)

---

app/helpers/motifs_helper.rb
app/models/motif.rb
app/views/agents/motifs/_form.html.slim
app/views/agents/motifs/_motif.html.slim
app/views/agents/motifs/show.html.slim
config/features.rb
config/locales/models/motif.fr.yml
spec/factories/motif.rb

linked to https://trello.com/c/0Uk03hAq/444-vad-configuration-du-motif

[VAD] configuration du motif

---

app/controllers/agents/agents_controller.rb

https://sentry.io/organizations/lapins/issues/1593419474/?environment=production&project=1811205&referrer=alert_email

[Fix] Fix empty date params

---

package-lock.json
package.json
yarn.lock

suite à l'alerte de sécurité https://github.com/advisories/GHSA-6c8f-qphg-qjgp

met à jour la lib kind-of

---

app/views/users/rdvs/_rdv.html.slim

https://trello.com/c/GZrPb6jh/596-vadusager-d%C3%A9tail-du-rdv

précise si le rendez-vous est à domicile

---

app/views/corona/_info_rdv.html.slim

encore un hack pour un département particulier. Un sujet intéressant de discussion :)

affiche un message spécifique pour le 62

---

app/controllers/stats_controller.rb
app/helpers/application_helper.rb
app/models/stat.rb
app/views/stats/_statistics.html.slim
app/views/stats/index.html.slim
config/locales/fr.yml
spec/models/stat_spec.rb

Affiche la répartition des rendez-vous par type de lieu et par semaine

[VAD] metrics

---

app/services/twilio_text_messenger.rb
app/views/rdv_mailer/_overview.html.slim
app/views/rdv_mailer/send_ics_to_user.html.slim
app/views/rdv_mailer/send_reminder.html.slim
config/locales/fr.yml
spec/services/twilio_text_messenger_spec.rb

https://trello.com/c/qv8HrKtL/593-vad-notifications-cr%C3%A9ation-modification-rappel

[VAD]  Notifications Création / Modification / Rappel

---

app/controllers/agents/users_controller.rb
app/services/duplicate_user_finder_service.rb
spec/services/duplicate_user_finder_service_spec.rb

**Enlarge duplicate finder:**
- same `email`
- same `phone_number`
- same `first_name + last_name + birth_date``
If multiple users are find, I take the one with the most rdvs
Waiting for [537](https://github.com/betagouv/rdv-solidarites.fr/pull/537) to filter duplicate on wizard.

[Doublons] Détecter les doublons

---

app/models/agent.rb
app/views/agents/rdvs/_form.html.slim

In the `agents` collection, only agents with same service `rdv.motif.service` were matched.
Leaving agents from `secretariat` even if `rdv.motif.for_secretariat == true`

[Bug][Secretariat] Problème de modification du RDV

---

app/javascript/packs/components/analytic.js

https://trello.com/c/B7nx3xh6/659-exclure-des-donn%C3%A9es-envoyer-%C3%A0-piwik

[Matomo] filtre les données de recherche

---

app/views/rdv_mailer/_overview.html.slim
spec/mailers/previews/rdv_mailer_preview.rb

linked to https://trello.com/c/YCt2zJFe/663-vadnotification-d%C3%A9faut-daffichage-adresse-dans-le-mail

fix overflow bug in send_ics mail for VAD

---

app/webpacker/components/motif-form.js

fixes https://sentry.io/organizations/lapins/issues/1620363023/?project=1811205

fix typo in motif-form.js selector

---

Gemfile
Gemfile.lock
app/views/admin/application/_navigation.html.erb

may fix sassc compilation problem
enables using custom controllers (not associated to resources)

bump administrate version from 0.13.0 to master

---

app/models/rdv.rb
app/views/agents/rdvs/show.html.slim
app/views/rdv_mailer/cancel_by_agent.html.slim

https://trello.com/c/g7EA7qqC/683-agent-retour-annulation

[Agent] Retour annulation

---

app/views/agents/relatives/show.html.slim
app/views/agents/users/show.html.slim

https://trello.com/c/GrEOzbyb/686-pourvoir-poser-un-rendez-vous-%C3%A0-partir-de-la-ficher-dun-proche-usager
https://trello.com/c/AalrVNVt/685-d%C3%A9placer-le-bouton-trouver-un-cr%C3%A9neau-en-haut-dans-la-fiche-usage

replace le bouton pour poser un rendez-vous

---

app/views/file_attente_mailer/send_notification.html.slim
app/views/rdv_mailer/_overview.html.slim
spec/mailers/previews/file_attente_mailer_preview.rb

https://trello.com/c/giRALVx0/643-notificationmail-enlever-le-motif-dans-les-mails-de-confirmation-et-de-rappels-et-file-dattente-de-rdv

[Mails] Remove motifs from mails

---

app/models/plage_ouverture.rb
app/models/plage_ouverture/ics.rb
app/models/rdv/ics.rb

Lié à
https://trello.com/c/1NK90kS3/696-ajout-dun-champs-uuid-aux-plages-douvertures
et prépare
https://trello.com/c/uBIfj7y5/695-notifications-pour-les-plages-douvertures

Ajoute un UID pour les iCal des plages d'ouverture

---

app/helpers/motifs_helper.rb
app/models/motif.rb
app/views/agents/plage_ouvertures/_form.html.slim

https://trello.com/c/2ncVyWrq/684-vad-etiquette-a-domicile-manquante-dans-les-plages-douvertures

display motif VAD badge on plage ouverture form

---

lib/tasks/piwik.rake

Ma première tentative était incomplète.
https://trello.com/c/3UBcDxUd/830-matomo-update-v2

Finalise l'exclusion des paramètres dans Matomo

---

app/blueprints/lieu_blueprint.rb
app/blueprints/plage_ouverture_blueprint.rb
app/blueprints/rdv_blueprint.rb
app/models/plage_ouverture.rb

https://trello.com/c/uBIfj7y5/695-notifications-pour-les-plages-douvertures
Je ne suis pas très satisfait/sûr des champs exposés dans cette API.
Je me demande si on doit exposer le payload iCal dans son intégralité ou pas.
Je suis très favorable à l'exposition de RRULE qui permet de faire un standard complexe mais complet.
En l'état
```json
{
"data": {
"id": 2,
"agent": {
"id": 1,
"email": "contact@rdv-solidarites.fr",
"first_name": "Johnny",
"last_name": "VALIDAY"
},
"end_time": "12:00:00",
"first_day": "2020-04-22",
"ical": "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:RDV Solidarités\r\nCALSCALE:GREGORIAN\r\nMETHOD:REQUEST\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Paris\r\nBEGIN:DAYLIGHT\r\nDTSTART:20200329T030000\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nRRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3\r …
```

Ajoute des notifications pour les plages d'ouverture

---

app/views/agents/jours_feries/index.json.jbuilder
app/webpacker/components/calendar.js

https://trello.com/c/ytxQaCIi/657-agenda-clic-sur-un-jour-feri%C3%A9

[Fix][Agenda] Clique sur un jour ferié

---

yarn.lock

fix https://github.com/betagouv/rdv-solidarites.fr/network/alert/yarn.lock/minimist/open

upgrade minimist yarn package to fix security alert

---

Makefile
scripts/deploy.rb

make deploy -> notif debut de deploy dans slack + declenchement du deploiement via le cli scalingo 
risque d'etre tres ephemere si on passe a des review apps bientot :)

added makefile and deploy script

---

Makefile

C'est sans aucune obligation. Ce sont les quelques entrées que j'utilise habituellement... Si ça ne vous dérange pas, c'est ce dont je me sert :)

ajoute des entrées dans le Makefile

---

app/controllers/agents/users_controller.rb
app/models/agent.rb
app/models/user.rb
app/views/agents/users/_form.html.slim
app/views/agents/users/show.html.slim
db/migrate/20200427093834_create_agents_users_join_table.rb
db/schema.rb

https://trello.com/c/gm9X6IN1/658-rdv-suivi-lier-lusager-%C3%A0-un-agent

Lier usage a un ou plusieurs agents (référent)

---

app/views/agents/users/_responsible_information.html.slim
app/views/agents/users/show.html.slim

Rectification d'un oubli : affichage des référents sur la page des proches.

affiche les referents sur la page des proches

---

lib/tasks/matomo.rake

* https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/SitesManager/API.php\#L636

😓 Finalise l'exclusion des paramètres dans Matomo 

---

app/webpacker/components/calendar.js

https://trello.com/c/jmKnXLdZ/849-agentagenda-rafra%C3%AEchissement-automatique

[Agent][Agenda] rafraîchissement automatique

---

scalingo.json

review apps are not created automatically yet as we still need to figure out how to handle super admin. 
however they can be created manually through scalingo dashboard for a specific PR

created scalingo.json for review apps

---

db/seeds.rb

faker causes problems for review apps as it's only in dev and test environments + it introduces unwanted randomness

improve seeds with a RDV and without faker

---

app/services/duplicate_user_finder_service.rb
spec/services/duplicate_user_finder_service_spec.rb

https://trello.com/c/rxQr4zzV/852-bug-agent-usager-pb-%C3%A0-la-cr%C3%A9ation-dun-proche

Bug [agent] [usager] pb à la création d'un proche

---

docs/update_metabase_db.sh

pas d'info sensible commitée, et c'est en pause, mais juste pour pas tout perdre si on decide de poursuivre un jour

docs to manually update the metabase DB

---

app/views/users/rdvs/_rdv.html.slim

improve cancel rdv dismiss modal ambiguous wording

---

app/webpacker/components/select2.js

https://trello.com/c/z3I45YZ1/856-agentprise-de-rdv-selection-agents-referent-dans-la-modale-dedition-usager-dans-le-flow-prise-de-rdv

charge le composant select2 dans les modals

---

app/views/mailers/users/rdv_mailer/rdv_upcoming_reminder.html.slim
spec/mailers/previews/users/rdv_mailer_preview.rb

cf https://sentry.io/organizations/lapins/issues/1660626207

fix render overview in upcoming rdv reminder mail

---

app/controllers/agent_auth_controller.rb
app/controllers/user_auth_controller.rb
app/views/agents/rdvs/show.html.slim

cf
https://trello.com/c/yFtP3xp1/862-agent-fixer-le-voir-dans-lagenda-pour-un-rdv-dun-autre-agent
and
https://trello.com/c/oFRuD9DK/861-agent-stocker-nom-prenom-dans-les-versions-des-rdvs-plutot-que-email

RDV history + separate page fixes

---

app/models/rdv.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb

https://trello.com/c/AVAA7q9I/854-bug-agent-prise-de-rdv-les-notes-libres-ne-senregistrent-pas

[bug] fix saving notes in RDV wizard flow for agents

---

app/views/mailers/common/_rdv_overview.html.slim

https://trello.com/c/zj9U9Bl5/858-agent-enlever-consignes-rdv-dans-mail-rdvcreatedstartssoon

hide rdv instructions in agents mails

---

app/views/agents/rdv_wizard_steps/step2.html.slim
app/webpacker/components/rdv_wizard_step2.js

cf https://trello.com/c/gfYBPsdQ/864-agent-bug-rechargement-lors-du-flow-de-prise-rdv

[bug] fix agents rdv wizard users reload after error

---

app/webpacker/stylesheets/components/_search_form.scss
package.json
yarn.lock

https://trello.com/c/I8Dxdjxy/855-usager-enlever-le-bouton-de-g%C3%A9olocalisation-bugg%C3%A9
j'en ai profité pour upgrader `places.js`
maintenant :

improve home address field : remove geoloc + fix overlapping clear icon

---

app/views/agents/users/_form.html.slim
app/views/agents/users/_responsible_information.html.slim

https://trello.com/c/k2XeEyJe/868-agentfiche-usager-libell%C3%A9s-diff%C3%A9rents-pour-le-champ-r%C3%A9f%C3%A9rent

repositionne le champ référent dans la fiche usager

---

app/views/users/users/_form.html.slim
spec/features/users/user_can_search_rdv_spec.rb

https://trello.com/c/A85ziBYW/875-usagerprise-de-rdv-adresse-de-la-recherche-adresse-de-lusager

[Usager][Prise de RDV] Adresse de la recherche / Adresse de l'usager

---

config/environments/production.rb

tentative de fix de l'envoi de mails depuis les review apps
ça ne fixe pas le pb :/ mais c'est quand même à prendre je pense :)

fix typo in action mailer config

---

app/views/agents/users/_form.html.slim

Agents référent => Agent(s) référent(s)
tiny wording fix asked by Elodie during demo

fix wording for agents referents in users form

---

app/views/agents/agents/show.html.slim
app/views/layouts/_left_menu.html.slim
app/views/layouts/application.html.slim
app/webpacker/components/menu.js
spec/features/agents/agent_can_crud_absences_spec.rb
spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb

cf https://trello.com/c/cn1iSHNI/375-agentagenda-perte-du-contexte-lorsque-lon-fait-une-action-pour-un-autre-agent
- menu simplifié avec regroupement planning + agenda
- liens contextuels vers plages ouvertures et absences en dessous du calendrier

[agents] improve other agent context visibility

---

db/seeds.rb

- skip callbacks sur les Plages d'ouverture et les Rdv pour eviter les mails
encore incomplet il faudrait des absences, plus de RDVs etc

Improve seeds : second orga, more lieux, more motifs

---

app/models/user.rb

simply removing a bit of dead code

remove deprecated User#valid_except_email? method

---

scripts/scale_review_app.sh

juste pour les hackers qui veulent pas aller cliquer sur le dashboard
`./scripts/scale_review_app.sh 659 down`
or
`./scripts/scale_review_app.sh 659 up`

added script to scale scalingo review apps easily

---

scripts/scale_down_all_review_apps.rb

add script to scale down all review apps easily

---

app/controllers/admin/application_controller.rb
scalingo.json

permet de mettre une variable d'env sur les review apps , 
quand presente : bypass oauth github super admin, utilise http basic auth

use basic auth for super admin auth depending on env var

---

app/helpers/application_helper.rb
app/views/agents/rdvs/_rdv_details.html.slim
app/views/agents/relatives/show.html.slim
app/views/agents/users/_responsible_information.html.slim

https://trello.com/c/4uwkCJ40/869-agentd%C3%A9tails-du-rdv-rendre-plus-visible-le-champ-notes-libres

[agent][détails du RDV] Rendre plus visible le champ "Notes libres'

---

app/lib/skip_callbacks.rb
app/models/concerns/skip_callbacks_concern.rb
spec/services/twilio_text_messenger_spec.rb

skip_callbacks is not threadsafe
cf cf https://mattpruitt.com/post/skip-callbacks/

fixing specs thread safety problem with skip_callbacks

---

app/views/corona/_info_rdv.html.slim

https://trello.com/c/FIPlIYe8/888-usager-modifier-bandeau-covid-pour-la-somme

new COVID warning special case for 80 Somme

---

app/views/agents/plage_ouvertures/index.json.jbuilder
app/views/agents/rdvs/index.json.jbuilder
app/webpacker/components/calendar.js
app/webpacker/stylesheets/components/_calendar.scss
spec/controllers/agents/plage_ouvertures_controller_spec.rb
spec/controllers/agents/rdvs_controller_spec.rb

https://trello.com/c/d0RVVlVk/453-agentagenda-affichage-des-statuts-de-rdv
De haut en bas (indeterminé/salle attente/vu/excusé/non excusé)

[agent][agenda] affichage des statuts de RDV

---

app/webpacker/components/calendar.js

https://trello.com/c/p6UeX5eV/879-bug-refresh-agenda
Je me suis appuyé sur cette discussion: https://stackoverflow.com/questions/54806006/turbolinks-5-and-setinterval-issue/54829449#54829449

[Bug] Refresh agenda

---

app/webpacker/stylesheets/application_users.scss
app/webpacker/stylesheets/components/_forms.scss
app/webpacker/stylesheets/components/_search_form.scss
app/webpacker/stylesheets/landing.scss

https://trello.com/c/kt8ywN07/874-agent-cacher-le-pin-de-geolocalisation-partout

[agent] cacher le pin de geolocalisation partout

---

app/views/devise/confirmations/new.html.slim

https://trello.com/c/MmSvkVJU/883-bug-404-apres-demande-re-envoi-verification-mail
Rails ajouté un 
```<input type="hidden" name="_method" value="patch">```

[Bug] 404 apres demande re-envoi verification mail

---

app/views/welcome/welcome_agent.html.slim

Pour rendre plus autonome les départements intéressés.

Ajoute un résumé des fonctionnalités

---

app/helpers/motifs_helper.rb
app/views/agents/motifs/_form.html.slim
app/views/agents/motifs/show.html.slim
app/views/agents/rdvs/_rdv_details.html.slim
config/features.rb

remove VAD flipper

---

app/views/welcome/welcome_departement.html.slim

https://trello.com/c/ynAdlEAM/898-usager-sur-la-phrase-de-description-de-la-homepage-ajouter-le-service-social
a tester sur https://demo-rdv-solidarites-pr707.osc-fr1.scalingo.io/departement/75?latitude=48.8546&longitude=2.3477&where=Paris+75000

add Service Social to description of departement homepage

---

docs/maintenance.html

Micro fix
Problème avec la source du logo sur la maintenance

[Fix] fix maintenance page

---

app/controllers/stats_controller.rb
app/helpers/rdvs_helper.rb
app/views/common/_header.html.slim
app/views/stats/_statistics.html.slim
app/views/stats/index.html.slim
config/routes.rb

- Ajout de 3 routes stats scopées au departement
- Ajout d'un `before_action` sur le stats_controller pour appliquer le scope aux rdvs/users du departement

[Stats] Scope stats to departement

---

app/controllers/admin/agents_controller.rb
app/controllers/agents/organisations/setup_checklists_controller.rb
app/controllers/agents/organisations_controller.rb
app/controllers/agents/passwords_controller.rb
app/controllers/application_controller.rb
app/controllers/organisations_controller.rb
app/helpers/organisations_helper.rb
app/mailers/admins/organisation_mailer.rb
app/models/agent.rb
app/models/organisation.rb
app/models/super_admin.rb
app/views/agents/organisations/index.html.slim
app/views/agents/organisations/setup_checklists/show.slim
app/views/layouts/_left_menu.html.slim
app/views/mailers/admins/organisation_mailer/new_organisation.html.slim
app/views/mailers/admins/organisation_mailer/organisation_created.html.slim
app/views/organisations/create.html.slim
app/views/organisations/new.html.slim
app/views/welcome/welcome_agent.html.slim
config/routes.rb
db/seeds.rb
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
spec/features/users/user_signs_up_and_signs_in_spec.rb
spec/mailers/previews/admins/organisation_mailer_preview.rb

https://trello.com/c/qz6bRKye/877-permettre-la-cr%C3%A9ation-dune-organisation-depuis-le-site-internet-et-proposer-un-tutoriel-de-base-pour-la-configuration

Crée un parcours pour une installation en autonomie

---

app/controllers/agents/organisations/stats_controller.rb
app/controllers/stats_controller.rb
app/models/stat.rb
app/views/stats/_statistics.html.slim
app/views/stats/index.html.slim
config/routes.rb

#N/A :sweat: 
Le premier graphique du nombre de RDV par semaine n'est pas fonctionnel sur les pages par département.
J'en ai profité pour ajouter des graphiques de déploiements #agents et #organisations  créés par semaine.

Corrige et enrichi les stats publiques

---

app/webpacker/packs/application.js

https://sentry.io/organizations/lapins/issues/1715739507/?environment=production&project=1811205&query=is%3Aunresolved

[Bug] Search BAN

---

app/webpacker/components/places-input.js

https://trello.com/c/gTCPwLIu/930-bug-ban-nom-commune

bugfix missing city infos in BAN search inputs 🙀

---

app/webpacker/components/places-input.js
app/webpacker/packs/application.js
app/webpacker/packs/controllers/versions_controller.js
package.json
yarn.lock

https://trello.com/c/bR6ukPkS/890-agent-user-r%C3%A9parer-support-ie-11-edge-18-closest-toggleattribute
- toggleAttribute n'est pas polyfilled par core-js -> utilisation de jQuery
- closest n'est pas polyfilled par core-js -> utilisation de jQuery
- fetch n'est pas polyfilled par core-js -> ajout d'un autre polyfill https://github.com/github/fetch

fixing IE11 polyfills : closest, toggleAttribute, CustomEvent

---

app/views/users/rdvs/index.html.slim
config/initializers/content_security_policy.rb

https://trello.com/c/8lG42wnh/936-usager-recueil-des-avis-avec-je-donne-mon-avis
avec « Je donne mon avis » de https://observatoire.numerique.gouv.fr/
Deux versions du bouton sont disponibles j'ai préféré le plus discret.

Ajoute un bouton pour récupérer des avis

---

app/views/layouts/_left_menu.html.slim

parametres apparaissent aussi pour agent non admin

fix scoping left menu parametres section to admins 🚩

---

app/views/agents/rdv_wizard_steps/step3.html.slim
app/views/agents/rdvs/_form.html.slim

https://trello.com/c/MbrzvSYo/932-agent-a-la-creation-de-rdv-permettre-recherche-autocompletee-des-lieux
in agent rdv wizard + in agent rdv form for updates

in agent rdv wizard, make lieu select a select2 input

---

app/helpers/users_helper.rb
app/models/motif.rb
app/models/rdv.rb
app/models/service.rb
app/views/agents/rdvs/_rdv.html.slim
db/seeds.rb

https://trello.com/c/DlPqZorv/948-agent-impression-des-rdvs-niveau-de-d%C3%A9tail-que-lon-souhaite-voir-appara%C3%AEtre

agent- Impression des RDVS

---

app/models/user.rb
app/views/agents/users/_form.html.slim
spec/models/user_spec.rb

Il manquait le cas d'un usager sur plusieurs organisation.

Patch creation proche

---

app/webpacker/components/calendar.js

Rend visible les créneaux de très courte durée

---

app/webpacker/packs/application.js
app/webpacker/packs/application_agent.js

https://trello.com/c/rbTL0OwO/969-agentusager-oeil-pour-visualiser-le-mot-de-passe-ne-fonctionne-plus

[User] L'oeil pour afficher le mot de passe ne fonctionne pas

---

app/services/send_transactional_sms_service.rb

lié à https://trello.com/c/ZQAIcRcq/828-envoyer-les-sms-avec-sendinblue
https://doc.scalingo.com/platform/app/environment#runtime-environment-variables

Explicite l'application dans le tag des SMS

---

app/helpers/users_helper.rb
app/views/agents/rdvs/_rdv.html.slim
app/views/agents/users/_responsible_information.html.slim
app/views/agents/users/show.html.slim
db/seeds.rb

https://trello.com/c/PMkqNIDR/970-affichage-des-infos-de-logement-dans-l%C3%A9dition-de-rdv

[bug] [agent] fix logement display in RDVs list

---

app/views/agents/absences/index.html.slim
app/views/agents/lieux/index.html.slim
app/views/agents/motifs/index.html.slim
app/views/agents/plage_ouvertures/index.html.slim

https://trello.com/c/vBdHTRxc/913-agent-completer-les-descriptions-des-pages-vides
facilement visible sur la review app avec ce compte : adrien@dipasquale.fr 123456

added empty instructions for first absences, lieux, motifs and plage ouvertures

---

app/dashboards/organisation_dashboard.rb

allow seeing + editing organisations.human_id from super admin

add organisations.human_id to super admin

---

app/controllers/agents/rdvs_controller.rb
app/helpers/rdvs_helper.rb
app/models/rdv.rb
app/views/agents/rdv_wizard_steps/step3.html.slim
app/views/agents/rdvs/_form.html.slim

https://trello.com/c/UN83Anmb/968-agent-lieu-de-rdv-par-d%C3%A9faut

[agent] stop selecting default lieu in RDV wizard

---

app/webpacker/administrate/index.js
app/webpacker/components/places-inputs.js
app/webpacker/packs/application.js
app/webpacker/packs/application_agent.js

simple refacto that allows having multiple addresses on a single page. not used yet, but preliminary to #774

refactor PlacesInput component to init multiple inputs per page

---

app/controllers/agents/creneaux/agent_searches_controller.rb
app/helpers/agents_helper.rb
app/helpers/creneaux_helper.rb
app/views/agents/creneaux/agent_searches/_creneau.html.slim
app/views/agents/creneaux/agent_searches/_creneaux.html.slim
app/views/agents/creneaux/agent_searches/_lieux.html.slim
app/views/agents/creneaux/agent_searches/by_lieu.js.erb
app/views/agents/creneaux/agent_searches/index.html.slim
app/views/agents/creneaux/agent_searches/index.js.erb
app/webpacker/components/agents_creneaux.js
app/webpacker/packs/application_agent.js
app/webpacker/stylesheets/application_agent.scss
app/webpacker/stylesheets/components/_creneaux.scss

Prémices du ticket : https://trello.com/c/AGzPGXNf/959-agent-les-cr%C3%A9neaux-propos%C3%A9s-sur-trouver-un-cr%C3%A9neau-ne-sajustent-pas-avec-les-rdv-d%C3%A9j%C3%A0-pos%C3%A9s
- Nettoyage de l'affichage avec des collapses (voir plus/moins)
- Ajout d'un bouton "prochaine disponibilité"

[Refacto] Clean design + add next availability btn

---

app/controllers/users/rdv_wizard_steps_controller.rb
app/form_models/user_rdv_wizard.rb
app/views/lieux/show.html.slim

https://trello.com/c/mWEe7VnM/985-user-undefined-method-servicesany-in-lieux-controller

[user] undefined method `@services.any?' in lieux controller

---

app/controllers/agents/creneaux/agent_searches_controller.rb
app/helpers/agents_helper.rb
app/views/agents/creneaux/agent_searches/_creneau.html.slim
app/views/agents/creneaux/agent_searches/_creneaux.html.slim
app/views/agents/creneaux/agent_searches/_lieux.html.slim
app/views/agents/creneaux/agent_searches/by_lieu.js.erb
app/views/agents/creneaux/agent_searches/index.html.slim
app/views/agents/creneaux/agent_searches/index.js.erb
app/webpacker/components/agents_creneaux.js
app/webpacker/packs/application_agent.js
app/webpacker/stylesheets/application_agent.scss
app/webpacker/stylesheets/components/_creneaux.scss
db/seeds.rb

followup to #769 after revert because of https://sentry.io/organizations/lapins/issues/1769832908
seems to bug when next_availability is nil 
don't know how to reproduce yet

[agent][trouver un creneau] add next availability button + collapse + UI improvements

---

app/webpacker/components/datetimepicker.js

https://trello.com/c/Y4yDu6Kz/1010-forcer-premier-jour-a-lundi-dans-les-datepickers

datepickers weeks start on monday, not sunday

---

app/controllers/agents/plage_ouvertures_controller.rb
app/views/agents/plage_ouvertures/_form.html.slim
app/views/agents/plage_ouvertures/_plage_ouverture.html.slim
app/views/agents/plage_ouvertures/edit.html.slim
app/views/agents/plage_ouvertures/index.html.slim
app/views/agents/plage_ouvertures/new.html.slim
app/webpacker/packs/controllers/recurrence_controller.js
db/seeds.rb
spec/controllers/agents/plage_ouvertures_controller_spec.rb
spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb

https://trello.com/c/ywpNNFsy/1003-creation-de-plage-ouverture-jour-de-debut-pas-pris-en-compte
and
https://trello.com/c/b08geApC/1011-creation-de-plage-douverture-la-barre-lat%C3%A9rale-se-ferme-lorsquon-cherche-une-date-de-fin-de-r%C3%A9currence
2 fixes : 
- wrong date format in moment with new datepicker was causing misinterpretation of the dates => start date were messy with monthly recurrences
- navigating in datepicker was erroneously navigating away from form sidebar for some browsers in some situations. simple and rough solution : move away from sidebar forms to dedicated pages :)

[agent] plage ouverture fixes : fix monthly recurrences + dedicated form pages

---

app/webpacker/components/motif-form.js

https://trello.com/c/aIIrOQaZ/1012-fix-closest-usage-in-motif-form

[agent] fix JS closest usage in motif form

---

app/views/agents/rdvs/show.html.slim
app/views/common/_recurrence.html.slim
app/webpacker/components/datetimepicker.js
app/webpacker/components/record-versions.js
app/webpacker/components/recurrence-form.js
app/webpacker/packs/application_agent.js
package.json
yarn.lock

https://trello.com/c/uKwbGhtx/990-remove-stimulus

Remove dependency on stimulus JS package  

---

spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb

https://trello.com/c/lUcnCKnZ/933-corriger-test-qui-faile-aleatoirement

fixing flaky spec for agent creneau creation

---

README.md

- Mise à jour de la version de ruby du projet indiquée dans le README.md

Update ruby version on README.md

---

app/controllers/agents/users_controller.rb
app/helpers/users_helper.rb
app/models/concerns/user/searchable_concern.rb
app/models/user.rb
app/views/agents/rdvs/_rdv.html.slim
app/views/agents/users/_responsible_information.html.slim
app/views/agents/users/_search.html.slim
app/views/agents/users/show.html.slim
app/views/common/_user_attribute.html.slim

https://trello.com/c/aoyln2ag/1016-agent-warning-usagers-avec-meme-numero

[agent] display warning for phone used by others in users#show

---

app/models/creneau.rb
app/models/rdv.rb
app/services/creneaux_builder_service.rb
app/webpacker/packs/application_agent.js
config/application.rb
spec/models/creneau_spec.rb
spec/services/creneaux_builder_service_spec.rb

https://trello.com/c/AGzPGXNf/959-agent-ajuster-les-cr%C3%A9neaux-propos%C3%A9s

[agent] align generated creneaux with overlapping RDVs and absences

---

app/helpers/agents_helper.rb
spec/helpers/agents_helper_spec.rb

related to https://trello.com/c/boJA0l8c/996-agents-garder-la-s%C3%A9lection-du-user
improves b96563ec57f6d81dd764eab906deddc2613fe4f6 to handle multiple user_ids even though it's unused yet

improve agent_ids and user_ids params in rdv wizard route helper

---

app/models/rdv.rb
spec/factories/rdv_event.rb
spec/models/rdv_spec.rb

https://trello.com/c/mPYYhcXM/1020-fix-rdv-deletion

fix deleting RDVs bug with dependent rdv events

---

config/initializers/content_security_policy.rb

https://trello.com/c/UusjcXAQ/1013-enable-policy-content-actual-blocking

enable CSP security

---

app/controllers/lieux_controller.rb
app/views/layouts/registration.html.slim
app/views/organisations/new.html.slim
app/views/welcome/welcome_agent.html.slim
spec/controllers/lieux_controller_spec.rb

https://trello.com/c/jZTIrLG2/981-usager-retirer-les-mentions-mds

replace MDS with departement to be more generic

---

app/helpers/rdvs_helper.rb
app/models/rdv.rb
app/models/stat.rb
app/views/agents/organisations/stats/index.html.slim
app/views/agents/stats/index.html.slim
app/views/stats/_rdv_counters.html.slim
app/views/stats/index.html.slim

https://trello.com/c/oL31Kv20/983-stats-r%C3%A9parer-la-fra%C3%AEcheur-des-statistiques

fix stats freshness by unfreezing date range

---

app/webpacker/components/agent-user-form.js
app/webpacker/components/agents_creneaux.js
app/webpacker/components/datetimepicker.js

https://trello.com/c/5NPOAv7d/1021-ie11-dispatchevent-change-is-broken
https://trello.com/c/tCv0o8RX/1022-fix-remove-from-dom-js-ie11

IE11 JS fixes - manual event triggering and remove from dom

---

app/blueprints/motif_blueprint.rb
app/blueprints/user_blueprint.rb
db/seeds.rb

https://trello.com/c/njHdVPIy/1007-interconnexion-rdv-sol-vers-outlook-rdv-ajouter-le-num%C3%A9ro-de-t%C3%A9l
https://trello.com/c/5w87iDZw/1006-interconnexion-rdv-sol-vers-outlook-rdv-ajouter-le-type-de-rdv
:sweat_smile:

Ajoute des champs aux notifications

---

app/views/agents/users/_duplicate_alert.html.slim

https://trello.com/c/KtgcJanE/1019-agent-au-moment-de-la-d%C3%A9tection-dun-usager-d%C3%A9j%C3%A0-existant-dans-le-flow-de-pose-de-rdv-changer-le-bouton-modifier-cet-usager-par-c

in agent rdv wizard, when duplicate user found, let agent pick it instead of exiting the flow

---

app/controllers/agents/users/rdvs_controller.rb
app/models/user.rb
spec/models/user_spec.rb

https://trello.com/c/hCDhZfkF/1029-incoherence-des-filtres-entre-compteur-rdv-a-venir-et-liste

fix incoherence in RDVs list: only show current user RDVs, not relatives

---

app/views/agents/users/_form.html.slim

https://trello.com/c/m2Qv3ZCB/1037-agents-utilise-le-m%C3%AAme-champ-date-partout

utilise le datepicker de jquery partout

---

app/views/agents/rdvs/show.html.slim

https://trello.com/c/G4YqIQeF/1038-agentsrdvs-ajout-dun-lien-explicite-pour-revenir-%C3%A0-lagenda

rend explicite le lien vers d'agenda depuis un rdv

---

app/controllers/health_checks_controller.rb

https://trello.com/c/iQ07hFf3/1044-mettre-en-place-une-alerte-en-cas-de-peu-de-mails-envoy%C3%A9s-le-matin
permettra de mettre en place des alertes depuis updown.io sur l'url https://www.rdv-solidarites.fr/health_checks/rdv_events_stats.json?min_mails=15&min_sms=40
res visible sur https://demo-rdv-solidarites-pr848.osc-fr1.scalingo.io/health_checks/rdv_events_stats.json?min_mails=1 (statut http 416)

add params thresholds to rdv events health endpoint

---

app/services/creneaux_builder_service.rb
spec/services/creneaux_builder_service_spec.rb

https://trello.com/c/RRAODoeY/1063-corriger-bug-cr%C3%A9neaux-nocturnes-%C3%A0-cause-dune-absence-finissant-tard

fix buggy night creneaux because of absence ending late

---

db/migrate/20200907084438_delete_old_notes_from_users.rb
db/migrate/20200907123203_remove_old_notes_from_user_profiles.rb
db/schema.rb

https://trello.com/c/Z0vnbwks/1027-supprimer-les-anciennes-notes
préliminaire à la reintroduction des notes dans les user profiles

Remove old_notes columns in users and profiles

---

app/controllers/admin/rdvs_controller.rb

https://trello.com/c/P3GFQqz2/1064-bug-redirection-agenda-quand-creation-de-rdv-pour-un-autre-agent

after rdv creation by other agent, redirect to correct agent's agenda

---

app/views/layouts/_left_menu.html.slim
app/views/layouts/registration.html.slim
app/webpacker/stylesheets/structure/_authentication.scss
app/webpacker/stylesheets/structure/_left-menu.scss
app/webpacker/stylesheets/structure/_right_sidebar.scss

https://trello.com/c/oRwiQaLW/1062-am%C3%A9liorer-lui-du-menu-lat%C3%A9ral

Improve left bar layout in admin and registration layout

---

app/helpers/users_helper.rb
app/models/user.rb
app/views/admin/users/show.html.slim

https://trello.com/c/rxp0FbGL/1084-usager-proche-apparait-apr%C3%A8s-suppression
cf https://demo-rdv-solidarites-pr888.osc-fr1.scalingo.io/admin/organisations/2/users/1

fix relatives current orga filter in admin

---

app/models/motif.rb
db/seeds.rb

https://trello.com/c/3ZJT9exS/1076-cr%C3%A9er-des-motifs-avec-le-m%C3%AAme-libell%C3%A9-dans-des-services-diff%C3%A9rents

allow motifs with same names in different services

---

app/helpers/users_helper.rb
app/models/user.rb
app/views/admin/rdvs/show.html.slim

https://trello.com/c/7C2lbUU5/1082-corriger-bug-vue-rdv-pour-usager-supprim%C3%A9
https://sentry.io/organizations/rdv-solidarites/issues/1887301469/?environment=production&project=1811205&query=is%3Aunresolved

fix admin/rdvs#show for soft deleted users

---

CONTRIBUTING
CONTRIBUTING.md

Pour faciliter la participation;
Coller aux « standards » des projets libres;
Pour documenter notre processus de développement, de travail;
J'ai déplacé certaines infos qui étaient dans des pages du wiki du projet github pour les mettre ici. Ça mériterais sans doute d'être affiner, mais c'est déjà un premier pas il me semble.

ajout d'un fichier contributing

---

app/webpacker/components/datetimepicker.js

https://trello.com/c/3dkr2YSz/1097-datetimepicker-mask

use datetimepicker mask for date inputs

---

app/services/search_creneaux_for_agents_service.rb

https://trello.com/c/TnnKqkg3/1098-bug-trouver-un-creneau-pour-autre-agent

fix agent filter for next availability in trouver un creneau interface

---

app/models/stat.rb

https://trello.com/c/gip22Gtx/1096-page-stats-bug-affichage-dates-graphiques-par-statut-de-rdvs
good catch @guillett ! took me a while to figure it out. chartkick doesn't do date ordering because they don't want to handle parsing dates, which makes sense. The problem actually originated from my hacky script that normalizes the data over 100%. I first excluded values with 0 to avoid dividing by 0, but this was the root of the problem. you need to have all dates present for all bins, otherwise they won't be ordered correctly.
hard to validate on the review app without prod data 🤷  but I checked locally with a prod dump

fix unordered dates in RDV by status stats chart

---

docs/maintenance.html

cannot be tested on the review app, but should fix the logo on our maintenance page

fix maintenance logo

---

app/blueprints/absence_blueprint.rb
app/models/absence.rb

https://trello.com/c/1CGyOx0E/1125-api-sortantes-pour-les-absences

Send notifications on absence events

---

app/blueprints/absence_blueprint.rb

https://trello.com/c/oCZq9gN5/1127-ajoute-endday-dans-la-repr%C3%A9sentation-json-des-absences

Add end_day to Absence JSON payload

---

app/mailers/agents/plage_ouverture_mailer.rb
app/models/plage_ouverture.rb
app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_updated.html.slim
db/seeds.rb
spec/mailers/previews/agents/plage_ouverture_mailer_preview.rb
spec/models/plage_ouverture_spec.rb

https://trello.com/c/tbXV9nTQ/1123-envoyer-un-ical-apr%C3%A8s-une-modification-de-plage-douverture

send email on plage ouverture updated

---

app/webpacker/components/calendar.js

https://trello.com/c/9lo8Bfby/1138-bug-decalage-timezone

Revert "force timezone to Paris in FullCalendar config (#932)"

---

app/views/layouts/registration.html.slim

remove 'digitalisez' catch phrase for agents

---

CHANGELOG.md
app/views/layouts/application_agent.html.slim

migrating changelog to doc.rdv-solidarites.fr

update changelog url to gitbook + add changelog with link to it

---

app/controllers/admin/rdvs_controller.rb
app/views/admin/rdvs/_rdv_status_dropdown.html.slim

https://trello.com/c/apuh1MqB/1159-r%C3%A9parer-bug-edition-rdv-dans-vue-laterale
je n'avais pas bien testé le cas d'édition depuis la sidebar. Il faut bien supporter distinctement le format js du format json pour que ça fonctionne

fix rdv edit sidebar format bug

---

app/webpacker/stylesheets/structure/_right_sidebar.scss

https://trello.com/c/lUgmthf9/1165-fix-scroll-right-bar

fix scroll right bar

---

app/views/common/_footer_users.html.slim

Cette PR corrige une erreur d'orthographe qui s'est glissée dans le footer ;)

Corrige une erreur d'orthographe

---

app/controllers/admin/users_controller.rb
app/policies/agent/rdv_policy.rb
app/views/admin/users/show.html.slim
spec/controllers/admin/rdvs_controller_spec.rb
spec/features/agents/agent_can_see_users_rdv_spec.rb
spec/policies/agent/rdv_policy_spec.rb

https://trello.com/c/MIKARYFu/1171-bug-permissions-rdvs-agents-intra-services

fix RDV policy scope to include other agents from same service

---

.gitignore
CONTRIBUTING.md
Makefile

Dans l'optique de m'essayer à (TCR](https://medium.com/@kentbeck_7670/test-commit-revert-870bbd756864) `(test && commit) || revert` j'ai voulu nettoyer les quelques fichiers qui n'était pas suivi dans git, mais qui restait « non suivi »
- un bout de texte à propos des tests de web hook. Je l'ai négligement poussé dans le fichier `CONTRIBUTING.md`
- le template de commit que j'utilise pour les moments où nous codons à plusieurs que j'ai ajouté dans le `.gitignore`
- la suppression de la commande `stop` du Makefile qui en fait, ne peux pas fonctionner

Nettoyage de la liste de mes fichiers non suivis

---

app/views/mailers/common/_rdv_cancellable.html.slim
app/views/mailers/users/rdv_mailer/rdv_created.html.slim
app/views/mailers/users/rdv_mailer/rdv_upcoming_reminder.html.slim

https://trello.com/c/Efnl6Bpu/1186-am%C3%A9lioration-texte-notification-usager
Un premier pas pour esayer de réduire le nombre le temps de traitement d'une annulation de rendez-vous.

Notifie clairement la possibilité d'annuler un rdv

---

app/models/concerns/rdv/address_concern.rb
app/models/rdv.rb

Libère de la 'place' dans le modèle RDV en extrayant les méthodes liées à l'adresse

extracted RDV address methods into concern

---

app/views/layouts/_left_menu.html.slim

fix left menu agent select JS bug from admin/rdvs#index

---

app/service_models/rdv_start_coherence.rb
spec/service_models/rdv_start_coherence_spec.rb

improve RdvStartCoherence to ignore past and canceled RDVs

---

app/views/admin/organisations/show.html.slim

#1003
Utilisation de la fonction d'aide `display_value_or_na_placeholder(value)`

afficher N/A quand les champs de l'organisation sont vides

---

app/models/motif.rb
spec/models/motif_spec.rb

should fix https://sentry.io/organizations/rdv-solidarites/issues/2058764816/?environment=production&project=1811205&query=is%3Aunresolved

improve Motif.search_by_name_with_location_type nil arg

---

db/migrate/20210106104714_fix_agents_with_missing_uid.rb
db/schema.rb

followup to https://github.com/betagouv/rdv-solidarites.fr/pull/1089
testé sur un dump de prod

migration to fix agents with missing uid

---

app/models/agent.rb
db/migrate/20210107091426_sync_deleted_agents_uid_with_email.rb
db/schema.rb
spec/models/agent_spec.rb

related to #1095 
migration tested on prod dump : only one case

fix syncing agents UID with soft deleted email

---

app/controllers/lieux_controller.rb

fix filtering motifs by service on user search - closes #1103

---

app/views/admin/users/show.html.slim

fix policy scope Rdvs in users show short rdvs lists - closes #1030

---

scripts/get_deployed_changes.rb

mis a jour le script deployed changes fonctionnalités ISO avec avant : 
- affiche dans un terminal les tickets finis au format MD `- [title](url)`
- archive les tickets dans le kanban

updated deployed_changes script for changelog to use github project

---

app/controllers/admin/departements/sectors_controller.rb
app/views/admin/departements/sectors/_form.html.slim

cf https://github.com/betagouv/rdv-solidarites.fr/issues/1081

improve redirection after sector creation

---

app/views/layouts/_left_menu.html.slim

cf #1106 
visible sur la demo app avec le compte polo@demo.rdv-solidarites.fr par ex

updated left menu lieux icon to building

---

app/views/admin/departements/zone_imports/new.html.slim

cf https://startups-detat.slack.com/archives/C42JDLWDS/p1610464376140100
il existe en fait un outil de geocodage de fichiers CSV sur https://adresse.data.gouv.fr/csv qui fait plutot mieux le job que ce que j'ai créé dans le codepen. Fail 🤦

change link to external secto tool from codepen to data gouv tool

---

app/views/static_pages/contact.html.slim

add link to thursdays tech open desk on contact page

---

app/views/common/_contact.html.slim
app/webpacker/stylesheets/components/_utilities.scss

#1105 
dur a tester sur la review app car les numeros de contact ne sont pas configurés pour les dpts de test

hide search form contact informations behind collapsable

---

app/controllers/support_tickets_controller.rb
app/form_models/support_ticket_form.rb
app/views/static_pages/contact.html.slim
app/webpacker/components/support-ticket-form.js
app/webpacker/packs/application.js
spec/form_models/support_ticket_form_spec.rb

ajoute un champ commune obligatoire uniquement pour les sujets de tickets usagers, j'ai été obligé de rajouter un peu de JS pour faire ça :/

improve support ticket form: add city for users + display email

---

scripts/export_sectors.rb

simple script pour exporter des CSV de zones par département si demandé

added script to export departement sectors CSV

---

app/controllers/admin/organisations_controller.rb

alphabetical order on admin/organisations#index

---

app/service_models/rdvs_overlapping.rb
spec/service_models/rdvs_overlapping_spec.rb

exclue les bornes du chevauchement

---

app/webpacker/components/select2-inputs.js

fix #1139
cf https://gist.github.com/bartlomiejmatlega/66ea6bcec658202677e1b81c49bd42ce

Fix reloading select2 JS inputs with turbolink on back navigation

---

app/views/layouts/application_agent.html.slim

supprime le lien vers l'ancienne roadmap

---

app/services/send_transactional_sms_service.rb
scripts/test_sms_sending.rb

https://sentry.io/organizations/rdv-solidarites/issues/2178938687/?environment=production&project=1811205&query=is%3Aunresolved

raise max SMS netsize concatenation limit from 3 to 10 - max

---

app/models/rdv.rb
app/models/user.rb
app/views/admin/users/show.html.slim
spec/models/user_spec.rb

affiche les prochains rdv sans les rdvs en cours

---

db/migrate/20210210171357_remove_role_from_agents.rb
db/schema.rb

remove agents.role column, moved to join table

---

app/views/users/users/edit.html.slim
app/views/welcome/index.html.slim

remove useless page titles from user-facing pages

---

docs/tech_tips.md
scripts/get_deployed_changes.rb

- précise l'usage de la variable d'env
- ajoute un brin de doc

Ajoute des infos dans le script de changelog

---

scripts/scalingo_dump.rb
scripts/scalingo_scale.rb

j'ajoute un script de scaling, ca sera plus simple pour ecrire une github action qui scale up et down le soir et weekend :)

scalingo scaling script + improve dump script

---

app/models/file_attente.rb

fix notifiable conditions for file attente notifications

---

app/service_models/transactional_sms/base_concern.rb
spec/service_models/transactional_sms/base_concern_spec.rb

replace œ with oe in SMS

---

app/service_models/rdvs_overlapping.rb
spec/service_models/rdvs_overlapping_spec.rb

fix RDV overlapping exact same times

---

app/controllers/health_checks_controller.rb

closes https://sentry.io/organizations/rdv-solidarites/issues/2221682679

fix health checks RDV event stats min comparisons

---

app/views/admin/rdvs/index.html.slim

https://sentry.io/organizations/rdv-solidarites/issues/2212334041/
pour reproduire par ex : agent > Mes statistques > tous les RDVs

fix admin/rdvs#index without status filter

---

app/helpers/admin_helper.rb
app/views/admin/lieux/index.html.slim
app/views/admin/motifs/index.html.slim

cacher le bouton d'ajout de lieu pour les agents non-admin

---

app/controllers/admin/static_pages_controller.rb
app/controllers/admin/support_tickets_controller.rb
app/controllers/agent_auth_controller.rb
app/controllers/static_pages_controller.rb
app/form_models/support_ticket_form.rb
app/policies/agent/support_ticket_policy.rb
app/views/admin/static_pages/support.html.slim
app/views/layouts/_left_menu.html.slim
app/views/layouts/application_agent.html.slim
app/views/static_pages/contact.html.slim
config/routes.rb
spec/form_models/support_ticket_form_spec.rb

Nouvelle page support dans l'admin

---

scripts/export_sectors.rb

Légère amélioration dans script d'export de secteurs pour trier sur le nom et l'afficher dans l'export

export sector names in script

---

app/controllers/organisations_controller.rb
config/locales/models/organisation.fr.yml
spec/controllers/organisations_controller_spec.rb

Limiter la création d'organisation par une personne non authentifiée

---

app/models/concerns/has_phone_number_concern.rb
app/models/user.rb

preliminary to #1215 
extraction d'un concern pour le formattage du numero de telephone en vue de le reutiliser pour les Territories

extract HasPhoneNumberConcern from User

---

spec/factories/sector.rb

should fix https://app.circleci.com/pipelines/github/betagouv/rdv-solidarites.fr/3905/workflows/3e15878c-ec31-4dd9-a731-daa05f2bed20/jobs/12341

fix flaky specs on sectors.human_id collisions

---

spec/factories/organisation.rb
spec/factories/territory.rb

Ajoute une limitation au moment de générer des numéros de département

limite la génération de num de dep à 100

---

config/locales/models/motif.fr.yml

replace les bons textes au bon endroit

---

app/controllers/admin/absences_controller.rb
app/controllers/admin/plage_ouvertures_controller.rb
app/helpers/plage_ouvertures_helper.rb
app/models/absence.rb
app/models/concerns/recurrence_concern.rb
app/presenters/plage_ouverture_presenter.rb
app/service_functions/admin/ics/plage_ouverture.rb
app/service_models/plage_ouverture_overlap.rb
app/services/creneaux_builder_for_date_service.rb
app/services/creneaux_builder_service.rb
app/views/admin/absences/_absence.html.slim
app/views/admin/absences/index.json.jbuilder
app/views/admin/plage_ouvertures/_overlapping_plage_ouvertures.html.slim
app/views/admin/plage_ouvertures/index.json.jbuilder
config/locales/models/rdv.fr.yml
spec/controllers/admin/plage_ouvertures_controller_spec.rb
spec/mailers/agents/plage_ouverture_mailer_spec.rb
spec/models/absence_spec.rb
spec/service_functions/admin/ics/plage_ouverture_spec.rb
spec/support/recurrence_concern.rb

J'ai découvert qu'il y avait parfois **occurence** et parfois **occurrence**... Après vérification, il semble qu’**occurrence** soit la bonne orthographe en français et en anglais. Cette PR faire un tour de chaque instance de ce mot pour corriger.

Occurrence prend 2 r en anglais et en français

---

app/views/admin/users/index.html.slim

liste uniquement les référents existant

---

app/service_models/transactional_sms/rdv_created.rb
config/locales/fr.yml
spec/controllers/lieux_controller_spec.rb
spec/service_models/transactional_sms/rdv_cancelled_spec.rb
spec/service_models/transactional_sms/rdv_created_spec.rb
spec/service_models/transactional_sms/reminder_spec.rb

affiche le  mois complet dans les notifications SMS

---

scripts/export_sectors.rb

broken by territories introduction

fix export_sectors script with territories

---

app/service_functions/admin/ics/plage_ouverture.rb

may fix #1219 
cf #1262 for the investigation that lead to this simple fix

add organizer field to Plage Ouverture ICS files

---

.github/workflows/ci.yml

déployer sur scaling depuis les github actions

---

.github/workflows/ci.yml

utilise l'anglais pour l'intégration continue

---

app/views/admin/rdv_wizard_steps/step3.html.slim

fix duplicate footer in admin/rdv_wizard_form_step#step3

---

scripts/copy_users_between_orgas.rb

demande de la Somme, ce script pourrait etre utile a generiser puis a rendre faisable depuis l'admin territoriale un jour

script to copy users between orgas, hardcoded values

---

app/models/rdv.rb
spec/helpers/rdvs_helper_spec.rb
spec/models/rdv_spec.rb

autorise le statut vu une heure avant le rdv

---

app/controllers/api/v1/users_controller.rb
config/routes.rb
spec/requests/api/v1/users_request_spec.rb

- Issue #1046 
- Ajout des routes et de l'entrée de controller pour générer l'url d'invitation

Ajout de l'endpoint pour récupérer une url d'invitation

---

scripts/copy_users_between_orgas.rb

C'est un script pour la copie d'agent vers une nouvelle organisation de la Somme.

prepare la copie des agents d'orgas de la somme

---

app/form_models/admin/rdv_wizard_form/step2.rb
spec/form_models/admin/rdv_wizard_form/step2_spec.rb

fixes #1292
Si je ne dis pas de bêtise, c’est de toute façon le `responsible` qui recevra les notifications.

Permet de prendre un rdv tél pour un enfant si le parent a un numéro

---

app/webpacker/components/recurrence-form.js
spec/factories/rdv.rb
spec/features/agents/agent_can_manage_recurrence_on_plage_ouverture_spec.rb

cette spec n'etait pas exécutée car le fichier ne finissait pas par _spec.rb
il faudrait peut etre rajouter une regle rubocop ou autre

fix recurrence feature spec

---

.rubocop_todo.yml
app/form_models/support_ticket_form.rb
db/migrate/20200903072742_restore_rdv_context.rb
db/migrate/20200907124800_migrate_user_notes_back_to_user_profiles.rb
db/migrate/20201118161148_remove_deprecated_absences_and_plages_ouvertures.rb
db/migrate/20210301135256_create_territories.rb

Pour corriger la règle ruboco Rails/Output

remplate les puts par des logger.debug

---

.rubocop_todo.yml
app/models/file_attente.rb
spec/controllers/admin/motifs_controller_spec.rb
spec/helpers/paper_trail_helper_spec.rb
spec/jobs/update_plage_ouvertures_expirations_job_spec.rb
spec/models/rdv_spec.rb
spec/models/user_spec.rb
spec/presenters/admin/rdv_user_presenter_spec.rb
spec/service_functions/rdv_exporter_spec.rb
spec/service_functions/rdv_updater_spec.rb
spec/service_models/time_slot_spec.rb
spec/services/jours_feries_service_spec.rb
spec/services/merge_users_service_spec.rb

mise en conformité de la règle Rails/Timezone

respect la règle d'usage de timezone

---

INSTALL.md
Makefile
app/controllers/omniauth_callbacks_controller.rb
bin/setup
config/environments/development.rb

* quelques commandes en plus dans le Makefile
* et mise en commun avec bin/setup
* retrait de commentaires obsolètes (sur le setup des jobs récurrents)
* simplification pour créer le premier SuperAdmin automatiquement en local

Améliorations du setup de développement

---

.rubocop_todo.yml
app/lib/departements.rb
app/mailers/application_mailer.rb
app/models/organisation.rb
app/models/user.rb
config/application.rb
config/environments/development.rb
db/seeds.rb
spec/rails_helper.rb

suite de #1321, et d’autres. Pour les `dependent:` j’ai fait un choix qui me semble raisonnable dans les trois cas; dans l’absolu, ce n’est pas une situation fréquente, en principe. Je crois.

More rubocop

---

.rspec
INSTALL.md
Makefile

followup #1372 pour faire tourner rubocop et rspec avec --parallel. Il y a peut-être des surprises avec rspec, c’est encore à tester.
(Je me dis que j’aimerais bien unifier ce qu’on fait faire à la CI et ce qu’on fait en local.)

Un peu plus d’améliorations de setup

---

.rubocop.yml
.rubocop_todo.yml
spec/controllers/admin/rdv_wizard_steps_controller_spec.rb
spec/controllers/admin/rdvs_controller_spec.rb
spec/form_models/admin/rdv_form_concern_spec.rb
spec/helpers/agents_helper_spec.rb
spec/service_models/plage_ouverture_overlap_spec.rb
spec/services/send_transactional_sms_service_spec.rb

rubocop encore

---

config/locales/models/rdv_event.fr.yml

Add missing i18n key file_attente_creneaux_available

---

.github/workflows/ci.yml
INSTALL.md
scripts/review_app_super_admin_password.sh

Plutôt que de retrouver la ligne avec le `grep` à chaque fois. (Attention, j’écris du shell script!)

Ajout d’un script pour simplifier la connection aux review apps en tant que superadmins

---

scripts/agent_et_motif_changent_de_service.rb

Ajout des éléments de reprise pour les plages d'ouverture et les motifs

mise à jour du script de migration

---

scripts/agent_et_motif_changent_de_service.rb

prepare le script pour chatillon

---

.rubocop.yml
.rubocop_todo.yml
spec/controllers/lieux_controller_spec.rb
spec/controllers/support_tickets_controller_spec.rb
spec/controllers/users/creneaux_controller_spec.rb
spec/controllers/users/rdv_wizard_steps_controller_spec.rb
spec/controllers/users/rdvs_controller_spec.rb
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
spec/form_models/admin/rdv_form_concern_spec.rb
spec/service_models/transactional_sms/base_concern_spec.rb
spec/service_models/users/creneau_search_spec.rb
spec/services/send_transactional_sms_service_spec.rb

Encore encore rubocop

---

app/views/admin/static_pages/support.html.slim

met à jour le lien vers les dernières nouveautés

---

app/controllers/agents/registrations_controller.rb
app/views/agents/registrations/edit.html.slim

fixup #1423, j’avais oublié des petits bouts de trucs inutiles

Fixup cleanup after #1423

---

INSTALL.md
README.md
bin/setup

met à jour les fichiers d'install et setup

---

scripts/scalingo_dump.sh

Pour pouvoir l'executé, j'ai du ajouter `bundle exec` devant les commandes `rails`

precise `bundle exec `

---

yarn.lock

yarn upgrade (webpack to 5.4)

---

.rspec

je pensais que c'était déjà en random, mais en fait non..

fait tourner les specs dans un ordre aléatoire

---

app/blueprints/absence_blueprint.rb
spec/blueprint/absence_blueprint_spec.rb

close #1399
Exporte la récurrence 

partage la recurrence

---

.rubocop.yml
.rubocop_todo.yml
app/controllers/admin/absences_controller.rb
app/controllers/users/creneaux_controller.rb
app/helpers/agents_helper.rb
app/helpers/paper_trail_helper.rb
app/views/admin/versions/index.html.slim
app/views/layouts/_left_menu.html.slim
spec/controllers/admin/plage_ouvertures_controller_spec.rb
spec/helpers/paper_trail_helper_spec.rb
spec/models/file_attente_spec.rb
spec/services/notifications/rdv/rdv_cancelled_by_agent_spec.rb
spec/services/notifications/rdv/rdv_cancelled_by_user_spec.rb
spec/services/notifications/rdv/rdv_cancelled_service_spec.rb
spec/services/notifications/rdv/rdv_created_service_spec.rb
spec/services/notifications/rdv/rdv_date_updated_service_spec.rb
spec/services/notifications/rdv/rdv_upcoming_reminder_service_spec.rb
spec/services/upsert_user_for_franceconnect_service_spec.rb

Résolution de quelques cas du rubocop_todo

Rubocop again and again

---

app/jobs/send_transactional_sms_job.rb
app/jobs/webhook_job.rb

Precises sms queue and webhook queue
Supprime aussi l'application_job inutilisé

Range les jobs dans des queues spécifique

---

app/mailers/agents/rdv_mailer.rb
app/service_functions/admin/ics/rdv.rb
spec/service_functions/admin/ics/rdv_spec.rb

Envoi des ics aux agents

---

.rubocop.yml
.rubocop_todo.yml

Ensuite, il ne reste plus que `Rails/Date`. J’ai commencé, il y a quelques subtilités (mais ça devrait aller)

Encore Rubocop

---

scripts/rspec_splitted.rb

Désactive les feature tests sur github 😔

---

.rspec

Est-ce que c'est ok de l'ajouter pour tout le monde ?
Je me demande d'ailleurs si c'est ok que ce fichier soit versionné, identique pour toute l'équipe :thinking:

profil les specs

---

app/helpers/rdvs_helper.rb
app/views/layouts/_left_menu.html.slim

Close #1495 
J'en ai profité pour supprimer les stats personnels également. Nous avions évoqué le fait d'attendre d'avoir une autre page d'accueil, mais je trouvais l'occasion trop belle. Peut-être faudra-t-il les remettre...

affiche le bon nombre de rdv à renseigner

---

app/controllers/static_pages_controller.rb
app/views/common/_footer_users.html.slim
app/views/static_pages/accessibility.html.slim
config/routes.rb

ajoute une déclaration d'accessibilité

---

app/models/concerns/payloads/rdv.rb
app/service_models/transactional_sms/base_concern.rb
spec/service_models/transactional_sms/base_concern_spec.rb

Utilise le meilleur numéro de téléphone du Rdv dans tous les sms

---

app/service_functions/rdv_exporter.rb
spec/service_functions/rdv_exporter_spec.rb

1187 ajouter commune premier responsable

---

app/views/layouts/_left_menu.html.slim

Replace les stats individuelles

---

app/views/admin/users/show.html.slim
app/views/users/users/edit.html.slim

close #1520 
Ça sera sans doute à revoir en élargissant la cellule familiale.

Tri les proches par age

---

app/blueprints/user_profile_blueprint.rb
app/controllers/api/v1/absences_controller.rb
app/controllers/api/v1/agents_controller.rb
app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/organisations_controller.rb
app/controllers/api/v1/user_profiles_controller.rb
app/controllers/api/v1/users_controller.rb
config/routes.rb
spec/requests/api/v1/absences_request_spec.rb
spec/requests/api/v1/agents_request_spec.rb
spec/requests/api/v1/paginated_requests_spec.rb

refs #1507, fixes #1336
* refactor de la gestion des erreurs
* ajout du support de pagination
* autorise la création d’une absence pour un agent en spécifiant son email
* nouvel endpoint pour récupérer la liste des agents

Améliorations de l’API

---

app/views/admin/motifs/_form.html.slim
app/views/admin/motifs/_motif_attributes.html.slim
app/views/common/_modal_confirmation.html.erb
config/locales/models/motif.fr.yml

Rend les liens cliquables dans les modales de confirmation

---

app/views/admin/rdv_wizard_steps/step2.html.slim
app/views/admin/users/search.json.jbuilder
spec/features/agents/users/agent_can_merge_users_spec.rb
spec/support/select2_spec_helper.rb

affiche le nom puis le prénom de l'usager

---

.github/workflows/ci.yml
.slim-lint.yml
Gemfile
Gemfile.lock
Makefile
app/views/users/rdv_wizard_steps/step2.html.slim
app/views/users/users/_form.html.slim

Avec tous les linters désactivés 😅 . On peut probablement les descendre petit à petit comme pour rubocop.
refs #1288

Ajout de slim-lint

---

app/controllers/admin/referents_controller.rb
app/policies/agent/user_policy.rb

Corrige la modification des référents d’usagers sur plusieurs orgas

---

scripts/compute_organisation_stats.rb

Cette PR est un update du script utilisé pour récupérer les infos de prise de 1er RDVs d'une organisation en prenant notamment en compte les utilisateurs ayant créés leur compte il y a plus de 26 jours (et non pas moins).

fix(script): Fix organisation stats script

---

app/views/admin/organisations/edit.html.slim
app/views/users/registrations/new.html.slim

cf https://fr.wikipedia.org/wiki/Plan_de_numérotation_en_France#Les_numéros_réservés_pour_les_œuvres_audiovisuelles
(Par ailleurs 061010101010 avait trop de chiffres.)

Utilise des numéro de téléphone réservés comme placeholders

---

app/controllers/admin/users_controller.rb
app/form_models/admin/user_search_form.rb
app/helpers/users_helper.rb
app/views/admin/rdv_wizard_steps/_card.html.slim
app/views/admin/rdv_wizard_steps/step2.html.slim
app/views/admin/users/_form.html.slim
app/views/admin/users/_user.html.slim
app/views/admin/users/index.html.slim
app/views/admin/users/new.html.slim
app/views/admin/users/simple_user_list.html.slim
app/webpacker/components/rdv_wizard_step2.js
app/webpacker/packs/application_agent.js
app/webpacker/stylesheets/_variables.scss
spec/controllers/admin/users_controller_spec.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
spec/features/agents/agent_can_see_users_rdv_spec.rb
spec/features/agents/relatives/agent_can_create_relative_spec.rb
spec/features/agents/relatives/agent_can_delete_relative_spec.rb
spec/features/agents/relatives/agent_can_update_relative_spec.rb
spec/features/agents/users/agent_can_delete_user_spec.rb
spec/features/agents/users/agent_can_merge_users_spec.rb
spec/features/agents/users/agent_can_update_user_spec.rb
spec/form_models/admin/user_search_form_spec.rb
spec/helpers/users_helper_spec.rb
spec/support/select2_spec_helper.rb

close #1348 
Ne plus afficher la liste des usagers ;
Obliger à chercher.

oblige à chercher pour afficher des usagers

---

app/controllers/omniauth_callbacks_controller.rb

confirme inscription après auth FC

---

app/controllers/omniauth_callbacks_controller.rb

1584 repare france connect

---

app/webpacker/components/select2-inputs.js

focus sur le champs de recherche d'une select2

---

app/views/admin/users/_user.html.slim

Close #1603 
Après la remise en place de la modale, nous avions aussi remis en place le mode de fonctionnement où il manque l'age et la date de naissance. Cette PR corrige ce manque

affiche date naissance et age

---

app/models/territory.rb
app/services/send_transactional_sms_service.rb
db/migrate/20210729000215_add_clever_technologies_enum_member_for_territory_sms_configuration.rb
db/schema.rb

ajoute un connecteur envoi sms pour le 77

---

app/services/send_transactional_sms_service.rb

1599 connecteur sms 77

---

app/webpacker/stylesheets/components/_calendar.scss

Raye les rendez-vous révoquées

---

app/views/admin/rdvs/_rdv_status_dropdown.html.slim
config/locales/models/rdv.fr.yml

Followup #1632
Demandes: A Perriot
See also #1642

Allow changing to noshow as soon as the Rdv is past?

---

app/controllers/admin/agents/rdvs_controller.rb
app/views/admin/agent_agendas/show.html.slim

refs #1634
Ça ne règle pas l’issue! Par contre, au moins le filtre par statut actuel fonctionne.

Correctly filter by status in the Agenda

---

config/routes.rb

Résous https://sentry.io/organizations/rdv-solidarites/issues/2634637824/?project=1811205&query=is%3Aunresolved

Supprime l'entrée de menu pour la préview d'email

---

app/webpacker/stylesheets/administrate/application.scss
app/webpacker/stylesheets/application.scss
app/webpacker/stylesheets/application_agent.scss
app/webpacker/stylesheets/components/_autocomplete.scss
spec/features/users/user_can_search_rdv_spec.rb

Close #1694
Entre autres trucs qui m’énervent: c’est plein de js externe pour une fonctionnalité centrale, et écrire des tests d’intégration pour ça serait infernal.

Corrige la saisie et l’autocomplétion des adresses

---

docs/tech_tips.md

document la preview d'email

---

spec/controllers/admin/referents_controller_spec.rb
spec/form_models/admin/rdv_search_form_spec.rb

Fix some tests that can randomly fail.

Fix flaky tests

---

app/blueprints/rdv_blueprint.rb
spec/blueprint/rdv_blueprint_spec.rb

rollback the compatibility introduced in #1656

Remove rdv_status_compatibility1

---

scripts/import_motifs_libelles.rb

ajoute un script d'import de libellé de motif

---

scripts/import_motifs_libelles.rb

précise l'url

---

Makefile

Je me demande si ça devrait être un script, mais j’ai envie de garder les choses les plus basiques possible.

Add recette/deployment tasks to the Makefile

---

app/views/admin/motifs/_form.html.slim

ajoute un lien vers la configuration du secteur

---

.github/issue_template.md

Parce que ça souligne beaucoup en rouge quand j'ajoute une issue :)

corrige le template d'issue

---

app/services/sms_sender.rb

Patch le connecteur en production pour pouvoir le tester en démo.

place les paramètres dans l'URL

---

app/services/sms_sender.rb

retour a des paramètres dans le corps, mais en supprimant le .to_json

Patch connecteur somme

---

app/form_models/admin/rdv_wizard_form.rb
app/form_models/concerns/admin/rdv_wizard_form_concern.rb
app/views/admin/rdv_wizard_steps/_card.html.slim
app/views/admin/rdv_wizard_steps/_stepper.html.slim
app/views/admin/rdv_wizard_steps/_title.html.slim
app/views/admin/rdv_wizard_steps/step1.html.slim
app/views/admin/rdv_wizard_steps/step2.html.slim
app/views/admin/rdv_wizard_steps/step3.html.slim
app/views/admin/rdv_wizard_steps/step4.html.slim
config/locales/admin_rdv_wizard_form.fr.yml
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb

Close #1607
Finalement, je n'ai pas mélangé les PR #1617 et  #1607 
Pas de grande modification sur le design par contre... 

affiche date et heure du rdv dans le titre

---

app/controllers/admin/absences_controller.rb
app/controllers/admin/agents_controller.rb
app/controllers/admin/lieux_controller.rb
app/controllers/admin/organisations_controller.rb
app/controllers/admin/plage_ouvertures_controller.rb
app/controllers/admin/rdvs_controller.rb
app/controllers/lieux_controller.rb
app/models/agent.rb
app/models/rdv.rb
app/policies/agent/absence_policy.rb
app/policies/agent/agent_policy.rb
app/policies/agent/agent_role_policy.rb
app/policies/agent/agent_territorial_role_policy.rb
app/policies/agent/organisation_policy.rb
app/policies/agent/plage_ouverture_policy.rb
app/policies/agent/rdv_policy.rb
app/presenters/paper_trail_augmented_version.rb
app/views/admin/rdv_wizard_steps/step3.html.slim
app/views/admin/rdvs/index.html.slim
config/brakeman.ignore
config/environments/development.rb
db/migrate/20210922140002_add_missing_indexes.rb
db/schema.rb
spec/policies/agent/absence_policy_spec.rb
spec/policies/agent/agent_policy_spec.rb
spec/policies/agent/agent_role_policy_spec.rb
spec/policies/agent/agent_territorial_role_policy_spec.rb

#1739, mais directement sur la production

Optimisations des requêtes ActiveRecord

---

app/blueprints/rdv_blueprint.rb

J'ajoute les attributs `cancelled_at` et `created_by` aux rdvs qui nous seront probablement utiles.

feat(api): Add attributes to rdvs blueprint

---

app/helpers/rdvs_helper.rb
app/views/layouts/_left_menu.html.slim
db/migrate/20210928142915_add_index_updated_at.rb
db/schema.rb

refs #1754
🚀 parce que c’est une PR directement sur production, et 🧹 parce qu’il y a une migration 😁.

🚀🧹[perf] Cache danger badge 

---

db/migrate/20210929093324_add_phone_number_index.rb
db/schema.rb
db/seeds.rb

refs #1754
Avant:
```
QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=386.23..386.23 rows=1 width=551)
->  Sort  (cost=386.23..386.23 rows=1 width=551)
Sort Key: (count(rdvs.id)) DESC
->  GroupAggregate  (cost=386.20..386.22 rows=1 width=551)
Group Key: users.id
->  Sort  (cost=386.20..386.20 rows=1 width=551)
Sort Key: users.id
->  Nested Loop Left Join  (cost=4.79..386.19 rows=1 width=551)
->  Nested Loop Left Join  (cost=4.65..385.99 rows=1 width=551)
->  Nested Loop  (cost=0.43..371.54 rows=1 width=543)
->  Nested Loop  (cost=0.29..363.37 rows=1 width=551)
:(  ==>         ->  Seq Scan on users  (cost=0.00..355.06 rows=1 width=543)
Filter: …
```

🚀  🧹  [perf] Make DuplicateUsersFinderService faster

---

Makefile

Fix make recette_deploy_to_production

---

spec/models/user_spec.rb

Maybe related to the tsvector changes in #1767 ?
Cf #1774, too

Disable suddenly failing test is models/user

---

app/controllers/super_admins/agents_controller.rb
app/controllers/super_admins/application_controller.rb
app/views/welcome/super_admin.html.slim

fixes #1764, et quelques micro-fixes sur superadmin au passage.

Fix superadmin auth

---

app/controllers/admin/agents_controller.rb
app/helpers/agents_helper.rb
app/views/admin/agents/search.json.jbuilder
app/views/layouts/_left_menu.html.slim
app/webpacker/components/planning-agent-select.js
config/routes.rb
db/seeds.rb

refs #1754
Avant:
```
18:24:53 web.1     |   Rendered layouts/_left_menu.html.slim (Duration: 1190.6ms | Allocations: 1243809)
```
Après:
```
18:28:34 web.1     |   Rendered layouts/_left_menu.html.slim (Duration: 60.9ms | Allocations: 46231)
```
Ajax like it's 2005 ! En réalité, on est pas _très_ loin d’avoir un petit controller stimulus et de retourner les options html directement. Mais ça sera pour la prochaine fois.

Faster left menu

---

app/controllers/admin/territories/zones_controller.rb

fixes RDV-SOLIDARITES-WN
followup #1820

Fix a crash when adding a new zone to a territory sector

---

app/models/agent.rb
app/models/motif.rb

Do not use the french dictionary for pg_search on agents and motifs

---

app/views/admin/rdv_wizard_steps/_actions.html.slim
app/views/admin/rdv_wizard_steps/_card.html.slim
app/views/admin/rdv_wizard_steps/_stepper.html.slim
app/views/admin/rdv_wizard_steps/step1.html.slim
app/views/admin/rdv_wizard_steps/step2.html.slim
app/webpacker/components/rdv_wizard_step2.js
app/webpacker/stylesheets/components/_utilities.scss
config/locales/fr.yml
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
spec/support/select2_spec_helper.rb

Fait en passant pour #1617/#1742, vu que je mets les mains là-dedans.
Avant-après:

Ajustements UI sur le wizard Rdv côté admin

---

app/helpers/rdvs_helper.rb

followup #1757 #1794 #1803. Ça ne sert plus aujourd’hui, on a un beau bandeau!

Remove the rdv_danger_badge helper

---

app/services/rdv_exporter.rb
spec/services/rdv_exporter_spec.rb

refs #1868
On passe du simple au double sur ma machine, ça devrait permettre de voir venir; par contre, il va falloir une vraie réponse à #1868. À vue de nez, le plus simple est de générer le fichier xls dans un job et de l’envoyer par mail à l’agent qui l’a demandé.

🚀 Follow Bullet recommendations in RdvExporter

---

app/views/admin/rdvs/_rdv_search_form.html.slim
config/locales/views/layouts.fr.yml
db/seeds.rb

Close #1872
Cassé depuis #1761 🤷 

Corrige l’affiche de la présélection de l’agent et de l’usager dans la recherche de Rdv

---

app/models/rdv.rb
app/views/admin/rdvs/_rdv_search_form.html.slim
app/views/admin/rdvs/index.html.slim
app/views/layouts/_rdv_a_renseigner.html.slim
app/views/layouts/application_agent.html.slim
config/locales/views/layouts.fr.yml
db/migrate/20211028135237_add_unknow_past_rdv_count_to_agents.rb
db/schema.rb
db/seeds.rb
scripts/set_agent_unknown_past_rdv_count.rb

* Retour des changements de #1803, #1874, #1875
* Déplacement de la migration des données dans un script à appeler manuellement

Rerun unknown_past_rdv_count

---

app/views/admin/organisations/setup_checklists/show.slim

(especially in development, the data in seeds.rb has many empty developers)

Avoid displaying thousands of lines in the welcome page

---

app/views/admin/rdvs/edit.html.slim

Remove still more inline selects of users and agents

---

app/views/admin/absences/index.html.slim
app/views/admin/agent_agendas/show.html.slim
app/views/admin/agents/index.html.slim
app/views/admin/invitations/index.html.slim
app/views/admin/lieux/index.html.slim
app/views/admin/motifs/index.html.slim
app/views/admin/plage_ouvertures/index.html.slim
app/views/admin/rdvs/show.html.slim
app/views/admin/territories/sectors/index.html.slim
app/views/admin/users/index.html.slim
app/views/admin/users/show.html.slim
app/views/layouts/application_agent.html.slim
app/views/users/creneaux/edit.html.slim
app/webpacker/stylesheets/structure/_page-head.scss
spec/support/page_spec_helper.rb

Remove the dark title bar and tweak the title size and breadcrumb

---

app/jobs/cron_job.rb

Do not try to run ScalingoAppRestarter in development

---

.env.sample

followup #1844
Of course this needs to be added to each developer's one .env file 🤷 .

Use port 3000 when starting the server locally via foreman

---

app/views/admin/rdvs/_rdv_status_dropdown.html.slim
app/views/admin/rdvs/show.html.slim
app/views/admin/versions/_resource_versions_row.html.slim

En passant pour #1617 :)
Avant-après: le plus gros changement est le passage à une seule colonne. J’ai envie de faire ça partout, et de continuer à trouver un meilleur design petit à petit (avec plus de marge, par exemple)

Ajustements sur l’affichage des rendez-vous

---

app/models/rdv.rb

🚀 MEP directe, c’est gênant en production.
fixes #1909
fixes [RDV-SOLIDARITES-XQ](https://sentry.io/organizations/rdv-solidarites/issues/2801612386/?project=1811205&query=is%3Aunresolved)

🚀 Avoid touching all rdvs when updating only one

---

app/webpacker/components/calendar.js

Send agenda loading errors to sentry and improve error message

---

app/views/layouts/_rdv_a_renseigner.html.slim
config/locales/views/layouts.fr.yml

Affiche les organisations dans le bandeau à renseigner

---

Gemfile
Gemfile.lock
app/controllers/admin/plage_ouvertures_controller.rb
app/controllers/admin/rdv_wizard_steps_controller.rb
app/controllers/admin/rdvs_controller.rb
app/controllers/admin/users_controller.rb
app/form_models/admin/edit_rdv_form.rb
app/form_models/admin/rdv_form_concern.rb
app/form_models/admin/user_form.rb
app/form_models/concerns/admin/rdv_wizard_form_concern.rb
app/helpers/admin_helper.rb
app/helpers/application_helper.rb
app/helpers/rdvs_helper.rb
app/models/application_record.rb
app/models/concerns/benign_errors.rb
app/models/plage_ouverture.rb
app/models/rdv.rb
app/services/rdvs_overlapping.rb
app/views/admin/rdv_wizard_steps/step4.html.slim
app/views/application/_model_errors.html.slim
spec/form_models/admin/rdv_form_concern_spec.rb
spec/form_models/admin/user_form_spec.rb

refs #1927
C’était en fait assez facile. J’ai encore un peu de nettoyage histoire de _dry_ un peu, mais ça ne devrait pas changer grand chose.

Remove activemodel-caution

---

app/views/admin/slots/_slots.html.slim

:rocket: masque une partie de la vue si pas de next availa

---

app/models/absence.rb
app/models/concerns/recurrence_concern.rb
app/models/plage_ouverture.rb
spec/models/concerns/recurrence_concern_spec.rb
spec/services/next_availability_service_spec.rb

:rocket: récupère toutes les absences

---

app/controllers/admin/creneaux/agent_searches_controller.rb
app/views/admin/creneaux/agent_searches/index.html.slim

🚀  Transmet les id usagers à l’étape suivante des résultats

---

app/views/admin/rdvs/show.html.slim
config/locales/fr.yml

🚀 Lie à duplication avec les bonnes informations

---

spec/form_models/admin/rdv_form_concern_spec.rb

Précise la date pour s'assurer que le test fonctionne toujours, même autour de minuit.

précise la date et l'heure du RDV

---

app/controllers/admin/rdvs_controller.rb
app/models/rdv.rb
app/policies/agent/rdv_policy.rb
app/views/admin/rdvs/edit.html.slim
app/views/admin/rdvs/new_participation.js.erb
app/views/admin/rdvs_users/_form.html.slim
app/views/common/_destroy_button.html.slim
app/webpacker/components/destroy-button.js
app/webpacker/components/rdv-user-select.js
app/webpacker/packs/application_agent.js
config/routes.rb

Close #1617, suite de #1870, #1889, #1742

Notifications fines par rendez-vous (4/N) : Modification a posteriori

---

app/controllers/admin/rdvs_controller.rb
app/views/admin/rdvs/edit.html.slim
config/locales/fr.yml

Prise en compte des remarques de #1931

Corrections suite à #1931

---

app/controllers/admin/rdvs_controller.rb
app/policies/agent/rdv_policy.rb
app/views/admin/rdvs/edit.html.slim
app/views/admin/rdvs/new_participation.js.erb
app/webpacker/components/rdv-user-select.js
config/routes.rb

En fait, le dernier commit de #1931 était expérimental, non fonctionnel et n’aurait pas du être mergé (ni poussé, en fait)

Corrige admin/rdvs#edit (suite à #1962 et #1931)

---

app/views/application/_model_errors.html.slim

En démo ce matin, il y avait une erreur à la création d'une plage d'ouverture...

fix l'utilisation de benign_errors

---

app/views/common/_creneaux.html.slim

Il restait un endroit non corrigé. C'est très bizarre 
ref #1950 
ref #1980 

:rocket: Fix really don't display agent name

---

Gemfile.lock
app/controllers/admin/agents_controller.rb
app/controllers/admin/invitations_controller.rb
app/controllers/admin/referents_controller.rb
app/controllers/admin/users_controller.rb
app/models/agent.rb
app/models/concerns/rdv/address_concern.rb
app/models/concerns/text_search.rb
app/models/user.rb
app/services/rdv_exporter.rb
config/initializers/inflections.rb
config/locales/models/rdv.fr.yml
spec/models/rdv_spec.rb
spec/models/user_spec.rb
spec/services/rdv_exporter_spec.rb

~~Ça pourrait être 4 PR séparées; c’est ce que je ferai s’il y a des soucis.~~
Edit: J’ai sorti les changements sur montrose et plage_ouverture, qui casse les spec sur github.
refs #1774; refs #1879 pour l’ajout de la précision de la file d’attente à l’export

Implémente et corrige les tests désactivés

---

Gemfile
Gemfile.lock
app/models/plage_ouverture.rb
spec/models/plage_ouverture_spec.rb
spec/support/recurrence_concern.rb

Closes #1774
Extrait de #1973: Les tests échouent sur github-ci mais pas en local. Je présume que c’est un problème de timezone.

Update montrose to fix plage_ouverture with multi-week intervals

---

spec/controllers/welcome_controller_spec.rb
spec/helpers/date_helper_spec.rb
spec/helpers/plage_ouvertures_helper_spec.rb
spec/helpers/user_notifications_helper_spec.rb
spec/spec_helper.rb

Corrige le problème de couverture de test en réduisant la limite.
Cette contrainte ne devait pas lever d'erreur avant la mise à jour des dépendances (?) https://github.com/betagouv/rdv-solidarites.fr/pull/1952

Fix test coverage

---

app/helpers/application_helper.rb
app/views/admin/motifs/_visibility.html.slim
app/views/admin/users/_notifications_preferences.html.slim
app/webpacker/stylesheets/_variables.scss
app/webpacker/stylesheets/components/_utilities.scss

Show phone number in notifications prefs

---

config/routes.rb

Supprime la route welcome_motif qui n'était pas utilisée.

supprime route welcome_motif

---

app/views/welcome/welcome_agent.html.slim
spec/features/accessibility/user_pages_spec.rb

Améliore l'accessibilité de l'accueil_mds

---

app/views/layouts/_flash.html.slim
spec/features/accessibility/user_pages_spec.rb

Close #1988 
Ajoute test d'accessibilité sur lieux_path.
Correction des erreurs renvoyées par le test.

1988 accessibility lieux path

---

app/services/slot_builder.rb
spec/services/slot_builder/busy_time_spec.rb

fixes #2006
Le problème était visible aussi bien sur la recherche de créneaux côté agents que côté usager.

🚀 Fix off_days not being properly handled in creneaux

---

spec/features/accessibility/user_pages_spec.rb

Close #1992
Ajout des tests d'accessibilité sur la route mds_path. 
Pas d'erreur renvoyée. 

ajoute test accessibilité sur mds_path

---

app/views/static_pages/contact.html.slim
spec/features/accessibility/user_pages_spec.rb

Close #1993
Ajout des tests d'accessibilité sur la route mds_path.
Correction des erreurs renvoyées par le test.

1993 accessibility contact path

---

app/services/search_context.rb

Je laisse un filtre des motifs sur le service lorsque celui-ci est passé dans l'URL

🚀 fix(invitations): filter on service when present

---

app/helpers/rdvs_helper.rb
config/locales/fr.yml
config/locales/models/rdv.fr.yml
spec/helpers/rdvs_helper_spec.rb

Adapte le message de confirmation d'annulation d'un RDV

---

.github/issue_template.md
.github/pull_request_template.md

Il s’agit un peu de dire la même chose mais en changeant le style, pour que ça soit moins invisible.
AVANT LA REVUE
REVUE

Ajuste les modèles d’issue et de PR

---

db/seeds.rb

followup https://github.com/betagouv/rdv-solidarites.fr/pull/2044#issuecomment-1021387398
AVANT LA REVUE
REVUE

Set search terms in seed data for Users and Agents

---

app/controllers/admin/agents/rdvs_controller.rb
app/controllers/admin/stats_controller.rb
app/controllers/admin/territories/sector_attributions_controller.rb
app/form_models/admin/user_search_form.rb
app/helpers/users_helper.rb
app/models/absence.rb
app/models/agent.rb
app/models/file_attente.rb
app/models/rdv.rb
app/models/territory.rb
app/models/user.rb
app/policies/agent/territory_policy.rb
app/presenters/admin/rdv_user_presenter.rb
app/services/duplicate_users_finder_service.rb
app/services/merge_users_service.rb
app/services/rdv_start_coherence.rb
app/services/rdvs_overlapping.rb
app/views/admin/lieux/_lieu.html.slim
app/views/admin/merge_users/_user_agents.html.slim
app/views/admin/users/show.html.slim
spec/form_models/admin/user_search_form_spec.rb
spec/models/rdv_spec.rb
spec/models/territory_spec.rb
spec/models/user_spec.rb

🚀 Remove useless scopes

---

docs/2-contributions.md

Commentaires bienvenus :)
AVANT LA REVUE
REVUE

🚀 Ébauche de style de code dans la doc

---

app/views/admin/territories/agents/index.html.slim

Followup #2021
Ce lien:
AVANT LA REVUE
REVUE

🚀 Fix “Réinitialiser” link in territory agents search

---

app/views/admin/creneaux/agent_searches/index.html.slim

github ne me laisse pas réouvrir #2108 que j’ai fermée pour relancer la review app. Quelle frustration, l’informatique.
AVANT LA REVUE
REVUE

🚀 Clarify comments after #2106

---

app/views/admin/users/index.html.slim

lié à #2109, un peu préliminaire: c’est sur la recherche des usagers. (Le problème de performance est sur le détail d’un usager.
AVANT LA REVUE
REVUE

🚀 Performance: cache users in admin/users

---

app/controllers/admin/referents_controller.rb
app/views/admin/referents/index.html.slim

fixes #2057
AVANT LA REVUE
REVUE

🚀 Paginate agents in referents#index

---

spec/controllers/admin/stats_controller_spec.rb
spec/models/stat_spec.rb
spec/spec_helper.rb

Nous avions réduit l'attente sur la couverture de test, mais ce n'était pas nécessaire...
J'ai malgré tout ajouté un ou deux tests au passage.
AVANT LA REVUE
REVUE

couvre les stats de test

---

app/models/agent.rb
app/models/user.rb

That's the recommended approach in https://github.com/heartcombo/devise/issues/1513
Fait en regardant 2029 et 1614; j’avais ça de côté depuis un moment.
AVANT LA REVUE
REVUE

Make remember_me true by default

---

app/views/stats/index.html.slim

ref #2067
Reste à régler un niveau de contraste lié à chart.js
AVANT LA REVUE
REVUE

Améliore l'accessibilité de la page public de stats

---

app/models/plage_ouverture.rb
app/models/rdv.rb

Je m’étais laissé un “TODO” :)
AVANT LA REVUE
REVUE

Modernisation: Utiliser Duration#in_minutes

---

app/models/absence.rb
app/models/agent.rb
app/models/agent_role.rb
app/models/agent_team.rb
app/models/agent_territorial_role.rb
app/models/agents_rdv.rb
app/models/file_attente.rb
app/models/lieu.rb
app/models/motif.rb
app/models/organisation.rb
app/models/plage_ouverture.rb
app/models/rdv.rb
app/models/rdv_event.rb
app/models/rdvs_user.rb
app/models/sector.rb
app/models/sector_attribution.rb
app/models/service.rb
app/models/super_admin.rb
app/models/team.rb
app/models/territory.rb
app/models/user.rb
app/models/user_profile.rb
app/models/webhook_endpoint.rb
app/models/zone.rb

🧹🧹🧹, un peu. Je vais aussi en profiter pour ajouter https://rubygems.org/gems/annotate, si ça vous va. 
AVANT LA REVUE
REVUE

Nettoyage: Rangement des attributes, relations, scopes, etc. dans les modèles

---

app/services/slot_builder.rb
spec/services/slot_builder_spec.rb

Close #2013 
Le bug était que des créneaux déjà entamés ou complètement fini étaient affichés comme disponibles.
Avant (capture d'écran prise juste avant 11h) :
Après (capture d'écran prise juste avant 11h) :
AVANT LA REVUE
REVUE

Afficher des créneaux à venir uniquement

---

app/views/common/_search_form.html.slim
app/views/lieux/index.html.slim
app/views/lieux/show.html.slim
app/views/organisations/new.html.slim
app/views/search/_address_selection.html.slim
app/views/search/_banner.html.slim
app/views/welcome/index.html.slim
app/views/welcome/welcome_agent.html.slim
app/views/welcome/welcome_departement.html.slim
app/views/welcome/welcome_service.html.slim
app/webpacker/stylesheets/administrate/application.scss
app/webpacker/stylesheets/application.scss
app/webpacker/stylesheets/components/_lieux.scss
app/webpacker/stylesheets/components/_search_form.scss
config/locales/views/lieux.fr.yml
spec/features/accessibility/user_pages_spec.rb

Close #1989 
Ajoute test accessibilité.
Correction des erreurs renvoyées par les tests.
- **AVANT**
-  **APRES**
AVANT LA REVUE
REVUE

1989 accessibilite lieu path

---

app/helpers/rdvs_helper.rb
spec/helpers/rdvs_helper_spec.rb

Histoire de soigner les petits détails :)
REVUE

Améliorer l'affichage des rdv collectifs dans l'agenda et le back office

---

app/views/common/_header.html.slim
app/views/common/_search_form.html.slim
config/locales/devise.fr.yml

Def #2191 
**AVANT/APRES** 
AVANT LA REVUE
REVUE

remplace  boutons oranges par boutons blancs pour améliorer l'accessibilité

---

app/views/admin/territories/sms_configurations/edit.html.slim

J'avais repéré cette boulette dans une autre PR... Mais autant faire la correction à part.
AVANT LA REVUE
REVUE

Corrige un path qui a subit une drôle d'attaque

---

app/views/users/users/_form.html.slim
spec/features/users/user_can_update_their_information_spec.rb

Ce fix répare un bug introduit dans https://github.com/betagouv/rdv-solidarites.fr/pull/2204, et qui empêche les utilisateurs de modifier leur profil. Les deux issues sentry suivantes sont concernées :
- https://sentry.io/organizations/rdv-solidarites/issues/3066934020
- https://sentry.io/organizations/rdv-solidarites/issues/3068535237
4 utilisateurs sont concernés, je leur enverrai peut-être un mail pour les prévenir quand ça sera résolu
REVUE

Fix pour le formulaire utilisateur

---

app/views/admin/territories/user_fields/edit.html.slim
config/locales/views/configuration.yml

@victormours 🙇 
AVANT LA REVUE
REVUE

Mini corrections de texte sur les champs optionnels

---

spec/features/accessibility/user_pages_spec.rb

Close #2097 
AVANT LA REVUE
REVUE

vérifie l'accessiblité de la page `users_rdvs_path`

---

db/seeds.rb

Comme #2267 c'est une petite extraction du chantier sur les rdv collectifs. :)
REVUE

Rend le seed plus réaliste pour les ateliers collectifs

---

app/views/admin/users/index.html.slim

Supprimer le cache nous posera peut-être d'autre problème. 
Il faudra les traiter autrement. Ou bien trouver une meilleure
clef de cache pour cette vue partiel.
close #2195
REVUE

s'assure d'aller à la bonne fiche usager

---

app/views/users/users/edit.html.slim
app/webpacker/stylesheets/components/_cards.scss
config/locales/views/user_rdvs.fr.yml
spec/features/accessibility/user_pages_spec.rb

Close #2099
Ajoute test d'accessibilité sur la page users_informations_path et correction des erreurs remontées.
AVANT LA REVUE
REVUE

Ameliore accessibilite users informations path

---

app/views/search/_banner.html.slim
app/views/search/_lieu_selection.html.slim
app/views/search/_motif_selection.html.slim
app/webpacker/stylesheets/_variables.scss
spec/features/accessibility/welcome_pages_spec.rb

Ajoute test d'accessibilité sur la route prendre_rdv_path et correction des erreurs renvoyées.
Sélectionnez le motif : 
Sélectionnez le lieu : 
AVANT LA REVUE
REVUE

Ameliore accessibilite prendre rdv path

---

app/helpers/organisations_helper.rb
app/views/admin/organisations/setup_checklists/show_conseiller_numerique.slim
spec/controllers/admin/agents_controller_spec.rb
spec/controllers/admin/invitations_devise_controller_spec.rb
spec/factories/agent.rb
spec/features/agents/admin_can_configure_the_organisation_spec.rb
spec/helpers/organisations_helper_spec.rb

Simplification de l'onboarding pour les cnfs phase 3

---

app/services/slot_builder.rb

Je continue de penser qu'il serait bon de créer les occurrences en base.
Et en attendant, il y a sans doute moyen de progresser dans ce qui est fait aujourd'hui.
AVANT LA REVUE
REVUE

Discussion pour améliorer les perfs sur le calcul de créneau

---

app/controllers/admin/rdvs_controller.rb

Un petit fix en passant pour le bug vu ce matin 😅 
REVUE

Fix pour l'édition de l'intitulé d'un rdv collectif

---

app/views/welcome/welcome_agent.html.slim

Supprime le bouton permettant de créer une organisation, un service et un compte agent depuis la production.
AVANT LA REVUE
REVUE

Redirect to demo to create orga

---

app/views/admin/rdvs/index.html.slim

Corrige ceci: 
AVANT LA REVUE
REVUE

Fix the rdv export link

---

db/schema.rb

Added by accident in #2328. @aminedhobb c’est un reste d’une expérience ou de quelque chose à venir?
AVANT LA REVUE
REVUE

Remove the “tokens” table in schema.rb

---

app/controllers/admin/rdvs_collectifs_controller.rb
app/services/notifiers/rdv_base.rb
app/services/notifiers/rdv_cancelled.rb
app/services/notifiers/rdv_collectif_participations.rb
app/services/notifiers/rdv_created.rb

Envoie les notifs pour l'ajout de participants, et corrige le bug pour les modifications
REVUE

Correctif pour les notifications de participants aux rdv collectifs

---

app/views/admin/organisations/index.html.slim

Ce commentaire avait été placé à une époque où le code en dessous
n'était pas le même...
C'est des trucs que j'avais faits sans trop m'en rendre compte dans la PR sur les droits d'accès. Je les extrais pour alléger la PR #2283
REVUE

Supprime un commentaire obsolète

---

app/helpers/motifs_helper.rb
app/views/admin/motifs/_motif.html.slim
app/views/admin/users/_responsible_form_fields.html.slim
app/webpacker/stylesheets/components/_motifs.scss
config/locales/motifs.yml
spec/helpers/motifs_helper_spec.rb

Close #2196
avant :
après : 
AVANT LA REVUE
REVUE

List motif collectif

---

app/services/sms_sender.rb

Une petite typo semble être passé à travers nos revues...
REVUE

Un petit oubli qui fait quelques erreurs dans l'envoie de SMS

---

db/seeds.rb

Micro PR pour un micro-fix des seeds utiles à rdv-insertion (désolé et merci 🙏)

fix(seeds): Petit correctif pour les seeds utiles à rdv-insertion

---

app/jobs/cron_job.rb
app/models/concerns/webhook_deliverable.rb
spec/jobs/cron_job/destroy_old_rdvs_job_spec.rb
spec/models/webhook_deliverable_spec.rb

Close #2345
AVANT LA REVUE
REVUE

Supprimer automatique les RDV de plus de 2 ans

---

app/controllers/stats_controller.rb
app/models/organisation.rb
app/models/rdv.rb
app/models/receipt.rb
app/models/stat.rb
app/models/territory.rb
app/views/stats/index.html.slim
config/locales/models/receipt.fr.yml
config/routes.rb

refs #1431
Ça ressemble à ça :
J’ai quelques PR à venir pour du nettoyage dans stats et pour la suppression des RdvEvent.
AVANT LA REVUE
REVUE

Affichage des receipts dans /stats

---

app/jobs/cron_job.rb
spec/jobs/cron_job/destroy_old_plage_ouverture_job_spec.rb

Close #2227
Mise en place de la suppression des plages d'ouvertures fermées depuis plus d'un mois
Mise en place des tests
AVANT LA REVUE
REVUE

Suppression plages ouvertures

---

app/controllers/admin/territories/agents_controller.rb

Un petit bout de nettoyage extrait de la grosse PR sur les droits d'accès.
ref #2209
REVUE

Supprime une méthode inutilisée

---

app/views/agents/mailer/invitation_instructions.html.erb
config/locales/devise.fr.yml

Un autre petit morceau de #2209 que je sors. Ça prépare le travail.
REVUE

Réduit la référence à l'organisation dans les messages

---

app/controllers/admin/rdvs_collectifs_controller.rb
app/views/admin/rdvs_collectifs/new.html.slim
config/locales/fr.yml
spec/features/agents/rdvs_collectifs/full_lifecycle_spec.rb

Closes #2351
avant : 
après :
Revue :

Collectif lieux ponctuels

---

app/views/users/relatives/edit.html.slim
app/views/users/relatives/new.html.slim
config/routes.rb
spec/features/accessibility/users_pages_spec.rb
spec/features/users/user_can_search_rdv_spec.rb

close #2102 
À propos du formulaire sur les `relatives` dans la vue usager
REVUE

rend accessible le formulaire relative user

---

app/javascript/components/calendar.js

Closes #2272
#Captures :
avant: 
après:
Revue :

ajout d'une vue en liste des rdvs sur une semaine

---

app/blueprints/lieu_blueprint.rb

Closes #2379
Dans la mesure où c’est purement additif, je ne pense pas qu’on ait besoin  de versionner.
Revue :

Add :single_use? to Lieu Blueprint

---

app/javascript/components/select2-inputs.js

Closes #2416
Avant:
Après:
Revue :

Améliore le message dans les champs de recherches vides

---

docs/decissions/2022-05-12-mise-en-place-bug-watcher.md

Il y a quelques point que nous n'avons pas clarifié : 
- Est-ce que nous faisons bien 15 jours ?
- Comment fait-on pendant les jours off de la personne désignée ?
- Est-ce qu'on affiche le planning des tours à l'avance dans l'agenda des jours off ?
- Est-ce que cette personne serait aussi la personne qui aide Nesserine et Myriam à traiter les tickets Zammad ?
- Quid du médico-social et des CNFS ? Est-ce que nous considérons une seule et même équipe dans ce cas ?
En dehors de comment on fait pour les 1/5 de chacune et chacun d'entre nous, et de l'histoire médico-social et CNFS, je suis plutôt pour faire 2 semaines, être la personne « référente tech » pour Myriam et Nesserine sur la période, mettre tout ça dans l'agenda.

Document la prise de décision sur le bug watcher

---

app/controllers/admin/rdvs_controller.rb
app/models/lieu.rb
app/views/admin/rdvs/edit.html.slim
config/locales/fr.yml

Pour pouvoir débugger tranquillement

Revert PR 2506

---

app/models/concerns/rdv/address_concern.rb
app/services/rdv_exporter.rb
spec/models/rdv_spec.rb

Tout est expliqué dans le commentaire, dîtes-moi si c'est pas clair !

Réparer un crash à l'export des RDV

---

docs/decisions/2022-06-13-garder-la-doc-technique-dans-le-depot-applicatif.md
docs/decisions/_template.md

Je suis à disposition pour discuter de tout ça ! :handshake:

Ajout ADR "Garder la doc technique dans le dépôt applicatif"

---

app/views/admin/territories/show.html.slim
spec/features/accessibility/configuration_pages_spec.rb

Nous n'avions pas fait de ticket sur ce point-là. Mais c'est une page nécessaire à tester... Comme toutes les pages.
Avant
Après
Revue :

Automatise le test du module de configuration

---

docs/decisions/2022-06-09-deploiement.md
docs/decisions/2022-06-09-internationalisation.md

À propos 
- de l'internationalisation
- du déploiement continu

Ajoute les décisions de jeudi 9 juin

---

spec/features/accessibility/configuration_pages_spec.rb

automatise le test d'accessibilité SMS config

---

app/views/layouts/application_agent.html.slim
spec/features/anybody/anybody_can_see_legal_pages_spec.rb

Répare les liens CGU, mention légales et politique de confidentialité.

---

spec/models/paper_trail_version_spec.rb

La PR en automerge est partie dès la validation. Je n'ai pas eu le temps
de prendre en compte la suggestion de Victor que voici.
ref #2603 
Revue :

Précise le titre d'une spec

---

app/views/admin/territories/agents/edit.html.slim

Pour limiter les organisations affichées sur les fiches des agents...
Revue :

Ajoute un filtre sur le territoire courant

---

app/controllers/admin/rdv_wizard_steps_controller.rb
app/controllers/users/rdv_wizard_steps_controller.rb
app/models/concerns/benign_errors.rb
spec/form_models/admin/rdv_form_concern_spec.rb

Les 4 commits expliquent assez bien l'intention des fixes, je vous laisse me dire ce que vous en pensez !
Revue :

Petites corrections autour du wizard form

---

app/models/agent.rb
app/models/concerns/text_search.rb
app/models/user.rb
spec/models/concerns/text_search_spec.rb

Mais sans faire de migration pour rafraichir les données utilisées pour le tri.

Tri les agents et usager sur l'aspect visible

---

app/views/admin/rdvs/_rdv_search_form.html.slim

Pour filtrer les lieux dans les filtres pour afficher les RDV
Closes #2576 
Revue :

Affiche les lieux actif trié par nom

---

app/views/common/_footer_users.html.slim
config/routes.rb

Pour tester en recette : https://production-rdv-solidarites-pr2640.osc-secnum-fr1.scalingo.io/
Pour signaler à [Dashlord que nous avons un budget](https://dashlord.incubateur.net/url/www-rdv-solidarites-fr/best-practices/#budget_page) ;
Pour permettre aux curieuses et aux curieux d'en savoir plus sur notre budget ;
Cette PR ajoute une entrée de menu qui ponte vers le pad public de budget de beta.gouv.
Revue :

Ajoute un lien vers le budget

---

docs/decisions/2022-07-28-tableau-projet-dans-github.md

Ajoute un petit morceau de décision de ne pas aller vers les nouveaux tableaux projet de github

Ajoute une décision de ne pas migrer de board

---

docs/liste-champs-db.md

C'était une page maintenue manuellement dans la doc. Il serait intéressant de pouvoir la générer automatiquement. C'est un élément utile (nécessaire) pour le RGPD.
Attention à faire en sorte que les champs soient « compréhensible » et donc pas le nom technique de la colonne.

Ajoute un doc de la liste des champs

---

app/controllers/admin/invitations_devise_controller.rb
app/controllers/admin/territories/invitations_devise_controller.rb

Pour les France Service, on va ajouter un nouveau service, et on commence à en avoir beaucoup. Sur les pages pour ajouter un nouvel agent, c'est beaucoup plus pratique si on trie les services par ordre alphabétique.
Revue :

Ordonne les services par nom pour les trouver plus facilement

---

app/views/stats/index.html.slim

Indiquer sur la page de stats que les chiffres sont pour les 2 domaines

---

.env.sample

Remove env variable SENTRY_DSN_RAILS to disable Sentry in dev env

---

app/form_models/admin/rdv_form_concern.rb
spec/form_models/admin/rdv_form_concern_spec.rb

Nous avons reçu beaucoup de message aujourd'hui à propos d'un blocage sur la création de RDV
- https://zammad10.ethibox.fr/#ticket/zoom/2765
- https://zammad10.ethibox.fr/#ticket/zoom/2764
- https://zammad10.ethibox.fr/#ticket/zoom/2763
- https://zammad10.ethibox.fr/#ticket/zoom/2762
- https://zammad10.ethibox.fr/#ticket/zoom/2760
- https://zammad10.ethibox.fr/#ticket/zoom/2759
- https://zammad10.ethibox.fr/#ticket/zoom/2758
- https://zammad10.ethibox.fr/#ticket/zoom/2756
- https://zammad10.ethibox.fr/#ticket/zoom/2755
- https://zammad10.ethibox.fr/#ticket/zoom/2749
Beaucoup transmis par le 26, mais certains par le 83 aussi. J'imagine que d'autres départements ont eu le problème, mais n'ont pas encore fait remonter l'info.
C'est dans la PR #2818 qu'un point nous a échappé : la …

Prend en compte la vérification users et agents pour la recherche de duplication de RDV

---

app/views/search/address_selection/_rdv_aide_numerique.html.slim
app/views/static_pages/presentation_for_cnfs.html.slim

Seb m'a fait remarqué des fautes d'orthographe, et j'ai aussi vu sur mon téléphone une amélioration de largeur en version mobile.

Petits correctifs sur la landing page CNFS

---

spec/features/agents/agent_can_configure_online_booking_spec.rb

Je n'ai pas compris pourquoi ce test est flacky sur le CI (mais pas en local, naturellement) : 
Du coup j'ai modifié le test en croisant les doigts pour qu'il passe à chaque fois sur le CI (j'ai l'impression que oui).
Revue :

fix flacky test

---

app/views/admin/agents/absences/index.json.jbuilder

Améliorer la visibilité des plages dans le calendrier

---

app/controllers/admin/agents/plage_ouvertures_controller.rb
app/javascript/components/calendar.js
app/views/admin/agent_agendas/show.html.slim
app/views/admin/agents/plage_ouvertures/index.json.jbuilder
app/views/admin/plage_ouvertures/index.html.slim
config/locales/views/plage_ouvertures.fr.yml
spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
spec/features/agents/agent_can_search_plage_ouverture_spec.rb

Add calendar in index plage ouverture

---

app/controllers/admin/rdvs_controller.rb
app/views/admin/rdvs/edit.html.slim

Ajouter le lien 'créer un usager' dans le formulaire d'édition d'un rdv

---

docs/decisions/2022-10-06-architecture-concerns.md

Suite à la réunion technique du 221006, on ajoute la décision prise aux ADR.

add adr about capacity concerns

---

docs/5-role-de-vigie.md

Suite à la rétro de tout à l'heure, voici une proposition d'extension du rôle de la vigie qui récapitule ce qu'on s'est dit.
Si vous pensez à des choses, objections, questions, réactions, etc... que vous n'aviez pas en tête pendant la rétro, mettez les en commentaire ici. :)

Extension du role de vigie

---

app/services/concerns/users/creneaux_search_concern.rb
spec/services/users/creneaux_search_spec.rb

Closes https://sentry.io/organizations/rdv-solidarites/issues/3688034098/events/ad520386c02042cdb6bf079f29d60bac/?alert_rule_id=899770&alert_timestamp=1666349244048&alert_type=email&environment=production&project=1811205&referrer=alert_email
Revue :

:ambulance: find geo attributed agents when lieu is nil

---

app/controllers/admin/rdvs_controller.rb
app/mailers/agents/export_mailer.rb
app/models/rdv.rb
spec/models/rdv_spec.rb

https://zammad10.ethibox.fr/#ticket/zoom/3030
Problème au niveau du search_for du rdv. Un agent dans une même organisation et dans un même service ne pouvait plus voir les rdv d'un autre agent dans la même organisation et service.

Fix bug de scope sur le search_for du RDV

---

spec/requests/api/v1/organizations_request_spec.rb
swagger/v1/api.json

documentation API organizations

---

spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/public_links_request_spec.rb
spec/swagger_helper.rb
swagger/v1/api.json

On documente le endpoint `public_links` avec swagger.
Revue :

document PublicLinks with rswag

---

app/controllers/api/v1/invitations_controller.rb
spec/requests/api/v1/groups_request_spec.rb
spec/requests/api/v1/invitations_request_spec.rb
spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/organizations_request_spec.rb
spec/requests/api/v1/rdvs_request_spec.rb
spec/swagger_helper.rb
swagger/v1/api.json

Ici on documente le endpoint `invitations` avec swagger.
Revue :

document Invitation with rswag

---

spec/requests/api/v1/agents_request_spec.rb
spec/requests/api/v1/groups_request_spec.rb
spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/organizations_request_spec.rb
spec/swagger_helper.rb
swagger/v1/api.json

document Agent API with rswag

---

spec/requests/api/v1/agents_request_spec.rb
spec/requests/api/v1/invitations_request_spec.rb
spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/rdvs_request_spec.rb
spec/requests/api/v1/users_request_spec.rb
spec/swagger_helper.rb
swagger/v1/api.json

On documente les endpoints autour du `user` avec swagger.
Revue :

document User endpoints with rswag

---

app/views/common/_franceconnect_button.html.slim
spec/features/accessibility/users_pages_spec.rb

- Ajout d'un `alt` sur les images FranceConenct
- Suppression d'un `h4` inutile.
Closes #2061
Revue :

Automatise test RGAA sur new session

---

config/application.rb
config/environments/test.rb
config/initializers/rack_attack.rb
spec/requests/api/v1/groups_request_spec.rb
spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/organizations_request_spec.rb
spec/requests/api/v1/paginated_request_spec.rb
spec/requests/api/v1/public_links_request_spec.rb
spec/support/api_spec_matchers.rb

Améliore les tests en variabilisant la config de rate limiting et de pagination dans cet environnement
Revue :

Configuration test for pagination and rate limiting

---

app/models/concerns/motif/category.rb
config/locales/models/motif.fr.yml
db/migrate/20221109101323_add_rsa_atelier_collectif_to_motif_category.rb
db/schema.rb

Encore une PR pour ajouter une catégorie de motif 😄. On devrait bientôt atteindre la limite des catégories possibles.

feat(migration) Add rsa atelier collectif to motif category

---

app/services/users/geo_search.rb

Remontée Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3729949637
Un renommage avait été oublié dans #3000. :wink:

Bug : le test de sectorisation plante car on appelle une méthode inconnue

---

spec/features/accessibility/users_pages_spec.rb

Ajoute un test d'accessibilité sur les écrans usagers.
Closes #2065 et #2066

Ajoute deux tests automatisé d'accessiblité

---

spec/features/accessibility/agents_pages_spec.rb

Les rdv sont créé 3 jours dans le futur, donc cette spec se mettait à échouer quand on arrive au mercredi et que les rdv ne s'affichent plus parce qu'ils sont le samedi.
On corrige ça avec un travel_to et des starts at pour que la date de la spec soit un lundi et que les rdv soient le mercredi

Corrige une spec

---

.gitignore
.rubocop.yml
README.md
docs/api/v1/description_api.md
spec/rails_helper.rb
spec/requests/api/v1/absences_request_spec.rb
spec/requests/api/v1/agents_request_spec.rb
spec/requests/api/v1/invitations_request_spec.rb
spec/requests/api/v1/motifs_request_spec.rb
spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/public_links_request_spec.rb
spec/requests/api/v1/rdvs_request_spec.rb
spec/requests/api/v1/user_profiles_request_spec.rb
spec/requests/api/v1/users_request_spec.rb
spec/support/api_spec_shared_examples.rb
spec/swagger_helper.rb
swagger/v1/api.json

Pour tester : https://demo-rdv-solidarites-pr3080.osc-secnum-fr1.scalingo.io/api-docs
On finalise ici la nouvelle documentation de l'API, avec : 
- des corrections mineures
- l'ajout de généralités, de codes de retour, d'erreur, de détails sur l'authentification
- le DRY de la spec pour éviter de répéter / d'encombrer la spec avec les cas d'erreur pas très intéressants
Closes #3013
Revue :

API doc fine tuning

---

app/controllers/users/rdv_wizard_steps_controller.rb

Petite faute de frappe sur un path

Correction de path

---

.env.sample
app/controllers/admin/rdvs_controller.rb
app/controllers/inclusion_connect_controller.rb
app/controllers/omniauth_callbacks_controller.rb
app/controllers/users/rdvs_controller.rb
config/initializers/content_security_policy.rb
docs/0-docs.md
docs/5-role-de-vigie.md
docs/decisions/2022-12-12-migrer-sentry-vers-instance-incubateur-beta.md

L'ADR présent dans la PR contient toutes les infos sur le contexte de ces changements.
Pour le reste, je mets des commentaires sur le diff de la PR.
Revue :

Migration vers Sentry de l'incubateur beta

---

app/views/admin/territories/agents/edit.html.slim

ref https://0pjwg.mjt.lu/lnk/AXMAAAbe-tcAAAAAAAAAAAuGem0AAAAAOA0AAAAAABxNxQBjruVTkNPBD0uNSqmZs0JnRTGUuQAGSdk/3/MMxMh4KFla7EfaeTD2S1mA/aHR0cHM6Ly9zZW50cnkuaW5jdWJhdGV1ci5uZXQvb3JnYW5pemF0aW9ucy9iZXRhZ291di9pc3N1ZXMvMTc0NzQvP3JlZmVycmVyPWFsZXJ0X2VtYWlsJmVudmlyb25tZW50PXByb2R1Y3Rpb24
Il semblerait qu'il manquait une URL à remanier suite a la modification #3216 
Revue :

Utilise l'`index` du `Admin::TeamsController`

---

app/sms/users/rdv_sms.rb

Juste une petite PR pour passer la suggestion d'amélioration faite dans la PR précédente : https://github.com/betagouv/rdv-solidarites.fr/pull/3234#discussion_r1062248646

Utilise le truncate de rails

---

app/helpers/admin_helper.rb

Mise à jour vers la nouvelle page de FAQ suite à la demande de Nesserine

Mise à jour du lien vers la FAQ CnFS

---

app/models/concerns/motif/category.rb
config/locales/models/motif.fr.yml
db/migrate/20230116135446_add_rsa_spie_to_motif_category.rb
db/schema.rb

Nouvelle category de motif RSA - SPIE

feat(migration) Add rsa spie to motif category

---

app/models/concerns/motif/category.rb
config/locales/models/motif.fr.yml
db/migrate/20230118141208_add_rsa_integration_information_to_motif_category.rb
db/schema.rb

ajout d'un nouveau motif category : `rsa_integration_information`

feat(motif category): add rsa integration information 

---

app/models/concerns/motif/category.rb
config/locales/models/motif.fr.yml
db/migrate/20230119140851_add_rsa_atelier_competences_and_rsa_atelier_rencontres_pro_to_motif_category.rb
db/schema.rb

J'ajoute les nouvelles catégories `RSA - Atelier compétences` et `RSA - Atelier rencontres professionnelles` .
Le nombre de catégories commence à être lourd, il faudra repenser cette logique pour avoir une ressource à part entière.

Ajout de 2 nouvelles catégories de motifs

---

app/controllers/api/v1/user_profiles_controller.rb
app/policies/agent/user_profile_policy.rb
config/routes/api.rb
spec/requests/api/v1/user_profiles_request_spec.rb
swagger/v1/api.json

Dans cette PR j'ajoute un endpoint pour pouvoir retirer un utilisateur d'une organisation via l'API.

feat(api): Add delete user_profile endpoint

---

app/views/admin/users/_responsible_form_wrapper.html.slim
spec/features/agents/agent_can_create_relative_and_responsible_spec.rb

ref https://zammad10.ethibox.fr/#ticket/zoom/4239
Ceci est un patch pour corriger la création d'usager combiné (un proche et son responsable).

Patch la création d'usager combiné

---

spec/features/agents/admin_can_configure_agent_access_rights_spec.rb

Cette PR ajoute une feature spec manquante dans la PR #3228

Ajoute une spec manquante

---

app/controllers/admin/rdvs_controller.rb
app/presenters/agent_removal_presenter.rb
app/views/admin/organisations/index.html.slim
app/views/admin/referent_assignations/index.html.slim
app/views/admin/territories/sector_attributions/_form.html.slim
app/views/admin/territories/sectors/show.html.slim
app/views/agents/registrations/edit.html.slim
app/views/search/_nothing_to_show.html.slim
app/views/static_pages/rdv_solidarites_presentation_for_agents.html.slim
app/views/users/registrations/edit.html.slim
config/locales/devise.fr.yml
config/locales/models/motif.fr.yml
config/locales/views/admin_rdvs.fr.yml
spec/controllers/search_controller_spec.rb
spec/features/users/user_can_manage_collective_rdv_spec.rb

récupération d'une PR de [ZoeThivet](https://github.com/ZoeThivet)
https://github.com/betagouv/rdv-solidarites.fr/pull/3329/commits/e8216b52f07f91efe53b895e32726917237a4a8a
co-authored-by: ZoeThivet

fix(wording): Fix typos & implement epicene writing in some places

---

app/models/domain.rb
app/views/admin/static_pages/support.html.slim

Pour tester : https://demo-rdv-solidarites-pr3401.osc-secnum-fr1.scalingo.io/
mis à jour des liens vers la documentations pour rdv-solidarité et rdv-aide-numérique.
Revue :

Liens vers la nouvelle documentation

---

app/views/admin/rdv_wizard_steps/_rdv_user_form.html.slim
app/views/admin/rdvs_users/_form.html.slim

Suite à une erreur dans #3433
Revue :

Bug: la checkbox d'activation des rappels a disparu

---

app/views/common/_footer_users.html.slim

Pour tester : https://demo-rdv-solidarites-pr3444.osc-secnum-fr1.scalingo.io/
Modification du lien vers la documentation utilisateur sur la page d'accueil. 
Revue :

modification du lien vers la documentation en page d'accueil

---

app/jobs/transfer_email_reply_job.rb
config/locales/mailers.fr.yml
spec/jobs/transfer_email_reply_job_spec.rb

Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3471

Amélioration de l'explication quand on transmet un mail d'usager au support

---

spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb

Cette spec avait une date de péremption. En utilisant "lundi dans deux semaines" je pense qu'elle devrait ne pas être flaky. :crossed_fingers: 
Revue :

Correction d'une spec périmée

---

app/models/motif.rb
spec/models/motif_spec.rb

voir https://sentry.incubateur.net/organizations/betagouv/issues/18611
Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3503

Correctif du soft delete pour les motifs qui ont des rdv soft deleted

---

app/services/users/geo_search.rb

Fixes https://github.com/betagouv/rdv-solidarites.fr/issues/3419
Pour plus d'infos sur la solution adoptée, il y a une explication détaillée ici: https://github.com/betagouv/rdv-solidarites.fr/issues/3419#issuecomment-1540073606

[3419] Ameliorer la requete sur l'ensemble des motifs individuels

---

app/controllers/api/ants/editor_controller.rb
app/controllers/super_admins/mairie_comptes_controller.rb
db/seeds/rdv_mairie.rb
scripts/clone_motifs.rb
spec/features/users/user_can_search_rdv_on_rdv_mairie_spec.rb
spec/requests/api/ants/available_time_slots_spec.rb

Cette PR corrige le branchement à l'api de l'ants qui faisait qu'on n'avait les créneaux que pour une seule mairie, et ajoute les distinctions entre les différents types de motifs proposés dans #3636
Closes #3636
Closes #3637

Correctif et amélioration du branchement à l'api de l'ants

---

app/controllers/api/v1/rdvs_controller.rb
app/models/rdv.rb
app/models/user.rb
spec/requests/api/v1/rdvs_request_spec.rb
swagger/v1/api.json

Closes #3619
J'ai préféré utiliser des scopes pour une meilleure lisibilité.
J'ai mis à jour la documentation Swagger.

Ajout de params pour filtrer par date les rdv dans l'index de l'API

---

app/mailers/custom_devise_mailer.rb
app/views/agents/mailer/invitation_instructions.html.erb
app/views/devise/mailer/invitation_by_superadmin_instructions.html.erb
config/locales/devise.fr.yml
spec/mailers/previews/custom_devise_mailer_preview.rb

Mise à jour du mail d'invitation

---

.rubocop.yml
spec/jobs/webhook_job_spec.rb

Fix du build linter et test aprés modification des constantes des webhook job (temporaire)

---

app/controllers/admin/agents_controller.rb
app/presenters/admin/prescripteur_experiment_motif_presenter.rb
spec/features/prescripteurs/motifs_for_prescripteur_only_spec.rb

Juste une pr pour nos feature flags bricolés

Activation des prescripteurs pour l'aveyron, et des intervenants pour les nouveaux cdad

---

app/presenters/admin/prescripteur_experiment_motif_presenter.rb

Demandé via Nesserine par la référente du médico-social dans les ardennes

Ouverture des prescripteurs a la demo des ardennes

---

app/jobs/concerns/default_job_behaviour.rb

Décrire le pourquoi des modifications
Closes #issue_number
Revue :

Correction des specs après un merge trop rapide

---

app/controllers/admin/rdvs_controller.rb

Reverts betagouv/rdv-solidarites.fr#3819

Revert "Changer l'ordre d'affichage des RDVs"

---

app/jobs/rdvs_export_send_email_job.rb

Si je m'étais moins précipité, j'aurais chopé cette erreur dès #3842 
Revue :

Correction du crash des exports (suite et fin)

---

app/controllers/api/v1/users_controller.rb
app/policies/agent/user_policy.rb
app/views/api/v1/users/invite_get.json.jbuilder
config/routes/api.rb
spec/requests/api/v1/users_request_spec.rb

Comme dit François :
Moins de code, plus de joie.
Nettoyage suite à https://github.com/betagouv/rdv-solidarites.fr/pull/3690
Le endpoint que je retire n'a pas été utilisé en 3 mois.

Nettoyage d'un endpoint inutilisé
