betagouv/rdv-solidarites.fr

app/services/duplicate_users_finder_service.rb
db/migrate/20220411085428_index_users_birth_date_and_first_name.rb
db/schema.rb

`find_duplicate_based_on_identity` is quite slow because `User#birth_date` (and `User#first_name`) are not indexed
Dans les logs de performance, c’est `Admin::UsersController#create` qui est particulièrement lent, mais ça pointe directement sur `duplicate_users_finder_service.rb` avec une grosse requête SQL sur birth_date, donc on sait où agir.
SQL EXPLAIN, avant/après:
```
=> EXPLAIN for: SELECT "users".* FROM "users" LEFT OUTER JOIN "rdvs_users" ON "rdvs_users"."user_id" = "users"."id" LEFT OUTER JOIN "rdvs" ON "rdvs"."id" = "rdvs_users"."rdv_id" WHERE "users"."deleted_at" IS NULL AND "users"."birth_date" = $1 AND "users"."first_name" ILIKE 'toto' AND "users"."last_name" ILIKE 'toto' GROUP BY "users"."id" ORDER BY COUNT(rdvs.id) DESC [["birth_date", "2022-04-01"]]
QUERY PLAN …
```

Optimize User duplicate search on creation

---

config/locales/devise.fr.yml

 Je me suis rendu compte qu'il manquait ce sujet, et que du coup les mails arrivaient avec le sujet "Invitation instructions cnfs", ce qui est pas top. C'est bien si on peut réparer ça avant de lancer les invitations d'aujourd'hui.
REVUE

Ajout du sujet des mails d'invitation cnfs

---

app/models/plage_ouverture.rb
app/services/plage_ouverture_overlap.rb
db/seeds.rb
spec/services/plage_ouverture_overlap_spec.rb

Sur skylight c’est ici: https://www.skylight.io/app/applications/RgR7i58P67xN/recent/6h/endpoints/Admin::PlageOuverturesController%23index?responseType=html
En local avec un agent qui a 4 PO hebdomadaires sur 4 jours de la semaines, je passe de ~500 ms à ~100 ms pour plages_ouvertures#index.
Je vais peut-être ajouter un ou deux tests spécifiques, si les cas que je mets de côté ne sont pas déjà couverts par les tests.
AVANT LA REVUE
REVUE

Améliore les performances de l’affichage des plages d’ouverture

---

app/models/plage_ouverture.rb
app/services/plage_ouverture_overlap.rb
spec/services/plage_ouverture_overlap_spec.rb

followup #2355. Je ne sais pas si c’est vraiment plus facile à comprendre; je crois que c’est équivalent :p
AVANT LA REVUE
REVUE

Clarifie PlageOuverture#overlapping_plages_ouvertures_candidates

---

app/controllers/admin/rdvs_collectifs_controller.rb

Suite à la discussion avec Christelle, cette PR corrige le bug sur l'envoi de notification à l'agent avec un ics.
Les notifications pour les ajouts de participants sont un peu plus compliquées à gérer, donc je préfère les faire dans une PR à part, et déjà corriger ça.
Par ailleurs, j'ai aussi remarqué que les intitulés ne s'affichent pas correctement dans les mails. Je vais essayer de corriger ça aussi dans une pr suivante.
J'ai testé en local, et j'ajouterai plus de tests la semaine prochaine
REVUE

Fix pour les notifications qui ne partent pas à la création de rdv collectif

---

app/helpers/rdvs_helper.rb
app/models/concerns/payloads/rdv.rb
app/models/rdv.rb
app/views/mailers/common/_rdv_overview.html.slim

Avant : 
Après : 
Il y avait un comportement différent pour la méthode `#name` entre les rdv activerecord et les payload de rdv. :-/
Ce fix un peu rapide ajoute un alias de méthode, mais la semaine prochaine ça mériterait de prendre un peu plus de temps pour réfléchir à renommer la colonne, ou la méthode name des payloads.
On discutait avec nicolas d'arrêter d'utiliser les payloads, et c'est un argument de plus dans cette direction.
REVUE

Corrige l'intitulé des rdv collectifs dans les mailers

---

app/views/admin/rdvs/edit.html.slim
db/seeds.rb

Il y a plus de 900 motifs en production. Une fois qu’on sait ce qu’on cherche, [le diagramme de performances est évident](https://www.skylight.io/app/applications/RgR7i58P67xN/recent/6h/endpoints/Admin::RdvsController%23edit?mode=memory&responseType=html).
En local avec 1000 motifs, je diminue le temps de chargement de la page par deux.
(Et en plus, le formulaire interdit la modification de motif.)
AVANT LA REVUE
REVUE

Ne pas charger tous les Motifs quand on modifie un Rdv

---

app/controllers/admin/agents/absences_controller.rb
app/controllers/admin/agents/plage_ouvertures_controller.rb
db/migrate/20220419093944_add_plage_ouverture_absence_index_updated_at.rb
db/schema.rb

Pour les agents qui configurent beaucoup de plages d’ouvertures, je crois qu’on y gagne pas mal. À surveiller: https://www.skylight.io/app/applications/RgR7i58P67xN/recent/6h/endpoints/Admin::Agents::PlageOuverturesController%23index?responseType=json
Utiliser une relation AR comme clé de cache utilise en fait son `COUNT` et `MAX(updated_at)`; c’est ce qu’on veut pour invalider le cache quand une plage d’ouverture (ou une absence) est ajoutée, modifiée ou supprimée.
Autre suggestion: j’utiliserais bien `fresh_when` dans ces méthodes; peut-être que ça rendrait même le cache redondant.
AVANT LA REVUE
REVUE

Garder en cache les occurrences des plages d’ouverture et des absences

---

app/views/admin/static_pages/support.html.slim
app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/devise/mailer/invitation_instructions_cnfs.text.erb
app/views/search/_motif_selection.html.slim
app/views/static_pages/contact.html.slim
app/webpacker/components/calendar.js
docs/2-contributions.md
public/404.html
public/500.html
spec/controllers/search_controller_spec.rb

Comme discuté suite à la mise en place de Zammad, cette PR affiche l'adresse support@rdv-solidarites.fr plutôt que contact@rdv-solidarites.fr à la plupart des endroits où on propose de nous contacter.
L'adresse contact reste celle qui envoie les mails.
J'ai aussi gardé l'adresse de contact dans la documentation pour nous signaler des vulnérabilités sur l'appli ou pour discuter de pull request, vu que ça me semblait être un autre niveau de discussion que le support utilisateur habituel.
REVUE

Afficher l'adresse de support plutôt que celle de contact

---

app/services/next_availability_service.rb
app/views/search/_lieu_selection.html.slim

Cette PR fixe les erreurs 500 que l'on avait lorsque l'on choisissait certains lieux (voir [ici](https://sentry.io/organizations/rdv-solidarites/issues/3036704829/?project=1811205&query=is%3Aunresolved) et [ici](https://sentry.io/organizations/rdv-solidarites/issues/3037209142/?project=1811205&query=is%3Aunresolved) sur Sentry).
En fait le problème est venu je crois après l'introduction des `start_booking_delay` et `end_booking_delay` dans #2325 où on appelait la méthode `step` sur des instances `ActiveSupport::TimeWithZone` et non plus sur des instances de `Date` ou `Datetime`.
J'en ai également profité pour faire un petit hack pour afficher `Aucune disponibilité` lorsqu'il y en a vraisemblablement pas. Pour ça je pars du postulat que les motifs qui ont le même nom ont le même …

fix(creneaux): Fix error when selecting a lieu

---

app/services/next_availability_service.rb

J'avais oublié de convertir le terme en argument de `step` dans  #2380 🤦‍♂️

fix(creneaux): Re-set proper type when searching next availability

---

.gitignore

Il manque le répertoire pids après le clone.
AVANT LA REVUE
REVUE

correction du gitignore

---

app/mailers/admins/system_mailer.rb

En discutant avec Nesserine et Myriam, elle m'ont dit que ce mail n'était jamais pertinent pour elles, et que ça ne fait qu'ajouter du bruit (surtout qu'on le reçoit depuis la démo en plus de la prod).
Cette pr fait qu'il ne sera envoyé qu'aux devs (cette adresse de forwarding est définie dans gandi)
REVUE

Envoyer le mail de monitoring seulement aux devs

---

app/views/admin/users/_responsible_form_fields.html.slim

Close #2374
avant : 
après :
AVANT LA REVUE
REVUE

retour à la ligne dans le formulaire du nouvel usager

---

db/seeds.rb

Dans cette PR, j'ajoute quelques lignes aux seeds afin d'obtenir des territories et organisations matchant les seeds de rdv-insertion. Les deux territoires et trois organisations ajoutés sont rattachés à un nouvel agent (Alain Sertion).

feat(seeds): ajouter des seeds pour rdv-insertion

---

app/views/common/_footer_users.html.slim

Un cnfs nous a fait remarquer que ce lien sur la page d'accueil était mort.
Il faudrait aussi qu'on mette à jour cette page de doc dans un second temps pour intégrer les nouvelles infos.
REVUE

Corrige un lien mort

---

app/controllers/admin/users_controller.rb
spec/support/select2_spec_helper.rb

`Admin::UsersController#search` est utilisé par les select de users, pour le rdv wizard, pour rdv#index, etc. Quand il n’y pas de nom saisi, on retourne “les dix premiers utilisateurs”, pour avoir quelque chose dans le select. C’est une mauvaise idée:
* déjà parce qu’on ne devrait pas faire fuire d’informations usagers, c’est pour ça que users#index est vide par défaut
* mais aussi parce qu’on trie par `LOWER(last_name)` pour prendre les dix premiers (dans `User#order_by_last_name`) que ce n’est pas indexé, et que ça veut dire qu’on trie tous les usagers de l’organisation.
AVANT LA REVUE
REVUE

Perf: Avoid sorting all users by name

---

app/controllers/lieux_controller.rb
app/services/concerns/users/creneaux_search_concern.rb
app/services/search_context.rb
app/views/search/_lieu_selection.html.slim

Nous rencontrons des soucis lors de l'affichage des prochaines disponibilités: 
* Nous voyons des lieux avec des prochaines disponibilités affichées, sauf que lorsque l'on clique sur le lieu il n'y a pas de créneaux disponibles. C'est dû au fait nous passons plus par la classe `Users::CreneauxSearch` pour appeler le `NextAvailabilityService` depuis #2305 , et donc on ne prenait plus en compte les agents attribués au secteur [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/3b84924d2a05eea8d6aef6d110345f6f4802f19d/app/services/concerns/users/creneaux_search_concern.rb#L25). Cette PR corrige ça en repassant par le `Users::CreneauxSearch`.
Avant
Après
* Certaines pages affichaient des calendriers vides sans créneaux et sans afficher la prochaine disponibilité. C'est parce qu'on ne …

refactor(creneaux): Always use min booking delay for next availability

---

app/views/admin/territories/agents/index.html.slim

Cette information n'apporte pas grand-chose à cet endroit. Il y aura
sans doute d'autres choses à ajouter à la place des équipes ici.
C'est des trucs que j'avais faits sans trop m'en rendre compte dans la PR sur les droits d'accès. Je les extrais pour alléger la PR #2283

Supprime les équipes de la vue listant les agents

---

app/views/mailers/agents/rdv_mailer/rdv_cancelled.html.slim
app/views/mailers/agents/rdv_mailer/rdv_created.html.slim
app/views/mailers/agents/rdv_mailer/rdv_date_updated.html.slim

Pourquoi nous pointions sur l'agenda et pas la fiche ?
C'est un truc que j'avais faits sans trop m'en rendre compte dans la PR sur les droits d'accès. Je l'extrais pour alléger la PR #2283

Pointe directement sur la fiche RDV

---

app/mailers/application_mailer.rb
app/mailers/custom_devise_mailer.rb

L'ajout du reply-to fera que les mails arriveront dans Zammad, qui est plus pratique pour les trier que la boîte mail partagée de contact.
Testé en local et en review app :) (voir ce ticket : https://zammad10.ethibox.fr/#ticket/zoom/22)
REVUE

Utiliser l'adresse de support en reply-to pour les mails

---

app/views/admin/rdvs/index.html.slim
app/views/admin/rdvs/show.html.slim

This is only following bullet hints. User’s responsible and Organisation are used when displaying the user name.
AVANT LA REVUE
REVUE

Preloads User#responsible and #organisation in Rdv#show

---

app/jobs/webhook_job.rb
spec/jobs/webhook_job_spec.rb

Close #2404
Les messages d'erreur de la Drôme ne contiennent pas de point ([voir Sentry](https://sentry.io/organizations/rdv-solidarites/issues/3183773178)).
Ceci est mon premier ticket, pour découvrir le workflow.

Écarter les fausse erreur de la Drôme sur les RDV non trouvé suite à l'appel API

---

bin/setup

(PR sans ticket car tout petit fix)
Lors de mon installation, l'appel à `cp` a déclenché
undefined method `cp' for main:Object (NoMethodError)
donc je suppose qu'il faut plutôt appeler `FileUtils.cp` (comme juste au dessus dans le fichier).

Crash de l'appel à `cp` dans bin/setup

---

app/jobs/webhook_job.rb
spec/jobs/webhook_job_spec.rb

Close #2404 
Je n'avais pas compris que certaines erreurs avaient un point et d'autres non. Je propose de matcher le début de l'erreur pour ne pas avoir à savoir si il y a un point ou pas. :wink:

Écarter les fausses erreurs de la Drôme (bis)

---

spec/features/agents/rdv_collectifs/finding_creneau_spec.rb

Visiblement le `js: true` rend ce test flaky, ce qui explique les échecs de CI depuis 15 jours. :wink: 
Cette spec a été introduite dans #2343. J'ai l'impression que le `js: true` n'est pas nécessaire, j'ai désactivé le JS dans mon navigateur et testé les fonctionnalités : elles fonctionnent ! :tada: 
Qu'en pensez-vous ?
Note : une solution alternative est d'installer la gem `rspec-retry`, avec laquelle j'ai eu de bonnes expériences : 
https://github.com/betagouv/rdv-solidarites.fr/compare/rspec-retry-frf?expand=1

Correction d'une spec JS flaky

---

app/models/user.rb
app/views/admin/users/show.html.slim
spec/features/agents/users/agent_can_display_user_spec.rb

Close #2249
AVANT LA REVUE
REVUE
------------

Réduire la confusion des messages d'information sur l'invitation et la connexion Franceconnect de la ficher usager

---

app/mailers/agents/rdv_mailer.rb
app/mailers/users/rdv_mailer.rb
app/models/concerns/payloads/rdv.rb
app/services/notifiers/rdv_base.rb
app/services/notifiers/rdv_cancelled.rb
app/services/notifiers/rdv_created.rb
app/services/notifiers/rdv_date_updated.rb
app/services/notifiers/rdv_upcoming_reminder.rb
app/views/mailers/common/_rdv_overview.html.slim
app/views/mailers/users/rdv_mailer/rdv_cancelled.html.slim
spec/mailers/agents/rdv_mailer_spec.rb
spec/mailers/previews/agents/rdv_mailer_preview.rb
spec/mailers/previews/users/rdv_mailer_preview.rb
spec/mailers/users/rdv_mailer_spec.rb
spec/models/concerns/payloads/rdv_spec.rb
spec/services/notifiers/rdv_cancelled_spec.rb
spec/services/notifiers/rdv_created_spec.rb
spec/services/notifiers/rdv_date_updated_spec.rb
spec/services/notifiers/rdv_upcoming_reminder_spec.rb
spec/services/rdv_updater_spec.rb

Pour #1431; pour l’instant, c’est seulement du refactor, mais ça permet de mettre le contenu de l’email dans le Receipt.
En ce qui concerne les jobs d’emails d’annulation, en fait pour les rdv je pense qu’on peut _ne rien faire_. J’ai le même refactor sous le couds pour les absence et plages d’ouvertures, et là, il faut faire un `deliver_now`. Pour les rdv, la suppression ne déclenche jamais elle-même d’envoi d’email.
AVANT LA REVUE
REVUE

Ne pas utiliser de payload pour les emails de Rdv

---

app/mailers/agents/rdv_mailer.rb
app/mailers/users/rdv_mailer.rb
app/services/notifiers/rdv_base.rb
app/services/notifiers/rdv_cancelled.rb
app/services/notifiers/rdv_created.rb
app/services/notifiers/rdv_date_updated.rb
app/services/notifiers/rdv_upcoming_reminder.rb
config/locales/mailers.fr.yml
spec/mailers/agents/rdv_mailer_spec.rb
spec/mailers/previews/agents/rdv_mailer_preview.rb
spec/mailers/previews/users/rdv_mailer_preview.rb
spec/mailers/users/rdv_mailer_spec.rb
spec/services/notifiers/rdv_cancelled_spec.rb
spec/services/notifiers/rdv_created_spec.rb
spec/services/notifiers/rdv_date_updated_spec.rb
spec/services/notifiers/rdv_upcoming_reminder_spec.rb
spec/services/rdv_updater_spec.rb

Le principal commit est le dernier, ou j’ajoute le sujet de l’email à `Receipt#content`. Le reste est un changement un peu discutable de style sur les mailers, où j’utilise la _parameterization_ de ActionMailer (cf https://api.rubyonrails.org/classes/ActionMailer/Parameterized.html) pour créer les Agents::RdvMailer et Users::RdvMailer. Je trouve ça mieux dans l’absolu, mais ça demande de toucher un peu tout, ce qui ne se justifie pas forcément. Je vous laisse juge :)
AVANT LA REVUE
REVUE

Refactor des RdvMailer pour intégrer le sujet dans le receipt

---

app/controllers/admin/absences_controller.rb
app/controllers/admin/plage_ouvertures_controller.rb
app/mailers/agents/absence_mailer.rb
app/mailers/agents/plage_ouverture_mailer.rb
app/models/concerns/payloads/absence.rb
app/models/concerns/payloads/plage_ouverture.rb
app/views/mailers/agents/absence_mailer/_absence_overview.html.slim
app/views/mailers/agents/absence_mailer/absence_created.html.slim
app/views/mailers/agents/absence_mailer/absence_destroyed.html.slim
app/views/mailers/agents/absence_mailer/absence_updated.html.slim
app/views/mailers/agents/plage_ouverture_mailer/_plage_ouverture_overview.html.slim
app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_created.html.slim
app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_destroyed.html.slim
app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_updated.html.slim
config/locales/mailers.fr.yml
spec/mailers/agents/plage_ouverture_mailer_spec.rb
spec/mailers/previews/agents/absence_mailer_preview.rb
spec/mailers/previews/agents/plage_ouverture_mailer_preview.rb
spec/models/concerns/payloads/absence_spec.rb
spec/models/concerns/payloads/plage_ouverture_spec.rb

Dans l’esprit de #2411 et #2412 (et en réalité, j’avais déjà commencé cette branche il y a longtemps)
* arrêt de l’utilisation des payloads pour créer les jobs de mailers
* utilisation des paramètres pour les mailers (avec `.with`), ça clarifie plutôt bien le code
* nettoyage i18n
* ajout de l’aperçu de la PO ou de l’absence dans le corps du mail
* ajout d’un lien vers la PO ou l’absence dans le corps du mail
* ⚠️ envoi des mails de suppression de façon synchrone
Ça ressemble à ça:
AVANT LA REVUE
REVUE

Refactor des mailers PlageOuverture et Absence

---

app/mailers/users/file_attente_mailer.rb
app/models/file_attente.rb
config/locales/mailers.fr.yml
spec/mailers/previews/users/file_attente_mailer_preview.rb
spec/models/file_attente_spec.rb

Petit oubli de #2411, pour utiliser les mailers paramétrés et enregistrer les receipts en fin de job plutôt qu’à la création du job.
AVANT LA REVUE
REVUE

Enregistre le Receipt dans FileAttenteMailer

---

app/jobs/cron_job.rb
spec/jobs/cron_job/destroy_old_plage_ouverture_job_spec.rb

Close #2428
Nouvelle PR suite à une mauvaise manip au cour de la précédente.
Les plages d'ouvertures de plus d'un an seront supprimées.
AVANT LA REVUE
REVUE

suppression des plages d'ouvertures de plus d'un an

---

webpack.config.js

Remise en place d'une option `devtool` pour webpack. 
Cette PR est aussi là pour vérifier que ça ne posera pas de problème en prod.
REVUE

précise "source-map" pour les devtool

---

app/services/next_availability_service.rb
spec/features/users/user_can_search_for_creneaux_spec.rb

Fix pour https://zammad10.ethibox.fr/#ticket/zoom/148
Le bug est que la recherche du prochain créneau ne prenait pas en compte le délai maximum de réservation.
Avant : 
On indique qu'un créneau est disponible, mais à l'étape suivante il est impossible d'en réserver.
Après : 
On indique correctement qu'aucun créneau n'est disponible
REVUE

Correctif pour la recherche de créneaux lorsque la prochaine plage d'ouverture est après le délai max de réservation

---

app/helpers/application_helper.rb
app/javascript/stylesheets/components/_cards.scss
app/views/admin/organisations/stats/index.html.slim
app/views/admin/stats/index.html.slim
app/views/stats/index.html.slim

Miettes de #2438
Ça se lit probablement plus simplement commit par commit, même si ce n’est globalement pas très complexe:
* Do not use add_query_string_params_to_url when unnecessary
* Do not explicitly specify the format in stats path sources
* Remove a nil param
* Add identifiers to stats cards and make them consistent
* Make headers self-referencing anchors
AVANT LA REVUE
REVUE

Cleanup stats views

---

app/services/concerns/users/creneaux_search_concern.rb
app/services/next_availability_service.rb
app/services/search_creneaux_for_agents_service.rb
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
spec/services/next_availability_service_spec.rb

Bug introduit dans https://github.com/betagouv/rdv-solidarites.fr/pull/2450/files : On s'est mis à appliquer le délai max de réservation aux agents, et non pas uniquement aux usagers.
Plutôt que systématiquement utiliser le `Motif#end_booking_delay` dans le NextAvailabilityService, on bouge cette logique métier un étage plus haut (et c'est plus cohérent), et on ajoute un paramètre optionnel de date max au NextAvailabilityService.
Comme pour tous les bugfix, il y a un test de non-régression.
Cette PR a malheureusement un air de déjà vu, puisqu'elle fait écho à ce fix d'il y a quelques mois pour les délais min : https://github.com/betagouv/rdv-solidarites.fr/pull/2170. Je me demande presque s'il nous faut quelque chose dans le nommage pour se souvenir que des délais ne s'appliquent qu'aux …

Ne pas utiliser le max_booking_delay pour les réservations faites par les agents

---

.github/pull_request_template.md

Je trouve l'usage de "Closes" plus parlant que "Close" : 
> This PR close**s** that issue.
------------
Et pour l'usage des headings en markdown, je me suis dit que ça nous permettrait de faire des descriptions de PR dans ce style : 
> Closes #issue_number
> 
> # Ce que j'ai fait
> 
> J'ai fait des trucs
> 
> ## Premier truc
> 
> C'était simple
> 
> ## Second truc
> 
> C'était moins simple
> 
> # Une note sur les specs
> 
> Ah vraiment les tests c'est rigolo.
> 
> # Checklist
> 
> Avant la revue :
> - [ ] Préparer des captures de l’interface avant et après
> - [ ] Nettoyer les commits pour faciliter la relecture
> - [ ] Supprimer les éventuels logs de test et le code mort
> 
> Revue :
> - [ ] Relecture du code
> - [ ] Test sur la review app / en local

Mini améliorations du template de PR

---

app/models/rdv.rb
app/services/rdv_exporter.rb
spec/models/rdv_spec.rb
spec/services/rdv_exporter_spec.rb

refs #1431 
`synthesized_receipts_result` n’est utilisé que dans l’export, et n’apparait pas dans l’interface; ça indique si _a priori_, des notifications ont été envoyées avec succès. Si la colonne est vide, il n’y a pas eu de notifications, sinon, c’est soit “Échec”, soit “Traité”. Au final, j’ai préféré donné le moins de détails possibles pour éviter que ça puisse être utilisé pour traiter les usagers de façon différente.
AVANT LA REVUE
REVUE

Ajoute le résultat des notifications à l’export

---

app/javascript/components/select2-inputs.js

Closes #2484
Nous avons 3 typologies d'usage de select2 avec le champ de recherche : 
1. Lorsque les balises <option> sont présentes dans le HTML, et que la saisie de recherche filtre ces options sans appel au serveur
2. Lorsque aucune <option> n'est présente dans le HTML et que la saisie déclenche un appel AJAX
3. Lorsque des balises <option> sont présentes dans le HTML **et** que la recherche est configurée pour utiliser AJAX lorsqu'une recherche est saisie
Le code ajouté dans #2479 avait pour but de cibler les selects qui sont dans le cas 2, mais il a aussi impacté les cas 1 et 3.
Le code que je propose permet de cibler uniquement le cas 2.
http://localhost:3000/departement/26?city_code=26362&latitude=44.921313&longitude=4.923011&street_ban_id=&where=Valence%2C+26000 …

Réparer la config de select2

---

app/views/common/_footer_users.html.slim
app/views/static_pages/cgu.html.slim
app/views/static_pages/mentions_legales.html.slim
app/views/static_pages/politique_de_confidentialite.html.slim
config/routes.rb

Rapatriement des pages CGU, Mentions légales, Politique de confidentialité depuis la doc vers l'application.
Initialement dans la doc parce que c'était plus simple pour Thomas H de les écrire là-bas. Elles sont peu retouchées maintenant. De plus, c'est un peu bizarre d'avoir ces pages dans la doc.
J'ajouterais que le mail de Sophie N. (26) de ce jour nous rappel que la doc n'étant plus en ligne, ces pages ne le sont plus non plus :-/
Le HTML écrit est sans doute améliorable, mais je crois qu'en première approche, ce n'est pas si mal ?
Revue :

Rappatrie les pages statiques qui était dans la doc

---

app/javascript/components/calendar.js
package.json
yarn.lock

Actuellement, lorsque FullCalendar rencontre une erreur HTTP lors d'un fetch, on a une remontée dans Sentry qui prend cette forme : 
> Non-Error exception captured with keys: message, xhr
Exemple : https://sentry.io/organizations/rdv-solidarites/issues/3251002405
**C'est gênant car on a des erreurs remontées côté JS qui nous disent seulement "une erreur XHR s'est produite" alors qu'elles pourraient nous donner l'URL de la requêtes HTTP ainsi que le contenu de la réponse !**
La raison est qu'on passe à `Sentry.captureException` un objet qui n'est pas une `Error`, et donc Sentry ne sait qu'en faire !
https://github.com/betagouv/rdv-solidarites.fr/blob/ba4933ab80d632a3997fdeb6f855a179ba30982c/app/javascript/components/calendar.js#L61
J'ai donc fait en sorte qu'on passe une vraie `Error` et …

Remonter davantage d'infos sur Sentry en cas d'erreur XHR d'appels FullCalendar

---

app/javascript/components/calendar.js
app/views/admin/jours_feries/index.json.jbuilder

Dans #2489 j'avais fait en sorte que les remontées soient groupées par path, mais en fait on a plein de paths différents, ce qui crée de nombreuses entrées Sentry :
Avec cette PR je groupe toutes les erreurs FullCalendar en utilisant le même fingerprint pour toutes les erreurs.
Une autre façon de faire aurait été de [modifier notre config Sentry](https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/) mais ça aurait créé une forme de nouvelle dépendance externe. Si on laisse ça dans le code, c'est sou nos yeux.
J'en ai profité pour :
- déplacer le code de gestion d'erreur dans une méthode séparée
- joindre à la remontée Sentry tous les headers de la réponse HTTP (en utilisant `XMLHttpRequest.getAllResponseHeaders`)
Bonus : [cette …

Grouper toutes les erreurs FullCalendar dans la même issue Sentry

---

app/models/plage_ouverture.rb
app/models/team.rb
app/policies/configuration/team_policy.rb
app/views/admin/absences/edit.html.slim
app/views/admin/agent_roles/edit.html.slim
app/views/admin/lieux/edit.html.slim
app/views/admin/motifs/show.html.slim
app/views/admin/organisations/show.html.slim
app/views/admin/plage_ouvertures/show.html.slim
app/views/admin/rdvs/show.html.slim
app/views/admin/territories/teams/_form.html.slim
app/views/admin/territories/teams/edit.html.slim
app/views/admin/territories/webhook_endpoints/edit.html.slim
app/views/admin/users/show.html.slim
app/views/admin/versions/_resource_versions_row.html.slim
config/locales/models/team.fr.yml

fixes #2146
Ce n’est pas un bug nouveau à cette PR, mais il y a un certain nombre de choses un peu bizarres avec les “virtual_attributes”, c’est à dire le truc qu’on utilise pour stocker les changements aux relations (et pas juste aux attributs).
En particulier, si le seul changement est dans `virtual_attributes`, aucune nouvelle version n’est enregistrée par `paper_trail` tout simplement parce que l’objet n’est pas `dirty`. En fait, notre façon de faire ne peut pas vraiment marcher; [il faudrait implémenter un `adapter`](https://github.com/paper-trail-gem/paper_trail#6c-custom-object-changes), c’est peut-être assez simple en fait.
Revue :

Afficher l’historique paper_trail pour les Équipes

---

app/models/rdv.rb
app/sms/users/file_attente_sms.rb
app/sms/users/rdv_sms.rb
db/schema.rb
spec/sms/users/file_attente_sms_spec.rb
spec/sms/users/rdv_sms_spec.rb

@yaf nous avait fait part de sa volonté de ne plus rendre facultatif l'ajout des tokens dans les sms de notifications: https://mattermost.incubateur.net/betagouv/pl/uh8is119r7b5xgz6b4c5kfdpga.
Cette PR répond à cela en enlevant le flag en DB `show_token_in_sms` sur la table `organisations`.

refactor(app): Remove show token in sms flag

---

app/helpers/plage_ouvertures_helper.rb
spec/helpers/plage_ouvertures_helper_spec.rb

Actuellement, l'heure de fin max qu'on propose pour les plages d'ouverture est 19h55. Si on crée une plage d'ouverture qui se finit à ce moment là, il est donc impossible de faire un rdv de 1h qui commence à 19h, or certains cnfs travaillent jusqu'à 20h.
Pour les absences, on va jusq'à 23h55, parce que aller jusqu'à minuit amènerait à la journée suivante.
Cette PR ajout les 5mn qui manquent. :)
voir https://zammad10.ethibox.fr/#ticket/zoom/291
Revue :

Permettre des plages d'ouverture qui permettent de faire un rdv à 19h

---

app/controllers/application_controller.rb
app/javascript/components/sentry.js
app/views/common/_env.html.erb
app/views/common/_env.html.slim

Actuellement, les remontées Sentry côté JS ne portent aucune info sur le user / agent connecté. 
Le but est donc de remonter ces infos afin de faciliter le débuggage de certaines erreurs ([celle-ci par exemple](https://sentry.io/organizations/rdv-solidarites/issues/3294462748/?environment=production)).
J'ai fait un test en remontant une erreur bidon : https://sentry.io/organizations/rdv-solidarites/issues/3300260790

Faire remonter le user dans Sentry côté JS

---

app/controllers/super_admins/lieux_controller.rb
app/dashboards/lieu_dashboard.rb
app/dashboards/organisation_dashboard.rb
app/views/super_admins/lieux/_form.html.slim
config/routes.rb

On a parfois des cas où les agents ne peuvent pas mettre l'adresse correcte d'un lieu parce qu'elle n'est pas dans la BAN. A court terme, on veut donc permettre à l'équipe support de créer ces lieux ou de les modifier pour mettre la bonne adresse. Ça leur permettra de répondre à ce genre de ticket en autonomie.
Exemple de ticket zammad : https://zammad10.ethibox.fr/#ticket/zoom/145
Revue :

Permettre aux super admins de créer et modifier des lieux

---

.github/workflows/ci.yml

Sur une suggestion de @francois-ferrandis, voici une petite modification qui devrait réduire les déclenchements de CI. Si seul le répertoire `docs` est modifié, alors il n'y aura pas de déclenchement de la CI (il parait :)).

Exclu `/docs` du déclenchement de la CI

---

app/controllers/lapin/sms_preview_controller.rb
app/sms/users/file_attente_sms.rb
app/sms/users/rdv_sms.rb
app/views/lapin/sms_preview/index.html.slim
app/views/lapin/sms_preview/preview.html.slim
config/routes.rb
spec/sms/users/file_attente_sms_spec.rb
spec/sms/users/rdv_sms_spec.rb

refs #2050
Pour l’instant, ça choisit au hasard un rdv en base pour lequel l’utilisateur a un numéro de téléphone; il faudrait avoir plusieurs scénarios avec différents lieux, des rdv de suivi, des rdv collectifs, mais j’hésite sur la façon de faire. C’est déjà reviewable en l’état :)
Revue :

Aperçu de développement des sms

---

.rubocop.yml
app/controllers/inbound_emails_controller.rb
app/javascript/stylesheets/mail.scss
app/jobs/transfer_email_reply_job.rb
app/mailers/agents/reply_transfer_mailer.rb
app/mailers/users/file_attente_mailer.rb
app/mailers/users/rdv_mailer.rb
app/models/rdv.rb
app/views/mailers/agents/reply_transfer_mailer/forward_to_default_mailbox.html.slim
app/views/mailers/agents/reply_transfer_mailer/notify_agent_of_user_reply.html.slim
config/locales/mailers.fr.yml
config/routes.rb
spec/jobs/transfer_email_reply_job_spec.rb
spec/mailers/previews/agents/reply_transfer_mailer_preview.rb
spec/mailers/users/rdv_mailer_spec.rb
spec/requests/inbound_email_spec.rb

Closes #1649
**Le fonctionnement en gros : lorsqu'un⋅e usagèr⋅e reçoit un mail de notif, iel peut y répondre par mail et sa réponse est transmise à / aux agent(s) liés au RDV.** 
Afin de pouvoir retrouver un RDV à partir de l'e-mail de réponse, il fallait stocker un identifiant dans la base et faire en sorte de le joindre au mail de réponse, en utilisant une adresse du type rdv+UUID@reply.rdv-solidarites.fr.
Il était possible de stocker le token dans :
- un `Rdv`
- un `RdvsUser`
- un `Receipt`
J'ai fait le choix de stocker le token dans Rdv pour le moment, principalement car les mailers n'ont pas accès aux RdvsUsers et au Receipts, et qu'il était donc difficile de générer l'adresse de ReplyTo depuis les mailers.
Je me suis aussi dit que si une personne était ajoutée par erreur à un RDV …

Permettre aux usagers de répondre directement aux agents

---

app/views/common/_env.html.erb

Depuis #2508, nous avons des remontées Sentry  `SyntaxError: Identifier 'ENV' has already been declared` : 
https://sentry.io/organizations/rdv-solidarites/issues/3300878842/?environment=production
La cause : j'ai modifié le `var` en `const` en pensant bien faire, mais au moment où turbolinks ré-injecte le JS issu du `<head>`, il tente de redéfinir la constante `ENV` et ça ne plaît pas aux navigateurs.
Cette PR est donc juste un revert à l'usage de `var`, qui permet le rechargement.

Permettre à turbolinks de recharger ENV côte JS

---

app/mailers/admins/organisation_mailer.rb

En ce moment ces mails sont forwardés manuellement depuis l'adresse contact vers l'adresse support (voir https://zammad10.ethibox.fr/#ticket/zoom/384 par exemple). Autant le faire directement :)

Envoyer les mails de demande de nouvelle orga directement au support

---

app/controllers/lapin/sms_preview_controller.rb
app/views/lapin/sms_preview/preview.html.slim
app/views/welcome/super_admin.html.slim
docs/4-notes-techniques.md

followup #2503, pour pouvoir changer les paramètres des données affichées.
Revue :

Amélioration des aperçus de SMS

---

app/javascript/components/calendar.js
config/application.rb

This reverts commit 2f6de6c016950b7fc97225caec9b544bc2bfb7b0.
Le lendemain du déploiement de cette PR, on nous a informé des incohérences dans l'affichage des heures :

Revert "Fix rdv start time display in calendar for non-metropole agents"

---

app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/devise/mailer/invitation_instructions_cnfs.text.erb
config/locales/devise.fr.yml
scripts/reinvite_cnfs_batch1.rb
scripts/reinvite_cnfs_batch2.rb
spec/mailers/previews/custom_devise_mailer_preview.rb

Les invitations envoyées en avril dernier sont arrivées à expiration, donc on veut ré-inviter les CNFS qui n'ont pas encore activé leur compte.
Le texte du mail est celui mis à jour par Matis ici : https://pad.incubateur.net/0qQsnV7qR_mTYnJ2yxc7jA
Pour tester les choses tranquillement, on pourra faire un premier envoi à 300 CNFS en faisant `rails runner scripts/reinvite_cnfs_batch1.rb`, et ensuite faire le reste de l'envoi avec `rails runner scripts/reinvite_cnfs_batch2.rb`
J'ai testé en local, et les mails partent bien avec le bon lien.
Le lien vers la vidéo est à jour.
Revue :

Ré-invitation des CNFS

---

app/views/admin/rdvs/_rdv.html.slim
app/views/admin/users/_responsible_information.html.slim
app/views/admin/users/show.html.slim

https://sentry.io/organizations/rdv-solidarites/issues/2999508699
On a `user_profile` à `nil` et donc ça crashe. Je ne suis pas certain que ce cas est censé se produire, mais il se produit depuis maintenant 4 mois ! Dîtes-moi si vous pensez qu'il vaut mieux investiguer comment on s'est retrouvés dans cette situation, plutôt que d'ajouter ces petits `if`.
Revue :

Bug > Crash sur la liste des RDVs si un⋅e user n'a pas de profil

---

app/views/admin/plage_ouvertures/index.html.slim
config/locales/views/plage_ouvertures.fr.yml

Simple petite phrase pour préciser dans l'écran l'information à propos
du délai de suppression automatique d'une plage d'ouverture fermée.
Cela fait partie d'un mouvement général pour ajouter de la documentation
dans les interfaces de l'application.
Avant
Après 
Closes #2434
Revue :

Informe sur la suppression de plage d'ouverture

---

config/initializers/assets.rb
config/locales/mailers.fr.yml
spec/mailers/previews/agents/reply_transfer_mailer_preview.rb

Cette PR retire la phrase 
> Vous trouverez en pièce jointe l'email original.
des mails que l'on transfert aux agents en cas de réponse.
Cette phrase avait été ajoutée pendant le développement initial dans #2473, quand j'avais l'intention de fournir en pièce jointe une copie de la réponse, mais au final j'ai renoncé à la fonctionnalité mais j'ai oublié de virer cette phrase du template.
J'ai glissé dans la PR un commit qui désactive la concurrence dans sprockets, ce qui permet d'éviter un crash. Plus d'infos ici :  https://github.com/rails/sprockets/issues/581

Supprimer une phrase fausse dans le ReplyTransferMailer

---

app/javascript/application_agent.js
app/javascript/components/calendar.js
app/javascript/components/recurrence-form.js
config/application.rb
package.json
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
yarn.lock

Closes https://github.com/betagouv/rdv-solidarites.fr/issues/2393
Cette PR est une version corrigée de https://github.com/betagouv/rdv-solidarites.fr/pull/2518
Le premier commit est un cherry-pick du premier fix, qui a été reverté entre temps, parce qu'il cassait le tooltip du calendrier pour les autres timezones.
Le deuxième commit est un correctif pour le tooltip du calendrier.
Le troisième commit ajoute une spec de non régression pour l'horaire d'affichage (c'est bien pratique que le navigateur de la ci ne soit pas sur la timezone de paris)
Revue :

Corrige l'heure d'affichage des rdv pour les fuseaux horaires hors métropole (bis)

---

app/policies/configuration/agent_policy.rb
spec/policies/configuration/agent_policy/scope_spec.rb

Suite aux changements sur les droits d'accès et les invitations, tout
passe maintenant par le module de configuration.
Sur ce module, nous pouvons voir la liste de tous les agents du
territoire.
Cette PR vis à réduire la visibilité en fonction de certains critères.
- les organisations auxquelles j'accède
- le service dont je fais partie
- ma situation dans le territoire (si je suis admin du territoire, je peux tout voir)
Avant
Après
_Ici, Marco qui est connecté est du service social, alors que tout les agents `first_name...` sont de la PMI_
Revue :

Réduit le scope des agents visible

---

app/controllers/admin/creneaux/agent_searches_controller.rb
app/controllers/admin/rdvs_controller.rb
app/controllers/application_controller.rb
app/controllers/concerns/admin/authenticated_controller_concern.rb
app/controllers/users/rdvs_controller.rb
config/initializers/omniauth.rb

Suite aux retours de Yannick, cette PR ne loggue pas les params pour toutes les actions côté agent, mais seulement pour quelques actions spécifiques que l'on a besoin de débugger.
-----
Dans le cadre de mon rôle de vigie, je vois des bugs qui remontent dans Sentry mais qui sont impossibles à investiguer car je n'ai pas les détails nécessaires pour les reproduire. En effet, Sentry désactive par défaut la remontée de l'URL, et les params pour mieux respecter le RGPD :
https://docs.sentry.io/platforms/ruby/guides/rack/migration/#removed-processors
Cette décision semble pertinent pour notre appli côté Users, mais je pense qu'il est raisonnable de remonter ces données pour les erreurs côté Agents, car les données ont moins de risques d'être personnelles.
Revue :

Fournir les params à Sentry pour certaines actions à débugger

---

app/controllers/admin/motifs_controller.rb
app/javascript/components/motif-form.js
app/models/rdv.rb
app/views/admin/motifs/_form.html.slim
app/views/admin/motifs/show.html.slim
app/views/users/rdvs/_rdv.html.slim
config/locales/models/motif.fr.yml
db/migrate/20220524141757_add_rdv_editable_by_user_and_rdv_cancellable_by_user_to_motifs.rb
db/schema.rb
spec/controllers/users/rdvs_controller_spec.rb
spec/features/users/user_can_manage_rdv_spec.rb
spec/models/rdv_spec.rb

Closes https://github.com/betagouv/rdv-insertion/issues/398
Nous avons eu plusieurs remontées de CD pour qui la possibilité de déplacer et/ou annuler RDV pose problème.
En effet, certains départements (le 64 notamment) ont des motifs de "convocation" aux RDV d'orientation pour les cas où les allocataires ne répondent pas à l'invitation de RDVI. Ils leur semblent alors incongru de laisser la possibilité aux usagers d'annuler ces RDVs.
J'ai donc ajouté deux attributs au niveau des motifs, qui rendent les RDVs sur ce motif non modifiable ou non annulable par les utiilisateurs
* `admin/motifs#edit` : 
* `admin/motifs#show`: 
-  `users/rdvs#show`: 
Quand le rdv est annulable et déplaçable: 
Quand le rdv est annulable seulement: 
Quand le rdv est ni annulable ni déplaçable: 
Revue :

feat(motifs): disallow rdv modifications by user

---

app/models/user.rb
spec/models/user_spec.rb

Dans cette PR je fixe la méthode qui checke si un token est encore valide introduit dans #1484 .
J'en profite pour rajouter des tests sur la méthode concernée.
N.B: Les noms des méthodes/attributs liés à ce mécanisme ne sont pas toujours très intuitifs, mais reprennent ce qui est fait dans la gem `devise_invitable`.
Revue :

fix(invitation): Invitation period validity

---

app/controllers/admin/agent_roles_controller.rb
app/controllers/admin/agents_controller.rb
app/controllers/admin/invitations_controller.rb
app/controllers/admin/invitations_devise_controller.rb
app/controllers/application_controller.rb
app/policies/configuration/agent_policy.rb
app/policies/configuration/agent_role_policy.rb
app/policies/configuration/territory_policy.rb
app/views/admin/agent_roles/edit.html.slim
app/views/admin/agents/_agent.html.slim
app/views/admin/agents/index.html.slim
app/views/admin/invitations/index.html.slim
app/views/admin/invitations_devise/new.html.slim
app/views/devise/invitations/edit.html.slim
app/views/layouts/_left_menu.html.slim
config/locales/devise.fr.yml
config/routes.rb
spec/controllers/admin/agent_roles_controller_spec.rb
spec/controllers/admin/agents_controller_spec.rb
spec/controllers/admin/invitations_controller_spec.rb
spec/controllers/admin/invitations_devise_controller_spec.rb
spec/features/agents/admin_can_configure_the_organisation_spec.rb

Dans #2283, l'[interface de gestion des agents et des invitations en cours "côté organisation"](https://user-images.githubusercontent.com/6357692/174080493-d1cd09be-4a7f-4a6a-94b2-abc740b2e177.png) a été supprimée au profit d'une interface située dans la config du territoire (voir captures dans la PR sus-citée).
Nous avons depuis reçu de nombreuses demandes au support quant à la disparition de l'interface existante, avec comme problème principaux :
- difficile de retrouver l'interface permettant d'inviter, lister, modifier et supprimer les agents
- impossibilité de lister les invitations envoyées mais pas encore acceptée (cette fonctionnalité n'avait pas été conservée lors du "déplacement" de l'interface fait dans la PR)
Cette PR a donc pour but de restaurer l'interface qui avait été …

Rétablir l'interface de gestion des agents/invitation au sein d'une organisation

---

app/views/admin/territories/invitations_devise/new.html.slim

À lister l'ensemble des organisations d'un agents, nous avons oublié que
certains agents sont sur plusieurs territoire.
C'est peut-être un point à résoudre d'ailleurs, est-ce que nous
souhaitons continuer à avoir des agents multiterritoire ?
Toujours est-il que cette PR limite les organisations afficher aux
organisations de l'agent DANS le contexte de ce territoire.
Revue :

Limite la liste des organisations dans la page d'invitation

---

spec/policies/configuration/agent_policy/scope_spec.rb

Plutôt que d'espérer que les agents soient toujours dans le bon ordre...
C'est suite à un test échoué (de manière aléatoire) j'ai jeté un œil à ce test et pensé qu'un `match_array` serait toujours mieux qu'un `eq`... Pas sur que ça résolve le coté flaky de ce test, mais c'est toujours un peu mieux comme ça.

Vérifie le contenu d'un tableau dans un test 

---

Gemfile.lock
spec/models/paper_trail_version_spec.rb

Suite à la mise à jour de Ruby, `Psych`, l'outil pour parser le `YAML` intégré à Ruby, a changé de mode de fonctionnement sur le parsing de certaines classes comme `Time`, `Date` et autres.
Conséquence, la lecture des changements (sérialisé en `YAML`) sur les objets suivis avec PaperTrail renvoyait une structure vide `{}`.
Cette PR ajoute un test (peut-être pas rangé au bon endroit ?) qui m'a permis de vérifier le mauvais fonctionnement avec un test, puis de m'assurer qu'avec la mise à jour de PaperTrail que ça fonctionnait correctement. Nous pourrions supprimer ce test, mais je crois que son coût relativement faible nous permet de le laisser dans le coin :)
Closes #2600 
Revue :

Met à jour la version de paper_trail

---

app/jobs/cron_job.rb
app/models/concerns/recurrence_concern.rb
app/services/slot_builder.rb
spec/support/recurrence_concern.rb

Closes #2542
Note : la méthode proposée dans le ticket ci-dessus (filtrer les plages d'ouvertures sur le jour de la semaine) s'est révélée inefficace car la recherche se fait sur une semaine complète. Cette PR est donc le résultat d'une investigation sans à priori sur les solutions technique, et dans ce sens elle s'inscrit dans la démarche plus généraliste de #2173.
Ayant déterminé que c'était le calcul des occurrences avec Montrose qui prenait le plus gros du temps, j'ai décidé d'éviter ce calcul en évitant de calculer toutes les occurrences à la demande en partant de la première. Pour ce faire, j'ai choisi de mettre en cache une occurrence récente, afin de partir de cette occurrence plutôt que de la première, en ainsi grandement diminuer le nombre d'itération nécessaire à générer une …

[Perf] Réduire le nombre d'occurrences à évaluer lors du calcul de créneaux

---

app/controllers/stats_controller.rb
app/models/stat.rb
app/views/admin/organisations/stats/index.html.slim
app/views/stats/index.html.slim
config/routes.rb
spec/features/agents/admin_can_see_the_organisation_stats_spec.rb
spec/features/anybody/anybody_can_see_stats_spec.rb
spec/models/stat_spec.rb

Suppression de stats peu intéressante.
Le nombre d'usagers ne représente pas vraiment l'utilisation de la plateforme par les usagers puisque ce sont les agents qui créent des fiches. Et ça a peut de rapport avec la participation à un RDV.
Le nombre d'organisations est plutôt lié à la façon dont souhaite s'organiser une structure.
Le nombre d'agents permet éventuellement de regarder le niveau de déploiement, mais un pourcentage en fonction du nombre d'agents de la structure serait plus intéressante.
Revue :

Suppression de stats peu intéressante

---

spec/features/agents/agent_can_see_rdv_in_calendar_spec.rb

Il m'arrive de lancer des tests le week-end, et celui-ci tombe toujours en panne...
J'ai également remanié le test pour le rendre plus lisible (pour moi).
Ça mérite sans doute une bonne discussion tech.
Je pose ici des éléments en duplication du pad tech.
Un fil stackoverflow regroupe la plupart des points d'entrée que j'ai
rencontré à travers le temps
https://stackoverflow.com/questions/12869026/what-is-the-argument-against-using-before-let-and-subject-in-rspec-tests
On y retrouve
- [Let's not](https://thoughtbot.com/blog/lets-not)
- [ThougthBot StyleGuide](https://github.com/thoughtbot/guides/blob/40090e22f298c380a51b958cb9d6454e1cd4f700/README.md)
- [Commit's discussion @thoughbot](https://github.com/thoughtbot/guides/commit/04b6e2ea8597ae46b24247b96da9b04645478fa0#r1906596)
- [Mystery …

Rend ce test correct le week-end aussi

---

app/helpers/stats_helper.rb
app/views/stats/index.html.slim

Cette PR ajoute de la visibilité sur les indicateurs utilisés par l'équipe CNFS pour mesurer l'adoption de RDV Solidarités par les agents
Pour faire un vrai graphe avec ces quatre pourcentages en stacked bar chart, ça commençait à faire du sql un peu compliqué, donc pour le moment on peut se contenter d'un indicateur qui nous donne les chiffres maintenant, et il y a 30 jours.
Revue :

Ajout de statistique d'activation des agents

---

.rubocop.yml
app/form_models/admin/rdv_form_concern.rb
app/models/rdv.rb
config/locales/models/rdv.fr.yml
spec/features/agents/agent_cant_create_duplicate_rdv_spec.rb

Closes #1633 
Voici les deux validations ajoutées :
- un avertissement (que l'on peut ignorer) quand un RDV existe déjà pour l'usager⋅e le même jour pour le même motif
- un blocage (erreur de validation) si il existe en base un RDV strictement similaire
Voici se qui s'affiche si il existe déjà un RDV qui a :
- le/la **même usager⋅e**
- le **même motif**
- a lieu le **même jour** (pas forcément à la même heure)
Le comportement de cet avertissement est le même que les autres avertissements déjà en place.
Voici se qui s'affiche si il existe déjà un RDV qui a :
- le/la **même usager⋅e**
- le/la **même agent⋅e**
- le **même motif**
- le **même lieu**
- le **même débute** et la **même fin**
Il s'agit d'un erreur de validation qui est déclenchée sur les formulaires de "wizard" et d'édition, elle …

Prévenir la création d’un rendez-vous en doublon

---

app/services/rdv_exporter.rb
spec/services/rdv_exporter_spec.rb

Pour préparer #1719 ?
Et surtout, pour faciliter la fusion des divers fichiers de statistique exporté organisation par organisation, cette PR ajoute une colonne à la fin avec le nom de l'organisation.
Pas très utile à priori, mais il faut voir que les statistiques sont en fait cumulées et chaque fichier est fusionné. Donc difficile, une fois fusionné, de repérer quel RDV est lié à quelle organisation.
Closes #2007
Revue :

Ajoute l'organisation dans l'export CSV

---

app/controllers/admin/rdvs_controller.rb
app/models/lieu.rb
app/views/admin/rdvs/edit.html.slim
config/locales/fr.yml
spec/features/agents/agent_can_update_rdv_spec.rb

Closes #2431
Suite à une première PR, une erreur empéchait les agents de modifier le statut du RDV.
L'ajout d'une spec d'intégration sur le changement de statut du rdv (https://github.com/betagouv/rdv-solidarites.fr/pull/2525) a permis de verifier que le problème ne persistait pas.
avant : 
après :
Revue :

Update lieu vers ponctuel

---

app/controllers/agents/calendar_sync_controller.rb
app/views/agents/calendar_sync/show.html.slim
config/locales/views/agents.fr.yml
spec/features/agents/calendar_export_spec.rb

Après une première démo à Myriam, on a déjà deux petites améliorations à faire sur les synchronisatiosn d'agenda :
- Ajouter le nom de l'agent dans l'url pour clarifier que les données exportées sont celles de son agenda. Il y avait une confusion sur quel lien envoyer aux référentes, donc le fait d'ajouter explicitement un nom dans cette url rend les choses plus claires
- Utiliser tout le temps le terme "agenda externe", et non pas "calendrier externe".
Revue :

Petites améliorations à la synchronisation d'agenda

---

app/views/admin/static_pages/support.html.slim
app/views/layouts/application_agent.html.slim
app/views/layouts/mailer.html.slim
app/views/users/registrations/new.html.slim

On avait oublié de corriger ces liens quand on a déplacé ces pages depuis la doc vers l'appli.
J'en ai profité pour chercher les autres liens vers la doc et les corriger.
Avant :
Après :
Revue :

Correction des liens sur la page de support

---

app/services/rdv_updater.rb
spec/services/rdv_updater_spec.rb

Lorsque l'on souhaite remettre un RDV annulé en RDV à venir, nous n'envoyons pas de notification à l'usager qui n'a aucun moyen de le savoir.
Cette PR propose d'envoyer une notification pour les RDV qui passe d'un statut annulé (à l'initiative de l'usager ou de l'agent) pour un statut autre.
L'outil de notification n'enverra pas de notification sur le RDV est passé.
Il n'y a pas d'autre statut que `unknown` pour les RDV futurs (en dehors des statuts d'annulation).
La notification envoyée est celle de la création d'un RDV. Ce qui aurait été le cas de toute façon si nous avions forcé à recréer un RDV plutôt que de le l'ouvrir à nouveau.
Closes #2538
Revue :

Notifie l'usager de la création d'un RDV suite à un RDV annulé

---

app/controllers/ics_calendar_controller.rb
spec/features/agents/calendar_export_spec.rb
spec/support/calendar.ics

On a eu la demande de la part de plusieurs référentes et de plusieurs cnfs d'ajouter le motif aux informations qui sont synchronisées avec les calendriers extérieurs.
Après discussion en interne dans l'équipe, on a conclu qu'il n'y avait pas de risque siginificatif en terme de confidentialité des données à faire cette modification : les rdvs exportés ne comportent pas l'identité, ni l'adresse, ni l'email ni aucune autre information sur l'usager. Tout au plus on peut avoir le nom de la ville pour un rdv à domicile
Pour accéder aux informations sur l'usager, on garde le lien vers RDVS dans la description de l'évènement
Au passage pour les ateliers collectifs, j'en ai profité pour ajouter le nombre de participants (comme ce qui s'affiche sur l'agenda RDVS)
Revue :

Affichage du motif dans l'export de calendrier

---

app/views/admin/organisations/setup_checklists/show.slim

Le lien vers « la vue usager » ne fonctionnait plus, suite à la fusion
des parcours usagers (#1901).
Étant, il me semble, peu utiliser, autant supprimer la ligne.
Permets de fermer le ticket sentry
https://sentry.io/organizations/rdv-solidarites/issues/3435012678/?alert_rule_id=899770&alert_timestamp=1658126342261&alert_type=email&environment=production&project=1811205&referrer=alert_email
Revue :

Supprime le lien cassé depuis la checklist

---

Gemfile
Gemfile.lock

Cette PR réutilise la version plus récente de sassc (le changement de version précédent venait d'ici : https://github.com/betagouv/rdv-solidarites.fr/pull/2548)

Use sassc 2.4.0

---

app/views/stats/index.html.slim

Ce matin, Matis avait un doute sur l'interprétation de ces stats : 
> Hey ! Avez-vous des éléments d'explication concernant ces chiffres : 
"Seine-Et-Marne : 
1658 agents ont été invités
97% ont accepté l'invitation (1606)
42% ont créé au moins un rdv (694)" 
Je pense tout particulièrement à "42% ont créé au moins un rdv (694)" sur les 1606 agents actifs. Ce sont les agents qui distribuent des RDV sans forcément en planifier pour eux ? 
Ce correctif vise à éviter les confusions pour les autres gens qui consultent les stats
Revue :

Clarification des stats sur les agents actifs

---

.rubocop.yml
app/form_models/admin/rdv_form_concern.rb
app/helpers/users_helper.rb
app/models/concerns/webhook_deliverable.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
spec/features/agents/agent_cant_create_duplicate_rdv_spec.rb

Cette PR corrige un bug qui fait que sous certaines conditions, à la création d'un Rdv, le payload du webhook envoyé contient un tableau de `users` vide.
La cause était la suivante : [cet accès à `rdv.users`](https://github.com/betagouv/rdv-solidarites.fr/blob/2ebaba8d1d2b1b68a3c18dd406aae2eb76d7427a/app/form_models/admin/rdv_form_concern.rb#L42) mémoïze la valeur à `[]` (ce code s'exécute avant l'enregistrement en base), et qu'ensuite, dans le callback `after_commit` qui génère le payload à envoyer en webhook, la valeur n'est pas rechargée depuis la base !
On peut donc conclure que le bug ne se produisait que lorsque l'on exécute le bloc passé au `select`, c'est à dire dans les cas où il existe en base un Rdv similaire : **même lieu, même motif, même heure, mais users et / ou agent …

Bug : champ `users` vide dans le payload du webhook à la création d'un Rdv

---

package.json
yarn.lock

La team sentry a travaillé sur la taille de la lib : 
https://blog.sentry.io/2022/07/19/javascript-sdk-package-reduced
Notre utilisation étant très basique, aucun breaking change ne semble nous concerner : 
https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#upgrading-from-6x-to-7x

Mettre à jour Sentry JS de v6 à v7

---

app/controllers/admin/rdvs_controller.rb
app/form_models/admin/rdv_search_form.rb
app/models/rdv.rb
app/views/admin/rdvs/_rdv_search_form.html.slim
spec/form_models/admin/rdv_search_form_spec.rb
spec/models/rdv_spec.rb

Pour faire la recette : https://production-rdv-solidarites-pr2635.osc-secnum-fr1.scalingo.io/
Closes #2458
Closes #2435 
Mise en place d'un lien de réinitialisation des champs de recherche d'un RDV.
Possibilité de rechercher par motifs
avant 
après
Revue :

2458 reinitialisation filtres select

---

app/views/search/_creneaux.html.slim
app/views/search/_motif_selection.html.slim
app/views/search/_motif_selection_card.html.slim
spec/features/users/user_can_be_invited_spec.rb
spec/features/users/user_can_search_for_creneaux_spec.rb

Pour faire la recette : https://production-rdv-solidarites-pr2634.osc-secnum-fr1.scalingo.io/
Closes #1790
Avant, les instructions paramétrées sur le motif apparaissaient dans une pop-up au moment de la sélection du crénaux.
Maintenant, elle apparaissent juste après la sélection du motif.
Revue :

Afficher les instructions de RDV au moment du choix du motif

---

app/services/notifiers/rdv_base.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb

Closes #2662
À es yeux, ce second appel est un comportement non attendu, que ce soit pour les consommateur de nos webhook autant que pour nous. Quand on a découvert le comportement (en rédigeant [ce test](https://github.com/betagouv/rdv-solidarites.fr/pull/2656/files#r924524864)), on a été surpris. C'est bien que le comportement n'est pas attendu.
De plus, le second webhook a strictement le même payload que le premier, on peut donc considérer qu'il est inutile pour les consommateurs de nos webhooks.
Revue :

Bugfix : envoi de 2 webhooks à la création d'un RDV

---

app/controllers/stats_controller.rb
app/models/stat.rb
app/views/stats/index.html.slim
config/routes.rb

Cette PR ajoute une version en graphe des stats ajoutées récemment
Ce graphe permet de mieux suivre le progrès du déploiement des CNFS, mais peut aussi avoir le même usage dans les département, et peut aussi servir de base aux réflexions sur les tarifs à base du nombre d'agents actifs.
Revue :

Ajout d'un graphe des agents actifs aux stats

---

app/javascript/components/calendar.js

Un truc que j'avais manqué dans #2671.
https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#severity-severitylevel-and-severitylevels
Erreur Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3441445025

Correction suite à la MAJ de Sentry JS en v7

---

app/services/search_context.rb
app/views/search/_motif_selection.html.slim
spec/services/search_context_spec.rb

Pour tester https://production-rdv-solidarites-pr2669.osc-secnum-fr1.scalingo.io/
Pour clarifier un peu la présentation des motifs ;
Pour aider l'usager à trouver le bon motif ;
Cette PR propose de les regrouper par service ;
C'est Sandra (80) qui a fait remonter par le biais de la mailling list que le filtre par service manque et que les motifs sont tous mélangés actuellement.
Avant :
Après :
Closes #2666
Revue :

Regroupe les motifs par service pour l'usager

---

app/views/admin/organisations/stats/index.html.slim
app/views/admin/stats/index.html.slim
app/views/common/_head.html.slim
app/views/common/_head_agent.html.slim
app/views/stats/index.html.slim

Depuis #2672 nous avons [une erreur](https://sentry.io/organizations/rdv-solidarites/issues/3444163260) lorsque nous visitons une page de stats en arrivant depuis une autre page, c'est à dire que la page de stats est chargée avec Turbolinks.
Visiblement, il faut que la ressource JS soit déclarée dans la section `<head>` pour que Turbolinks puisse la charger correctement. Je ne n'ai pas pris le temps d'explorer le fonctionnement précis de Turbolinks, mais le bug semble bien corrigé maintenant que le pack `charts.js` est bien déclaré dans `<head>`.
Comment reproduire : visiter la page d'accueil usagers (http://localhost:3000/) puis cliquer sur "Statistiques". Les charts ne s'affichent pas et on a une erreur (`Chartkick is not defined`) dans la console du navigateur. Si on visite …

Fix: charts défectueux si on charge la page avec Turbolinks

---

app/helpers/admin_helper.rb
app/views/admin/organisations/setup_checklists/show_conseiller_numerique.slim
app/views/admin/static_pages/support.html.slim
app/views/agents/calendar_sync/show.html.slim
app/views/layouts/registration.html.slim
config/locales/views/agents.fr.yml

Cette PR finit le travail sur https://github.com/betagouv/rdv-solidarites.fr/issues/2598
Myriam a confirmé que suite aux discussions avec les différentes référentes, on peut ouvrir la synchro à tout le monde.
On ajoute le lien vers la synchronisation de calendrier au menu des agents, et on le met en avant dans l'onboarding des CNFS.
La nouvelle version de la FAQ est rédigée dans notion, il faudra mettre à jour la FAQ au moment du déploiement.
Avant :
Après : 
Revue :

Ouverture de la synchronisation avec des agendas externes

---

scripts/import_conseillers_numeriques.rb

Closes https://github.com/betagouv/rdv-solidarites.fr/issues/2688
On a actuellement plus de 1700 CNFS dont l'invitation a expiré, et pour qui on voudrait envoyer une relance.
Cette PR est une implémentation simple de ce mécanisme de relance. J'ai testé en local, ça fonctionne comme prévu
Revue :

Réinviter les CNFS dont l'invitation a expiré

---

app/views/stats/index.html.slim

Maintenant qu'on modifie la date d'invitation en faisant des relances, les statistiques du mois précédent sont faussées. Il vaut donc mieux se servir de la date de création de l'agent, qui elle reste inchangée.
Avant :
Après : on devrait retrouver des chiffres normaux.
Revue :

Correctif pour les stats d'agents actifs après relances.

---

app/controllers/admin/rdvs_controller.rb
spec/controllers/admin/rdvs_controller_spec.rb

Dans le contexte de la PR #2681 nous avons découvert un bug.
Un nouveau lieu ponctuel était créé à chaque mise-à-jour du rdv
Cette PR fait en sorte de réutiliser le lieu ponctuel.
Revue :

reutilise le lieu existant

---

app/form_models/user_rdv_wizard.rb
app/views/search/_creneau_selection.html.slim
app/views/search/_lieu_selection.html.slim
app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim

Pour tester https://production-rdv-solidarites-pr2694.osc-secnum-fr1.scalingo.io/
Les modifications faites dans #2636 propos à un usager de pouvoir revenir en arrière, changer de modif, de lieu, de créneaux. Or, dans le cadre d'une invitation, le contexte est « proposé » et n'a pas de raison d'être modifié.
Cette PR propose donc d'affiche le contexte sans proposer de navigation.
Avant
Après
Revue :

Affiche le contexte sans possibilité de navigation dans le cadre d'une invitation usager

---

app/services/search_context.rb
spec/features/allocation_for_search_context_spec.rb

Nous avons constaté une fuite mémoire nous obligeant à redémarrer les serveurs une à deux fois par jour.
Ce problème était présent sur le parcours `prendre_rdv` réalisé plus tôt pour le contexte des invitations via data.insertion. Une fois fusionné, ce parcours a été utilisé dans un plus grand nombre de cas, dont des cas où la requête pose un problème (trop grand nombre d'objets créés).
Plutôt que de combiner les lieux et les plages d'ouverture dans la requête, nous utilisons directement le `lieu_id` sur la table `plage_ouvertures`. Ça réduit de beaucoup les allocations mémoires.
- avant : **11 465 932 allocations**
- après :    **101 774 allocations**
Le pad de notre exploration qui a permis d'arriver à ce résultat : https://pad.incubateur.net/jeLsvF9LTdWN4nM-IIl1FQ?edit
Closes #2686 …

Simplifie le filtre sur les lieux

---

app/services/off_days.rb
spec/services/off_days_spec.rb

Il semble que parfois, nous demandions la liste des jours féries sur une période vide... Possible lorsque la période est réduite en fonction des contraintes des motifs (période de réservation)
Cette PR ajoute une garde pour pallier ce type d'erreur
Ref : [sentry issue 3276720900](https://sentry.io/organizations/rdv-solidarites/issues/3276720900/?project=1811205&query=is%3Aunresolved+sdk.name%3Asentry.ruby.rails&sort=date&statsPeriod=14d)
Revue :

Renvoie aucun jours fériés sur une période vide

---

app/views/application/_model_errors.html.slim

Pour tester https://production-rdv-solidarites-pr2704.osc-secnum-fr1.scalingo.io/
Closes #1665
Modifie le style du lien qui permet d'ignorer le message d'erreur
avant : 
après :
Revue :

transforme le bouton en lien

---

app/helpers/users_helper.rb
app/views/admin/merge_users/_user_selection.html.slim

Pour tester https://production-rdv-solidarites-pr2709.osc-secnum-fr1.scalingo.io/
Closes #2705
Mise en place d'un badge pour identifier un usager utilisant FranceConnect lors de la fusion de deux usagers.
Revue :

badge FranceConnect lors de la fusion d'usagers

---

app/form_models/merge_users_form.rb
app/helpers/application_helper.rb
spec/form_models/merge_users_form_spec.rb
spec/merge_users_form_spec.rb

Pour tester https://production-rdv-solidarites-pr2702.osc-secnum-fr1.scalingo.io/
Closes #1762
Closes #2391 
mise en place du message d'erreur de fusion d'usager quand l'un utilise FranceConnect
- avant : 
- après : 
Revue :

Affiche une erreur plutôt qu'une page 422 lors d'un problème de fusion d'usager

---

app/controllers/admin/rdvs_collectifs_controller.rb
app/models/rdv.rb
app/services/notifiers/rdv_cancelled.rb
app/services/notifiers/rdv_collectif_participations.rb
app/services/rdv_updater.rb
spec/features/agents/rdvs_collectifs/editing_spec.rb
spec/services/rdv_updater_spec.rb

Ce correctif est motivé par ce message sur le mattermost des cnfs
(https://discussion.conseiller-numerique.gouv.fr/cnum/pl/nobz17ucptn5fcd59675g36uow)
Le protocole pour reproduire ce premier bug était le suivant : 
- inscrire un usager avec une adresse email à un rdv collectif en activant les notifications de création et modification
- désactiver les notifications de création et modification
- bug: l'usager reçoit un mail d'annulation.
Le premier commit ajoute un test de non-régression pour ce bug.
En regardant l'implémentation, je me suis rendu compte qu'il y avait le bug symétrique pour l'activation des notifications de création et modification.
Le deuxième commit corrige ces deux bugs en regardant les détails des participations, et non pas juste la liste des usagers avec les …

Correctifs pour les notifications sur les rdv collectifs

---

app/models/concerns/text_search.rb
spec/features/agents/agent_can_search_plage_ouverture_spec.rb

_Pour tester https://production-rdv-solidarites-pr2726.osc-secnum-fr1.scalingo.io/_
Cette PR précise le nom de la table utilisée dans le tri.
Sans vraiment avoir creusé pourquoi lorsqu'un agent admin faire une recherche de plage d'ouverture, cela fonctionne, alors que pour un agent non admin, ça fait une erreur 500, cette précision ici permet de résoudre le problème.
_Il serait intéressant d'explorer POURQUOI ce contexte différent ajoute ce problème, mais ça pourrait être abordé dans une autre PR, ou plus tard en tout cas_
avant (erreur 500 en dev)
après
Closes #2701 
Ferme aussi https://sentry.io/organizations/rdv-solidarites/issues/3405099935/?project=1811205&query=is%3Aunresolved+sdk.name%3Asentry.ruby.rails&sort=date&statsPeriod=14d
Revue :

Précise la table utilisé pour le tri de la recherche

---

.rubocop.yml
app/services/sms_sender.rb
app/sms/application_sms.rb
app/sms/users/base_sms.rb
app/sms/users/rdv_sms.rb
scripts/sms_sender_test.rb
spec/controllers/admin/rdvs_controller_spec.rb
spec/factories/territory.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
spec/features/agents/agent_can_update_rdv_spec.rb
spec/features/agents/rdvs_collectifs/agent_can_create_rdv_collectif_spec.rb
spec/features/users/user_can_be_invited_spec.rb
spec/form_models/admin/edit_rdv_form_spec.rb
spec/models/file_attente_spec.rb
spec/services/notifiers/rdv_cancelled_spec.rb
spec/services/notifiers/rdv_created_spec.rb
spec/services/notifiers/rdv_upcoming_reminder_spec.rb
spec/services/notifiers/rdv_updated_spec.rb
spec/services/rdv_updater_spec.rb
spec/services/sms_sender_spec.rb
spec/sms/sms_netsize_spec.rb
spec/support/sms_stubbing.rb

Suite à #2720 les SMS n'étaient plus envoyés car la valeur de `@sender_name` fournie aux APIs d'envoi de SMS était vide.
Revue :

Correction de bug: les SMS ne partent plus car sender_name est vide

---

spec/sms/sms_netsize_spec.rb

Comme ça on revient au vert, ce qui est plus pratique pour les nouvelles PRs qui n'ont rien à voir.

Mini fix d'une spec qui n'avait été lancée que seule

---

app/mailers/agents/rdv_mailer.rb
app/mailers/users/rdv_mailer.rb
app/views/mailers/agents/rdv_mailer/rdv_updated.html.slim
app/views/mailers/users/rdv_mailer/rdv_updated.html.slim
config/initializers/sentry.rb
spec/mailers/agents/rdv_mailer_spec.rb
spec/mailers/previews/agents/rdv_mailer_preview.rb
spec/mailers/previews/users/rdv_mailer_preview.rb
spec/mailers/users/rdv_mailer_spec.rb

Closes #2728
Je suis allé au plus simple, j'ai fait en sorte qu'on ne mentionne pas l'ancienne adresse si on a pas de `lieu_id`.
Une amélioration possible serait d'afficher "Chez vous" ou "au téléphone", mais la conception logicielle actuelle rend la chose un peu complexe, et l'urgence est de permettre de débloquer les notifications bloquées (et qui continuent de s'accumuler) !
Au moment du merge de cette PR je lancerai le script suivant pour supprimer les notifications de jobs passés (qui n'auront donc jamais l'info).
```ruby
Delayed::Job.where("last_error LIKE ?", "%Lieu without an ID%").find_each do |job|
(%r{/lapin/Rdv/(?<rdv_id>\d+)} =~ job.handler)
rdv = Rdv.find(rdv_id)
job.destroy if rdv.starts_at < Time.zone.now
end
```
Note : j'en ai profité pour corriger les previews, qui …

Traiter les emails bloqués

---

app/presenters/paper_trail_augmented_version.rb
app/views/admin/versions/_version.html.slim
spec/features/agents/disabled_fields_spec.rb

Un petit fix pour un bug qu'on a repéré ce matin, lié à https://github.com/betagouv/rdv-solidarites.fr/pull/2204 et https://github.com/betagouv/rdv-solidarites.fr/issues/2192
- Un usager est dans 2 territoires différents (par exemple un territoire médico-social et le territoire cnfs)
- Un agent modifie une valeur spécifique au médico-social dans le territoire médico-social (par exemple le nombre d'enfants
- Côté cnfs, ce champs n'apparait pas sur la fiche usager, mais il apparait dans l'historique de changements
Ce correctif filtre les champs désactivés dans la l'historique de changements
Revue :

Ne pas afficher les versions des champs désactivés de la fiche usagers

---

config/environments/test.rb

L'activation de cette fonctionnalité ne nous coûte rien et pourrait nous aider à détecter des erreurs dans les clés de traduction.
- [X Supprimer les éventuels logs de test et le code mort
Revue :

S'assurer de la disponibilité des clés de traduction en env de test

---

app/javascript/components/places-inputs.js

Le temps de debounce configuré pour la recherche de lieu était de 100 ms, ce qui a pour effet de lancer la recherche à presque chaque frappe de touche !
Le problème est donc que l'on va envoyer une vingtaine de requêtes à [l'API](https://adresse.data.gouv.fr/api-doc/adresse), ce qui la surcharge inutilement, risque potentiellement de ralentir le navigateur et n'augmente pas particulièrement notre temps de réponse à nous !
J'ai testé plusieurs valeurs, et 800 ms m'a paru équilibré : suffisamment long pour laisser le temps de taper, mais sans trop attendre pour lancer la requête.
Revue :

Utiliser un délai de debounce équilibré

---

app/models/domain.rb
app/views/static_pages/domaines.html.slim

Il y avait un petit oubli sur la page d'explication de différence entre les deux domaines.
avant : 
après : 
Pour faire un fix un peu ceinture-bretelles, j'ai aussi modifié la méthode `Domain#to_s` pour que si on fait à nouveau cet oubli ça soit moins un problème
Revue :

Correctif de l'affichage de domaine

---

app/controllers/organisations_controller.rb
app/models/agent.rb
app/views/mailers/admins/organisation_mailer/organisation_created.html.slim

Lors d'une promenade dans le code, j'ai été surpris par cette variable d'environnement qui n'est plus utilisé. Après vérification, tout ceci n'est plus utilisé. Autant le supprimer donc.
Revue :

:broom: Supprime du code devenu inutilisé à propos de l'embarquement autonome

---

docs/5-role-de-vigie.md

Suite à la discussion de la semaine dernière avec Nathalie et François lors du point tech, voici une doc qui récapitule ce qu'on s'est dit sur le rôle de vigie et sur les erreurs ActiveRecord::NotFound

Ajout de documentation pour le rôle de vigie

---

app/views/admin/organisations/setup_checklists/show_conseiller_numerique.slim

On a eu pas mal de cnfs qui se plaignaient via le mattermost et le support de la lenteur de la synchro webcal, donc on a décidé avec Nesserine de plutôt mettre un lien vers la FAQ, qui explique en détails les avantages et inconvénients des différents modes de synchro, plutôt que de leur proposer directement la synchro, qui ensuite les déçoit s'ils ne connaissent pas bien son fonctionnement.
Revue :

Supprimer le lien vers la synchro webcal dans l'onboarding des cnfs

---

spec/sms/sms_netsize_spec.rb

Le fait d'appeler `stub_netsize_ok` avant chaque spec faisait qu'on stubbait, pour les specs d'erreur :
- d'abord une réponse OK 
- puis une réponse d'erreur
Il semblerait que lorsque la suite de test est exécuté dan un certain ordre, le stub OK était joué plutôt que le stub d'erreur. Je ne suis pas arrivé à reproduire le cas, mais si on fait en sorte de ne pas appeler deux fois `stub_request`, on ne devrait pas avoir de souci.
Revue :

Correction de flaky specs sur les envois de SMS par netsize

---

app/views/admin/users/show.html.slim

Closes #2433
Pour informer les agent·es de la suppression automatique des RDV au bout de deux ans, on ajoute un petit texte d'information : 
J'ai choisi de mettre un `alert-info` dans le footer de la card parce que c'est ce qui me semblait à la fois le plus lisible et le moins envahissant. C'est discutable toutefois, on peut tout à fait le mettre ailleurs ou challenger le texte.
Revue :

info alert: old appointments are deleted

---

app/views/admin/motifs/_form.html.slim

On répare ici le lien mort qui mène à la documentation sur la sectorisation.
Closes #2601
Revue :
Aller sur : http://localhost:3000/admin/organisations/1/motifs/new
Vérifier le lien "Documentation sur la sectorisation" :

fix dead link to 'sectorisation doc'

---

app/models/domain.rb

La constante `ALL_BY_URL` n'est pas fiable dans les review apps car elle contient
```ruby
{
"production-rdv-solidarites-pr2734.osc-secnum-fr1.scalingo.io" => <Domain:0x00007f89fe07f708 @name="RDV Aide Numérique">
}
```
Le piège c'est que l'on veut du code qui permet de déterminer le domaine à partir de l'URL demandée, mais aussi une fonction qui permet de déterminer le host à partir d'un `Domain` donné, et que ces deux fonctions ne sont pas symétriques pour les review apps. Si vous avez une idée pour expliciter ça de façon claire dans le code, je suis preneur !
Revue :

Bugfix: les review apps utilisent le domaine "RDV Aide Numérique" au lieu de "RDV Solidarités"

---

app/views/admin/rdvs_collectifs/motifs/index.html.slim
spec/controllers/admin/rdvs_collectifs/motifs_controller_spec.rb

Closes #2708
Lors de la création d'un RDV collectif, s'il n'y a pas de motif collectif : 
- et que l'agent·e est admin : on lui ajoute un bouton pour créer un motif
- et que l'agent·e n'est pas admin : on lui met un message pour l'informer qu'il lui faut de l'aide
Revue :

allow to create a collective Motif if needed and possible

---

spec/support/sentry_helper.rb

Il y a un bug dans la gem `sentry-ruby` : le `Sentry::TestHelper#teardown_sentry_test` ne clear pas les breadcrumbs.
[J'ai ouvert une PR pour corriger la gem](https://github.com/getsentry/sentry-ruby/pull/1881), mais en attendant on peut merger ce fix dans notre code.
Revue :

Corriger une spec qui est flaky à cause de Sentry::TestHelper

---

app/form_models/admin/rdv_form_concern.rb
spec/features/agents/agent_cant_create_duplicate_rdv_spec.rb

First Commit and PR for beta gouv, :D yay
Closes #2763 
Je n'ai pas accés à Zammad pour voir le ticket de l'issue d'origine mais j'ai réussi à reproduire en local et à fix le problème décrit.
J'ai également du modifier la methode "check_duplicates" qui ajoutait l'erreur à l'enregistrement active record y compris pour les rdv annulés.
Il y a peut être possibilité de refacto les 2 methodes qui me semblent redondantes mais je n'ai pas assez de connaissance sur le projet pour l'instant.

Duplicates RDV validations now use NOT_CANCELLED_STATUSES enum in rdv form concern

---

app/mailers/admins/grc_92_mailer.rb
app/mailers/agents/absence_mailer.rb
app/mailers/agents/export_mailer.rb
app/mailers/agents/plage_ouverture_mailer.rb
app/mailers/application_mailer.rb
app/mailers/concerns/common_mailer.rb
app/mailers/custom_devise_mailer.rb
app/models/concerns/ical_helpers/ics.rb
config/brakeman.ignore
config/initializers/constants.rb
config/initializers/devise.rb
spec/features/users/user_can_reset_his_password_spec.rb
spec/jobs/transfer_email_reply_job_spec.rb
spec/mailers/agents/plage_ouverture_mailer_spec.rb
spec/mailers/agents/rdv_mailer_spec.rb
spec/mailers/custom_devise_mailer_domain_spec.rb
spec/mailers/users/rdv_mailer_spec.rb

Lorsque les usager⋅es et agents reçoivent un e-mail, ils voient qu'il provient de "support@rdv-solidarites.fr".
Cette PR fait en sorte que le l'expéditeur soit nommé en fonction du domaine. 
Au passage, j'ai déplacé dans un concern `CommonMailer` les choses qui étaient en commun entre `ApplicationMailer` et `CustomDeviseMailer`.
Revue :

Définir le nom de l'envoyeur des e-mails

---

app/jobs/cron_job.rb
app/services/scalingo_app_restarter.rb

Suite à une fuite mémoire assez lente, pour laquelle nous n'avons pas trouvé de résolution, nous avons mis en place un cronjob de redémarrage nocturne. Chaque nuit à 2 heures du matin.
Pour le déploiement sur OVH/Kubernetes, nous ne pouvons pas fonctionner avec le même mécanisme (il y a un appel à l'API Scalingo). 
Cette PR propose donc de ne pas déclencher ce job s'il n'y a pas la variable d'environnement `SCALINGO_RESTARTER_APP_ID`
Revue :

Arrête le redémarrage auto en dehors de Scalingo

---

app/models/absence.rb
config/locales/views/agents.fr.yml

Nous avons changé le terme « absence » pour « indisponibilité » il y a un certain temps. Un label est passé à travers les mailles du filet.
Signalé ce matin par la Somme (80), il 
Avant 
Après
Revue :

Corrige un label incohérent dans l'écran des préférences de notification agents

---

app/services/add_conseiller_numerique.rb
db/seeds.rb

Maintenant qu'on a fait l'annonce pour le nouveau nom de domaine, on peut directement créer des comptes sur RDV Aide Numérique pour les nouveaux cnfs qu'on invite.

Utiliser RDV Aide Numérique pour les nouveaux comptes de CNFS

---

app/models/organisation.rb
app/models/rdv.rb
app/views/layouts/_domain_change_banner.html.slim
app/views/layouts/application_agent.html.slim

La communication sur le mattermost des cnfs n'a pas touché autant de monde que ce qu'on espérait (principalement parce qu'on n'a pas pu faire une notification générale `@all`), donc pour s'assurer que les gens concernés par le nouveau nom de domaine soient au courant, on ajoute un peu de communication directement dans l'appli lorsqu'ils se connectent sur le mauvais domaine.
Revue :

Bannière de communication sur le nouveau nom de domaine

---

.gitignore
app/controllers/admin/users_controller.rb
app/models/agent.rb
app/models/concerns/text_search.rb
app/models/plage_ouverture.rb
app/models/team.rb
app/models/user.rb
spec/models/concerns/text_search_spec.rb

_Pour tester https://production-rdv-solidarites-pr2791.osc-secnum-fr1.scalingo.io/_
Closes #2790
Comme décrit dans l'issue, le but ici est de passer d'un système de recherche textuel non pondéré à un système pondéré.
Je vous conseille de lire également le [ticket Zammad](https://zammad10.ethibox.fr/#ticket/zoom/2595) pour comprendre le contexte de ce besoin.
Les modèles sur lesquels on voulait pouvoir chercher par texte (`User`, `Agent`, `Team` et `PlageOuverture`) avaient une colonne `search_terms`, dont la valeur était une concaténation de la valeur d'une liste de champs (nom, prénom, email pour les users / agents ou le nom de l'équipe pour les teams). Ce champ était donc **un vrac de termes** issus d'autres colonnes. Le problème, c'est que certaines colonnes devraient avoir plus …

Améliorer la pertinence de la recherche texte

---

.github/workflows/ci.yml

La commande `db:setup` :
1. crée la base (`db:create`)
2. charge le schéma (enums, tables, colonnes, index) (`db:schema:load`)
3. **charge seeds.rb** (`db:seed`)
Sauf erreur de ma part, nous ne voulons pas que les seeds soient fait en environnement de test ! :zany_face: 
J'ai donc remplacé par les commandes qui font les étapes 1 et 2. :wink: 
Revue :

Bug : la base de donnée de test (features) est seedée sur la CI

---

app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/devise/mailer/invitation_instructions_cnfs.text.erb

Dans le mail d'invitation des CNFS, on leur met un lien vers le canal d'entraide pour RDV Aide Numérique sur leur mattermost.
Maintenant que le canal mattermost a été renommé (et qu'un canal utilisant l'ancienne url a été créé pour que les anciens liens ne mènent pas vers une 404), on peut changer le lien dans le mail d'invitation.
Revue :

Mise à jour du lien vers le mattermost d'entraide pour les CNFS

---

app/services/add_conseiller_numerique.rb
app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/devise/mailer/invitation_instructions_cnfs.text.erb
config/locales/devise.fr.yml
scripts/import_conseillers_numeriques.rb
spec/services/add_conseiller_numerique_spec.rb

L'export qu'on obtient depuis l'espace coop fournit une adresse email pour chaque conseiller numérique différente de leur adresse mail "officielle" qui se termine par `conseiller-numerique.fr`.
L'équipe betagouv cnfs nous a confirmé qu'ils utilisaient cette adresse mail pour la communication auprès des cnfs, puisque la plupart d'entre eux n'utilisent pas beaucoup leur adresse officielle. C'est souvent leur adresse mail pro dont il se servent au sein de leur structure.
Pour gagner en visibilité, on va donc envoyer les mails d'invitation à cette adresse pro en plus de l'adresse officielle. On espère que ça augmentera la proportion de cnfs qui se mettront à se servir de RDV Aide Numérique (le nom sous lequel ils connaissent RDV Solidarités).
L'objectif final est de maximiser le nombre de …

Envoi des emails d'invitations des cnfs à leurs adresses pro non-cnfs

---

.env.sample
app/jobs/cron_job.rb

Nous avons eu, à une époque, des problèmes de fuite mémoire ;
Nous n'avons pas trouvé d'où ça venait ;
Nous avons donc mis en place un redémarrage automatique.
Avoir une variable d'environnement API TOKEN de scalingo dans les variables d'environnement est un peu délicat. Et la solution de redémarrage automatique qui a été mis en place s'appuie là-dessus.
Pour des raisons de sécurité, et parce que nous avons travaillé sur certains sujets de fuite mémoire depuis, cette PR propose de supprimer ce redémarrage automatique.
Si jamais nous avons besoin de le remettre, nous pourrons étudier
- la correction des fuites mémoires
- le redémarrage par un autre moyen
Revue :

Supprime le redémarrage nocture de RDV-Solidarités

---

app/views/static_pages/cgu.html.slim
spec/features/anybody/anybody_can_see_legal_pages_spec.rb

Pour l'équipe juridique : Notre appli, RDV Solidarités, est maintenant également disponible sous le nom RDV Aide Numérique à une autre url. Les fonctionnalités sont toutes les mêmes, c'est seulement le nom et le logo qui changent pour pouvoir être utilisé par des agents qui font de la formation au numérique. Les cgu sont accessibles depuis les deux sites (https://www.rdv-solidarites.fr/cgu et https://www.rdv-aide-numerique.fr/cgu).
Nous essayons ici de mettre à jour nos CGU pour expliquer cette évolution. Pour voir les nouvelles cgu sous un format plus lisible que le diff git, vous pouvez les trouver ici : https://production-rdv-solidarites-pr2757.osc-secnum-fr1.scalingo.io/cgu
Nous auvons besoin de votre avis sur quelques questions : 
- Est-ce que les changements proposés ici vous …

Mise à jour des CGU pour inclure RDV Aide Numérique

---

app/models/domain.rb
config/environments/production.rb
scalingo.json

Suite à une alerte sur le fait de ne pas utiliser l'app Scalingo de prod comme app parente des review apps :
https://mattermost.incubateur.net/betagouv/pl/jgxs346bq7gmid5j5c6msimfpw
**Proposition : faire de l'app `demo-rdv-solidarites` la parente de nos review apps.**
:warning:  J'ai aussi pris pour parti pris de désactiver l'envoi de mails et SMS par défaut sur les review apps, mais c'est à discuter.
Cette PR a pour but d'override les variables d'ENV sensibles afin de ne pas les utiliser dans les review apps. En effet, une faille de sécurité présente dans une review app pourrait compromettre les secrets stockés en ENV.
Lecture intéressante : https://doc.scalingo.com/platform/app/review-apps
Pour les variables suivantes, définir une valeur `change_me_if_needed` à la place de la valeur …

Ne pas fuiter les variables d'ENV dans les review apps

---

app/helpers/motifs_helper.rb
app/views/admin/rdv_wizard_steps/step1.html.slim
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb

Closes #2788
L'idée de @Holist de grouper les motifs collectifs et individuels ensembles me paraissait moins facile à mettre en place car un niveau de groupage par nom de service est déjà mis en place et select2 n'autorise qu'un niveau de groupage par défaut (https://select2.org/options#hierarchical-options)
Revue :

Add group type to motifs select in RDV creation

---

app/views/admin/plage_ouvertures/index.html.slim
spec/factories/plage_ouverture.rb
spec/features/agents/agent_can_search_plage_ouverture_spec.rb

Closes #2725
Avant:
Lorsqu'on lance une recherche, l'onglet sélectionné est oublié
Après:
L'onglet est conservé lorsqu'on fait une recherche. La recherche est préservée au changement d'onglet.
Point d'attention: par défaut la vue n'avance que les plage non expirées. J'ai fait en sorte que l'onglet correspondant soit actif au chargement de la page sans params du coup. Vérifier que ce soit le comportement voulu. J'ai aussi améliorer les tests sur cette partie.
Revue :

Preserve plage search when tab changes

---

app/models/concerns/user/franceconnect_frozen_fields_concern.rb
app/views/admin/merge_users/new.html.slim

Closes #2706 
Mise en place d'un blocage qui empèche la fusion des champs utilisés par franceconnect.
Permet de guider les agents lors de la fusion d'usagers.
avant :
après :
Revue :

Anticipe les problèmes de fusion d'usagers ayant utilisé FranceConnect

---

app/form_models/merge_users_form.rb
spec/form_models/merge_users_form_spec.rb

ref https://zammad10.ethibox.fr/#ticket/zoom/2543 et https://zammad10.ethibox.fr/#ticket/zoom/2633
Dans le processus de fusion usager ;
Lorsqu'un usager a utilisé FranceConnect pour s'authentifier ;
Nous ne pouvons pas modifier son prénom, son nom de naissance ni sa date de naissance ;
Mais si nous sélectionnons les valeurs de cet usager ayant utilité FranceConnect ;
Alors, nous avons un message qui nous bloque, en disant que ce n'est pas possible de mettre à jour parce qu'il y a un utilisateur qui a utilisé FranceConnect
Cette PR modifie le contrôle en question pour ne pas bloquer si les valeurs sélectionnées sont celles de l'utilisateur ayant utilisé FranceConnect.
Cette PR est une sécurité supplémentaire, mais devrait plus être utile (sauf à vérifier aussi coté serveur) lorsque nous …

autorise le choix de l'usager franceconnecté

---

app/mailers/concerns/ics_multipart_attached.rb
spec/mailers/concerns/ics_multipart_attached_spec.rb

Peut-être que c'est aussi la cause de #2823 ?
Depuis #2768, nous avons 3 copies de la pièce jointe ICS.
La raison, c'est que la méthode `mail` est appelée ici :
https://github.com/betagouv/rdv-solidarites.fr/blob/02f470b7490cfdad7a58181b15459d173bb6da71/app/mailers/concerns/common_mailer.rb#L24
Et donc la méthode `mail` surchargée dans `IcsMultipartAttached` est bien appelée 3 fois plutôt qu'une.
J'ai tenté un fix à base de `after_action`, mais j'ai eu des complications, donc je suis partie sur une stratégie de détection des attachments déjà en place.
Pour info, j'ai checkout un commit du mois de juillet pour rédiger mon test, qui était au vert, puis j'ai checkout la production actuelle, le test est passé au rouge, puis j'ai appliqué les correctifs.
Revue :

Bugfix : 3 copies du fichier ICS dans les mails de notifs

---

app/controllers/search_controller.rb
app/models/organisation.rb
app/services/add_conseiller_numerique.rb
app/services/search_context.rb
app/views/admin/motifs/_form.html.slim
app/views/admin/motifs/show.html.slim
app/views/admin/organisations/show.html.slim
config/routes.rb
db/migrate/20220920123327_scope_external_id_uniqueness_to_territory.rb
db/schema.rb
db/seeds.rb
spec/features/users/user_can_use_link_to_take_rdv_in_organisation_spec.rb
spec/services/add_conseiller_numerique_spec.rb

Voir : https://www.notion.so/juvenile-limburger-f93/Prise-de-RDV-par-des-usagers-227911452f5645e3bb5599a51a6da746
Le but est de proposer un lien par lequel les usagers peuvent prendre RDV auprès d'une organisation. La référence à cette organisation peut être fait soit :
- par un ID d'organisation
- par un ID externe d'organisation, qui correspond à l'ID du CNFS dans l'espace coop des CNFS, que l'on stocke dans `external_id`
Note : L'espace coop est la source de vérité, c'est à dire que l'on utilise les IDs de cette base pour retrouver une organisation de notre côté, et les services de cartographie qui sont nos partenaires utiliseront aussi ces mêmes IDs.
- On a ajouté un paramètre `organisation_id` au `SearchContext`. Si il est présent, on filtre les motifs sur l'organisation pointée.
- …

Permettre de prendre RDV via un lien public, sans sectorisation

---

app/controllers/admin/rdvs_controller.rb
app/form_models/admin/rdv_search_form.rb
app/views/admin/agent_agendas/show.html.slim
app/views/admin/rdvs/_rdv.html.slim
app/views/admin/rdvs/_rdv_search_form.html.slim
app/views/admin/rdvs/index.html.slim
app/views/admin/rdvs_collectifs/index.html.slim
spec/form_models/admin/rdv_search_form_spec.rb

Closes #2707 
Suppression de "Détails Usager". 
Cela poserai problème en terme d'UX pour les rdv collectifs et cette feature n'est presque pas utilisée.
Revue :

Suppression de 'Détails Usager' dans la liste des RDV

---

.rubocop.yml
app/services/sms_sender.rb

Closes #2748
Le plus simple m'a paru d'introduire une méthode `handle_failure` à qui ont peut commander de retry ou non.
Pour rappel, la liste des erreurs netsize est dispo ici : 
https://linkmobility.it/wp-content/uploads/sites/11/2020/09/Netsize-Implementation-Guide-REST-API-1.pdf
J'ai inclus `117 Invalid campaign name` à la liste des erreurs permanentes, car visiblement [on en a quelques-unes](https://sentry.io/organizations/rdv-solidarites/issues/3527994850/events/1621b9e39b524ffc9604317b84af2f10/?project=1811205&statsPeriod=14d) et j'imagine que le retry ne sert à rien dans ce cas non plus. :thinking: 
Chaud pour discuter de mon approche, je suis pas 100 % convaincu.
J'en ai profité pour faire en sorte qu'on ajoute un message lorsqu'on raise l'exception, afin d'avoir plus de …

Ne pas réessayer d'envoyer un SMS quand le numéro est invalide

---

.env.sample
config/environments/development.rb
config/environments/production.rb
config/routes.rb

Cette PR est pour qu'on puisse merger celle-ci: https://github.com/betagouv/rdv-solidarites.fr/pull/2774/files
En testant en local, j'ai vu que l'appli ne démarrait pas s'il n'y avait pas de variable d'env LOG_LEVEL, donc pour être compatible avec le setup qu'on a actuellement en production et en demo, j'ai ajouté une valeur de fallback, et une valeur recommandée pour le `.env.sample`.
J'ai aussi réparé les routes modifiées. D'après ce que je comprends, on veut ajouter la route `get '.well-known/acme-challenge/:challenge' => 'acme_plugin/application#index'`, sans changer les routes métier.

Rend la branche recette compatible avec la prod

---

app/controllers/application_controller.rb

Closes #2540
L'exception `ActionDispatch::Cookies::CookieOverflow` est levée lorsque le cookie que l'on veut écrire lors de la réponse HTTP dépasse 4096 octets ([voir source Rails](https://github.com/rails/rails/blob/977868b3389f1cbf4e7083cff59057a4cb6e9622/actionpack/lib/action_dispatch/middleware/cookies.rb#L635)).
Le problème est donc ici que l'on écrire trop de données dans le cookie. La raison, c'est que l'on stocke la session dans le cookie. C'est le mécanisme de stockage de session par défaut de Rails, et c'est le plus simple et le plus fonctionnel [^1]. 
On peut alors se demander : que stocke-t-on de potentiellement volumineux dans la session, dans le contexte où cette erreur est rencontrée ? On voit qu'elle apparaît principalement dans un contexte de création de RDV [via le …

Corrige le crash `ActionDispatch::Cookies::CookieOverflow`

---

app/blueprints/motif_blueprint.rb
app/models/motif.rb
app/models/webhook_endpoint.rb
app/views/admin/territories/webhook_endpoints/_form.html.slim

Suite à des évolutions sur RDV-Insertion, nous avons besoin de rapatrier les motifs sur notre application.
Du coup j'active ici l'envoi des webhooks lors des ajouts / modifications / destruction de motifs en incluant le module `WebhookDeliverable` au niveau du model. 
Ces webhooks ne seront envoyés que si on coche la case "motifs" sur la page d'édition du webhook dans le module de configuration.
J'ajoute également l'id de l'organisation associée dont nous avons besoin dans le payload envoyé. 
Avant:
Après:

Envoyer des webhooks pour les motifs

---

config/environments/test.rb
spec/controllers/admin/absences_controller_spec.rb
spec/controllers/admin/invitations_devise_controller_spec.rb
spec/controllers/admin/plage_ouvertures_controller_spec.rb
spec/features/agents/admin_can_configure_the_organisation_spec.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
spec/features/agents/agent_can_reset_his_password_spec.rb
spec/features/agents/rdvs_collectifs/full_lifecycle_spec.rb
spec/features/agents/users/agent_can_create_user_spec.rb
spec/features/agents/users/agent_can_update_user_spec.rb
spec/features/users/user_can_be_invited_spec.rb
spec/features/users/user_can_reset_his_password_spec.rb
spec/features/users/user_can_search_rdv_spec.rb
spec/features/users/user_can_use_link_to_take_rdv_in_organisation_spec.rb
spec/features/users/user_signs_up_and_signs_in_spec.rb
spec/rails_helper.rb
spec/services/add_conseiller_numerique_spec.rb
spec/services/rdv_updater_spec.rb
spec/sms/sms_netsize_spec.rb

Actuellement, nous avons la config suivante dans `test.rb` : 
```ruby
config.active_job.queue_adapter = :inline
```
Avec cette config, lorsque nous appelons `perform_later` (ou `deliver_later` pour un mail), le job n'est pas mis à la queue comme en prod, mais exécuté immédiatement, de façon synchrone.
Cette configuration a pour avantage d'être simple : on ne reproduit pas le comportement de la prod, mais on a un comportement proche, puisque les jobs s'exécutent en général assez rapidement en prod.
Le problème, c'est que : 
- cette simplification est mensongère, elle communique mal le fonctionnement réel de notre app
- elle nous empêche de vérifier si un job a bien été mis à la queue, ou de vérifier qu'ucn job n'a été mis à la queue (ce qu'on veut faire dans #2843 par exemple)
Je propose …

Utiliser les helpers ActiveJob dans les tests

---

app/controllers/stats_controller.rb
app/models/territory.rb
spec/models/territory_spec.rb

_pour tester https://demo-rdv-solidarites-pr2837.osc-secnum-fr1.scalingo.io/_
Issue #2826 
vue : `/stats?territory=:id`
- fix doublons des agents reliés à un territoire via les organisations
- suppression des requêtes via le controller au profit des relations activerecord via les modèles
**avant**
**après**
Revue :

fix-2826: dédoublonne les agents sur les statistiques

---

app/controllers/static_pages_controller.rb
app/javascript/stylesheets/application.scss
app/javascript/stylesheets/components/_bubble.scss
app/javascript/stylesheets/components/_utilities.scss
app/models/domain.rb
app/views/common/_header.html.slim
app/views/search/address_selection/_rdv_aide_numerique.html.slim
app/views/static_pages/presentation_for_cnfs.html.slim
config/routes.rb
spec/features/accessibility/public_pages_spec.rb

Cette première version de la landing page a été conçue par l'équipe support, afin d'avoir une page de présentation acceptable pendant la [NEC](https://www.rdv-aide-numerique.fr/) la semaine prochaine.
**Voir la page ici :** 
https://demo-rdv-solidarites-pr2842.osc-secnum-fr1.scalingo.io/accueil_cnfs
Revue :

Implémenter landing page CNFS pour la NEC

---

app/javascript/components/motif-form.js

Closes https://sentry.io/organizations/rdv-solidarites/issues/3622151981 et toutes les issues relevées par sentry sur la méthode `toggleSectorisation`
Le bug se produit lorsque je suis connecté en tant qu'agent conseiller numérique.
Le js souhaitait appliquer des comportements au bloc de Sectorisation géographique qui n'est pas présent dans ce contexte
Le fix conditionne l'application des comportements à la présence de ce bloc
Revue :

Hotfix: motif-form.js

---

app/services/sms_sender.rb
config/initializers/typhoeus.rb
spec/sms/sms_netsize_spec.rb

En ce moment on a une erreur fréquente lors de l'envoi des SMS : 
> NetSize error: Invalid campaign name
Mais nous n'avons pas de traçage de la requête que l'on envoie à Netsize, et donc nous ne savons pas quel `campaignName` nous leur fournissons.
Cette PR ajoute du logging autour de toutes les requêtes que nous faisons avec Typhoeus, et donc notamment celles faites par le `SmsSender`.
**Le but est de pouvoir avoir des données à fournir à Netsize au moment où l'on va leur faire une demande au support.**
J'ai essayé de tester sur la review app en activant temporairement l'envoi de SMS, mais j'ai bel et bien reçu les SMS sur mon téléphone, donc pas d’échec d'envoi, donc de remontée Sentry.
Revue :

Ajouter du logging Sentry autour de nos requêtes HTTP

---

app/helpers/motifs_helper.rb
app/javascript/components/motif-form.js
app/javascript/stylesheets/components/_utilities.scss
app/views/admin/motifs/_form.html.slim
app/views/admin/motifs/show.html.slim
spec/features/agents/agent_can_crud_motifs_spec.rb

Closes #2721 & #2808 
- les champs dépendants de la réservation en ligne sont masqués à l'utilisateur
- les champs liés à la réservation en ligne sont masqués à l'utilisateur
- les champs qui comprenaient des checkbox ont été remplacés par des "Oui" et les explications sont passées en `hint`
+ https://demo-rdv-solidarites-pr2848.osc-secnum-fr1.scalingo.io/
+ se log en tant que martine@demo.rdv-solidarites.fr
+ aller dans `paramètres` -> `vos motifs`
Revue :

Motif: Affichage conditionné pour les prises de RDV en ligne

---

app/services/merge_users_service.rb
spec/services/merge_users_service_spec.rb

Closes #2766
Permet de maintenir les informations de l'usager connecté via FranceConnect lors de la fusion d'usagers.
Ainsi, quelque soit l'usagé source ou modifié, les champs "franceconnect_openid_sub" et "logged_once_with_franceconnect" seront conservé.
Revue :

conserve les attributs franceconnect lors de la fusion d'usagers

---

.env.sample
.env.test
.gitignore
bin/setup

La semaine dernière j'ai lancé la suite de tests localement et la spec suivante a échoué :  
https://github.com/betagouv/rdv-solidarites.fr/blob/83a8acb07b06b63ebd570dfd0f29b79dae06b618/spec/features/super_admin/migrating_an_agent_spec.rb
Le message d'erreur m'indiquait que la page était indisponible car elle demandait une authentification Basic Auth ! La raison, c'était que dans mon fichier local (gitignoré) `.env`, j'avais défini `ADMIN_BASIC_AUTH_PASSWORD=123456`, et donc le système de protection par Basic Auth était activé.
**J'ai alors lu [la doc de `dotenv`](https://github.com/bkeepers/dotenv/tree/45b712a#what-other-env-files-can-i-use) et j'ai appris que le fichier `.env` était utilisé dans tous les environnements, et donc mon fichier `.env` était utilisé par les tests ! La doc …

Utiliser des fichiers .env distincts en test et en dev

---

app/javascript/application_agent.js
app/javascript/components/clipboard.js
app/views/admin/organisations/online_bookings/show.html.slim
spec/features/agents/agent_can_configure_online_booking_spec.rb

Lié à #2825 
On ajoute un bouton pour copier facilement le lien de réservation.
On utilise ici la vieille façon de faire (sélectionner le contenu de l'input, puis envoyer la commande `copy` avec `execCommand`). En effet, on devrait pouvoir demander la permission `clipboard-write` au navigateur et, le cas échéant, utiliser `navigator.clipboard.writeText`. Malheureusement ça ne semble toujours pas bien supporté par les navigateurs basés sur Chromium, avec un résultat erratique : des fois ça fonctionne, des fois pas...
Revue :

Copier le lien de réservation avec un bouton

---

app/views/admin/merge_users/new.html.slim
spec/form_models/merge_users_form_spec.rb

Mise en place du test et amélioration de la vue pour bloquer la fusion de deux utilisateurs s'étant déjà connecté avec FranceConnect
Revue :

Bloque la fusion de deux utilisateur utilisant FranceConnect

---

app/helpers/plage_ouvertures_helper.rb
app/models/plage_ouverture.rb
app/views/admin/plage_ouvertures/_motifs_duration_exceed.html.slim
app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
app/views/admin/plage_ouvertures/show.html.slim

Pour tester : https://demo-rdv-solidarites-pr2857.osc-secnum-fr1.scalingo.io/
Closes #2565 
- Depuis l'édition d'une plage d'ouverture, un agent pouvait ajouter un motif avec une durée supérieure aux durées prévues par la plage
- L'interface gère différents warnings non bloquant afin que l'agent puisse rectifier, soit la plage d'ouverture, soit le motif
Revue :

Gestion d'un warning lorsqu'un motif dépasse la durée d'une plage d'ouverture

---

app/controllers/admin/territories/agents_controller.rb
app/policies/configuration/agent_policy.rb
spec/controllers/admin/territories/agents_controller_spec.rb
spec/policies/configuration/agent_policy_spec.rb

Pour tester https://demo-rdv-solidarites-pr2878.osc-secnum-fr1.scalingo.io/
Closes #2789
Normalement, le fix répond bien au bug soulevé par l'issue. Je n'ai pas réinventée la roue et j'ai juste repris ce qui était fait avant la PR suivante : https://github.com/betagouv/rdv-solidarites.fr/pull/2283
Par contre, mettre le nez dans le code m'a interrogé sur le niveau de finesse de nos autorisations sur cette page. Je crois que j'aurais préféré être plus granulaire et avoir des formulaires séparés avec chacun leur controller (dans notre cas un TeamMembership controller ou un truc du genre) et leurs policies associées. Au minimum, vu que l'update ne sert qu'à de l'update de team, ce serait pas mal d'avoir une policy dédiée sans passer par la `territorial_admin_or_allowed_to_manage_agent_part?` …

Permettre d'editer les équipes des agents

---

app/views/common/_footer_users.html.slim
app/views/common/_header.html.slim
app/views/search/address_selection/_rdv_solidarites.html.slim
spec/features/accessibility/public_pages_spec.rb

Bug introduit dans #2842, lorsque la route `accueil_mds` a été dépréciée au profit du nom générique (médico-social et CNFS) `presentation_agent`.
Cependant, des références à `accueil_mds` avaient été laissées dans le code, ce qui avait notamment pour effet de casser l'adaptation du header lorsqu'on est sur la page de présentation aux agents.
En effet, lorsqu'on est sur la page de présentation agents on devrait voir ça
mais avec le bug on avait ça :
Revue :

Bugfix: header not adapting on agents presentation page

---

app/views/admin/motifs/_form.html.slim

Traite [le ticket #554 côté RDV-Insertion](https://github.com/betagouv/rdv-insertion/issues/554)
Cette PR permet de retirer la catégorie d'un motif, lorsqu'une catégorie a déjà été attribuée à un motif ; la page `edit` ne le permettait pas jusque là.

Permettre de retirer la catégorie d'un motif

---

app/controllers/admin/rdvs_controller.rb
app/views/admin/rdvs/_rdv.html.slim
app/views/admin/rdvs/index.html.slim
app/views/admin/rdvs/show.html.slim
spec/features/agents/rdv_details_spec.rb

Ref : https://zammad10.ethibox.fr/#ticket/zoom/2865
Lors des changements récents sur la fiche RDV pour afficher les participants, quelques modifications ont été apportées au design en général. Ces modifications ont fait disparaitre la possibilité de changer les statuts sans changer de page.
Cette PR corrige ce petit oubli.
Un phénomène intéressant apparait : la partie JavaScript qui recharge le bloc de RDV dans la liste fait apparaitre les boutons de modification et duplication. Je pense que nous pourrions les afficher en permanence, y compris dans cette liste. 
Revue :

reste sur la liste des RDVS au changement de statut

---

app/views/stats/index.html.slim

Actuellement, lorsqu'on visualise les stats d'un territoire, la section "Notifications envoyées" affiche un graphique dont les données sont issues de **tous les territoires**.
Avec ce fix, on s'assure d'afficher le graph du territoire. Exemples avec la Haute Garonne, qui n'a en réalité aucun RDV : 
Revue :

Bugfix: le graphique de stats de notifications n'est pas scopé au territoire sélectionné

---

app/models/concerns/rdv/updatable.rb

Suite à un retour d'un département utilisant RDV-Insertion, on s'est rendu compte que les webhooks n'étaient plus envoyés lorsque le statut d'un rendez-vous était mis à jour depuis l'interface admin.
En creusant dans le code, j'ai remarqué que c'était parce que suite à la refacto récente et la mise en place du concern `Rdv::Updatable`, les mises à jour du rdv et les envois de notifications sont englobés dans une transaction (ce qui est une bonne chose).
Mais à cause de [cette ligne](https://github.com/betagouv/rdv-solidarites.fr/blob/7f2e8b7facc8955c5a750fce407f8b7f47a36dea/app/services/notifiers/rdv_base.rb#L56) dans le service de notifications,  les webhooks ne sont pas envoyés.
J'ai fait un hotfix qui consiste à réactiver l'envoi de webhook au sein de la transaction après l'envoi des …

fix(webhooks): Trigger webhooks when updating status

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
spec/features/agents/agent_can_see_rdv_in_calendar_spec.rb
spec/rails_helper.rb

Closes #2676
Je propose d'utiliser Redis pour le cache **et** les sessions sur tous les environnements, afin d'avoir une reproduction fidèle de la prod en test et en local.
Pour l'env de test il y a des particularités :
- l'utilisation de [parallel_tests](https://github.com/grosser/parallel_tests) nous oblige à isoler les clés Redis de chaque runner
- on préfixe les clés avec `test:` pour isoler les données Redis de test et celles de dev local
Note : J'ai choisi de ne pas définir de TTL pour les sessions car actuellement nous n'avons pas d'expiration des sessions, si j'ai bien compris. Il pourrait être intéressant de discuter dans une autre PR de la mise en place d'une durée à partir de laquelle une session expire si il n'y a pas d'activité.
- désactiver le [mode …

Utiliser Redis pour stocker les sessions

---

app/controllers/public_api/public_links_controller.rb
app/controllers/search_controller.rb
app/models/plage_ouverture.rb
config/routes.rb
db/seeds.rb
spec/factories/organisation.rb
spec/requests/api/v1/organisations_reservation_disponible_spec.rb

Closes #2874
Le contexte est décrit dans #2874. :wink: 
Nous avons fait le choix de permettre de passer seulement un territoire (à travers le paramètre `departement`), et de retourner toutes les organisations de ce territoire qui ont des plages d'ouverture ouvertes.
Comme les tests le décrivent, la réponse ne contient que les organisations qui ont des plages ouvertes, et celles qui n'ont pas de plages n'y sont pas listées. C'est un choix de design pour une première étape, qui simplifie légèrement l'implémentation. À l'avenir nous pourrons introduire un booléen pour indiquer si la réservation est ouverte ou non, tout en continuant à fournir le lien public de façon indépendante.
Nous avons essayé de proposer un format d'API qui soit un minimum compatible avec l'existant, sans pour autant …

Offrir une API qui permet de déterminer si il est possible de prendre RDV dans une organisation

---

app/policies/agent/rdv_policy.rb
spec/policies/agent/rdv_policy_spec.rb

Closes #2829
Lorsqu'un agent "admin" ou "secretaire" modifie un rdv, il peut l'attribuer à un agent d'un autre service, d'une même organisation, que celui du motif de ce rdv. Mais ces rdvs ne sont pas visible des agents en question.
Cette PR permet à un agent d'un autre service de voir ses rdvs attribués au sein de ce service.
Revue :

visualiser un rdv d'un autre service

---

app/controllers/public_api/public_links_controller.rb
app/models/plage_ouverture.rb
spec/requests/public_api/public_links_spec.rb

Issue Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3660252449
Lorsqu'une organisation a des plages d'ouvertures, elle est censé figuré dans les résultats de l'API. Mais si elle n'a pas d'`external_id`, ça n'a pas de sens de l'inclure puisque les utilisateurs de l'API ne pourront pas faire la correspondance.
Revue :

Corriger le crash de /public_api/public_links quand une org n'a pas d'external_id

---

app/views/admin/rdvs/_rdv_search_form.html.slim
app/views/admin/rdvs/index.html.slim
spec/features/accessibility/agents_pages_spec.rb

Cette PR ajoute un test automatisé sur la page de liste des RDV.
Elle apporte aussi une correction : pour l'accessibilité, ce n'est pas ok d'avoir des « dropdown » sans contenu. J'ai donc ajouté « Tous » pour indiquer ce que le filtre fait avec cette selection.
Avant 
Après
Revue :

Automatise l'accessibilité de la liste des RDV

---

scripts/import_conseillers_numeriques.rb

L'ID court était un ID legacy côté espace Coop, c'est bien maintenant l'ID long qui sert de référence dans le modèle de données partagé avec la carto.
Revue :

Utiliser l'ID long lors de l'import des CNFS

---

.github/workflows/ci.yml

On a le message suivant dans nos workflows GitHub Actions :
> Node.js 12 actions are deprecated.
> For more information see:
> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
>
> Please update the following actions to use
Node.js 16: actions/checkout, actions/checkout
Revue :

Update GitHub `actions/checkout` because v2 is deprecated

---

app/controllers/super_admins/migrations_controller.rb
spec/features/super_admin/migrating_an_agent_spec.rb

@NesserineZarouri nous a signalé un crash lors d'une migration d'un agent d'une org à une autre :
> Nom est déjà utilisé pour un motif avec le même type de RDV
Le problème était que l'on itérait plusieurs fois sur le même motif car la jointure étais multiplicatrice. Et du coup on essayait de créer plusieurs copies du même motif, ce qui est interdit par les validations
On parle de l'action effectuée en cliquant ici : 
Revue :

Réparer un crash à la migration d'un agent d'une org à une autre

---

docs/1-installation.md

Il me semble qu'il faut maintenant installer redis localement pour développer, n'est-ce pas ? Sinon les sessions ne peuvent pas être enregistrées.

:memo: add redis requirement

---

app/models/agent.rb
app/models/motif.rb
app/models/user.rb

Closes #2915
Rappel : ce ticket a été créé car nous avons constaté des ralentissements, ainsi que des erreurs `PG::TRDeadlockDetected`. Nous supposons que des écritures concurrentes en base peuvent être la cause, et nous avons remarqué que depuis peur, nous avions un `agent.rdvs.touch_all` à chaque connection d'un agent.
On voit que le `touch_all` a bien été ajouté pour invalider le cache des partials des RDVs ici : #1847
Nous sommes donc face à a problématique suivante : **comment savoir quand invalider le cache d'une partial qui utilise potentiellement des dizaines de champs sur 4 ou 5 table ?**
La question est donc de savoir : est-ce que l'on peut définir une liste de champs utilisés dans la partial, et ensuite utiliser cette liste au moment de déclencher l'invalidation du cache (par …

Problèmes de perfs, impact des hooks : after_update -> { rdvs.touch_all }

---

app/views/admin/rdvs_collectifs/_rdv.html.slim

Closes #2884
J'ai repéré en faisant cette issue que le delete redirigeait forcément à l'index des rdv individuel, qu'on delete un rdv individuel ou collectif. Question: c'est voulu ou je peux corriger ça?
Revue :

Supprimer les RDV collectif depuis l'index

---

app/controllers/admin/territories/sectorizations_controller.rb
app/views/admin/territories/sector_attributions/new.html.slim
app/views/admin/territories/sectorisation_tests/search.html.slim
app/views/admin/territories/sectorizations/show.html.slim
app/views/admin/territories/sectors/edit.html.slim
app/views/admin/territories/sectors/index.html.slim
app/views/admin/territories/sectors/index_map.html.slim
app/views/admin/territories/sectors/new.html.slim
app/views/admin/territories/sectors/show.html.slim
app/views/admin/territories/show.html.slim
app/views/admin/territories/zone_imports/create.html.slim
app/views/admin/territories/zone_imports/new.html.slim
config/locales/views/configuration.yml
config/routes.rb

_Pas une grosse priorité, mais j'ai fait ça en tant que participant à du logiciel libre, en dehors de mes heures factures_
Cette PR range les pages de configuration de la sectorisation derrière un menu approprié
Avant
Après
puis, dans le menu sectorisation 
Je n'ai pas repris la carte, car le lien est déjà présent -et lié- aux secteurs 
Je chemin de fer est enrichi
Revue :

Range la sectorisation derrière le menu du même nom

---

app/views/search/_creneau_selection.html.slim
app/views/search/_lieu_selection.html.slim
spec/features/accessibility/public_pages_spec.rb

Je rends le recap des choix d'un usager invité plus lisible lors de la sélection du lieu et de la sélection du créneau.
Avant
Après 
Avant 
Après

feat(view): Improve recap UI for invitations

---

app/blueprints/rdv_blueprint.rb
app/blueprints/rdvs_users_blueprint.rb
spec/blueprint/rdv_blueprint_spec.rb

Closes #2865
Ajout du champ status de rdvs_users dans l'api
Revue :

Permet l'ajout des status utilistateurs des rdv dans l'API

---

app/controllers/search_controller.rb
app/services/search_context.rb
app/views/search/_lieu_selection.html.slim
spec/features/users/user_can_be_invited_spec.rb
spec/features/users/user_can_search_for_creneaux_spec.rb

J'ajoute dans cette PR la possibilité de ne pas afficher aux utilisateurs les lieux n'ayant pas de prochaines disponibilités.
Cela fait suite à la demande de nombreux départements utilisant RDV-Insertion, notamment ceux qui utilisent la sectorisation par agent. En effet, lorsqu'un motif est sectorisé par agent, on affiche tous les lieux pour lesquels il y a une plage d'ouverture pour ce motif, et ce n'est que lorsque l'on calcule la prochaine disponibilité [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/dde3f21e1a71f1ae15a71a2fd864e3429c6adf6e/app/services/concerns/users/creneaux_search_concern.rb#L22) que le filtre se fait sur les agents du secteur. On affiche donc beaucoup de lieux avec seulement quelques-uns ayant des disponibilités, ce qui peut être perturbant.
Pour répondre …

feat(search): Show available lieux only

---

app/controllers/admin/rdvs_controller.rb
app/helpers/users_helper.rb
app/models/agent.rb
app/models/motif.rb
app/models/rdv.rb
app/models/user.rb
app/views/admin/rdvs/_rdv.html.slim
app/views/admin/rdvs/_short_rdvs_list.html.slim
app/views/admin/rdvs/_users_table.html.slim
app/views/admin/rdvs/index.html.slim
app/views/admin/rdvs_collectifs/index.html.slim

Il y a un an, dans #1847, [la liste des RDV a été mise en cache](https://github.com/betagouv/rdv-solidarites.fr/blob/5879b5cc1aecc8926d44fbe3144dad5868327b45/app/views/admin/rdvs/index.html.slim#L60) afin d'améliorer les performances. La partial de RDV contenant des données issues du motif, des agents et des usagers, il a fallu mettre en place un mécanisme d'invalidation de cache à base de `rdv.touch_all` lorsque ces associations sont modifiées.
La semaine dernière, nous avons découvert qu'à chaque connexion d'un agent, tous ses RDVs prenent un `touch_all` car des champs techniques (`last_sign_in_at`, etc) sont mis à jour à ce moment là. Nous avons donc tenté de limiter le nombre de cas où le `touch_all` est appelé dans #2916, mergé jeudi dernier.
Malheureusement, ce matin (le lundi …

[Perfs] Cesser de mettre en cache les partials de RDV

---

Gemfile
Gemfile.lock
config/environments/development.rb

Depuis quelques semaines nous avons à nouveau des soucis de performances (exemple : #2916, #2937), et donc j'ai régulièrement ressorti la gem `rack-mini-profiler` pour débugger manuellement les queries N+1. 
C'est un outil simple et efficace, je vous recommande cette [introduction de 9 minutes](https://www.youtube.com/watch?v=8SkjRkDZRZU) si vous ne connaissez pas.
J'ai toujours eu l'habitude de l'activer en local sur mes projets, et ça a pour effet de garder à l'esprit l'aspect "perf" lorsque l'on développe en local.
Je propose donc de l'ajouter au Gemfile, et donc de l'activer par défaut en environnement `development`.
Au passage, je propose de modifier le log level en local afin que les logs affichent les requêtes SQL, car la plupart du temps je trouve que c'est désirable.
Je vous lais …

Améliorer l'observabilité des performances en local

---

app/controllers/ics_calendar_controller.rb
app/models/agent.rb

Pour les agents qui ont beaucoup de RDVs, l'appel au endpoint ICS est lent car on ne précharge pas les associations, et qu'on prend les 500 RDVs les plus récents, même si il sont vieux de plusieurs mois. J'ai donc décidé de corriger ces deux aspects.
Un exemple de gain de perf sur l'agent `id=312`, pour lequel on retournait auparavant les 500 RDVs les plus récents, et qui avec cette version du code retourne les RDVs qui ont moins d'un mois (231 RDVs), avec en plus le préchargement des associations : on passe de 6300 ms à 400 ms.
Le cache est aussi une options très valable pour ce cas d'usage, mais je ne l'ai pas utilisé afin de ne pas complexifier le potentiel débuggage d'une fonctionnalité qui déjà est soumise au bon vouloir du polling des clients iCalendar.
Revue :

[Perfs] Lenteurs du feed ICS

---

app/views/admin/rdvs_collectifs/_rdv.html.slim
spec/requests/admin/rdv_collectifs_spec.rb

Dans la PR #2895 nous avons ajouté un bouton pour pouvoir supprimer un RDV Collectif depuis l'index des RDV Collectif.
La suppression n'est pas possible si nous ne sommes pas admin de l'organisation. Cette PR propose donc de ne pas afficher l'icône tant que l'agent n'est pas admin de l'organisation.
Revue :

Permet la suppression d'un RDV collectif uniquement pour les admins d'organisation

---

app/controllers/admin/creneaux/agent_searches_controller.rb

Hot fix pour le crash: https://sentry.io/organizations/rdv-solidarites/issues/3685202828/?project=1811205&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox
Ce qu'il se passe : lorsque le motif ne requiert pas de lieu, mais qu'il n'y a pas de  résultat, on allait quand même vers la page de sélection de créneau.
Ce qu'on fait pour corriger : on évite de rediriger vers la page des créneaux s'il n'y a pas de résultat pour un motif qui ne requiert pas de lieu.
Revue :

:ambulance: dont redirect to slots when no result

---

Gemfile
Gemfile.lock
spec/spec_helper.rb

Requis pour les M1 : https://github.com/SeleniumHQ/selenium/issues/11066
J'ai du adapter un peu le helper du driver qui a changé avec l'upgrade de version.
A priori c'est ok mais si quelqu'un qui maitrise mieux capybara que moi peut s'en assurer ce serait top :)
https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#before
https://github.com/teamcapybara/capybara/issues/2511
https://support.smartbear.com/crossbrowsertesting/docs/automated-testing/frameworks/selenium/about/use-of-desiredcapabilities-has-been-deprecated.html
https://stackoverflow.com/questions/56522499/cromedriver-driver-manage-logs-getbrowser-fails-on-chromedriver-75-0-3770-8

Upgrade webdriver gem

---

.rubocop.yml
app/controllers/users/rdvs_controller.rb
app/form_models/admin/rdv_collectif_search_form.rb
app/lib/lapin/range.rb
app/services/next_availability_service.rb
docs/2-contributions.md
scripts/load_absences_csv.rb
spec/controllers/admin/rdv_wizard_steps_controller_spec.rb
spec/controllers/search_controller_spec.rb
spec/controllers/users/rdv_wizard_steps_controller_spec.rb
spec/controllers/users/rdvs_controller_spec.rb
spec/factories/agent.rb
spec/factories/rdv.rb
spec/features/users/user_can_search_rdv_spec.rb
spec/form_models/user_rdv_wizard_spec.rb
spec/helpers/rdvs_helper_spec.rb
spec/jobs/cron_job/file_attente_job_spec.rb
spec/jobs/cron_job/reminder_job_spec.rb
spec/lib/lapin/range_spec.rb
spec/mailers/agents/rdv_mailer_spec.rb
spec/models/concerns/recurrence_concern_spec.rb
spec/models/file_attente_spec.rb
spec/models/stat_spec.rb
spec/services/users/creneau_search_spec.rb

L'usage de la classe ruby `DateTime` est réservée aux dates historiques. La manipulation de dates "modernes" doit être faîte à travers `ActiveSupport::TimeWithZone`, qui gère les calculs en prenant compte la timezone.
Voici un exemple de piège quand on utilise `DateTime` :
```ruby
jeudi_14h = DateTime.new(2022, 10, 27, 14)
jeudi_14h.in_time_zone("Paris")
```
On peut voir que DateTime n'utilise pas l'offset de la timezone définie par défaut dans notre appli. Cela peut-être une source d'incompréhension. Mais il y a aussi un autre piège, qui est lié à l'usage d'un offset plutôt que d'une timezone :
```ruby
une_semaine_plus_tard = jeudi_14h + 7.days
une_semaine_plus_tard.in_time_zone("Paris")
```
Le changement d'heure ayant lieu le 29-30 octobre cette année, on peut voir que "une semaine plus …

Ne pas utilise DateTime pour manipuler des dates modernes

---

app/models/absence.rb
app/models/concerns/ensures_realistic_date.rb
app/models/plage_ouverture.rb
spec/factories/absence.rb
spec/features/agents/agent_can_crud_absences_spec.rb
spec/models/concerns/ensures_realistic_date_spec.rb

Closes #2914
J'ai corrigé les années foireuses en base, j'ai supprimé les 5 absences qui avaient pour année 0200, 0201 ou 0202, car elles n'étaient pas récurrentes.
J'ai préféré une validation en back car c'est bien plus simple et robuste qu'une config de datepicker, et vu la rareté du phénomène, autant aller au plus simple.
Revue :

Plages d'ouverture et indisponibilités commençant au début du 20ème siècle

---

app/views/admin/slots/index.html.slim
config/locales/fr.yml
spec/controllers/admin/slots_controller_spec.rb

Fix le crash suivant : https://sentry.io/organizations/rdv-solidarites/issues/3693276826/?alert_rule_id=899770&alert_timestamp=1666616065780&alert_type=email&environment=production&project=1811205&referrer=alert_email
Il se produit sur la recherche de créneau côté agent·e lorsqu'il n'y a pas de résultats. On met un message pour informer l'agent·e : 
Revue :

fix: crash when there is no slot search results

---

.rubocop.yml
spec/requests/api/v1/organisations_request_spec.rb
spec/swagger_helper.rb
swagger/v1/api.json

On ajoute la documentation du endpoint `/organisations` au format swagger.
Revue :

document Organisations with rswag

---

app/controllers/admin/rdvs_controller.rb
app/controllers/admin/territories/agent_territorial_access_rights_controller.rb
app/form_models/admin/rdv_search_form.rb
app/mailers/agents/export_mailer.rb
app/models/rdv.rb
app/policies/agent/agent_policy.rb
app/policies/configuration/territory_policy.rb
app/services/rdvs_user_exporter.rb
app/views/admin/rdvs/index.html.slim
app/views/admin/territories/agents/edit.html.slim
app/views/mailers/agents/export_mailer/rdvs_users_export.html.slim
config/locales/fr.yml
config/locales/models/agent.fr.yml
config/locales/views/admin_territories_agents.yml
config/routes.rb
db/migrate/20221004125920_add_allow_to_download_metrics_to_agent_territorial_access_rights.rb
db/schema.rb
db/seeds.rb
spec/controllers/admin/rdvs_controller_spec.rb
spec/form_models/admin/rdv_search_form_spec.rb
spec/mailers/agents/export_mailer_spec.rb
spec/mailers/previews/agents/export_mailer_preview.rb
spec/policies/configuration/territory_policy_spec.rb

Closes #2008 
- En tant qu'admin d'un territoire, je peux donner droit à un agent de télécharger toutes les données dans un nouveau format de rdvs par usager sur l'ensemble des organisations auxquelles il accède
- En tant qu'agent ayant droit de télécharger toutes les données de rdvs par usager, j'accède à cette action depuis l'interface de la liste des RDV
@NesserineZarouri @MYRIAMKEDDAD : https://demo-rdv-solidarites-pr2900.osc-secnum-fr1.scalingo.io/admin/organisations/1/rdvs en tant que martine@demo.rdv-solidarites.fr
Revue :

Téléchargement des rdvs par usager sur plusieurs organisations

---

app/services/search_context.rb

Perf : explosion combinatoire de motifs et plages: motifs_ids contient des doublons
Revue :

Hotfix: énorme requête SQL qui met Postgres à genoux

---

spec/requests/api/v1/groups_request_spec.rb
spec/requests/api/v1/invitations_request_spec.rb
spec/requests/api/v1/organisations_request_spec.rb
spec/requests/api/v1/organizations_request_spec.rb
spec/requests/api/v1/rdvs_request_spec.rb
spec/support/api_spec_macros.rb
swagger/v1/api.json

On ajoute des macros pour faciliter l'écriture des docs de l'API, en particulier : 
- pour l'authentification
- pour la pagination
Revue :

api doc: utility macros

---

app/models/concerns/rdv/authored_concern.rb
app/services/rdv_exporter.rb
app/services/rdvs_user_exporter.rb

- usage de `find_each.with_index` plutôt que `each_with_index`
- préchargement des associations des RDVs afin d'éviter les requêtes N+1
Aujourd'hui (et plusieurs fois cette semaine), la RAM du worker de jobs a explosé : 
On peut voir que cette soudaine augmentation coincide avec l'exécution d'un job `Agents::ExportMailer#rdv_export sur l'orga 106 et pour l'agent 3028. 
J'ai donc reproduit le phénomène en local, et voici les perfs (sur ma machine, Framework 11th Gen Core i5) : 
- 269 secondes (4 minutes 20 secondes)
- 1 373 536 ko de RAM (1,3 Go)
Après les améliorations effectuées dans cette PR : 
- 53 secondes
- 567800 ko de RAM (554 Mo)
La taille en octets est la taille du process ruby après chargement de Rails exécution de l'export, obtenue en exécutant ce script avec le runner Rails : …

Perfs - Optimisation RAM exports de RDVs

---

docs/bonnes-pratiques-de-tests.md
spec/controllers/admin/motifs_controller_spec.rb
spec/factories/absence.rb
spec/factories/agent.rb
spec/factories/factories_spec.rb
spec/factories/file_attente.rb
spec/factories/motif.rb
spec/factories/plage_ouverture.rb
spec/factories/rdv.rb
spec/factories/team.rb
spec/factories/territory.rb
spec/factories/user.rb
spec/factories/webhook_endpoint.rb
spec/factories/zone.rb
spec/form_models/admin/rdv_form_concern_spec.rb

Avant toute chose : **le cœur de cette PR, ce sont les modifications apportées aux factories**. Les autres modifs sont des corrections de tests et l'ajout d'un nouveau test.
Le problème : actuellement ous avons dans nos factories des appels à `create(:une_association)`, ce qui signifie que même si on appelle à travers un build(:mon_modele), on fait un appel en base à cause du `create`.
Je pense qu'en lisant cette section de la belle doc FactoryBot vous verrez de quoi je parle : https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#build-strategies-1
J'ai aussi ajouté un spec qui valide les factories (piqué chez [thoughtbot](https://thoughtbot.com/blog/testing-your-factories-first)), qui permet de voir dans les logs la quantité d'appels à la base faits quand on build une …

Éviter les écritures en base inutiles dans les  factories

---

app/mailers/agents/absence_mailer.rb
spec/mailers/agents/absence_mailer_spec.rb

Actuellement, lorsqu'une absence (aka. indisponibilité) est supprimée, un mail est envoyé à l'agent, avec en pièce jointe un fichier ICS qui est censé indiquer au client mail / agenda de l'agent qu'il faut "annuler" cette absence. 
**Or, le champ "STATUS" indique actuellement `STATUS:CONFIRMED` alors qu'il devrait indiquer `STATUS:CANCELLED`.**
Cette PR corrige ce bug, et ajoute une une spec du `Agents::AbsenceMailer`, qui est un beau copié / collé de la spec de `Agents::PlageOuvertureMailer`.
Pour la petite histoire, j'ai ajouté la spec en bossant sur un autre sujet, et c'est comme ça que j'ai remarqué le bug (le dernier exemple échouait).
Revue :

Bugfix : l'ICS envoyé dans le mail #absence_destroyed n'a pas le bon statut

---

docs/bonnes-pratiques-de-tests.md
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/capybara_config.rb

Actuellement on utilise la stratégie :truncation, qui est lente car à **chaque test** on écrit en base puis on exécute ceci : 
```
(0.2ms)  DELETE FROM "active_storage_blobs"
(0.2ms)  DELETE FROM "rdvs_users"
(0.2ms)  DELETE FROM "rdvs"
(0.1ms)  DELETE FROM "agent_territorial_access_rights"
(0.3ms)  DELETE FROM "agents"
(0.1ms)  DELETE FROM "agents_organisations"
(0.2ms)  DELETE FROM "agents_rdvs"
(0.2ms)  DELETE FROM "agents_users"
(0.1ms)  DELETE FROM "delayed_jobs"
[...]
```
Le but est donc ici d'utiliser les transactions, plus rapides, quand c'est possible. 
J'en profite pour déplacer la config capybara dans un fichier séparé, comme ça le fichier `spec_helper.rb` contient ce qu'il doit contenir : le minimum pour lancer un test sans avoir besoin de Rails.
Revue :

Utiliser les transactions Postgres dans les tests

---

app/controllers/admin/creneaux/agent_searches_controller.rb
app/views/admin/creneaux/agent_searches/index.html.slim
app/views/admin/slots/index.html.slim
config/locales/fr.yml
config/locales/views/agent_searches.fr.yml

« Retour aux filtres » le retour du bouton qui s'affiche en haut de la proposition de créneaux côté agents.
ref : https://zammad10.ethibox.fr/#ticket/zoom/3044
Dans le Pas-de-Calais (et ailleurs ?) ;
Un agent (souvent du secrétariat) réalise un RDV de préqualification (souvent au téléphone) avec un usager ;
L'agent note les informations recueillies dans le contexte du RDV ;
En fin de RDV, l'agent duplique le RDV courant, choisi un nouveau motif (et autres ?) pour un nouveau RDV avec l'usager ;
Cela permet de faire une orientation en maintenant les informations récoltées dans le contexte du RDV.
Le contexte et la duplication ont été créés dans RDV-Solidarité pour ce cas d'usage.
Nous avions enlevé ce bouton dans la PR #2860 parce que nous avions oublié pourquoi il était là.
Le voilà de …

replace le retour aux filtres dans l'affichage des créneaux

---

spec/services/search_creneaux_without_lieu_for_agents_service_spec.rb

J'utilise timecop pour enlever la dépendance aux périodes de l'année. Le test bugguait aujourd'hui à cause des jours fériés (1er novembre) par ex.
Aussi, j'ai cru me rendre compte en faisant ce petit debug que le `build_result` de `SearchCreneauxForAgentsService` n'était pas testé. C'est le cas ? C'est voulu?
Revue :

Fix flaky test with no time dependance

---

app/controllers/admin/rdvs_controller.rb
app/controllers/api/v1/rdvs_controller.rb
app/policies/agent/rdv_policy.rb

Pour tester : https://demo-rdv-solidarites-pr3004.osc-secnum-fr1.scalingo.io/
Nous avons ajouté la possibilité de regarder les RDV d'une des organisations dont nous avons accès dans la liste des RDV.
Le problème vient des policies en place qui limite la visualisation des RDV à ceux de l'organisation courante.
Cette PR propose d'élargir la restriction de la policy sur les RDV pour autoriser la visualisation des RDV de toutes les organisations auxquelles l'agent accède.
Closes #3003
Revue :

Élargie la policy sur les RDV pour afficher tous les RDV des organisations auxquelles l'agent accède

---

app/mailers/agents/export_mailer.rb
spec/mailers/agents/export_mailer_spec.rb

Lorsqu'il n'y a qu'une seule organisation dans le fichier exporté, nous précisons son identifiant dans le fichier exporté.
C'était le comportement habituel avant l'ajout du filtre sur les organisations accessibles. Ce changement à boulversé les mécanismes et habitude pour le département du var (ref : https://zammad10.ethibox.fr/#ticket/zoom/3070), aussi, cette PR remet en état le fonctionnement ancien.
Pas de modification sur le nouvel export, il est nouveau et ne casse donc aucun mécanisme existant. À voir si la demande est faite pour faire pareil plus tard.
Closes #3005
Revue :

Précise l'organisation dans le nom de fichier

---

app/controllers/admin/creneaux/agent_searches_controller.rb
spec/requests/admin/creneaux/agent_searches_spec.rb

Dans le cas d'un motif de RDV téléphonique (ou à domicile) ; 
nous ne vérifions que si des créneaux étaient disponibles ; 
Si la date de dispo était sur la semaine d'après, donc dans `next_availability` alors, nous affichions un message : « aucun créneaux disponible » alors que c'est faux.
Cette PR ajoute un test sur ce cas et modifie cette vérification dans le contrôleur de recherche de créneaux des agents.
Closes #3019
Revue :

Affiche les prochains créneaux disponibles dans les semaines qui suivent pour des motifs qui ne sont pas sur place

---

app/services/users/geo_search.rb

Un commentaire https://github.com/betagouv/rdv-solidarites.fr/pull/3000#discussion_r1011480213 n'avais pas été pris en compte dans la PR #3000. Cette PR corrige cet oubli.
Revue :

Renomme une méthode pour la faire correspondre à l'autre méthode

---

.github/pull_request_template.md

Pour faciliter les tests et revues en autonomie par l'équipe de support utilisateur, mettre le lien vers la review app dans la description permet de la rendre plus accessible.

Incite à mettre l'url de review app dans la pr

---

spec/features/agents/agent_can_configure_online_booking_spec.rb

Dans le code d'origine, la navigation qui se faisait dans le before ligne 7 était exécutée avant la création de la plage d'ouverture dans le before ligne 31 (les befores sont executés dans l'ordre de déclaration).
Pour que le test passe, il fallait donc qu'on soit dans le cas d'une race condition où l'écriture en base par le script de test se fasse avant la lecture par le serveur suite au click_link.
Le fix consiste donc à faire la navigation dans le `it`, qui est executé après l'écriture en base par le before.
En plus de ce fix, j'en ai profité pour enlever le `js: true` sur 2 des 3 exemples. Vu qu'on test juste le html, le `js: true` servait juste à ouvrir le sous-menu. Plutôt que de faire ça dans chaque test, on vérifie que la navigation marche bien dans le premier test, et ensuite on …

Correction d'une flaky spec

---

app/views/admin/users/_responsible_form_fields.html.slim
app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim

En préparant les maquettes sur la réservation en ligne, j'ai remarqué ces trois petits détails qui étaient rapides à corriger : 
- se servir du terme `usager` et non pas `utilisateur` de manière cohérente sur le formulaire côté agent
- correctif d'un mauvais alignement causé par un problème d'indentation
- suppression d'un fichier vide ajouté par erreur

Trois corrections mineures

---

app/controllers/admin/organisations/stats_controller.rb

Emergency Fix pour les stats.
Cause : cette PR https://github.com/betagouv/rdv-solidarites.fr/pull/3004
Sur cette ligne : https://github.com/betagouv/rdv-solidarites.fr/blob/296891fc1b04cd410c5e669df836a584b7793534/app/policies/agent/rdv_policy.rb#L18
J'ai simplement scope les rdvs des stats des organisations au niveau du controlleur dédié à cela.
Avant la PR en question cela était fait au niveau de la policy. Cela me semble plus logique comme ca.

fix organisation scope for organisations stats

---

app/controllers/admin/users_controller.rb
app/helpers/users_helper.rb
app/models/user.rb
app/services/duplicate_users_finder_service.rb
app/views/admin/merge_users/_user_relatives.html.slim
app/views/admin/users/show.html.slim
app/views/users/users/edit.html.slim
spec/controllers/admin/users_controller_spec.rb
spec/models/user_spec.rb

Nous utilisions un scope `active` sur les usagers pour n'avoir que ceux qui n'était pas marqué comme supprimé par une opération de `soft_delete`.
Nous avons un retour sur un cas de figure où nous avons oublié d'utiliser ce scope (il y en a peut-être plusieurs ?).
Cette PR remplace le scope `active` par un `default_scope` qui écarte les usagers marqué comme supprimé. Comme nous avons fait pour les RDV.
Closes #3027
Revue :

Masque par défaut les usagers marqués supprimé

---

app/controllers/admin/agents/absences_controller.rb
app/controllers/admin/agents/plage_ouvertures_controller.rb
app/views/admin/agents/absences/index.json.jbuilder
app/views/admin/agents/plage_ouvertures/index.json.jbuilder
spec/controllers/admin/agents/absences_controller_spec.rb
spec/controllers/admin/agents/plage_ouvertures_controller_spec.rb

Suite au déploiement de la PR #3050 (dans laquelle on met à jour Ruby et plein de gems), les requêtes de FullCalendar vers `Admin::Agents::PlageOuverturesController#index` et `Admin::Agents::AbsencesController#index` on commencé à échouer en remontant l'erreur :
> can't dump hash with default proc
Une [explication complète de cette erreur sur StackOverflow](https://stackoverflow.com/a/6392704/2864020) indique que la cause est qu'il est impossible de Marshal des objets (pour les mettre en cache par exemple) si ils ont pour variable d'instance des `proc`. Les objets `ActiveRecord` étant souvent dans ce cas, il est déconseillé de vouloir mettre ce type d'objet en cache.
Cette propose donc de mettre en case la réponse JSON de ces endpoints, plutôt que de mettre en cache les records.
Note : je …

Bugfix: la mise en cache d'objets `ActiveRecord` cause parfois un crash

---

app/views/admin/agents/rdvs/index.json.jbuilder
config/initializers/css_color_names.rb
spec/features/accessibility/agents_pages_spec.rb

Comme indiqué dans https://github.com/betagouv/rdv-solidarites.fr/pull/3059, la spec était souvent au vert parce que le test d'accessibilité était fait avant que les rdvs ne soient chargés en ajax.
Lorsque les rdvs avaient le temps de charger, on avait alors une erreur à juste titre : le fond gris était trop clair pour être accessible.
Cette PR modifie la spec pour qu'elle échoue de façon fiable, et met un gris plus sombre pour rendre le texte lisible.

Correction d'une flaky spec d'accessibilité

---

app/controllers/admin/rdvs_controller.rb
app/mailers/agents/export_mailer.rb
spec/controllers/admin/rdvs_controller_spec.rb
spec/mailers/agents/export_mailer_spec.rb

Il est possible pour un agent de fournir le paramètre `scoped_organisation_id` qu'il veut pour exporter les RDVs de cette orga. :scream: 
Revue :

Bugfix: un agent peut passer un paramètre HTTP pour exporter une orga arbitraire

---

docs/2-contributions.md

Suite aux discussions sur nos pratiques de merge de PR de jeudi dernier, je propose ici une doc, qui pourra servir de base à des discussions au prochain point tech.
Une lecture utile pour comprendre les options offertes par GitHub : https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github#squashing-your-merge-commits

:memo:  Ajout d'une section de doc sur les pratiques de merge de PRs

---

app/views/application/_model_errors.html.slim

Dans le cadre de la réservation par les prescripteurs, on utilise le partial de benign errors qui est bien pratique pour afficher des avertissements. A l'usage, on s'est rendu compte qu'il était parfois difficile à lire, et on propose donc ici quelques modifications de design pour améliorer ça.
Avant : 
Après : 
Il y a deux modifications :
- Pour mettre moins de texte mais quand même faire comprendre qu'il s'agit d'avertissements, on remplace le petit texte `Avertissement :` par des icônes `⚠️`
- Pour clarifier quelles sont les actions possibles, on change le style du texte d'explication pour utiliser le même style que les hints sur les champs de formulaire, et on ajoute un peu d'espace entre ce texte et les cta.

Amélioration de la lisibilité des avertissement

---

app/helpers/users_helper.rb
app/lib/lapin/range.rb
app/models/creneau.rb
app/services/off_days.rb

Pour info, la nouvelle implémentation de `OffDays.all_in_date_range` est 10x plus rapide que l'ancienne (on passe de 100 µs à 10 µs par appel).
Revue :

Mettre à jour les jours fériés de 2023

---

app/controllers/agents/preferences_controller.rb
app/controllers/inclusion_connect_controller.rb
app/controllers/users/sessions_controller.rb

[Depuis Rails 7](https://edgeguides.rubyonrails.org/configuring.html#config-action-controller-raise-on-open-redirects), la méthode `redirect_to` lève une exception  `ActionController::Redirecting::UnsafeRedirectError` si l'URL passé n'a pas le même host que la requête courante.
Ce comportement a été mis en place pour se protéger des "attaques par open redirect", c'est à dire pour éviter qu'un attaquant puisse passer une URL arbitraire vers laquelle rediriger.
Issue Sentry pour la connection InclusionConnect : https://sentry.io/organizations/rdv-solidarites/issues/3751755402
La première étape de connexion avec InclusionConnect consiste à rediriger vers `InclusionConnect.auth_path`. 
```ruby
redirect_to InclusionConnect.auth_path(session[:ic_state], inclusion_connect_callback_url)
```
La …

Bugfix: Rails 7 remonte une erreur quand on redirect vers InclusionConnect

---

app/views/admin/users/_duplicate_alert.html.slim
spec/features/agents/users/agent_can_create_user_spec.rb

Lors d'une discussion / démo avec @NesserineZarouri, nous nous sommes dits que le label du bouton proposant d'« Associer cet usager à l'organisation XXX » serait plus clair si nous disions « Associer cet usager à l'organisation courante ».
Pour tester : https://demo-rdv-solidarites-pr3103.osc-secnum-fr1.scalingo.io/
Avant :
Après : 
Revue :

Améliore le label d'un bouton

---

Gemfile
Gemfile.lock

Closes #3108 
Dans la mise à jour Rails 7 (#3066), nous sommes aussi passés de `puma (5.6.5)` à `puma (6.0.0)`. Or, depuis la version 6.0, puma retourne une 501 pour requête HTTP qui a une méthode exotique. 
Pourquoi est-ce problématique ? Tout est expliqué dans l'issue #3108 !
La solution pour le moment est de rester en version 5, puis de mettre à jour quand pua aura donné la possibilité de configurer son nouveau comportement, ça se discute déjà ici : https://github.com/puma/puma/issues/3014
On peut tester en envoyant une requête HTTP similaire vers la prod et vers la review app : on passe bien à une erreu 404
```
curl -i -X PROPFIND https://www.rdv-solidarites.fr/principals/users/toto@exemple.fr
HTTP/2 501 
[...]
curl -i -X PROPFIND …
```

Remontées 5xx sur les metrics Scalingo (requêtes PROPFIND)

---

app/models/rdv.rb
app/services/concerns/users/creneaux_search_concern.rb
app/services/next_availability_service.rb
app/services/search_creneaux_for_agents_service.rb
app/services/search_creneaux_without_lieu_for_agents_service.rb
app/services/slot_builder.rb
spec/services/slot_builder/busy_time_spec.rb
spec/services/slot_builder_spec.rb
spec/services/users/creneaux_search_spec.rb

En rajoutant les jours fériés de 2023, j'ai modifié l'implémentation de la méthode `OffDays.all_in_date_range` afin qu'elle utilise un `Set` plutôt qu'un `case` sur l'année. La nouvelle implémentation est 10x plus rapide que l'ancienne (on passe de 100 µs à 10 µs par appel).
En lisant le code du `SlotBuilder`, j'ai réalisé qu'il prenait en paramètre `off_days` et qu'il passait ce tableau à travers toute la stack des méthodes qui décomposent le calcul de créneaux. Ce fonctionnement a deux avantages :
1. on n'appelle `OffDays.all_in_date_range` qu'une seule fois (en haut de la stack)
2. la liste des jours fériés est une dépendance explicite
À mes yeux, ces deux avantages ne valent pas le coup face à la complexité apportée par un paramètre supplémentaire. 
Côté performance, imaginons que …

Calcul de créneau : simplification de la manipulation des jours fériés

---

spec/factories/rdv.rb
spec/services/rdv_exporter_spec.rb

Dans #1064, on avait ajouté dans la factory des RDV une valeur forcée sur les timestamps : 
```ruby
FactoryBot.define do
factory :rdv do
created_at { Time.zone.parse("2020-06-05 13:51") }
updated_at { Time.zone.parse("2020-06-05 13:51") }
```
Ces lignes ont été ajoutées pour tester l'export de RDVs sans avoir à persister les données en base (usage de `build` plutôt que `create`), ce qui est une bonne idée pour les perfs (la durée d'exécution est multipliée par 3-4 si on utilise `create` dans ce cas précis).
Cependant peut considérer que cet ajout dans la factory est dangereux car on a le comportement dans tous les tests
```ruby
create(:rdv).created_at.inspect
```
Ce PR déplace donc ces défauts dans un `trait` et utilise ce `trait` dans la spec d'export.
Revue :

Factory RDV : timestamps trompeux

---

spec/mailers/custom_devise_mailer_domain_spec.rb

Cette spec était flaky car on ne maîtrisait pas les valeurs de `created_at` des RDVs.
Revue :

Correcion de flaky spec sur les domaines utilisés par les mailers Devise

---

.rubocop.yml
app/controllers/api/v1/invitations_controller.rb
app/controllers/concerns/token_invitable.rb
app/controllers/users/invitations_controller.rb

Il me semble qu'elle nous gêne plus qu'autre chose, car'en 2022 on n'a même plus idée d'utiliser les versions dynamiques, car ça fait des années qu'on ne les voit plus dans les guides.
Revue :

Désactiver la cop `Rails/DynamicFindBy`

---

config/environments/test.rb

En lançant les specs avec spring en local, ça accélère le temps de chargement des specs d'environ 2.5s (ce qui est très appréciable)
Depuis la mise à jour à rails 7, on a changé cette option de config, et j'avais droit à cette erreur en lançant une spec avec spring :
```
/Users/victormours/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/spring-4.1.0/lib/spring/application.rb:100:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.
(RuntimeError)
```
Et maintenant ça marche mieux. Je n'ai pas l'impression que ça change le temps d'exécution des specs sans spring.
L'inconvénient potentiel que j'y vois, c'est que ça fait un point subtil sur lequel la config de test change …

Permettre l'usage de Spring avec Rails 7

---

app/controllers/users/rdvs_controller.rb
app/models/creneau.rb
app/services/next_availability_service.rb
app/views/admin/creneaux/agent_searches/_lieu_search_results.html.slim
app/views/admin/slots/_slots.html.slim
app/views/common/_creneaux.html.slim
app/views/search/_creneaux.html.slim
app/views/users/rdvs/_creneaux.html.slim
config/environments/test.rb
spec/controllers/users/rdvs_controller_spec.rb

Issue Sentry : https://sentry.io/organizations/rdv-solidarites/issues/3270502722
Nous avons un crash lorsqu'un usager tente de déplacer un RDV sur un autre créneau (`Users::RdvsController#creneaux`) :
```
PG::DataException: ERROR: range lower bound must be less than or equal to range upper bound
```
La raison pour laquelle on passe un range "à l'envers", c'est que l'on récupère une liste de créneaux non ordonnés, et on prend le premier et le dernier élément de la liste. Et parfois, le premier créneau de la liste commence plus tard que le dernier créneau de la liste : 
```ruby
@all_creneaux = @rdv.creneaux_available([...]) # créneaux dans lee désordre
return if @all_creneaux.empty?
start_date = @all_creneaux.first.starts_at.to_date
end_date = [start_date + 6.days, …
```

Crash lors de d'un déplacement de RDV (`range lower bound must be...`)

---

app/views/static_pages/accessibility.html.slim

There was a missing space before RDV-Solidarités
Décrire le pourquoi des modifications
Il manque un espace entre le `à` et `RDV-Solidarités` en gras, utiliser `>` à la place de `|` corrige ceci
Closes #issue_number
Revue :

Fix typo on accessibility

---

app/controllers/search_controller.rb
app/controllers/users/rdv_wizard_steps_controller.rb
app/helpers/search_context_helper.rb
app/views/common/_search_form.html.slim
app/views/search/_creneaux.html.slim
app/views/search/_lieu_selection.html.slim
app/views/search/_motif_selection.html.slim
app/views/search/address_selection/_rdv_solidarites.html.slim
app/views/users/rdv_wizard_steps/step1.html.slim
app/views/users/rdvs/index.html.slim
spec/features/agents/agent_can_test_online_booking_spec.rb

Le but de cette PR est de permettre aux agents de tester le début de la prise de rdv côté usager, en évitant la redirection vers l'agenda s'ils cliquent sur leur liens de prise de rdv.
Ils ne pourront pas aller jusqu'à la fin de prise de rdv, puisque c'est bloqué par #949, mais ça permet déjà d'avoir un aperçu des motifs et créneaux disponibles.
C'est aussi une première étape pour faciliter la prise de rdv par agent prescripteur.
Normalement, rien ne change pour les usagers
Par ailleurs, d'un point de vue technique, ça a plus de sens d'utiliser explicitement une route de prise de rdv comme adresse de redirection quand on est en train de faire de la prise de rdv

Permet aux agents de tester les liens de prise de rdv

---

docs/decisions/2022-11-24-soft-delete-rdv-and-other.md

La discussion autour des `soft_delete` et tout ce que cela entraine reviens souvent sur la table.
Là encore, suite à divers problèmes en production, nous nous remettons à en parler.
Cette PR propose de poser nos réflexions de la semaine dans un document, en espérant que ça puisse nous servir de socle de discussion la prochaine fois (nous gagnerons peut-être un peu de temps ?).

Documenation autour des `soft_delete`

---

app/helpers/agents_helper.rb
app/models/agent.rb
app/views/admin/agents/_agent.html.slim

Pour tester : https://demo-rdv-solidarites-pr3132.osc-secnum-fr1.scalingo.io/
Mise en place d'un badge pour indiquer, dans la liste des agents, lesquels ont été actif durant le dernier mois ou non.
Closes #2678
avant mise en place du tag :
après :
Revue :

Visualiser les agents inactifs

---

app/helpers/search_context_helper.rb
app/services/search_context.rb
app/views/search/_motif_selection.html.slim
app/views/search/_service_selection.html.slim
app/views/users/rdvs/index.html.slim
spec/features/accessibility/public_pages_spec.rb
spec/features/agents/agent_can_test_online_booking_spec.rb
spec/features/users/user_can_search_rdv_spec.rb
spec/requests/prendre_rdv_spec.rb

Lorsqu'un usager sans agent référent vient pour prendre RDV ;
Une fois son adresse saisie et le service choisi ;
Nous lui affichons l'ensemble des motifs (autorisé par la sectorisation) ;
Il peut donc prendre un RDV pour un motif de suivi SANS avoir d'agent référent affecté... C'est un bug.
Après discussion avec les référentes durant [la réunion du 15 novembre 2022](https://www.notion.so/rdvs/Tableau-de-Bord-Consortium-642af48b73d04187b1b10c62b6d7c3d9#4248cffd14314096b3592650e219606c) ; cette PR
Ici, avec le paramètre `agent_id`, l'agent référent ne proposant qu'un seul motif de suivi à la réservation en ligne, nous arrivons directement au choix du lieu.
Closes #2966
Revue :

Ajoute un parcours pour les RDV sur des motifs de suivi pour l'usager

---

scripts/import_conseillers_numeriques.rb

Les CNFS existants ne veulent plus être relancés.
Revue :

Ne pas ré-envoyer de mail d'invtation aux CNFS existants lors de l'import

---

app/controllers/admin/rdvs_controller.rb
app/controllers/api/v1/public_links_controller.rb
app/mailers/agents/export_mailer.rb
app/models/agent.rb
app/models/application_record.rb
app/models/motif.rb
app/policies/agent/absence_policy.rb
app/policies/agent/agent_policy.rb
app/services/users/geo_search.rb
docs/2-contributions.md

Dans plusieurs endroits du code, lorsque l'on veut combiner des requêtes en base dont la structure est incompatible, on récupère une liste d'ID retournée par chaque requête, puis on passe la combinaison de ces IDs à une requête finale.
Cette méthode a deux inconvénients : 
- elle multiplie le nombre d'aller-retours entre Ruby et Postgres
- elle instancie des tableaux (parfois grands) en mémoire puis les passe à Postgres qui va devoir les parser
- on fait des opérations de dédoublonnage en mémoire en Ruby au lieu de laisse Postgres gérer l'exécution d'une sous-requête
Qu'en dîtes-vous ? :upside_down_face:

Utiliser des sous-requêtes SQL plutôt que de passer des listes d'IDs

---

app/blueprints/motif_blueprint.rb

J'ajoute l'attribut `follow_up` au blueprint des motifs, qu'on utilise maintenant que l'on gère les rdvs avec référents.

feat(webhooks): Add follow_up attribute to motif blueprint

---

config/environments/test.rb
spec/features/allocation_for_search_context_spec.rb

Depuis peu on a des échecs sur `allocation_for_search_context_spec.rb`.
Je pensais que la raison était l'usage l'instanciation de tableau d'IDs ici : 
https://github.com/betagouv/rdv-solidarites.fr/blob/04800e14a27354e2ce01bd95ec8ae50d2cf05515/app/models/motif.rb#L183
Mais en fait, la véritable cause était que nous chargions le fichier `app/models/rdv.rb` pour la première fois dans la méthode ci-dessus, et que ce chargement causait beaucoup d'allocation mémoires (légitimes).
Je propose que l'on active le eager loading de l'application en CI. Je suis tenté de même l'activer pour les exécutions locales des tests également, qu'en pensez-vous ?
PS :  Pour devenir un pro du chargement de code, le guide officiel est comme toujours très bien fait ! …

Éviter que la spec sur l'allocation mémoire soit flaky

---

app/controllers/admin/organisations/online_bookings_controller.rb
app/models/organisation.rb
app/views/admin/organisations/online_bookings/show.html.slim
spec/models/organisation_spec.rb

Ticket Zammad : https://zammad10.ethibox.fr/#ticket/zoom/3557
Ceci est une petite amélioration conçue avec @NesserineZarouri pour répondre en partie à la demande ci-dessus. Cela permet aux agents d'avoir des liens plus agréables à manipuler, en particulier si ils sont sur plusieurs organisations. :wink: 
Note : la partie `org_slug` de la route n'est pas du tout utilisée, sa seule utilité est de justement faire des liens qui portent une information pour les humains. Il est inspiré du fonctionnement de StackOverflow, où les liens suivants sont équivalents :
- https://stackoverflow.com/questions/1302022
- https://stackoverflow.com/questions/1302022/best-way-to-generate-slugs-human-readable-ids-in-rails 
Revue :

Ajouter le nom de l'organisation dans le lien de réservation en ligne

---

app/models/concerns/rdvs_user/creatable.rb
spec/features/users/user_can_register_to_collective_rdv_spec.rb

Je viens de m'apercevoir de cet oubli.
C'est fix et j'ai adapté le test en conséquence. Je travaille sur un test un peu plus complet dans cette PR : https://github.com/betagouv/rdv-solidarites.fr/pull/3153 
Je modifie la PR en suivant en prenant en compte ces modifications et j'ajouterai 2 tests : un test avec des participants existant et un test sans participant pour les différentes situations (usager invité et usager connecté).

Fix multiple notifications aprés l'ajout d'une participation pour un rdv collectif

---

app/models/concerns/rdv/updatable.rb
app/models/concerns/rdvs_user/creatable.rb
app/services/notifiers/rdv_base.rb

Pour rendre notre code un peu plus lisible, on peut grouper ensemble les changements de valeur de `rdv.skip_webhooks`. Ça permet d'éviter que les notifiers aient des effets de bord, et qu'on ai un bug si on oublie de faire cet appel après un notifier.

Petit refacto de skip_webhooks

---

spec/services/users/creneaux_search_spec.rb

De temps en temps ce test échoue, notamment sur github.
Je n'arrive pas à reproduire en local mais je pense que le problème est que les 2 rdv créés lors du test ont les mêmes dates de démarrage et de temps en temps la méthode `next_availability` de `Users::CreneauxSearch` renvoi l'un ou l'autre des rdv alors que le test attend un rdv bien défini : `expect(subject.next_availability).to eq(rdv)`

Fix flaky test creneaux_search_spec.rb

---

app/form_models/user_rdv_wizard.rb
spec/features/users/user_can_register_to_collective_rdv_spec.rb

En travaillant sur les réservations de rdv collectif par prescripteur, on a trouvé un bug qui avait lieu dans le cas d'une race condition de réservation :
- Un usager commence son inscription pour le rdv collectif, se connecte, commence le wizard mais n'a pas encore confirmé son rdv
- D'autres usagers finissent leur inscription, et le rdv n'a plus de disponibilités
- Le premier usager passe à l'étape suivante dans le wizard -> Erreur 500 parce que le scope `Rdv.collectif_and_available_for_reservation` ne renvoie plus le rdv collectif sélectionné.
Le fix est donc de ne pas filtrer par rdv avec des places disponibles dans le rdv wizard. C'est ensuite la méthode `#creneau` qui va renvoyer nil, et le controller qui va rediriger vers le début de la prise de rdv

Evite les erreurs lors d'une race condition de réservation en ligne de rdv collectif

---

app/services/add_conseiller_numerique.rb
scripts/backfill_agent_territorial_access_rights.rb
spec/services/add_conseiller_numerique_spec.rb

Fix pour https://sentry.io/organizations/rdv-solidarites/issues/3793554494/?project=1811205
Une fois que la logique sera corrigée et le script de backfill lancé, on pourra ajouter une validation ou un autre mécanisme pour s'assurer que les agents ont des access rights.

Ajout des territorial access rights à l'import des CNFS

---

app/helpers/plage_ouvertures_helper.rb
app/views/common/_recurrence.html.slim
spec/helpers/plage_ouvertures_helper_spec.rb

Ticket Zammad : https://zammad10.ethibox.fr/#ticket/zoom/3527
Dans ce ticket, un agent nous demande de pouvoir faire terminer une plage d'ouverture à 21h, car pour le moment on ne propose des choix que jusqu'à 20h.
Je propose donc d'étendre ces choix jusqu'à 23h pour être tranquille. Je pense que ce changement n'est pas gênant pour les agents qui n'ont pas besoin de finir si tard, tout en permettant de le faire si besoin.
Note : on pourrait aussi modifier l'affichage de l'agenda pour qu'il affiche les soirées, mais si c'est un besoin on le fera dans un autre ticket, car ça pose des questions d'UX.
Pour tester : Se connecter avec `martine@demo.rdv-solidarites.fr / 123456` et créer une plage d'ouverture : 
https://demo-rdv-solidarites-pr3152.osc-secnum-fr1.scalingo.io/admin/organisations/1/a …

Permettre de créer des plages d'ouverture qui finissent après 20h

---

app/views/admin/rdvs/_rdv_details.html.slim
app/views/mailers/common/_rdv_overview.html.slim
app/views/stats/index.html.slim

Nous avons des pages très visitées qui affichent un (s) alors qu'on peut facilement accorder en nombre.
Revue :

Utiliser `pluralize` à la place de "(s)"

---

app/views/common/_inclusionconnect_button.html.slim

Suite à l'entretien avec Sonia, PM sur le service Inclusion Connect, elle nous propose de modifier la phrase d'explication. 
Avant :
Après :

Modification de l'explication d'inclusion connect

---

app/policies/agent/rdv_policy.rb
app/views/admin/agent_agendas/show.html.slim
app/views/admin/rdvs/_rdv_visibility.html.slim
app/views/admin/rdvs/index.html.slim
app/views/admin/users/show.html.slim

Pour tester : https://demo-rdv-solidarites-pr3142.osc-secnum-fr1.scalingo.io/
En tant que professionnel attaché au service social ; 
Lorsque je vais voir la fiche d'un usager ;
Alors, je visualise ses RDV ayant un motif lié au service social.
Le problème, c'est que ça ne permet pas à ces professionnels de savoir si l'usager prend des RDV en PMI pour son ou ses enfants.
Dans le Pas-de-Calais, il n'y a pas d'application métier pour la PMI, aussi les agents utilise RDV Solidarités pour faire du suivi. Mais là, l'information n'est pas visible. Et depuis le début, les professionnels du service secrétariat et admin ne se rendent pas compte de ce non-visibilité des autres agents sur les RDV des autres services... Cela pose un problème.
Cette PR à un petit objectif très simple : documenté ce qui …

Affiche quels RDV peuvent être vues par l'agent

---

Gemfile
Gemfile.lock

Depuis Rails 7, la façon de définir `default_timezone` a changé : 
DEPRECATION WARNING: ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.default_timezone` instead.
L'appel déprécié était fait par la gem `groupdate`, dont la version datait de décembre 2019. J'ai mis à jour vers la dernière version, datant d'avril 2022. J'ai cherché "breaking" dans [le changelog](https://github.com/ankane/groupdate/blob/master/CHANGELOG.md) et je ne vois rien d'alarmant. J'ai aussi vérifié le rendu de la page `/stats` en local, et le changement de version semble bien ne rien changer.
Revue :

Éviter le message de dépréciation sur `ActiveRecord::Base.default_timezone`

---

app/controllers/api/v1/users_controller.rb
spec/requests/api/v1/users_request_spec.rb

Il y avait un petit bug sur l'endpoint `api/v1/:organisation_id/users/:user_id`: Si l'agent et le `user` n'appartenaient pas à l'organisation en question, cet endpoint renvoyait quand même le `user`. Je fais en sorte de régler ça en cherchant toujours le user dans le scope de l'organisation défini par l'URL.

fix(api): Render not_found when user does not belong to org

---

app/services/search_context.rb
app/views/search/_organisation_selection.html.slim
spec/features/users/user_can_search_rdv_spec.rb

Pour rappel, suite à l'ouverture des plages d'ouvertures sans lieux, nous avions dû ajouter une étape de sélection d'organisation dans #3118 , car ça posait un souci lorsque plusieurs motifs de plusieurs organisations étaient disponibles (cas du 64).
Ici j'affiche également la prochaine disponibilité sur ces organisations comme ce qu'on fait avec les lieux et filtrent celles qui n'ont pas de dispos.
J'en profite pour retoucher un peu le `user_can_search_rdv_spec`, pour que chaque bloc de test ait ses propres variables. 
Des variables étaient appelés d'un bloc à l'autre et créaient des incohérences. Je trouve ça également plus lisible.

Montrer les prochaines disponibilités par organisation

---

app/models/concerns/rdv/updatable.rb
spec/models/concerns/rdv/updatable_spec.rb

Je suis tombé sur un bug en investiguant ce ticket : https://github.com/betagouv/rdv-solidarites.fr/issues/3144
A priori le bug que j'ai trouvé n'explique pas le problème du ticket (?) mais c'est un bug critique car depuis cette refacto : https://github.com/betagouv/rdv-solidarites.fr/pull/3099 les notifications de modification et d'annulation par les agents pour les rdv collectifs ne partent plus !
De plus les tests n'allaient pas assez loin et on se contentait de vérifier l'appel à la méthode new du notifier et pas l'envoi réél de la notification.

[BUG] Les notifications ne sont pas envoyées aux usagers pour les modifs des rdv collectifs coté agent

---

app/views/search/address_selection/_rdv_aide_numerique.html.slim
app/views/search/banners/_rdv_aide_numerique.html.slim
config/initializers/content_security_policy.rb

Pour tester : https://demo-rdv-solidarites-pr3188.osc-secnum-fr1.scalingo.io/
L'idée de cette PR n'est pas d'avoir la landing page parfaite, mais plutôt de dépenser une heure de boulot pour améliorer grandement la page actuelle qui est très rustique.
Note : j'ai utilisé une iframe pour afficher la carte, idéalement ce serait top si l'équipe carto pouvait proposer une page sans layout pour cet usage ! 
Revue :

Amélioration rapide de la page d'accueil de rdv-aide-numerique.fr

---

app/controllers/admin/territories/rdv_fields_controller.rb
app/controllers/admin/user_in_waiting_rooms_controller.rb
app/javascript/components/calendar.js
app/jobs/cron_job.rb
app/mailers/agents/waiting_room_mailer.rb
app/models/concerns/rdv/using_waiting_room.rb
app/models/rdv.rb
app/models/territory.rb
app/views/admin/agents/rdvs/index.json.jbuilder
app/views/admin/rdvs/_rdv.html.slim
app/views/admin/rdvs/_rdv_status_dropdown.html.slim
app/views/admin/rdvs/_waiting_room.html.slim
app/views/admin/territories/rdv_fields/edit.html.slim
app/views/admin/user_in_waiting_rooms/create.js.erb
app/views/mailers/agents/waiting_room_mailer/user_in_waiting_room.html.slim
config/locales/mailers.fr.yml
config/locales/models/rdv.fr.yml
config/locales/views/configuration.yml
config/routes.rb
db/migrate/20221011071059_add_optionals_fields_to_territories.rb
db/schema.rb
spec/form_models/admin/edit_rdv_form_spec.rb
spec/mailers/previews/agents/waiting_room_mailer_preview.rb
spec/models/concerns/rdv/updatable_spec.rb
spec/models/concerns/rdv/using_waiting_room_spec.rb
spec/models/rdv_spec.rb
spec/models/territory_spec.rb
spec/requests/admin/configure_user_in_waiting_room_spec.rb
spec/requests/admin/user_in_waiting_room_spec.rb

Nous utilisions un statut de RDV pour signaler un usager en salle d'attente.
La fonctionnalité est utilisée par les personnes à l'accueil pour prévenir les travailleurs et travailleuses médico-sociaux.
Certains départements auraient aimé pouvoir signaler un usager en salle d'attente par email. Jusqu'à présent, elle ne faisait qu'un remplissage hachuré du RDV dans l'agenda.
Cette PR propose d'extraire la gestion du signalement d'usager en salle d'attente des statuts de RDV.
Dans le module de configuration, à propos de la fiche RDV, nous pouvons activer l'utilisation de ce module en choisissant l'une des options de signalement (ou les deux) : email et/ou hachure dans l'agenda.
Si une des deux options de notification est cochée, que le RDV est du jour, et qu'il a un statut `unknown`, alors …

notifier l'agent de l'arrivée d'un usager en salle d'attente

---

app/controllers/concerns/token_invitable.rb
app/services/notifiers/rdv_base.rb
config/routes.rb
spec/features/agents/rdv_wizard/step4_spec.rb
spec/models/concerns/rdvs_user/creatable_spec.rb
spec/services/notifiers/rdv_created_spec.rb
spec/sms/users/rdv_sms_spec.rb

Les sms envoyés aux responsables n'avaient pas de token. Voir https://sentry.incubateur.net/organizations/betagouv/issues/15798/?environment=production&query=is%3Aunresolved (une cinquantaine d'occurrences par jour)
Pour la spec, j'ai pas vraiment trouvé de test qui faisait vraiment des vérifications sur les sms au niveau intégration, donc je me suis positionné à ce niveau, vu qu'on est vraiment sur du bug difficile à voir autrement qu'en intégration.
Le fix est de s'assurer qu'on génère bien un token pour le user qui est notifié, et pas le user qui participe (et de faire la vérification correspondante au moment de l'authentification).
En regardant les tests de plus près, je me suis rendu compte que c'était pas évident de tester que le bon lien était envoyé, et qu'une bonne modification à …

Correctif pour les tokens envoyés dans les sms aux responsables

---

app/jobs/application_job.rb
app/mailers/application_mailer.rb
app/mailers/custom_mailer_delivery_job.rb
spec/jobs/custom_mailer_delivery_job_spec.rb

Actuellement, nous avons des jobs de mailer qui retry et qui remontent dans Sentry car ils ne trouvent pas la plage d'ouverture ou l'absence passée en paramètre.
Nous pouvons supposer qu'il s'agit d'une création / édition suivie d'une suppression. En effet, lorsqu'une plage / absence est modifiée, un job est mis à la file pour envoyer un mail d'information. Mais quand une plage / absence est supprimée, la suppression et l'envoi du mail sont synchrones. Il est donc possible que, lorsqu'un modifie puis supprimer dans la foulée, le job s'exécute une fois que l'élément soit supprimé.
Cette PR vise donc à passe sous silence les cas où le record n'est pas trouvé lors de la phase de dé-serialization du job. :wink: 
On a actuellement 82 jobs en retry, on pourra les supprimer avec 
```ruby …
```

Ignorer les jobs de mailers qui ne trouvent pas la plage / absence

---

app/services/search_context.rb
spec/features/users/user_can_search_rdv_spec.rb
spec/services/search_context_spec.rb

Certaines organisations comme celles du 64 ont des motifs qui ont le même nom et le même type mais avec des services différents.
Dans ces cas-là il faut s'assurer qu'un choix de service soit fait côté usager,  sinon ça crée des incohérences: le motif étant retrouvé à partir du nom et du type, on se retrouver à calculer des créneaux sur deux motifs distincts d'une page à l'autre.

Toujours montrer la page du choix de service lorsqu'il y en a plusieurs

---

app/views/search/_service_selection.html.slim

Je change ici l'url vers laquelle on est redirigée au moment de la sélection du service pour utiliser `prendre_rdv_path` de manière analogue à ce qu'on fait à la sélection de  motif ou de lieu.
Le helper `path_to_motif_selection` reste utilisé pour le retour en arrière.

Fix chemin après sélection de service

---

app/javascript/components/motif-form.js
app/views/admin/motifs/_form.html.slim

Pour tester : https://demo-rdv-solidarites-pr3192.osc-secnum-fr1.scalingo.io/
L'objectif ici est de ne pas afficher le paramétrage de la sectorisation quand un motif est créé pour un rdv de suivi réservable en ligne.
Closes #3125
avant:
après :
Revue :

masque la sectorisation en cas de rdv de suivi

---

app/views/admin/rdvs/_short_rdv.html.slim

Les libellés de motif ne précisent pas toujours si c'est un motif de RDV collectif. Idem pour les motifs de suivis.
Des départements nous ont demandé d'ajouter un badge pour visualiser le type de RDV dans la liste des RDV à venir d'un usager.
close #3210
Pour tester : https://demo-rdv-solidarites-pr3215.osc-secnum-fr1.scalingo.io/
Avant :
Après : 
Revue :

Affiche collectif ou suivi sur la liste RDV usager

---

config/locales/models/attributes.fr.yml

Le département des Hautes-Seine nous a signalé qu'un label dans l'écran de fusion d'usager n'était pas traduit. Cette PR propose une correction
close #3211
Pour tester : https://demo-rdv-solidarites-pr3214.osc-secnum-fr1.scalingo.io/
Avant 
Après
Revue :

Ajoute la clef et traduction pour le responsible

---

app/mailers/agents/rdv_mailer.rb
app/models/rdvs_user.rb
app/views/mailers/agents/rdv_mailer/rdv_cancelled.html.slim
app/views/mailers/agents/rdv_mailer/rdv_created.html.slim
app/views/mailers/common/_rdv_overview.html.slim
config/locales/mailers.fr.yml
spec/features/prescripteurs/can_add_a_user_to_a_rdv_collectif_spec.rb

Les titres des emails et le contenu à destination des agents lors des inscriptions et annulations des participants aux rdv collectifs ne sont pas cohérents.
Il n'y a pas de changement concernant les emails à destination des usagers.
Voici les changements que cette PR met en place : 
Création Avant/Après :
Annulation Avant/Après :

Plus de cohérence dans les titres et contenu des emails à destination des agents pour les rdv collectifs

---

app/controllers/admin/territories/teams_controller.rb
app/views/admin/creneaux/agent_searches/index.html.slim
app/views/admin/territories/teams/index.json.jbuilder
config/routes.rb
spec/controllers/admin/territories/teams_controller_spec.rb
spec/requests/admin/territories/cruds_teams_configuration_spec.rb

Pour éviter d'avoir des comportements différents, de multiplier les actions, cette PR propose, comme évoqué dans le ticket #2201, de regrouper l'action de recherche et d'index pour les équipes.
ref #2201
Revue :

Utilise l'action index plutôt que search pour Teams

---

app/controllers/admin/territories/zones_controller.rb
app/models/zone.rb
app/views/admin/territories/zones/_form.html.slim
config/locales/views/admin_territories_sectors.fr.yml
spec/models/zone_spec.rb
spec/requests/admin/territories/crud_zones_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3212.osc-secnum-fr1.scalingo.io/
Afin de faciliter la création de commune ou de rue à la chaîne ; Des référentes nous ont demandé d'ajouter un bouton pour créer et ajouter une nouvelle zone (rue ou commune).
À la manière de ce qui existe déjà pour les secteurs.
Cette PR ajoute le bouton et les mécanismes liés à la sélection de la rue ou de la commune
Close #1672
Revue :

Ajoute un bouton pour recréer une zone tout de suite

---

app/models/stat.rb

Ajout du label prescripteur aux stats

---

app/services/add_conseiller_numerique.rb
app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/devise/mailer/invitation_instructions_cnfs.text.erb
config/locales/devise.fr.yml
scripts/import_conseillers_numeriques.rb
spec/services/add_conseiller_numerique_spec.rb

Plusieurs CnFS nous ont reprochés d'être trop insistants dans nos mails d'invitation. Pour le moment, on désactive donc les cc qui sont envoyés à leur adresse mail non officielle (c'est donc un rollback de https://github.com/betagouv/rdv-solidarites.fr/pull/2811, en plus du rollback des relances fait dans https://github.com/betagouv/rdv-solidarites.fr/pull/3149).
Si on améliore un peu notre mail et/ou notre stratégie de relance, on pourra envisager de remettre ces adresses en cc.

Ne pas utiliser les adresse mail non-officielles des cnfs

---

app/models/rdv.rb

Cette PR est un correctif rapide pour #3233 pour débloquer les usagers et agents en attendant que la PR https://github.com/betagouv/rdv-solidarites.fr/pull/3234 soit prête.
Il n'y a pas de changement d'interface, puisque la validation en front est encore là, mais au moins ça évitera les erreurs.

Correctif rapide pour #3233

---

app/form_models/admin/rdv_form_concern.rb
app/sms/users/rdv_sms.rb
app/views/admin/rdvs/edit.html.slim
app/views/admin/rdvs_collectifs/new.html.slim
spec/features/agents/rdvs_collectifs/agent_can_create_rdv_collectif_spec.rb
spec/features/agents/rdvs_collectifs/full_lifecycle_spec.rb
spec/sms/users/rdv_sms_spec.rb

correctif long terme pour #3233 (en plus de #3235)
On transforme l'erreur de validation en avertissement, puisqu'il y a des cas où les intitulés ont une bonne raison de faire plus de 50 caractères.
Avant :
Impossible de mettre un intitulé de plus de 50 caractères, et les rdv existants sont soit tronqués soit en erreur
Après :
On met un avertissement, et on laisse l'agent choisir l'intitulé

Changement de la contrainte sur la longueur des intitulés

---

app/models/rdv.rb
spec/features/users/user_can_manage_collective_rdv_spec.rb
spec/models/rdv_spec.rb

fixes https://github.com/betagouv/rdv-solidarites.fr/issues/3227
C'est le plus petit fix possible pour corriger le bug, mais d'autres questions restent en suspens.
Ces deux états dépendent de l'action de l'usager, mais un seul des deux est autorisé dans l'interface.
Si je comprend bien le code, il n'est pas possible de passer directement une participation en revoked. Il faut passer le rdv en revoked, ce qui fera passer la participation dans cet état aussi, et pourtant on a bien de la logique pour mettre à jour le rdv à partir de ce changement de participation.
La machine à état (liste des états possibles et des transitions autorisées d'un état à l'autre) de l'ensemble 
Pour le moment, un rdv collectif en "Absence non excusée" signifie que aucun des participants n'est venu. Est-ce que ça …

Ne pas passer des rdv collectifs en annulés en cas d'annulation de l'usager

---

.env.sample
app/views/common/_franceconnect_button.html.slim
spec/features/users/user_can_login_using_france_connect_spec.rb

Ce matin j'ai demandé l'ajout du domain rdv-aide-numerique.fr à notre config FranceConnect, et j'en ai profité pour lire les guidelines : https://partenaires.franceconnect.gouv.fr/monprojet/recetter/
> Merci de faire attention à l’écriture du terme « FranceConnect » et d’accoler les deux mots France et Connect partout où « FranceConnect » est mentionné.

Respecter la casse de "FranceConnect"

---

app/controllers/static_pages_controller.rb
app/views/static_pages/microsoft_domain_verification.json.erb
config/routes.rb
spec/requests/domain_verification_spec.rb

Actuellement, quand on lance une synchro Outlook, Microsoft indique que notre app est "unverified", ce qui est le cas puisqu'on n'a pas fait le processus de vérification. Cette PR permet de faire cette vérification en ajoutant le bon fichier au bon endroit

Ajout de la vérification de domaine pour la synchro Outlook

---

app/controllers/static_pages_controller.rb
spec/requests/domain_verification_spec.rb

Toujours dans le contexte de la mise en prod d'outlook (https://github.com/betagouv/rdv-solidarites.fr/issues/3246), j'ai eu une erreur lors de la vérification du domaine : il faut que le header Content-Type soit exactement `application/json`, et non pas `application/json; charset=utf-8`.
J'en profite pour ajouter un lien vers la doc depuis le controller.
J'ai testé la vérification avec la review app, ça m'a permis d'apprendre qu'il faut aussi un content-length, et je l'espère d'éviter une énième PR de correctif 😬 
(ping @damienlethiec pour info)

Correction du content type pour la vérification de publisher Azure Microsoft

---

app/jobs/outlook/mass_destroy_event_job.rb
spec/jobs/outlook/mass_destroy_event_job_spec.rb

En testant la synchro outlook, on a eu un cas où l'event avait déjà été supprimé sur outlook (potentiellement à cause d'une race condition de deux jobs qui tournaient en parallèle, mais ça pourrait aussi arriver si l'évènement a déjà été supprimé manuellement sur le calendrier outlook). Avec l'implémentation précédente, ça faisait une boucle infinie d'appel à l'api d'outlook.
Dans cette nouvelle implémentation, on se dit que ce n'est pas grave s'il y a des erreurs lors de la suppression des évènements, et on déconnecte l'utilisateur même s'il y a encore potentiellement des évènements dans son calendrier outlook.
lié à #3246 et #3115

Permet la déconnexion Outlook en cas d'erreur de suppression d'un event

---

spec/jobs/outlook/update_event_job_spec.rb

Dans le cas où l'id 12 avait déjà été affecté (ce qui peut arriver puisque les specs tournent dans un ordre aléatoire), on avait une erreur sur cette spec.
De manière générale c'est toujours plus safe d'éviter d'assigner des id dans les lets.

Corrige une flaky spec

---

app/controllers/admin/territories/teams_controller.rb
app/views/admin/territories/teams/index.html.slim
spec/requests/admin/territories/cruds_teams_configuration_spec.rb

ref https://zammad10.ethibox.fr/#ticket/zoom/4079
La recherche d'équipe dans la page de liste des équipes fonctionne bien.
Dans le formulaire pour « Trouver un RDV », la liste n'est pas filtrée par la saisie.
Le problème, c'est que d'un côté, nous utilisions un paramètre `serach` alors que de l'autre, nous utilisons `term`.
`term` est plus largement utilisé dans notre application, aussi cette PR propose de remplacer le paramètre `search` dans la liste des équipes par `term`.

Recherche une équipe

---

app/helpers/admin_helper.rb
app/models/domain.rb
app/models/rdv.rb
app/views/admin/motifs/_form.html.slim
app/views/admin/motifs/show.html.slim
app/views/admin/organisations/setup_checklists/show_conseiller_numerique.slim
app/views/admin/static_pages/support.html.slim
app/views/agents/outlook_sync/show.html.slim
app/views/agents/webcal_sync/show.html.slim
app/views/layouts/_cnfs_online_booking_banner.html.slim
spec/models/domain_spec.rb

Le but premier de cette PR était de faire que dans l'index des rdv côté usager, les rdv pris avec un service autre que les CNFS soient visibles (c'est utile notamment pour les Pass Numérique et les Maisons France Service).
Au passage, j'en ai profité pour passer d'autres features flags qui étaient sur le service en feature flags sur le domaine. Ce fonctionnement sur le service est du legacy d'avant qu'on ai deux domaines différents.
Avec cette PR, l'appli se comporte de manière plus cohérente pour les membres d'une même équipe.
Cette PR introduit aussi un léger changement de comportement, qui est la suite de la mise en place de RDV Aide Numérique : côté usager, on arrête d'afficher sur RDV Solidarités les rendez-vous pris sur RDV Aide Numérique (on avait laissé ça en place pour la période …

Correctifs pour les services autre que CnFS sur le domaine RDV Aide Numérique

---

Gemfile
Gemfile.lock

Lors de #2548 la version de la gem `mail` a été fixée en RC car c'était la seule version compatible avec Ruby 3.1.
Une version stable est sortie il y a un mois (le 3 décembre 2022), et donc on peut cesser de fixer la version et utiliser la dernière version en date ! :tada:

Mise à jour de la gem `mail` qui était fixée en version RC

---

scripts/scalingo_dump.sh

Ce script se base sur la sortie de la commande `scalingo backups-download` pour déterminer le nom du fichier tar.gz à extraire, mais sur ma machine cette méthode ne fonctionne jamais, et donc je dois faire les choses à moitié à la main à chaque fois.
Ce fix emploie donc une autre méthode : télécharger le tar.gz puis retrouver le fichier tar.gz le plus récent, ce qui semble plus robuste que de parser STDOUT, bien que ce ne soit toujours pas idéal.

Fix scalingo_dump.sh

---

app/controllers/admin/rdvs_controller.rb
app/controllers/agent_auth_controller.rb
app/models/user.rb
app/views/admin/rdvs/index.html.slim

Une fois encore, Skylight nous indique qu'une minorité de requêtes sur la liste des RDVs est très lente (jusqu'à 55 secondes !).
Nous pouvons voir que 99% du temps est passé en base, et une majorité de ce temps est passé à évaluer une requête qui compte les participations pour afficher ceci : 
Et je propose donc de ne pas faire cette requêtes, pour gagner beaucoup en perf, et afficher ceci à la place : 
En utilisant `rack-mini-profiler`, j'ai trouvé et corrigé les requêtes N+1, et j'ai donc complété ce que l'on passe à `includes` pour que tout soit préchargé.
Aussi, dans la vue, au lieu de faire `@rdvs.any?` (qui déclenche une requête `SELECT 1 FROM ...` pour vérifier si au moins un record existe), on peut utiliser `@rdvs.total_count`, que nous avons de toute façon déjà chargé pour …

Améliorer les perfs de la liste des RDVs (janvier 2023)

---

Gemfile.lock

Cette mise à jour permet de corriger le crash qui a lieu avec Ruby 3.2 lorsqu'on appelle `save_and_open_page`.
Voir : https://github.com/copiousfreetime/launchy/pull/138

Mise à jour de la gem launchy

---

app/models/organisation.rb
app/models/webhook_endpoint.rb

Dans cette PR j'ajoute une méthode pour envoyer des webhooks sur l'url de destination pour toutes les ressources liés à l'organisation du `webhook_endpoint`.
Cette méthode nous est utile notamment lorsqu'on lie une organisation de RDV-S à RDV-U.
Pour l'instant l'idée est de l'appeler manuellement sur le `webhook_endpoint` en question.
On pourrait améliorer ça en:
* proposant de l'appeler depuis la page du `webhook_endpoint` 
* l'appelant éventuellement dans un `after_create` callback pour ceux liés à RDV-I

feat(webhooks): Add method to trigger webhook for subscribed resources

---

app/views/common/_footer_users.html.slim
app/views/layouts/application_agent.html.slim

Je suppose que l'intention de base était de pointer vers le dernier commit, et non vers la liste des commits, puisque le hash n'a aucune valeur dans ce contexte.

Correction du lien vers le source du projet

---

app/controllers/search_controller.rb
app/controllers/users/rdv_wizard_steps_controller.rb
app/form_models/user_rdv_wizard.rb
app/helpers/search_context_helper.rb
app/services/search_context.rb
config/routes.rb
spec/features/users/user_can_open_resin_link_spec.rb

Rés'In est une plateforme pilotée par l’équipe inclusion numérique de la Métropole de Lyon. Leur site propose un parcours "[Orienter un bénéficiaire](https://resin.grandlyon.com/orientation)", qui permet de trouver les services répondant à une besoin. 
La liste des structures pouvant répondre à ce besoin est déterminée lors du parcours, constitué d'une suite de questions (ex: "Je souhaite acquérir des compétences numériques" -> "Utilisation d'internet" -> "Trouver un RDV dans une structure d'accompagnement"). À la fin de ce parcours, Rés'In souhaite pouvoir proposer un lien vers RDV Aide Numérique qui affiche toutes les lieux qui ont des plages d'ouvertures ouvertes pour le motif "Accompagnement individuel".
Il nous a semblé raisonnable d'introduire un lien personnalisé pour Rés'In pour …

Rés'in > Permettre de passer plusieurs orgas dans un lien public de résa

---

app/jobs/cron_job.rb

D'après [la doc](delayed_cron_job) de la gem `delayed_cron_job` : 
> Note that if you have a CronJob scheduled and change its `cron_expression` in its source file, you will have to remove any scheduled instances of the Job and reschedule it (e.g. with the snippet above: `rails db:migrate`). This is because the `cron_expression` is already persisted in the database (as `cron`).
Mais j'ai testé en local, et nous ne sommes pas obligés de supprimer le job de cron puis de le re-créer, nous pouvons simplement faire un `update` sur l'expression, et un callback `ActiveRecord` se chargera de mettre à jour l'heure de prochain lancement de ce job (on peut voir la définition de ce callback [ici](https://github.com/codez/delayed_cron_job/blob/c01812bd8a65fd74cd1dcfd5b3515bf63c391c5e/lib/delayed_cron_jo …

Bugfix: mettre à jour l'expression CRON en base lorsqu'elle change dans le code

---

app/models/agent.rb
app/models/organisation.rb
app/services/agent_removal.rb
spec/services/agent_removal_spec.rb

J'ajoute une option `dependent: :destroy` à la relation à Agents <-> Organisations pour que les callbacks soient appelés quand un agent est retiré d'une orga et ainsi envoyer le webhook correspondant.
En faisant ça je me suis rendu compte que le service `AgentRemoval` ne prenait pas en compte les validations avant destruction, notamment [celle-ci](https://github.com/betagouv/rdv-solidarites.fr/blob/28d83cc6b443058f7525d190f06beaa3f298ca39/app/models/agent_role.rb#L42). 
Du coup j'ai adapté le service et ses tests pour prendre ça en compte, mais si c'est pas le comportement que l'on veut je peux changer (peut-être que @yaf ou @francois-ferrandis ont un avis là-dessus ?).

fix(webhook): Trigger webhook when agent removed from org

---

app/views/admin/rdvs/index.html.slim

Fixes #3069
Nous avons des demandes d'export qui contiennent plus de 30 000 RDVs. Lorsque ces exports sont traités, il arrive que SendInBlue nous informe qu'il ne peut pas envoyer une pièce jointe de plus de 14 Mo. Que se passe-t-il à ce moment là ? L'agent ne reçoit pas le mail, et donc iel re-demande l'export. 
Conséquences : 
- l'agent ne peut pas obtenir l'export dont il a besoin
- notre base de donnée et notre système de jobs sont ralentis
**La solution fondamentale est de questionner les besoins de chaque persona, mais ça demande beaucoup de temps.**
En attendant de faire ce travail, j pense que limiter la taille des exports à 10 000 RDVs permet d'éviter les blocages actuels, sans être non plus trop contraignant (au lieu d'avoir un export sur les 2 derniers mois, l'agent peut …

Empêcher d'exporter trop de RDVs

---

app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/static_pages/politique_de_confidentialite.html.slim

Pour info, je viens de créer et configurer une boite mail contact@rdv-solidarités.fr pour qu'elle redirige les mails reçus vers contact@rdv-solidarites.fr (et donc vers le Zammad). :wink: 
Revue :

Corrige une erreur dans le nom de domaine de l'e-mail de contact

---

.env.sample

Mise à jour du .env.sample pour documenter les variables DEGRADED_SERVICE_MESSAGE_AGENTS et DEGRADED_SERVICE_MESSAGE_USERS permettant d'afficher le bandeau en cas de problèmes.
Revue :

documente la variable d'environnement DEGRADED_SERVICE_MESSAGE_AGENTS

---

app/javascript/stylesheets/components/_rdv_status.scss
app/models/rdvs_user.rb
app/models/stat.rb
app/views/admin/rdvs/_rdv_status_dropdown.html.slim
config/locales/models/rdv.fr.yml
db/migrate/20230213155047_remove_waiting_from_enum_status.rb
db/schema.rb
spec/helpers/rdvs_helper_spec.rb
spec/swagger_helper.rb
swagger/v1/api.json

Ici on enlève ce qu'il reste du status des rdv `waiting` et qui n'est plus utilisé.
On migre les status `waiting`encore en db vers le status par défaut : `unknown`
Cette PR fait suite à celle ci https://github.com/betagouv/rdv-solidarites.fr/pull/3263 qui couvrait trop de choses différentes.

Suppression du status waiting

---

app/controllers/admin/rdvs_collectifs_controller.rb
app/models/concerns/rdv/updatable.rb
app/services/notifiers/rdv_collectif_participations.rb
app/services/notifiers/rdv_created.rb
app/services/notifiers/rdv_upcoming_reminder.rb
app/services/notifiers/rdv_updated.rb
spec/models/concerns/rdv/updatable_spec.rb
spec/models/concerns/rdvs_user/status_changeable_spec.rb
spec/services/notifiers/rdv_cancelled_spec.rb
spec/services/notifiers/rdv_upcoming_reminder_spec.rb
spec/services/notifiers/rdv_updated_spec.rb
spec/support/notifications_helper.rb

Close : https://github.com/betagouv/rdv-solidarites.fr/issues/3345
Cette PR remplace en partie https://github.com/betagouv/rdv-solidarites.fr/pull/3263 qui faisait trop de choses différentes.
Ici on se contente de : 
- Régler un premier bug de notifications d'annulations multiple (l'issue ci dessus) lorsqu'un usager annule sa participation et que le rdv est ensuite annulé par un agent, l'usager qui avait annulé sa participation reçoit un nouveau mail d'annulation.
- Régler un bug de notification de rappel pour les rdv annulés par les agents. (dans le scope de `Notifiers::RdvUpcomingReminder`) Je viens de découvrir ce bug critique en travaillant sur cette PR.
- Refacto (lisibilité et améliorations des tests) du `NotificationHelper`
- Commentaires et tests
J'ai également replacé l'appel du …

Bug Fix notifications multiples lors de l'annulation d'une participation à un rdv

---

spec/jobs/outlook/create_event_job_spec.rb
spec/jobs/outlook/destroy_event_job_spec.rb
spec/jobs/outlook/mass_create_event_job_spec.rb
spec/jobs/outlook/mass_destroy_event_job_spec.rb
spec/jobs/outlook/update_event_job_spec.rb
spec/models/concerns/outlook/synchronizable_spec.rb
spec/models/outlook/event_spec.rb

Certains tests étaient flaky car on avait utilisé des IDs codés en dur.
J''en ai corrigé la plupart, certains restent mais utilisent des IDs du genre `456_000` donc peu de risque de collision.

Correction flaky tests causés par IDs codés en dur

---

app/services/search_context.rb
spec/features/users/user_can_be_invited_spec.rb
spec/services/search_context_spec.rb

Dans cette PR j'applique dans le `SearchContext` un filtre sur les `organisation_ids` envoyés dans l'URL d'invitation.
Du coup je renomme la variable `fallback_organisation_ids` en `preselected_organisation_ids` car elle n'est plus utilisée uniquement en tant que fallback.
Ce filtre n'apparait que maintenant parce qu'avant nous n'avions pas un mécanisme de régulation côté RDV-I pour restreindre le nombre d'orgas que l'on référençait dans l'URL.
Remarque: le paramètre dans l'url reste `organisation_ids`. Je pourrais le renommer en `preselected_organisation_ids` et avoir la possibilité de passer les 2 (le temps que le nouveau nom de paramètre soit pris en compte côté RDV-I), mais je me suis dit que ça allait beaucoup de paramètres et nous allons de toutes façons séparer (encore une fois 😅 ) …

feat(search): Filter motifs on organisation ids

---

app/controllers/admin/absences_controller.rb
app/views/admin/absences/_absence.html.slim
app/views/admin/absences/_form.html.slim
app/views/admin/absences/index.html.slim
spec/controllers/admin/absences_controller_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3322.osc-secnum-fr1.scalingo.io/
Après l'affichage des organisations dans le tableau des absence (pr #3320), ici on affiches toutes les indisponibilités d'un agent sur le même tableau, quelque soit l'organisation. On permet également de choisir l'organisation pour laquelle l'indisponibilité sera créée.
avant :
après : 
avant :
après :
Revue :

Affiche toutes les indisponibilités

---

app/views/users/rdvs/_rdv.html.slim
spec/features/users/user_can_see_rdv_instruction_spec.rb

Les restrictions s'affichent lorsque l'on selectionne un motif.
Lorsque l'on arrive directement sur la page du RDV depuis une notification, ou bien que l'on suit un lien d'invitation qui a présélectionné le motif, ces instructions ne s'affichent pas.
Cette PR propose d'afficher les « restrictions » associé à un motif sur la fiche du RDV de l'usager.
Close #3291
Close #3302
Revue :

Affiche les restrictions dans la page du RDV usager

---

app/helpers/users_helper.rb

Pour tester : https://demo-rdv-solidarites-pr3348.osc-secnum-fr1.scalingo.io/
Nous continuons d'afficher que l'usager a été supprimé de cette organisation alors que l'option de visibilité des usagers à travers tout le territoire est active. Ça n'a plus de sens. Cette PR propose de ne plus prendre en compte ce badge si l'option est activée.
Avant
Après
Closes #3347
Revue :

N'affiche pas les badges de suppression si non nécessaire

---

app/policies/agent/user_policy.rb
app/views/admin/users/search.json.jbuilder
spec/features/agents/users/users_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3372.osc-secnum-fr1.scalingo.io/
Lorsque les départements activent la visibilité des usagers sur le territoire entier, il y a un bug d'affichage qui donne une drôle d'impression.
C'est lié à une multiplication des usagers lors d'une jointure sur les `user_profiles` pour filtre, dans les policies, les usagers que l'on a le droit de voir (soit en regardant sur l'organisation courante, soit en listant l'ensemble des organisations).
La solution n'est pas sans risque sur la performance, mais je n'en trouve pas de meilleure pour le moment.
Il serait sans doute intéressant de lier les usagers directement au territoire. Et peut-être d'envisager qu'un usager n'appartient qu'à un seul territoire...
Il y avait un indice du problème dans …

Liste les usagers unique d'un territoire

---

app/models/rdvs_user.rb
spec/models/rdv_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3370.osc-secnum-fr1.scalingo.io/
Les RDVs supprimés (soft-deleted) continuaient à apparaître dans la fiche des usagers. Cette PR corrige le bug.
Closes #3284
Revue :

N'affiche plus les rdvs supprimés des utilisateurs

---

scalingo.json

La stack `scalingo-18` est déprécié et sera phased out en avril (le mois prochain). Nous avons reçu un mail nous indiquant que nos apps sont sur cette stack : 
> List of impacted apps: demo-rdv-solidarites, production-rdv-solidarites, demo-rdv-solidarites-pr3181, demo-rdv-solidarites-pr3276, demo-rdv-solidarites-pr3349, demo-rdv-solidarites-pr3354, demo-rdv-solidarites-pr3356, demo-rdv-solidarites-pr3358, demo-rdv-solidarites-pr3368, demo-rdv-solidarites-pr3370, demo-rdv-solidarites-pr3373, demo-rdv-solidarites-pr3374, demo-rdv-solidarites-pr3376
Je mets donc à jour la stack dans le fichier `scalingo.json`, ce qui a pour effet de tester sur la review app. Si tout est OK nous pourrons changer la stack sur la démo puis la prod.
https://doc.scalingo.com/platform/internals/stacks/stacks#migrat …

Mettre à jour la stack Scalingo (de `scalingo-18` à `scalingo-22`)

---

app/jobs/sms_job.rb
app/jobs/transfer_email_reply_job.rb
app/jobs/webhook_job.rb
config/initializers/filter_parameter_logging.rb
config/initializers/lograge.rb

Closes #3259 
Deux choses faites dans cette PR pour éviter la fuite de données personnelles dans les logs : 
1. Désactivation du logging des args pour les jobs sensibles `(SmsJob` et `WebhookJob`).
2. Suppression d'une config lograge introduite dans #3191 qui avait pour effet de logger les paramètres de requêtes HTTP (alors que par défaut [lograge ne logge pas les paramètres](https://github.com/roidrage/lograge#what-it-doesnt-do)). J'ai réalisé qu'on avait ces fuites en cherchant le mot clé "couple" dans nos logs. Si ce manque de log nous handicape on reviendra sur la décision, mais pour le moment soyons prudents !
Revue :

Désactiver le log des args sensibles des jobs

---

app/views/admin/absences/edit.html.slim
app/views/admin/absences/index.html.slim
app/views/admin/absences/new.html.slim
app/views/layouts/_absences_change_banner.html.slim

Pour tester : https://demo-rdv-solidarites-pr3380.osc-secnum-fr1.scalingo.io/
Mise en place d'un bandeau pour prévenir les utilisateurs de la modification de gestion des absences
Closes [#3378](https://github.com/betagouv/rdv-solidarites.fr/issues/3378)
Revue :

Bandeau d'information pour les absences

---

config/initializers/good_job.rb

Dans ma PR pour passer à GoodJob (#3338), j'ai dû m'endormir sur mon clavier et j'ai modifié la date d'exécution de `DestroyRedisWaitingRoomKeys` de 03:00 à 13:00. ([voir cette ligne](https://github.com/betagouv/rdv-solidarites.fr/pull/3338/files#diff-ac799e1c76b47172aff65443ca19a667b17de6a8d2d4b68677d1c2d4f52916c6R43))
Au passage, j'ai fait en sorte que chaque job de cron se lance à heure locale fixe car je trouve que c'est plus facile à comprendre (pas de conversion en UTC à faire quand on veut savoir à quelle heure le truc s'est lancé hier). 
J'ai pris soin à ne pas mettre d'heure entre 02:00 et 02:59 pour éviter les embrouilles avec les changements d'heure.
J'ai aussi fait en sorte que les jobs ne s'exécutent pas à la même heure, car j'ai remarqué que `UpdateExpirationsJob` et …

Corriger l'heure de nettoyage des salles d'attente + cron à heure locale

---

app/models/rdv.rb

Crash du job en boucle : https://sentry.incubateur.net/organizations/betagouv/issues/25617
On se trouvait dans un cas où le RDV n'était plus réservable entre aujourd'hui et son heure de fin. Je n'ai pas débuggé quel RDV exactement, mais la correctif semble raisonnable. D'ailleurs on avait déjà fait la même chose à [un autre endroit où l'on appelait la même méthode](https://github.com/betagouv/rdv-solidarites.fr/blob/27706ecba7311c2e050dc89eb6b45ad36b82e213/app/services/concerns/users/creneaux_search_concern.rb#L16).
Revue :

Correction du crash de FileAttenteJob

---

spec/requests/api/v1/users_request_spec.rb

La durée d'une invitation est de 86 400 secondes soit 24 heures. Le test était donc incorrect les jours qui ne durent pas 24 heures.
Revue :

Correction d'un test qui échoue au changement d'heure

---

app/services/merge_users_service.rb
spec/services/merge_users_service_spec.rb

Pour tester :
- Prendre un rdv via https://demo-rdv-solidarites-pr3416.osc-secnum-fr1.scalingo.io/prendre_rdv_prescripteur/62
- Se connecter côté agent pour dédoublonner manuellement l'usager créé
Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3415
Plutôt que de supprimer d'anciennes participations et d'en créer des nouvelles, on change juste le user_id. Il se peut que ça nous évite aussi des bugs sur les statuts des participations.

Correctif pour dedoublonnage prescripteurs

---

app/form_models/prescripteur_rdv_wizard.rb
spec/features/prescripteurs/can_create_rdv_for_a_user_spec.rb
spec/form_models/prescripteur_rdv_wizard_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3404.osc-secnum-fr1.scalingo.io/prendre_rdv_prescripteur/62
Le dédoublonnage se fait maintenant avec le nom, prénom et numéro de téléphone
L'interface ne change pas, on réutilise juste l'usager s'il existe déjà.
Closes #3035 
Revue :

Dédoublonnage des usagers lors de la prise de rdv par prescripteurs.

---

app/controllers/admin/rdvs_controller.rb

Depuis l'optimisation mise en place dans #3396, les RDVs sont ordonnés par ID au sein de chaque page, alors qu'ils devraient être ordonnés par heure de début.
Ce fix s'assure que l'ordre est bien conservé au sein de la page.
Revue :

Bugfix: les RDVs ne sont pas ordonnés proprement au sein de chaque page

---

app/models/organisation.rb
spec/models/organisation_spec.rb

close : https://github.com/betagouv/rdv-insertion/issues/933
Demande de rdv-insertion mais qui peut très bien être utile pour rdv-s également.
J'ai modifié uniquement le modèle `organisation` de façon à ne pas rajouter de validations erronés sur les autres modèles (`user` entre autre).

Ajout d'une validation pour les organisations avec un téléphone à 4 chiffres

---

app/views/admin/receipts/_receipts.html.slim
app/views/admin/users/index.html.slim
app/views/admin/versions/_resource_versions_row.html.slim

Closes #3412
Note : j'ai mis 7 jours, mais je suis preneur d'avis sur la durée idéal. :thinking: 
J'ai regardé à la main, et toutes les clés sans TTL en prod commencent par l'une de ces trois valeurs : 
- `"cache:views/admin/users/_user"`
- `"cache:views/admin/receipts/_receipt"`
- `"cache:views/admin/versions/_resource_versions_row"`
J'ai donc bien corrigé ces 3 templates ! :tada: 
Une fois la PR mergée on pourra supprimer les clés qui n'ont pas de TTL avec ce script : 
```ruby
redis = Redis.new(url: Rails.configuration.x.redis_url)
cursor, keys_in_page = redis.scan(0, match: "*", count: 1000)
deleted_count = 0
while cursor.to_i != 0
puts "Page size: #{keys_in_page.size}\t  Cursor: [#{cursor}]"
keys_in_page.each do |key|
if redis.ttl(key) == -1
redis.del(key)
puts "DELETED #{key}" …
```

Expirer le cache de toutes les vues

---

app/jobs/cron_job.rb
config/initializers/good_job.rb

Closes #3314 
J'ai choisi 2 ans d'âge car les RDVs sont gardés 2 ans et que nous utilisons les versions pour l'export des RDVs (colonne `"créé par"`). Tout cela peut changer car idéalement selon moi : 
- on devrait supprimer les RDVs avant 2 ans
- on ne devrait pas dépendre des versions PaperTrail pour un export (à débattre)
Revue :

Purger les anciennes versions PaperTrail

---

app/jobs/outlook/mass_create_event_job.rb
app/jobs/outlook/sync_event_job.rb
app/models/agents_rdv.rb
app/models/concerns/outlook/event_serializer_and_listener.rb
spec/features/agents/agent_can_sync_his_account_to_outlook_spec.rb
spec/jobs/outlook/mass_create_event_job_spec.rb

(Ne peut pas être testé en review app à cause de l'oaut outlook)
Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3446
Le bug était causé par le fait qu'on ne settait pas le flag `outlook_create_in_progress` au moment de la création d'events dans le mass import. J'en ai profité pour déplacer ça dans le job.

Correctif de la synchro initiale avec outlook

---

.rspec

Comme discuté en point tech, cette PR enlève la liste des specs lentes qui ajoute du bruit quand on lance les specs et qui ne semble pas nous donner des infos dont on se serve.

Supprime la liste des specs lentes

---

app/controllers/admin/agents_controller.rb
app/controllers/admin/territories/agent_roles_controller.rb
app/services/agent_removal.rb
config/locales/fr.yml
spec/controllers/admin/territories/agent_roles_controller_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3386.osc-secnum-fr1.scalingo.io/
Un problème de suppression de plages d'ouverture suite à la suppression d'un agent d'une organisation a été remonté (https://zammad10.ethibox.fr/#ticket/zoom/3958). 
Il y a deux chemins possible pour supprimer un agent d'une organisation. Si l’utilisateur passe par le panneau de configuration des agents, il est possible de retirer un agent d'une organisation sans le supprimer. L'objectif de cette PR est de modifier le comportement de cette suppression.
Closes #3237
Revue :

modification du comportement de suppression d'un agent

---

app/helpers/agents_helper.rb

Permet de régler le bug du menu "Planning" qui se ferme lorsque que l'on accède à la page des RDV collectifs
avant : 
après : 
Closes #3442
Revue :

Corrige le bug du menu Planning sur les RDV collectifs

---

app/controllers/application_controller.rb
app/controllers/prescripteur_rdv_wizard_controller.rb
app/views/mailers/prescripteur_mailer/rdv_created.html.slim
public/robots.txt
spec/features/prescripteurs/can_create_rdv_for_a_user_spec.rb
spec/mailers/previews/prescripteur_mailer_preview.rb

Pour tester : https://demo-rdv-solidarites-pr3445.osc-secnum-fr1.scalingo.io/
Le but de cette PR est de corriger les erreurs liées à cette issue Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/20566/?environment=production&project=74&query=is%3Aunresolved
En regardant de plus près les referer des différentes occurrences de l'erreur, on a plusieurs cas différents :
- des gens qui naviguent deux fois vers le formulaire de prescripteur à partir d'un même lien (probablement ou l'ouvrant dans deux onglets différents)
- parfois des gens qui naviguent directement vers les pages de formulaire prescripteur depuis une recherche google
Le fix principal de cette PR est donc de faire une redirection vers la page d'accueil quand on ne trouve pas le créneau pour lequel le …

Correctif pour la navigation prescripteur

---

app/jobs/concerns/default_job_behaviour.rb
spec/jobs/application_job_spec.rb

Actuellement, lorsque nous remontons des erreurs de job à Sentry, nous n'avons pas les métadonnées du job. Avec cette PR nous aurons l'ID du job, sa queue et ses arguments. :tada: 
Revue :

Fournir à Sentry les métadonnées des jobs

---

.active_record_doctor
.github/workflows/ci.yml
Gemfile
Gemfile.lock
db/migrate/20230413163145_add_foreign_keys.rb
db/schema.rb
spec/models/concerns/outlook/event_serializer_and_listener_integration_spec.rb

Closes #3317
Voir la doc de la gem ici : 
https://github.com/gregnavis/active_record_doctor#detecting-missing-foreign-key-constraints
J'ai configuré pour ignorer les faux positifs (des colonnes qui finissent par "_id" mais ne sont pas des références internes).
Dans la migration je supprime dans 2 tables des références mortes que nous avions (dieu merci il n'y en avait que sur 2 tables).
Pour éviter de retomber dans la même situation, j'ai ajouté un job dans la CI, il échouera si la commande `RAILS_ENV=test bundle exec rails active_record_doctor:missing_foreign_keys` ne retourne pas 0 (la valeur de succès en bash).
Revue :

Ajouter les clés étrangères manquantes

---

app/controllers/admin/rdv_wizard_steps_controller.rb
app/form_models/admin/rdv_wizard_form/step4.rb
app/form_models/concerns/admin/rdv_wizard_form_concern.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb

Avant : 
On faisait croire que le rdv était confirmé alors que ce n'était pas le cas : 
Après : 
Pas de faux messages de confirmation
Le bug avait été introduit dans https://github.com/betagouv/rdv-solidarites.fr/pull/2818
Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3443
Revue :

Correctif du flash de confirmation dans le rdv wizard 

---

app/jobs/concerns/default_job_behaviour.rb
app/jobs/cron_job.rb
app/jobs/sms_job.rb
app/jobs/webhook_job.rb
app/mailers/custom_mailer_delivery_job.rb
spec/jobs/sms_job_spec.rb
spec/jobs/webhook_job_spec.rb
spec/sms/sms_netsize_spec.rb

Closes #3428
J'ai choisi de n'appliquer ce comportement que sur les jobs les plus bruyants, car il me paraît dangereux de passer sous silence par défaut les échecs de tous les types de jobs, notamment les jobs rarements appelés (`MassDestroyEventJob`, `TriggerWebhookJob`) ou les jobs de cron, qui s'exécutent une fois par jour.
À discuter bien sûr ! :slightly_smiling_face: 
Note : le diff des specs est plus facile à comprendre quand on ignore le whitespace
Revue :

Ne pas logger les premiers échecs de jobs dans Sentry

---

spec/support/select2_spec_helper.rb

Dans cet exemple d'échec de flaky spec : 
https://github.com/betagouv/rdv-solidarites.fr/actions/runs/4818192711/jobs/8579848917
Nous voyons :
> expected to find text "Théodore LE GALL" in "[...]participants\nMelchior LE GALL\nAlcibiade MARTIN\nLieu[...]"
Nous avions donc dans notre test 2 usagers portant le même nom de famille (`"LE GALL"`). Voilà ce qu'il se passait : 
```ruby
add_user(user1) # Melchior LE GALL
... # Le select2 affiche alors à ce moment une liste incluant Melchior LE GALL
add_user(user2) # Théodore LE GALL
fill_in(class: "select2-search__field", with: user.first_name) # on lance une recherche avec "Théodore"
find("li", text: user.last_name).click # on clique sur Melchior CAR LA REQUÊTE AJAX CI-DESSUS N'EST PAS TERMINÉE
```
Dans `full_lifecycle_spec.rb`, définir le même …

Correction de flaky spec : clic sur un nom ambigu

---

app/views/common/_inclusionconnect_button.html.slim

J'avais ajouté `target="_blank"` dans #3336 sans réfléchir parce que c'était l'exemple donné dans [la doc](https://betagouv.github.io/itou-theme/content-ic.html).
J'ai trouvé ça étrange à l'usage et après [confirmation](https://mattermost.incubateur.net/betagouv/pl/x7hkc7ai638m9mzsowgportcfe) j'ai retiré cet attribut.
Revue :

Ne pas ouvrir InclusionConnect dans un nouvel onglet

---

app/views/users/rdvs/_rdv.html.slim

Bug découvert lors d'une démo à @ousmanedev : j'ai créé un motif et son champ `restriction_for_rdv` semble avoir pour valeur par défaut `""`.
je corrige donc ici la condition d'affichage de ce champ sur le récapitulatif du RDV.
Revue :

Bugfix: Section "Restrictions" affichée même quand vide

---

app/helpers/motifs_helper.rb
app/mailers/users/rdv_mailer.rb
app/views/admin/motifs/show.html.slim
app/views/common/_creneaux.html.slim
app/views/mailers/common/_rdv_overview.html.slim
app/views/prescripteur_rdv_wizard/confirmation.html.slim
app/views/search/_motif_selection.html.slim
app/views/users/participations/index.html.slim
app/views/users/rdvs/_rdv.html.slim

- En ce qui concerne les instructions après la prise des RDVs, les liens y sont déjà cliquables. Pas de changement à faire.
- En ce qui concerne les mails envoyés aux usagers, ils ne contiennent pas les instructions pré-RDV. Il n'y a donc pas de changement à faire.
- Le seul fichier impacté est: `app/views/users/rdvs/_rdv.html.slim`
Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3467
Lien (https://google.fr) non cliquable
Lien (https://google.fr) cliquable

[3467] Make links in Motifs restriction text (Motif#restriction_for_rdv) clickable

---

app/controllers/prescripteur_rdv_wizard_controller.rb
app/controllers/users/participations_controller.rb
app/form_models/prescripteur_rdv_wizard.rb
app/models/concerns/rdvs_user/creatable.rb
app/views/prescripteur_rdv_wizard/new_prescripteur.html.slim
config/routes.rb
spec/features/prescripteurs/can_create_rdv_for_a_user_spec.rb
spec/models/concerns/rdvs_user/creatable_spec.rb

Pour tester : https://demo-rdv-solidarites-pr3498.osc-secnum-fr1.scalingo.io/
Avant : le formulaire prescripteur ne mettait pas de message d'erreur si on met un nom de famille vide
Après : 
Le fix ajoute principalement une validation back-end à un formulaire qui n'avait que des validations front.
Au passage, sur le dernier commit, j'ai fait en sorte que la méthode `#create_and_notify` lève explicitement une erreur si la participation n'est pas persistée. Au début je pensais que ça pouvait éviter d'autres erreurs sur le formulaire de prescripteur, mais en regardant de plus près, ça ne change rien à ce cas. Je suis quand même tenté de laisser ces modifs pour être plus défensif sur la création de participations.
Closes #3497
Après avoir mergé, ça pourra être bien de manuellement corriger les …

Ajout de validation sur le formulaire de prescripteur

---

app/models/agent.rb
spec/services/agent_removal_spec.rb

On avait des objets AR qui étaient encore présent en mémoire, alors qu'ils sont supprimés en DB. Il suffisait d'enlever le stub pour voir le bug 😢 
Closes #3501

Correctif pour la suppression d'agents

---

app/blueprints/organisation_blueprint.rb
app/controllers/api/v1/organisations_controller.rb
app/dashboards/organisation_dashboard.rb
app/models/agent.rb
app/models/organisation.rb
app/models/rdv.rb
app/services/add_conseiller_numerique.rb
app/views/layouts/_domain_change_banner.html.slim
db/migrate/20230504120852_add_verticale_to_organisations.rb
db/schema.rb
db/seeds/cnfs.rb
db/seeds/rdv_insertion.rb
spec/features/agents/admin_can_configure_the_organisation_spec.rb
spec/features/users/user_can_reset_his_password_spec.rb
spec/mailers/agents/absence_mailer_spec.rb
spec/mailers/custom_devise_mailer_domain_spec.rb
spec/mailers/users/rdv_mailer_spec.rb
spec/requests/api/v1/public_links_request_spec.rb

Closes #3495 
Plutôt que d'ajouter un nouvel attribut au model `Organisation` pour le flag des organisations de rdv-insertion, il a été décidé de modifier l'attribut existant `new_domain_beta`  qui permettait de distinguer (boolean) les organisations rdv_aide_numerique des organisations rdv_solidarites.
Le nouvel attribut se nomme `verticale` pour correspondre à notre vocabulaire métier. 
C'est un enum qui peut prendre plusieurs valeurs : `rdv_solidarites` (par défaut), `rdv_aide_numerique` et enfin `rdv_insertion`.
Pour le moment seul les 2 premiers ont un impact au niveau du domaine, de l'expéditeur des mails... (mais ca pourrait être le cas dans le futur pour rdv_insertion également)
La 3eme valeur `rdv_insertion` va permettre d'afficher quelques éléments d'UX spécifiques à …

Modification de l'attribut new_domain_beta => verticale

---

app/jobs/transfer_email_reply_job.rb
spec/jobs/transfer_email_reply_job_spec.rb

Ce ticket zammad aurait pu être évité si on avait réussi à transférer le mail à l'agent : https://zammad10.ethibox.fr/#ticket/zoom/5376
Il n'a pas pu être transféré correctement, puisque le rendez-vous était soft deleted
Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3505

Permet le transfert des mails aux agents pour les rdv soft deleted

---

app/blueprints/motif_blueprint.rb

Côté rdv-insertion, nous souhaitons désormais récupérer le champ `instruction_for_rdv` des motifs rdv-solidarités afin de les afficher sur les sms/mails/courriers de convocation que nous générons ([PR #995 côté rdv-i](https://github.com/betagouv/rdv-insertion/pull/995)) . En effet, lorsqu'un message de convocation est généré, le bénéficiaire RSA n'a pas pu voir cette instruction au moment de la prise de RDV, il faut donc lui afficher ailleurs.

Ajouter instruction_for_rdv au motif_blueprint

---

spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb

Visiblement cette spec a tendance à échouer car elle se base sur des temps relatifs.
Il me semble que la spec juste au dessus n'échoue pas car elle utilise des plages récurrentes `:daily`, donc je pense qu'on peut tenter ça.
Revue :

Correction flaky spec (15 mai 2023)

---

app/javascript/components/motif-form.js
app/models/motif.rb
app/services/search_context.rb
app/views/admin/motifs/_form.html.slim
app/views/admin/motifs/_visibility.html.slim
app/views/admin/motifs/show.html.slim
app/views/admin/rdv_wizard_steps/_rdv_user_form.html.slim
app/views/admin/rdvs_users/_form.html.slim
app/views/admin/rdvs_users/_notifications_lifecycle.html.slim
config/locales/models/motif.fr.yml
spec/services/search_context_spec.rb

Reverts betagouv/rdv-solidarites.fr#3508
Je propose qu'on revert la PR qui permettait d'ouvrir les motifs reservés aux agents aux utilisateurs ayant une invitation. 
On a pas assez anticipé tous les cas de figure avant qu'on la déploie, notamment le suivant  : 
Les motifs de convocations sont sur la même catégorie que les motifs d'invitations **et** les agents ont des plages d'ouvertures sur ces motifs pour pouvoir placer ces rdvs, ce qui fait qu'ils apparaissent dans la liste des motifs disponibles aux utilisateurs invités.
Nous comptons retravailler le principe de convocation sur rdv-insertion, et donc on peut réfléchir à contourner ce problème, mais je ne pense pas que ce soit la bonne solution à ce problème.
Est-ce qu'il serait envisageable de rajouter un enum `bookable_by` qui serait …

Revert "Adapter le code spécifique rdv-insertion en utilisant le nouvel attribut `verticale`"

---

app/models/agent.rb
app/views/admin/rdvs/_rdv.html.slim
spec/features/agents/rdv_details_spec.rb

[#3481] La suppression d'un agent rend inaccessible l'index des rdv des usagers qui ont eu des rdv avec lui

---

app/controllers/application_controller.rb
app/controllers/concerns/domain_detection.rb
app/controllers/inclusion_connect_controller.rb
app/controllers/super_admins/application_controller.rb
app/javascript/components/calendar.js
app/mailers/admins/organisation_mailer.rb
app/mailers/agents/reply_transfer_mailer.rb
app/mailers/application_mailer.rb
app/mailers/concerns/common_mailer.rb
app/mailers/custom_devise_mailer.rb
app/models/concerns/ical_helpers/ics.rb
app/models/domain.rb
app/services/sms_sender.rb
app/views/admin/static_pages/support.html.slim
app/views/common/_env.html.erb
app/views/devise/mailer/invitation_instructions_cnfs.html.erb
app/views/mailers/prescripteur_mailer/rdv_created.html.slim
app/views/prescripteur_rdv_wizard/confirmation.html.slim
app/views/search/_nothing_to_show.html.slim
app/views/static_pages/contact.html.slim
app/views/static_pages/politique_de_confidentialite.html.slim
app/views/static_pages/presentation_for_cnfs.html.slim
config/initializers/constants.rb
spec/controllers/inclusion_connect_controller_spec.rb
spec/features/users/user_can_reset_his_password_spec.rb
spec/mailers/custom_devise_mailer_domain_spec.rb
spec/mailers/users/rdv_mailer_spec.rb
spec/models/concerns/ical_helpers/ics_spec.rb
spec/services/add_conseiller_numerique_spec.rb

Closes #3534
La majorité des changements consistent à remplacer une valeur en dur par une variable `domain.support_email`.
Concernant l'adresse secretariat-auto@rdv-solidarites.fr, j'ai ajouté un commentaire d'explication sur sa raison d'être. Je pense qu'il n'est pas nécessaire de la décliner à tous nos domaines car c'est une adresse technique, les agents ne la voient pas ou peu.
Il y avait un usage de `SUPPORT_EMAIL` dans `SmsSender`, pour l'envoi de SMS avec le fournisseur "Contact Experience". Ce fournisseur n'est plus utilisé, j'ai supprimé les méthodes des fournisseurs obsolètes.
https://demo-rdv-solidarites-pr3537.osc-secnum-fr1.scalingo.io/
Vous pouvez définir la variable d'env `REVIEW_APP_DOMAIN` à `RDV_AIDE_NUMERIQUE` ou `RDV_MAIRIE` puis redémarrer la review app pour tester les …

[#3534] Utiliser des adresses e-mail de support différentes selon le domaine

---

scripts/import_conseillers_numeriques.rb

Afin de simplifier l'utilisation de ce script, et le rendre plus accessible au reste de l'équipe, j'ai ajouté un peu de doc, et un rescue qui permettra de limiter les opérations manuelles (habituellement j'avais besoin de modifier le csv puis relancer tout l'import à chaque échec)

Ajout de doc d'usage et de récupération des erreurs au script d'import de cnfs

---

app/controllers/admin/referent_assignations_controller.rb
spec/controllers/admin/referent_assignations_controller_spec.rb

Issue Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/18832
Pour reproduire : 
- Se connecter avec martine@demo.rdv-solidarites.fr / 123456
- Visiter le profil usager de Patricia DUROY
- Dans la section "Agents référents", cliquer "Modifier"
- Double cliquer vite sur le bouton "Ajouter" d'un des agents de la liste
On voit que l'app crash car on demande deux fois d'ajouter le référent.
J'ai donc fait en sorte que l'action d'ajout soit idempotente.
Note : l'issue Sentry regroupe deux erreurs. L'une avait lieu lors de l fusion usager et a été corrigée dans #3526, et la second erreur est celle corrigée ici. Il me semble important de corriger l'erreur plutôt que de l'ignorer, pour éviter d'avoir à faire face à l'ambiguïté des remontes Sentry (groupées ensembles par erreur …

Bugfix vigie : crash lors de l'assignation double d'un agent référent

---

app/services/users/geo_search.rb

Dans l'espoir de limiter l'utilisation mémoire et cpu de la base, cette PR propose de scoper un peu plus la requête qui est faite à la base du GeoSearch.
Avec les méthodes `individual_and_collectifs_motifs_ids` et `available_motifs_base`, on va chercher une liste d'ids, et ensuite s'en servir comme paramètres de requête pour aller chercher les motifs qui correspondent aux contraintes de sectorisation de la recherche en cours (https://github.com/betagouv/rdv-solidarites.fr/pull/3511).
Actuellement, on ne scope quasiment pas cette liste d'id, et on se retrouve à passer plusieurs milliers d'ids en paramètre. On peut de manière simple scoper cette liste d'id avec le département et en excluant les motifs non ouverts à la réservation en ligne. On passe ainsi de plusieurs milliers d'id à …

Allègement de la requête de motifs du geosearch

---

app/controllers/super_admins/mairie_comptes_controller.rb

Quand on a fait la démo, des gens ont remarqué que la durée par défaut recommandée par l'ANTS est de 15 mn pour les rdv pour les passeports et/ou cartes d'identité

Utiliser la durée de rdv recommandée par l'ANTS

---

app/views/users/user_name_initials_verification/new.html.slim
config/locales/views/user_name_initials_verification.yml

Suite à la review de ce matin avec Mehdi, on veut clarifier qu'il s'agit d'exemples
Avant : 
Après :

Ajout d'un texte d'exemple pour la vérification de nom de famille

---

app/models/domain.rb
app/views/common/_footer_users.html.slim

Pour tester : https://demo-rdv-solidarites-pr3593.osc-secnum-fr1.scalingo.io/
Suite à la recette de ce matin avec Mehdi
Avant : 
Après : 
(Le logo n'est pas le bon, mais c'est corrigé par https://github.com/betagouv/rdv-solidarites.fr/pull/3591)

Correctif du texte du footer

---

app/views/admin/plage_ouvertures/_form.html.slim

Suite à la recette de ce matin, cette PR corrige le point suivant : 
Dans la page de création d’une plage d’ouverture, s’il y a un seul lieu disponible, le présélectionner

Présélectionner le lieu si il y en a qu'un dans les plages d'ouvertures

---

app/views/dsfr/rdv_mairie/homepage.html.slim

Pour les mairies pilotes, on veut les inciter uniquement à prendre rendez-vous avec nous, pour avoir le maximum de feedback.
On fait donc de la prise de RDV le CTA principal.
Avant :
Après :

Simplification du parcours utilisateur d'embarquement pour RDV Mairie

---

app/controllers/search_controller.rb
spec/features/agents/agent_can_test_online_booking_spec.rb

En testant, je me suis rendu compte que les liens directs pour la réservation chez une mairie étaient cassés. Ce petit correctif moyennement joli répare ça pour le premier onboarding de tout à l'heure.

Corrige les liens de réservation en ligne pour les mairies

---

app/services/sms_sender.rb

Dans le cadre de la préparation à l'audit de sécurité, on a aperçu cette faille. J'ai testé manuellement et l'envoi de sms marche correctement en https.
Je vais contacter le dsi du 77 pour faire une rotation du mot de passe basic auth.

Correction du protocole de connexion à clever technologies

---

app/blueprints/agent_role_blueprint.rb
app/models/agent_role.rb
app/views/admin/motifs/_form.html.slim

Je termine la migration commencé ici :
https://github.com/betagouv/rdv-solidarites.fr/pull/3609
Les changements sont effectifs dans rdv-insertion ici :
https://github.com/betagouv/rdv-insertion/pull/1120
J'ai aussi enlevé une classe inutile (un oubli d'une précédente pr)

Nettoyage suite au renommage d'attribut `AgentRole` effectif coté rdv-i

---

app/views/users/sessions/new.html.slim

Après discussion avec Mehdi, suite à l'ouverture de la fonctionnalité prescripteur dans la Somme, on veut rendre le lien "Je suis un prescripteur qui oriente un bénéficiaire" utilisable pour tous les départements.
C'est utile pour les prescripteurs qui ont "perdu" le lien de prescription, et maintenant qu'on a un peu de recul sur la fonctionnalité, on est en confiance pour avoir ce lien dans tous les départements.

Ouverture du lien alternatif pour prescripteur dans tous les département

---

app/controllers/concerns/token_invitable.rb
app/controllers/search_controller.rb
app/controllers/user_auth_controller.rb
app/controllers/users/rdv_wizard_steps_controller.rb
app/controllers/users/rdvs_controller.rb
app/controllers/users/user_name_initials_verification_controller.rb
app/form_models/user_rdv_wizard.rb
app/models/invitation.rb
app/models/user.rb
app/services/search_context.rb
app/views/search/_creneau_selection.html.slim
app/views/search/_creneaux.html.slim
app/views/search/_lieu_selection.html.slim
app/views/search/_motif_selection.html.slim
app/views/search/_organisation_selection.html.slim
app/views/search/_rdv_collectif.html.slim
app/views/search/_selected_motif_recap.html.slim
app/views/search/_service_selection.html.slim
config/locales/devise.fr.yml
spec/controllers/concerns/token_invitable_spec.rb
spec/controllers/search_controller_spec.rb
spec/controllers/users/rdv_wizard_steps_controller_spec.rb
spec/controllers/users/rdvs_controller_spec.rb
spec/controllers/users/user_name_initials_verification_controller_spec.rb
spec/features/accessibility/public_pages_spec.rb
spec/features/allocation_for_search_context_spec.rb
spec/features/users/user_can_be_invited_spec.rb
spec/features/users/user_can_manage_collective_rdv_spec.rb
spec/services/search_context_spec.rb

Grâce à ce qui a été fait dans #3568, on peut maintenant faire en sorte que des motifs soient réservables uniquement par des utilisateurs invités. Cependant, il est encore facile pour un utilisateur de prendre rdv sur un motif réservé aux utilisateurs invités:
* En utilisant le token qu'il a reçu dans la notification sms/mail lui permettant de consulter/modifier son rdv
* En retrouvant dans l'historique de son navigateur l'url contenant le token avec laquelle il a pris rdv 
Cette PR répond à ces 2 problématiques. En plus de ça, on fait également en sorte que les paramètres fixés dans l'url d'invitation ne soient pas modifiables par l'utilisateur.
On change tout d'abord le fonctionnement du concern `TokenInvitable`, en faisant 2 actions distinctes : 
* S'il y a un token dans l'url et qu'il …

Refacto du traitement des token d'invitations

---

app/views/admin/agents/_agent.html.slim

C'est un oubli dans ma dernière PR de mise en place des intervenants.
Ce tag n'a pas lieu d'être dans l'ux pour les agents intervenants car ils ne se connectent pas.
avant :
après :

Enlever le tag `inactif` de l'index des agents pour les agents intervenants

---

.rubocop.yml
app/controllers/api/ants/editor_controller.rb
spec/features/users/user_can_search_rdv_on_rdv_mairie_spec.rb
spec/requests/api/ants/available_time_slots_spec.rb

On a remarqué que la mairie de Parçay Meslay n'apparaissait pas dans le motuer de recherche de l'ANTS, alors que les autres y sont et qu'ils ont des disponibilités.
Après un échange de mail avec l'équipe technique de l'ants, ils nous on donné cette réponse :
> Le bug arrive quand on vous envoie plusieurs valeurs de meeting_point_ids, vous ne prendez en considération que le dernier.
> Exemple de requête multi-valeurs:
curl --location --request GET 'https://rdv.anct.gouv.fr/api/ants/availableTimeSlots?meeting_point_ids=11&start_date=2023-06-23&end_date=2023-09-23&meeting_point_ids=3&documents_number=1&reason=CNI' \
Ils n'utilisent pas de crochets `[]` pour passer un tableau de valeurs, et donc quand rails parse la query string, on obtenait `params[:meeting_point_ids] == 3`.
Le fix est donc …

Correctif pour le branchement des mairies proches d'une autre mairie sur le moteur de recherche de l'ANTS

---

config/initializers/good_job.rb

Voir https://github.com/bensheldon/good_job#configuration-options
En ce moment on a environ 380k jobs réussis stockés sur la table good job. J'ai l'impression que ça cause des problèmes de performance, puisque la page de dashboard de good job met beaucoup de temps à charger (et fait parfois des timeouts quand on cherche un job spécifique).
Actuellement, on utilise la valeur par défaut de ce paramètre de config, qui est de 2 semaines. Je pense qu'on peut se débrouiller avec 1 semaine dans la plupart des cas, et que ça va alléger cette table.
On va avoir beaucoup de suppression au moment où on merge cette PR, donc je vais plutôt faire ça en fin de journée.

Supprimer les jobs une semaine après leur exécution (à la place de 2 semaines)

---

app/javascript/components/select2-inputs.js
app/javascript/components/service-filter-for-motifs-selects.js
app/views/admin/motifs/_form.html.slim
app/views/admin/plage_ouvertures/_form.html.slim
spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb

Fait suite à un travail entamé ici : https://github.com/betagouv/rdv-solidarites.fr/pull/3601
On en a discuté avec Victor et il s'avère qu'il y a bcp de formulaire qui auraient nécessité des modifications de ce type pour sélectionner automatiquement l'élément comme ici : 
```ruby
- lieux = policy_scope(Lieu).enabled.ordered_by_name
= f.association :lieu, \
collection: lieux, \
label_method: :full_name, \
label: false, \
include_blank: true, \
required: false, \
selected: (lieux.size == 1 ? lieux.first.id : nil), \
```
Ce n'est pas la solution idéale, l'objectif est de trouver une solution globale pour que le comportement par défaut soit de sélectionner automatiquement l'élément d'une collection d'un formulaire quand cette collection n'en contient qu'un seul.
J'ai commencé à travailler sur …

Amélioration UX sélection automatique des options quand il y en a qu'une dans tous les formulaires

---

app/services/inclusion_connect.rb

Ajout nécessaire pour la future version d'Inclusion Connect pour pouvoir récupérer les infos du profil IC
["given_name"] et ["family_name"].
Avant la mise à jour on pouvait récupérer ces informations sans avoir le bon scope...
Le système à jour est moins permissif et on a besoin de ce scope.

Ajout de profile dans le scope Inclusion Connect

---

app/views/common/_creneaux.html.slim
app/views/search/_creneau_selection.html.slim
app/views/search/_lieu_selection.html.slim
app/views/search/_motif_selection.html.slim
spec/factories/motif.rb
spec/features/users/user_can_be_invited_spec.rb
spec/features/users/user_can_manage_collective_rdv_spec.rb
spec/features/users/user_can_search_rdv_spec.rb

Closes #3424
Il semblerait que l'on ai un fichier `app/views/common/_creneaux.html.slim` qui ne sert à rien et porte à confusion.
Celui qui est utilisé est `app/views/search/_creneaux.html.slim`
J'aimerai avoir votre avis, en fonction je le supprimerai.
Je fix également un bug graphique lié à une mauvaise indentation dans `app/views/search/_creneau_selection.html.slim`
Avant : 
Après :

Afficher la modal des instructions du rdv après la sélection du lieu

---

app/models/domain.rb

fixes  #3651
Le record CNAME a bien été ajouté, il n'y a plus qu'à changer l'url canonique.

Changement du nom de domaine de démo pour les mairies

---

app/services/search_context.rb

La méthode `filter_motifs` du `SearchContext` filtre des motifs sur des attributs d'organisations associées aux motifs.
Elle prend en entrée une collection de motifs où les organisations sont déjà loadées [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/32cf82dec8988457f2de8f8b67f7cf7265fd3733/app/services/users/geo_search.rb#L115).
Cependant, depuis [ce changement](https://github.com/betagouv/rdv-solidarites.fr/commit/86248632a162534e76a81ac62bdae741f4c92963), les organisations ne sont plus préloadées dans le cas d'une invitation où on fallback sur les organisations préselectionnées.
Ça engendrait cette erreur: https://sentry.incubateur.net/organizations/betagouv/issues/48338/?project=74&query=is%3Aunresolved&referrer=issue-stream
Je remédie à ça ici et j'en profite pour …

fix(search): always join organisation table for matching motifs 

---

Gemfile
Gemfile.lock
db/seeds/rdv_mairie.rb
spec/spec_helper.rb
spec/support/capybara_config.rb

Fix des problèmes de features tests sur la CI
Merci à Amine qui a eu le même soucis et l'a résolu ici : https://github.com/betagouv/rdv-insertion/pull/1229
J'ai mis à jour `selenium-webdrivers` et `capybara`. J'ai enlevé la gem `webdrivers` qui posait problème.
J'ai également nettoyé la configuration de Capybara pour l'adapter aux modifications.
J'aimerai avoir un 2eme avis à ce sujet, je pense que ce que j'ai enlevé était redondant (et en cours de dépréciation notamment pour l'argument `:capabilities`)

Fix features tests sur la CI, mise à jour capybara et selenium-webdrivers

---

app/controllers/agents/mot_de_passes_controller.rb
app/models/concerns/agent/custom_devise_token_auth_user_omniauth_callbacks.rb
app/policies/agent/agent_policy.rb
app/views/agents/mot_de_passes/edit.html.slim
app/views/agents/registrations/edit.html.slim
app/views/layouts/_left_menu.html.slim
app/views/layouts/registration.html.slim
config/locales/models/agent.fr.yml
config/routes.rb
spec/features/agents/agent_can_reset_his_password_spec.rb
spec/features/agents/agent_can_see_stats_spec.rb
spec/features/agents/change_password_spec.rb

Suite de https://github.com/betagouv/rdv-solidarites.fr/pull/3694, dans le contexte de https://github.com/betagouv/rdv-solidarites.fr/issues/3624
Le formulaire de compte de l'agent est difficile à comprendre parce qu'il peut permettre deux choses différentes : changer les infos du compte (nom et prénom par exemple), et/ou changer le mot de passe. Ces deux comportements dépendent des champs qu'on remplit dans le formulaire "Votre compte", et en plus ils ne sont pas forcément très liés.
Pour gagner en clarté (et préparer la suite de ce ticket où on voudra encourager les agents avec des mots de passes faibles à les changer), on sépare donc ce formulaire en deux : un pour le compte, un pour le mot de passe.
Après un peu de recherche sur ce qui était possible avec Devise, j'étais un peu déçu : …

Extraction du formulaire de changement de mot de passe des agents

---

app/controllers/admin/rdvs_controller.rb
config/locales/fr.yml

Cette PR est un sparadrap en attendant d'avoir une meilleure solution pour https://github.com/betagouv/rdv-solidarites.fr/issues/3701. On indique aux admins comment obtenir un export s'ils ne reçoivent rien, pour éviter qu'ils contactent le support.

Aider les agents à obtenir un export sans contacter le support

---

app/models/outlook/api_client.rb

Remontée Sentry en erreur à cause d'un problème de nommage de variable dans l'api outlook.
Cela ne régle pas le problème pour lequel on recoit des remontées sentry mais ca sera déjà plus clair.
https://sentry.incubateur.net/organizations/betagouv/issues/56340/?project=74&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h
https://sentry.incubateur.net/organizations/betagouv/issues/56165/?project=74&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h

Fix name error event in sentry for outlook

---

app/models/outlook/api_client.rb

Les jobs de synchro outlook bloquent notre file d'attente de jobs.
Je remet comme c'était initialement en attendant de trouver un code propre pour cette gestion d'erreur.

Rollback sur la gestion d'erreur de synchro sentry

---

app/views/search/_lieu_selection.html.slim

@SalmaBennani nous a remonté un bug en ce qui concerne la sélection d'un lieu lorsqu'un usager veut prendre rdv (sur des rdv dont le motif a un message de restriction).
Il s'agit d'un bug dans la modal dont l'id se basait sur le motif.
Ce bug a été implémenté avec le changement d'emplacement pour la modal du message de restriction [ici](https://github.com/betagouv/rdv-solidarites.fr/pull/3661)
Il y avait donc une seule et même modal pour tout les lieux et c'était le premier lieux qui était selectionné méme quand l'usager voulait s'inscrire dans un autre lieux.
Ce petit fix régle le problème.

Bug sur la modal de restriction des rdvs avec plusieurs lieux

---

app/jobs/concerns/default_job_behaviour.rb
spec/jobs/application_job_spec.rb

En lien avec https://github.com/betagouv/rdv-solidarites.fr/issues/3724
Implémentation d'un timeout pour nos jobs.
En cas de dépassement de :
+ de 1 heure pour les queues 'exports'
+ de 30 secondes pour toutes les autres queues
On arrête le job
On log l'erreur dans sentry
On retry sur le même principe que pour les autres erreurs (à des intervalles exponentielle 20 fois)

Mise en place d'un timeout pour les jobs

---

app/jobs/concerns/default_job_behaviour.rb
spec/jobs/application_job_spec.rb

Suite à la mise en place de timeout pour nos jobs nous avons remarqué que les jobs de la queue "cron" peuvent prendre plusieurs minutes. On a décidé pour rapidement traiter le "problème" de mettre en place la même politique de timeout que pour les exports pour les jobs cron qui tournent la nuit (1 heure de timeout)

Mettre une heure de timeout pour les cronjobs

---

app/jobs/cron_job.rb
config/initializers/good_job.rb
docs/architecture-technique.md
spec/jobs/cron_job/destroy_old_rdvs_and_inactive_users_job_spec.rb

Cette PR est une première étape pour https://github.com/betagouv/rdv-solidarites.fr/issues/3623
Pour être cohérent avec ce qui est déjà fait pour les rdvs, j'ai désactivé les webhooks : c'est pas une suppression au niveau métier, mais pour des raisons rgpd, donc c'est pas nécessaire de renvoyer les infos aux systèmes externes (au contraire, on veut supprimer les données, pas les propager encore plus). Et on compte sur les systèmes externes auxquels on envoie les données pour qu'ils suppriment les vieilles données.

Suppression automatique des comptes usagers inactifs

---

app/jobs/cron_job.rb

En faisant le test en prod, je me suis rendu compte que les webhooks partaient pour les user_profiles. Je pense pas que ça soit très grave, mais pour être cohérent avec les autre suppression je pense qu'il veut mieux ne pas les envoyer.

ne pas envoyer de webhooks pour les user profiles lors de la suppression d'usagers inactifs

---

app/views/admin/agent_roles/edit.html.slim
app/views/admin/plage_ouvertures/show.html.slim
app/views/admin/rdvs/_rdv_details.html.slim
app/views/mailers/agents/absence_mailer/_absence_overview.html.slim
app/views/mailers/agents/plage_ouverture_mailer/_plage_ouverture_overview.html.slim

Juste un petit détail que j'ai remarqué en travaillant sur une autre pr :  il y a plusieurs endroits où on utilise le terme "professionnel" à la place d'agent dans l'interface du back office.
Pour rendre l'appli plus claire, on veut toujours utiliser le même terme pour la même chose.

Petite correction du terme utilisé dans l'interface pour désigner les agents

---

spec/rails_helper.rb

Pour reproduire l'erreur : `bundle exec rspec spec/features/agents/rdv_details_spec.rb:49 spec/features/anybody/anybody_can_see_legal_pages_spec.rb:6 --order=defined --format=doc`
(J'ai repéré ça en voyant le build d'une autre pr sur laquelle je bosse échouer. Le nom du user dans l'erreur m'a permis de comprendre quel fichier leakait des données dans les suivants, et j'ai pu ensuite trouver le bon test en reprenant le seed du build qui échouait)
Il nous manquait l'appel à Warden qui déconnecte les utilisateurs après avoir fait un login_as (même si l'agent ne semble plus exister en base)

Correctif d'erreurs aléatoires sur le build

---

app/jobs/cron_job.rb
app/mailers/agents/account_deletion_mailer.rb
app/views/mailers/agents/account_deletion_mailer/upcoming_deletion_warning.html.slim
config/initializers/good_job.rb
db/migrate/20230823144508_add_agents_account_deletion_warning_sent_at.rb
db/schema.rb
docs/architecture-technique.md
spec/jobs/cron_job/destroy_inactive_agents_spec.rb
spec/jobs/cron_job/destroy_old_rdvs_and_inactive_accounts_job_spec.rb
spec/jobs/cron_job/inactive_agents_spec.rb
spec/mailers/previews/agents/account_deletion_mailer_preview.rb

closes #3623 
La définition qu'on prend d'un agent inactif est :
- n'a pas de rdv (tous les rdv de plus de 2 ans sont supprimés automatiquement)
- ne s'est pas connecté depuis au moins 2 ans (ou ne s'est jamais connecté et son compte a été créé depuis au moins 2 ans)
30 jours avant de supprimer le compte d'un agent, on lui enverra ce mail :
On s'assurera toujours que l'agent a au moins 30 jours entre l'avertissement et la suppression du compte, ce qui veut dire que quand on mettra cette PR en prod on enverra une vague de mail pour tous les agents qui sont inactifs depuis 2 ans ou plus, et 30 jours plus tard on fera les premières suppressions.
Ce mécanisme fait aussi que s'il y a un dysfonctionnement et qu'on prend du retard à envoyer les mails d'avertissement, on laissera quand même aux …

Suppression des comptes agents inactifs

---

app/views/search/banners/_rdv_solidarites.html.slim

Dans cette PR, je change légerement le wording de la landing page des invitations. La raison : certaines invitations sont désormais parfois envoyées par des associations non liées aux départements  (d'où les changements des lignes 7-11). J'en profite pour changer un peu le wording de la ligne 2, ce qui permet de gagner beaucoup d'espace (ce qui n'est pas négligeable sur mobile) + enlève le `(e)` (cf screenshots : avant/après)

Changement de wording pour les invitations

---

app/views/mailers/agents/account_deletion_mailer/upcoming_deletion_warning.html.slim
spec/mailers/previews/agents/account_deletion_mailer_preview.rb

voir https://zammad10.ethibox.fr/#ticket/zoom/7402
Un agent avait deux comptes avec deux adresses emails qui arrivent sur la même boite mail. Un des compte est inutilisé, et elle a donc reçu un mail d'avertissement de suppression de compte, et n'a pas vu que c'était pour son compte inactif.
Le but de cette PR est donc de clarifier quel compte sera supprimé pour éviter ce petit moment d'angoisse.
Voilà à quoi ressemblera le mail :

Ajoute l'adresse email de l'agent dans le mail d'avertissement de suppression de compte

---

app/models/motif.rb
spec/factories/motif.rb
spec/models/motif_spec.rb

Je suis tombé sur ce bug lors du travail sur le soft delete (#3580) : normalement, un motif est censé être supprimé si il n'est lié à aucun RDV, et soft deleted si il est lié à au moins un RDV. Mais en réalité, à cause de ce bug, il est toujours soft deleted.
Le bug était dû à l'usage de `rdvs.unscoped` depuis une méthode d'instance de `Motif`. En effet, `unscoped` a pour effet de supprimer la condition `WHERE rdvs.motif_id = ?`, et donc c'est équivalent à `Rdv.all`.
Le truc drôle, c'est qu'il y avait un test pour cette fonctionnalité, mais l'usage de `let` étant lazy, on testait le soft delete du motif sans RDV dans un état où la base était vierge de tout RDV ! Peut-être un argument en la faveur du chargement des seeds avant tous les tests unitaires, pour tester sur une base non vide …

Bugfix: un motifs n'est jamais supprimé, toujours soft deleted

---

app/controllers/admin/motifs_controller.rb
app/views/admin/motifs/_motif.html.slim
spec/features/agents/sectorisation/motifs_spec.rb

Lors d'une réunion avec les référentes de la Drôme, elles nous ont fait remarquer qu'il y a un bug d'affichage qui fait que les niveaux de sectorisation ne sont plus affichés dans l'index des motifs si un motif est ouvert au public (ce qui est toujours le cas pour les motifs qui utilisent la sectorisation), et mais qu'il est affiché pour les motifs qui ne le sont pas.
Il y avait effectivement eu un contresens sur la dernière modification de `app/views/admin/motifs/_motif.html.slim:11`.
Cette PR ajoute une spec et un correctif.

Correctif sur l'affichage de la sectorisation dans l'index des motifs

---

app/services/sms_sender.rb
spec/services/sms_sender_spec.rb

utiliser les receipt params (fix temporaire) pour utiliser netsize au lieu de sfr pour les départements 62 et 92

Reload sms provider to be able to send waiting sms from 62 and 92

---

.rubocop.yml
app/services/sms_sender.rb
spec/services/sms_sender_spec.rb

Rollback du code mis en place le 12/09/2023.
On réactive le mail2SMS

Réactivation de SFR Mail2SMS suite aux problèmes du 12 septembre

---

db/migrate/20230912082341_update_rdv_notifications_level_default.rb
db/schema.rb
spec/services/notifiers/rdv_cancelled_spec.rb
spec/services/notifiers/rdv_created_spec.rb

close https://github.com/betagouv/rdv-insertion/issues/1277
Modification du niveau de notification par défaut **pour les nouveaux agents** qui seront désormais notifiés de toutes les actions faites par les usagers ou d'autres agents sur les rdv.
Auparavant le niveau par défaut était : `soon` qui notifie les événements uniquement si ceux la ont lieu moins de 24h avant le rdv.
C'est une demande de rdv-insertion, c'est plus logique et plus compréhensible pour les nouveaux agents (qui peuvent très bien modifier le niveau de notif de leur profile si ils le souhaitent).

Modification du niveau de notification par défaut des Agent à `others` au lieu de `soon`

---

app/controllers/admin/agents_controller.rb
app/controllers/admin/territories/invitations_devise_controller.rb
app/controllers/organisations_controller.rb
app/models/agent.rb
app/services/admin_creates_agent.rb
spec/controllers/admin/invitations_controller_spec.rb
spec/controllers/inclusion_connect_controller_spec.rb
spec/features/agents/agents/create_agents_spec.rb
spec/features/agents/agents/invite_agents_spec.rb
spec/models/agent_spec.rb

Dans https://github.com/betagouv/rdv-solidarites.fr/pull/3748, on a introduit des changements aux validations sur le prénom et nom.
Ça a introduit un bug qui fait qu'on ne peut pas inviter un agent dans une deuxième organisation avant qu'il n'ai accepté l'invitation (remonté par l'équipe RDV Insertion, voir ce message sur mattermost : https://mattermost.incubateur.net/betagouv/pl/k3n1h5rd9id7mghusrt5mnaozy)
On reste obligés d'avoir des validations contextuelles (similaire au `validates :last_name, presence: true, on: :update` qu'on avait avant), puisqu'on a deux cas similaires avec des règles différentes sur la présence du prénom :
- un agent basique qui vient d'être invité mais qui n'a pas encore activé son compte n'a pas de prénom. On veut pouvoir l'inviter dans d'autres organisations. …

Correctif pour les validations de nom et prénom sur les agents

---

app/views/admin/motifs/_motif.html.slim
app/views/admin/motifs/show.html.slim
config/locales/models/motif.fr.yml

Dans la continuité de https://github.com/betagouv/rdv-solidarites.fr/issues/3125, puisque la sectorisation n'a pas de sens pour les motifs de suivi, il ne faut pas qu'on affiche les infos de sectorisation dans l'index des motifs et le résumé d'un motif pour un motif de suivi.
Le cas ne s'était pas présenté jusqu'à aujourd'hui, mais la Drôme est en train d'ouvrir de la réservation en ligne avec de la sectorisation sur certains motifs et du suivi sur d'autres.
On contracte ici un petit peu de dette technique, puisqu'on a du fonctionnement commun entre des conditions à trois endroits :
- `app/views/admin/motifs/show.html.slim`
- `app/views/admin/motifs/_motif.html.slim`
- `app/javascript/components/motif-form.js`
et que je fais cette pr sans test vu le niveau de risque faible et le besoin …

Correction de l'affichage de la sectorisation pour les motifs de suivi

---

app/dashboards/agent_dashboard.rb
app/dashboards/agent_territorial_role_dashboard.rb
app/models/territory.rb
config/locales/fr.yml
config/locales/models/agent.fr.yml
config/locales/models/territory.fr.yml

close : https://github.com/betagouv/rdv-solidarites.fr/issues/3747
On ajoute ici la possibilité de définir des admins de territoires dans le `super_admin` via le formulaire agent.
J'ai ajouté les traductions correspondantes pour que ce soit clair dans l'interface que l'action porte sur les admin de territoires.
Une petite subtilité de la gem `administrate` qui utilise la traduction `helpers.label` pour les index et les show (raison pour laquelle tous les labels de nos pages show et index ne sont pas traduits dans le `super_admin`) et les traductions habituelles `activerecord` pour les autres pages qui contiennent des formulaires (new, edit...)
PI, cette PR n'a pas pour but de clarifier les différences entre les tables `agent_territorial_roles` et `agent_territorial_access_rights`. C'est …

Ajout de la possibilité de définir des agents admins de territoires dans le super_admin

---

app/models/concerns/full_name_concern.rb
spec/models/concerns/full_name_concern_spec.rb

Dans le cas où le nom de naissance saisi est le même que le nom de famille, il est inutile d'afficher le nom de naissance entre parenthèses.
Une autre option serait d'interdire de saisir le même nom de famille et nom de naissance, mais ça impliquerait une gêne potentielle pour l'agent, et poserait la question des données existantes. Je suis donc allé au plus simple.
Revue :

Bugfix: le nom de naissance est affiché même si il est identique au nom de famille

---

app/services/admin_creates_agent.rb
app/services/admin_updates_agent.rb
spec/features/agents/agent_can_crud_intervenants_spec.rb

Suite à cette remontée sentry : https://sentry.incubateur.net/organizations/betagouv/issues/60610/?project=74&referrer=webhooks_plugin
Nous avons des erreurs d'envoi smtp (email null) pour les intervenants.
Cette PR fix ce problème en utilisant le système de notification existant.
On désactive les notifs lorsque l'on créé un intervenant ou que l'on passe un agent en intervenant.
Une fois la PR merge je ferai les changements à la main pour les intervenants existants en demo et en prod.

Désactiver les notifications pour les intervenants

---

app/controllers/super_admins/application_controller.rb

Ça permet de savoir à qui s'adresser dans l'équipe quand on voit une erreur remonter.

Remonter dans Sentry le super admin connecté

---

app/controllers/admin/agents_controller.rb
app/views/admin/territories/invitations_devise/new.html.slim

Dans le cadre de https://github.com/betagouv/rdv-solidarites.fr/issues/2312, on avait interdit aux cnfs de créer des comptes avec des niveaux de permission qui permettraient de créer des rdv pour éviter de trop grandes dépenses en sms.
Avec un peu plus de recul, on se rend compte que ce problème était largement surévalué.
On préfère simplifier le code, et uniformiser le comportement de l'appli.
Si des cnfs veulent inviter des collègues, et que ça leur permet d'utiliser l'appli efficacement, tant mieux.
Cette PR sera encore plus utile quand on aura pu merger https://github.com/betagouv/rdv-solidarites.fr/pull/3798

Permet aux CnFS d'inviter des agents avec n'importe quel niveau de permission

---

config/initializers/omniauth.rb

La première tentative appelait `request.env.to_json`, mais il y avait probablement des self-reference dans le hash, donc on obtient `stack level too deep (SystemStackError)` :
https://sentry.incubateur.net/organizations/betagouv/issues/66850/?project=74&referrer=webhooks_plugin
Je pense qu'on peut logger les valeurs qui sont des strings et voir si ça suffit.
Revue :

Bugfix: logger l'environnement Rack lors de l'échec Omniauth

---

app/jobs/concerns/default_job_behaviour.rb
app/jobs/cron_job.rb
app/jobs/export_job.rb
app/jobs/outlook/mass_destroy_event_job.rb
spec/jobs/application_job_spec.rb

On avait un timeout de 30 secondes par défaut. Or, le job de suppression en masse d'événements Outlook a besoin de plus de 30 secondes.
https://sentry.incubateur.net/organizations/betagouv/issues/66829/?referrer=webhooks_plugin
Je fais donc en sorte de pouvoir définir des timeouts spécifiques par classe de job.
Revue :

Définir un timeout différent par type de job

---

app/jobs/webhook_job.rb
app/services/sms_sender.rb
config/initializers/typhoeus.rb
spec/jobs/webhook_job_spec.rb
spec/models/outlook/api_client_spec.rb

Suite au [post-mortem du 12 septembre 2023](https://pad.incubateur.net/KB2I5pdMSGag6VaBxL8mfQ#), nous avons décidé de mettre un timeout à toutes nos requêtes HTTP pour éviter d'avoir des jobs qui tournent trop longtemps et congestionnent nos queues.
J'ai donc ici ajouté dans `config/initializers/typhoeus.rb` un timeout par défaut à toutes nos requêtes Typhoeus. Aussi, désormais, si aucun callback `on_failure` n'est défini au niveau de la requête, c'est un callback par défaut qui s'exécute et lève une exception en cas de timeout.
Revue :

Utiliser un timeout au niveau HTTP

---

config/initializers/omniauth.rb

Un fingerprint avait été conçu pour grouper les erreurs par provider **et** type d'erreur. Mais en fait la clé `omniauth.error.strategy` contient une instance d'une stratégie, dont l'`inspect` change donc à chaque fois.
```json
{
"fingerprint": [
"#<OmniAuth::Strategies::Franceconnect:0x00007fed4f158da0>",
"csrf_detected"
]
}
```
Avec cette nouvelle version, on aura : 
```json
{
"fingerprint": [
"OmniAuth::Strategies::Franceconnect",
"csrf_detected"
]
}
```
Revue :

Stabiliser le fingerprinting des erreurs omniauth

---

app/jobs/concerns/default_job_behaviour.rb
app/jobs/trigger_webhook_job.rb
app/models/webhook_endpoint.rb

On a des levées de `Timeout.timeout` sur ce job donc visiblement il a besoin de plus de temps.
Le contexte aujourd'hui : pluie de notifs Sentry.
Revue :

Donner un peu de temps à TriggerWebhookJob

---

app/controllers/admin/organisations/stats_controller.rb
spec/controllers/admin/organisations/stats_controller_spec.rb

remarqué par la référente de la Drôme (voir le ticket zammad https://zammad10.ethibox.fr/#ticket/zoom/7833)
Les stats par organisation étaient pour tous les rdvs visibles par l'agent, et non pas ceux de l'organisation

Correctif pour les stats par organisation

---

app/models/concerns/user/ants.rb
app/services/ants_api/appointment.rb
spec/controllers/admin/organisations/stats_controller_spec.rb

suite au pic d'erreur de timeout depuis hier : https://sentry.incubateur.net/organizations/betagouv/issues/67365/?environment=production&project=74&query=is%3Aunresolved&referrer=issue-stream
Pour éviter de bloquer les utilisateurs qui veulent prendre rendez-vous, on ajoute un timeout et on considère que le numéro de pré-demande est valide.
Cela introduit un léger risque de doublons de rendez-vous, mais on considère que c'est tolérable plutôt que de bloquer la prise de rendez-vous pour tout le monde.

Ajout d'un timeout aux appels synchrones de l'api ANTS

---

app/models/concerns/user/ants.rb

Ils ont confirmés qu'ils ont un soucis de leur côté, on raccourcit le timeout en attendant qu'ils le réparent.

Raccourcissement du timeout ants

---

db/migrate/20231002124541_add_index_to_rdvs_uuid.rb
db/schema.rb

https://sentry.incubateur.net/organizations/betagouv/issues/67442/?project=74&referrer=webhooks_plugin
Nous avons eu un timeout de la requête
```ruby
Rdv.unscoped.find_by(uuid: uuid) if uuid
```
ce qui m'a fait remarquer qu'il n'y a pas d'index sur cette colonne ! :fearful: 
Revue :

Ajout d'un index sur `rdvs.uuid`

---

app/controllers/admin/rdvs_controller.rb

Discuté avec @mekaidmekaid : on sait qu'il y a un ensemble de quick wins à faire sur la page de liste des RDVs (avoir des onglets "RDVs à venir", "RDVs du jour", "RDVs passés", etc...). Ceci étant dit, les référent⋅es ont affirmé qu'un ordre de RDV antichronologique serait plus utile que l'ordre chronologique, **même si cela implique de voir des RDVs futurs en premier**.
Revue :

Changer l'ordre d'affichage des RDVs

---

app/models/concerns/user/ants.rb

Reverts betagouv/rdv-solidarites.fr#3817
Les perturbations semblent terminées donc on peut considérer que 4 secondes est une valeur raisonnable pour attendre une réponse synchrone.

Revert "Raccourcissement du timeout ants"

---

app/views/admin/agents/absences/index.json.jbuilder
app/views/admin/agents/plage_ouvertures/index.json.jbuilder

En explorant le sujet "agenda multi orga", nous avons repéré ce bug.
Les plages d'ouvertures de l'orga courante est en bleu, celles des autres orgas sont en gris.
La couleur des plages d'ouvertures ne change pas lorsqu'on change d'orga.
La clé de cache ne contient pas l'organisation courante.
Plusieurs solutions possibles : 
1.  ajouter `@organisation.id` dans la clé de cache
2. ne plus utiliser de cache sur les plages d'ouvertures en JSON
J'ai opté pour la 1, car je pense que ce cache est utile avec tout le polling qu'on fait et la basse fréquence d'invalidation.
Chaud d'avoir vos avis ! :wink: 
PS : l'attribut `url` des données renvoyées est aussi impacté par ce bug, car il dépend lui aussi de l'orga.
Revue :

Bugfix : mauvaises couleurs des plages d'ouverture

---

app/helpers/creneaux_helper.rb
app/views/admin/motifs/_form.html.slim

Fiche notion de l'opportunité : https://www.notion.so/rdvs/Partage-de-motifs-inter-orga-ca4a0ffcd9144da6b825adea46921345
Testable sur la review app ici : https://demo-rdv-solidarites-pr3835.osc-secnum-fr1.scalingo.io/
Le nom du motif est utilisé côté usager pour chercher des créneaux à travers plusieurs orgas (c'est la paramètre `motif_name_with_location_type`). En effet, dans plusieurs départements, les motifs sont dupliqués d'une orga à l'autre. Il est donc essentiel que les noms des motifs soient les mêmes à travers toutes orgas d'un même département.
Certaines référentes nous disent utiliser le copier / coller pour s'assurer que les motifs ont bien le même nom à travers toutes les orgas qu'elles configurent.
On peut imaginer qu'un autocomplete dans le champ du nom du motif permette …

Aider à la cohérence des noms de motifs entre les orgas (autocomplétion à la saisie)

---

.rubocop.yml
app/controllers/api/rdvinsertion/invitations_controller.rb
app/controllers/search_controller.rb
app/controllers/users/rdv_wizard_steps_controller.rb
app/controllers/users/rdvs_controller.rb
app/form_models/user_rdv_wizard.rb
app/lib/lapin/range.rb
app/models/motif.rb
app/policies/agent/organisation_policy.rb
app/services/concerns/users/creneaux_wizard_concern.rb
app/services/invitation_search_context.rb
app/services/search_context.rb
app/services/web_invitation_search_context.rb
app/services/web_search_context.rb
app/views/search/address_selection/_rdv_mairie.html.slim
app/views/search/address_selection/_rdv_solidarites.html.slim
config/routes/api.rb
spec/controllers/search_controller_spec.rb
spec/features/allocation_for_search_context_spec.rb
spec/features/users/user_can_be_invited_spec.rb
spec/requests/api/rdvinsertion/creneau_availability_spec.rb
spec/services/web_invitation_search_context_spec.rb
spec/services/web_search_context_spec.rb
spec/support/shared_context/search_context.rb

Restore après revert betagouv/rdv-solidarites.fr#3844
Fix d'une methode manquante (`public_link_organisation`) dans le `WebInvitationSearchContext`
Celle ci n'étant pas utilisée dans le contexte des invitations j'ai ajouté une méthode `public_link_organisation` qui renvoi nil et le test qui va bien.

Restore "Refacto `SearchContext` et mise en place de l'api de calcul de créneaux pour RDVI"

---

db/migrate/20231017125305_reunite_prod_schema.rb
db/schema.rb

Problème : le `schema.rb` ne reflète pas l'état de la db de production.
Liste des différences entre la db de prod et nos db de dev / test / review app :
Il est probable que ce soit Scalingo qui ait activé cette extension sur toutes ses bases PG pour offrir la fonctionnalité de stats de requêtes (qui nous est d'ailleurs fort utile parfois).
Depuis Rails 7.0, la précision par défaut des colonnes `datetime` est passée de `nil` à `6`. Cette PR définit donc la précision à 6 pour tous nos champs en prod, afin que nous adhérions au standard de Rails, et que nous n'ayons plus à nous poser la question à l'avenir.
Visiblement les commentaires Postgres ne sont pas gardés en prod, et vu l'usage plus que sporadique que nous en avons, nous pouvons décider de virer les 3 qu'il reste. …

Rétablir la cohérence entre la DB de prod et schema.rb

---

app/views/search/_nothing_to_show.html.slim
spec/features/users/user_can_manage_collective_rdv_spec.rb
spec/features/users/user_can_search_rdv_spec.rb

Dans la continuité de #3831 , on rend plus générique le texte montré aux usagers quand aucun créneau n'est trouvé.

Généralisation du texte montré aux usagers quand aucun créneau n'est trouvé

---

app/jobs/webhook_job.rb
config/initializers/typhoeus.rb

Problématique : lorsqu'on copie une base d'une instance vers notre db de dev, les webhooks restent activés. Le risque est donc d'appeler les URLs des webhooks accidentellement en lançant le worker de jobs par exemple.
Je propose que l'on désactive par défaut les appels HTTP en dev, du moins ceux que l'on fait avec Typhoeus (webhooks, synchro Outlook). On fait 2 appels GET avec Faraday, ils sont inoffensifs.
Revue :

Bloquer les requêtes HTTP en dev

---

app/dashboards/service_dashboard.rb
app/models/service.rb

Problème : sur l'interface super-admin, sur le formulaire d'édition de service, il y a un select pour modifier les motifs. 
Ce select liste tous les motifs de toutes les orgas. Il est donc facile d'arriver sur ce formulaire (pour éditer la verticale, par exemple :wink: ) et de se retrouver à modifier accidentellement la liste des motifs pour une raison quelconque, par exemple :
- le multiselect JS tronque les valeurs
- on clique sur une petite croix à cause d'un trackpad de laptop bon marché
Et si on retire un motif de la liste et que l'on clique sur "Enregistrer", le motif est supprimé (sauf si il a des RDV, auquel cas ça plante).
Ce select est donc dangereux en plus d'être inutile, donc je propose de le virer. :wink: 
Revue :

Éviter une édition accidentelle des motifs d'un service

---

app/controllers/agents/users_controller.rb
app/helpers/users_helper.rb
app/javascript/stylesheets/components/_select2.scss
app/lib/phone_number_validation.rb
app/models/user.rb
app/views/admin/rdv_wizard_steps/step2.html.slim
app/views/agents/users/search.json.jbuilder
config/routes.rb
db/seeds/medico_social.rb
spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
spec/features/agents/rdv_wizard/step2_spec.rb
spec/requests/agents/users_spec.rb
spec/support/select2_spec_helper.rb

L'objectif de cette PR est d'éviter la création de doublons usager par les agents lors de la prise de rendez-vous.
Aujourd'hui, on essaye d'éviter les doublons en avertissant l'agent d'un doublon potentiel lorsqu'il a fini de remplir la fiche usager lors de la création du rdv (voir le screenshot en début de l'issue).
Dans cette PR, on cherche à éviter que l'agent ai besoin de revenir en arrière après avoir rempli une fiche, et on étend le périmètre de la recherche d'usager à tout le territoire (puisque de toutes façons la recherche de doublon lors de la création de l'usager se fait à l'échelle de toute la base).
On améliore aussi l'UX de la recherche sur deux points :
- On rend explicite que cette recherche peut se faire par numéro de téléphone et email, en changeant le placeholder, et …

Eviter la création de doublons usager
