betagouv/rdv-solidarites.fr

- app/assets/javascripts/administrate/places.js.erb
- app/javascript/packs/components/places-input.js.erb
Comme on accepte autre chose que les suggestions de type adresse, certaines valeurs sont parfois undefined, ce changement fait sauter la virgule mais permet d'afficher simplement et correctement tous les types de suggestion.
> [Home] Fix undefined in search if type is not address

- app/assets/stylesheets/components/_calendar.scss
- app/javascript/packs/components/calendar.js
- app/views/agents/rdvs/index.json.jbuilder
- spec/controllers/agents/rdvs_controller_spec.rb
Voila le visuel pour des RDV passé (plus de supperposition avec le nom de la plage) pour des durées de 30, 25, 20, 15, 10 min.
Je pense qu'a terme il faudrait analyser le % des RDV de - de 30min... S'il il est élevé on devra spliter les heures en tranche de 20min.
> [Agent][Agenda] Visuel du RDV dans agenda

- app/models/creneau.rb
Le code de carl avait déjà effacé le comportement.
> [RDV] Remove unused Rdv name

- app/models/plage_ouverture/ics.rb
- app/models/rdv/ics.rb
- spec/models/plage_ouverture/ics_spec.rb
- spec/models/rdv/ics_spec.rb
* Définition du champ ATTENDEE / https://tools.ietf.org/html/rfc5545#section-3.8.4.1
* Définition de la valeur CAL-ADDRESS / https://tools.ietf.org/html/rfc5545#section-3.3.3
Tentative de résolution de [[agent] [Outlook] la plage d'ouverture envoyée de rdv-solidarités vers Outlook n'apparaît pas dans l'outlook (soit erreur à l'ouverture de la PJ/ soit ne s’intègre pas à l'Outlook)](https://trello.com/c/wmYVeX4z/568-agent-outlook-la-plage-douverture-envoy%C3%A9e-de-rdv-solidarit%C3%A9s-vers-outlook-nappara%C3%AEt-pas-dans-loutlook-soit-erreur-%C3%A0-louverture-d)
> Struture le champs ATTENDEE comme attendu dans le RFC

- spec/controllers/agents/absences_controller_spec.rb
- spec/factories/absence.rb
- spec/factories/agent.rb
- spec/factories/motif.rb
- spec/features/agents/agent_can_crud_absences_spec.rb
- spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
```
visit organisation_agent_absences_path(agent.organisations.first.id, other_agent.id)
```
Le `onchange: "Turbolinks.visit($('.select2-input option:selected').attr('data-url'))"` n'est pas pris en compte
> [Test] Rajouter un test sur la prise de RDV  sur un autre calendrier / Plage ouverture / Absence

- config/environments/development.rb
this allows seeing the default development logs with the router etc. 
By default on my machine, using foreman (or overmind) I don't see these logs. can you confirm that you prefer it this way @jjf21 and @yaf?
> force logging to STDOUT in development with foreman

- .gitignore
- db/seeds.rb
Improve seeds:
- pass variables instead of relying on first id being 1
- improve created models attributes defaults
- create a PlageOuverture model
and the .ruby-gemset file is useful for `rvm`, my terminal is configured to auto switch gemset when entering this repo (it's a bit overkill considering bundler but I'm used to it)
> improve seeds and add .ruby-gemset to gitignore

- spec/models/file_attente_spec.rb
I think the `ActiveJob::Base.queue_adapter = :test` might have explained part of the randomly failing tests as it was not being reverted afterwards, so jobs would be enqueued asynchronously, which is not expected in the test suite
> stop changing queue_adapter in some tests

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_utilities.scss
- app/javascript/packs/application.js
- app/javascript/packs/components/motif-form.js
VAD motifs cannot be performed by the secretariat
when VAD is checked:
- force uncheck secretaraiat
- disable the secretariat checkbox 
- make secretariat block grayed out (translucent) so it's clear it's not compatible.
---
I try to write mostly vanilla JS and as little jQuery as possible, let me know if you don't like it
> [VAD] disable secretariat option in motif config when VAD

- app/helpers/rdvs_helper.rb
- app/models/rdv.rb
- app/models/rdv/ics.rb
- app/views/agents/rdvs/index.json.jbuilder
- app/views/agents/rdvs/show.html.slim
- spec/controllers/agents/rdvs_controller_spec.rb
- spec/helpers/rdvs_helper_spec.rb
- spec/models/rdv/ics_spec.rb
preliminary to #534 where I'll be adding behaviour to these methods.
I don't think these methods belong to the RDV model but to a helper as they are only presentational. 
I've slightly refactored the specs to expect for more 'hardcoded' instead of dynamic values that rely on the seeds generated by the factories. I find it much less error prone and more explicit this way. 
I've also added a dedicated spec file for the RdvsHelper where I'm unit testing these methods
this PR can be read commit by commit
> [Tech] Refactor rdv.name_for_user and agent to separate helpers

- app/helpers/rdvs_helper.rb
- app/views/agents/rdvs/_rdv_details.html.slim
- spec/factories/rdv.rb
- spec/helpers/rdvs_helper_spec.rb
linked to https://trello.com/c/T9BNYXUH/595-vadagent-identifier-les-rdv-%C3%A0-domicile
I didn't fully respect the specs:
- I used emojis instead of fa-icons in the calendar view to simplify both coding and testing
- For balance I also added an icon for phone meetings
> [VAD] display VAD information in agents RDVs and calendar views

- config/initializers/content_security_policy.rb
https://trello.com/c/hCBelpsx/218-secu-r%C3%A9gler-les-points-remont%C3%A9s-par-securityheaderscom
Une première tentative en mode report-only pour ne rien casser.
TODO si approuvée :
> Enable content security policy in report only mode

- app/controllers/agents/rdv_wizard_steps_controller.rb
- app/form_models/rdv_wizard.rb
- app/helpers/motifs_helper.rb
- app/helpers/rdvs_helper.rb
- app/javascript/packs/components/calendar.js
- app/models/rdv.rb
- app/models/user.rb
- app/views/agents/creneaux/agent_searches/_creneaux.html.slim
- app/views/agents/creneaux/agent_searches/index.html.slim
- app/views/agents/rdv_wizard_steps/step1.html.slim
- app/views/agents/rdv_wizard_steps/step2.html.slim
- app/views/agents/rdv_wizard_steps/step3.html.slim
- app/views/agents/users/_form.html.slim
- spec/factories/motif.rb
- spec/factories/user.rb
- spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
- spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
- spec/form_models/rdv_wizard_spec.rb
https://trello.com/c/SbLo91uF/594-vad-pose-dun-rdv-sur-lagenda
ℹ️ this PR can be read commit by commit, they are pretty self-contained
ℹ️ Screenshots below 👇
Updates in the RDV Wizard:
- Reorder the steps : you now choose users before choosing the date, location and agents
- Ask for a location for VAD rdvs. Defaults to the first user's address
- Display motifs 'options' (online / phone / VAD) in the dropdown and labels
- Slightly change the header row of already selected options during step 2
- explicited a few wordings : 
- "Choisir l'usager" -> "Choisir le ou les usagers"
- "Créer" -> Créer un usager / Créer RDV
Updates in "Trouver un Creneau":
- Display motifs 'options' (online / phone / VAD) in the dropdown
- Redirect towards step 2 of the RDV wizard (pick users) instead of step 3 …
> [VAD] Update agents RDV wizard to choose a location

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
linked to https://trello.com/c/yibIcLXq/601-fix-randomly-failing-feature-specs
this PR makes integration specs take a screenshot (HTML + png) upon each failure.
Locally:
On CircleCI : 
cf https://github.com/mattheworiordan/capybara-screenshot/
and https://github.com/mattheworiordan/capybara-screenshot/issues/211#issuecomment-321857907 
and https://circleci.com/docs/2.0/artifacts/
I also fixed the `store_test_results` directive that was pointing to the wrong directory. It lets us see a formatted view of failing tests on CircleCI:
> automatically take screenshots when integration specs fail

- spec/spec_helper.rb
linked to https://trello.com/c/yibIcLXq/601-fix-randomly-failing-feature-specs
logs are written to `tmp/capybara/chrome.spec_full_description.browser/driver.log` and on CircleCI they are uploaded as artifacts so you can see them after the tests have run. 
note: they may still be duplicated across different specs, I'm not sure if the logs are cleared between tests
> [Tech] write chrome headless logs to files during feature specs

- .circleci/config.yml
this will notify us on slack when a job's build/test/lint step fails on the master branch only.
cf https://circleci.com/orbs/registry/orb/circleci/slack
I added the `SLACK_WEBHOOK` env var on CircleCI 
I tested once by switching to this branch and failing a test on purpose, it seemd to work
> [tech] add CI failure Slack notifications for master branch

- app/models/rdv.rb
- spec/factories/rdv.rb
- spec/models/rdv/ics_spec.rb
- spec/models/rdv_spec.rb
https://trello.com/c/nDvnpBQd/546-annulation-supprimer-les-motifs-de-confirmation-pour-les-rdv-pass%C3%A9s
> [Annulation] ne pas notifier l'usager pour les rdv dans le passé

- spec/models/user_spec.rb
```  1) User#add_organisation when organisation is associated with many organisations is expected not to change `User#organisation_ids`
Failure/Error: it { expect { subject }.not_to change(user, :organisation_ids) }
expected `User#organisation_ids` not to have changed, but did change from [67, 68] to [68, 67]
https://stackoverflow.com/a/19436763
> [Rspec] Failed test / array order

- spec/spec_helper.rb
ca a l'air d'aider en tout cas en local, et au moins pour le `spec/features/agents/admin_can_configure_the_organisation_spec.rb:92` "Voir le Motif"
> enable Capybara.disable_animation option to prevent some flaky tests

- app/controllers/lieux_controller.rb
- app/controllers/welcome_controller.rb
- app/views/common/_search_form.html.slim
- app/views/lieux/show.html.slim
- app/views/lieux/show.js.erb
cf https://trello.com/c/PHIBzZko/690-r%C3%A9parer-les-recherches-pour-des-motifs-devenus-indisponibles-%C3%A0-la-r%C3%A9servation-en-ligne
pour reproduire le cas problematique facilement : 
- creer un RDV dans le futur puis l'annuler
- garder ouvert le mail de notif d'annulation envoyé au user
- passer le motif du RDV en "indisponible à la résa en ligne" 
- cliquer sur le lien du motif
aujourd'hui ça lève une 500 : https://sentry.io/organizations/lapins/issues/1614694881/?project=1811205
cette PR modifie le comportement pour que gerer ca plus soft et afficher un message d'erreur explicite : 
note: 
je n'ai pas pu m'empecher de renommer les variables `@motifs` et `@motif` qui contiennent des noms de motifs et pas des motifs.
> Fix searches with unavailable motifs

- config/locales/fr.yml
https://trello.com/c/E9Hfq5L2/678-vadnotifications-heure-pas-affich%C3%A9e-dans-le-mail-de-confirmation-de-rdv-vad
> Fix VAD RDV mails time format

- app/controllers/agents/motifs_controller.rb
- app/models/motif.rb
- spec/controllers/agents/motifs_controller_spec.rb
resoud deux tickets car en fait difficilement dissociables:
https://trello.com/c/PqADEs7M/689-agentvad-permettre-la-cr%C3%A9ation-de-motifs-de-m%C3%AAme-libell%C3%A9s-mais-de-types-de-rdv-diff%C3%A9rents
et
https://trello.com/c/dC6NiD9C/699-agent-retirer-le-comportement-createorupdate-%C3%A0-la-cr%C3%A9ation-de-motif
cette PR change la contrainte d'unicité des motifs, aujourd'hui la contrainte est : 
- aucun motif avec le même nom au sein d'une orga.
maintenant : 
- aucun motif **actif** (non-supprimé) avec le même nom et le même `location_type` au sein d'une orga
je n'ai pas rajouté de tests car je pense que ça reviendrait à tester AR et que les tests ne seraient pas plus lisibles que le code mais c'est discutable
> allow motifs with same name but different location types

- app/controllers/lieux_controller.rb
Je ne pense pas que ça resolve complétement le problème, mais c'est un premier pas dans la bonne direction je crois.
https://trello.com/c/D1FkScBO/564-perf-optimiser-lieuxcontrollerindex
Nous faisions 2 fois le calcul de créneau dans le cas où il n'y a qu'un seul lieu. Maintenant, on le fait une fois que ce soit pour un ou plusieurs lieu.
Une piste que j'aimerais explorer c'est le fait de calculer les créneaux disponible AVANT de les afficher. Peut-être dans un autre ticket ? Comment procéder ?
> Effectue la redirection avant la recherche de créneau

- app/models/creneau.rb
- app/views/common/_creneaux.html.slim
- spec/factories/creneau.rb
- spec/models/creneau_spec.rb
cf https://trello.com/c/zc0mkTqD/682-agenttrouver-un-cr%C3%A9neau-rendre-le-d%C3%A9lai-mini-et-maxi-inactif-c%C3%B4t%C3%A9-agent
J'ai ajouté des specs pour la méthode que je modifie et un peu refacto les existantes:
- moins de create, plus de build (= moins d'acces DB)
- introduction d'une factory Creneau. ca eloigne un peu le contexte du test @yaf mais ca me parait quand meme mieux pour pas répéter 50 fois les memes choses, et permettre de reutiliser un creneau qui ne respecte pas les booking delays ailleurs ... c'est discutable
- refacto les fonctions too_late? et too_soon? en respects_max/min_booking_delays (a l'envers donc). plus explicite et moins de doubles negations. 
- ajouté une methode qui regroupe les deux `respects_booking_delays`
cette PR peut etre lue commit par commit
> let agents bypass booking delays in trouver un creneau interface

- app/models/rdv.rb
- spec/models/rdv_spec.rb
https://trello.com/c/nDvnpBQd/546-annulation-supprimer-les-notifs-de-confirmation-pour-les-rdv-pass%C3%A9s
On vérifier sur l'échelle d'une journée, maintenant, c'est à la seconde prêt.
> pas de notification pour un rdv posé il y a une heure

- app/controllers/application_controller.rb
- app/controllers/users/rdvs_controller.rb
- app/controllers/users/relatives_controller.rb
- app/views/users/rdvs/new.html.slim
- app/views/users/relatives/new.html.slim
- spec/controllers/users/relatives_controller_spec.rb
cf https://trello.com/c/E0ngGLpB/840-usager-dans-le-tunnel-de-prise-de-rdv-auto-s%C3%A9lectionner-le-proche-nouvellement-cr%C3%A9%C3%A9
pour le faire : 
- rajout d'un paramètre get `created_user_id` qui est ajouté à l'url vers laquelle la modale de création de proche retourne
- modification de l'action `users/rdvs#new` pour prendre en compte ce parametre, et generalement mieux hydrater l'objet `@rdv` et l'utiliser en priorité dans la vue
en refacto bonus dans cette PR : 
- remplacement du parametre `callback_path` explicitement passé par l'utilisation de `request.referer`
> auto select newly created relative in users rdv form

- app/webpacker/components/calendar.js
cf https://trello.com/c/HtWCNUBJ/839-agent-calendrier-en-double-apres-retour
cf https://github.com/turbolinks/turbolinks#making-transformations-idempotent exactly this case
> [bug] fix returning on calendar duplicate with turbolinks

- app/services/creneaux_builder_service.rb
- spec/services/creneaux_builder_service_spec.rb
cf https://trello.com/c/nb3LeyAY/833-ne-pas-afficher-les-cr%C3%A9neaux-pass%C3%A9s-dans-trouver-un-creneau-ceux-du-matin-du-jour-meme
cette PR est plus complexe qu'elle n'aurait pu l'etre mais j'avais commencé par rajouter une option `include_past` en pensant qu'on avait besoin des deux cas. finalement ce n'est pas le cas. mais j'ai gardé le refacto plus generique des 'options' dans le service, dites moi si vous voulez que je l'enleve.
Je pense que dans les tests au moins c'est plus lisible
> no past slots in find a slot interface

- app/webpacker/components/calendar.js
fix https://sentry.io/organizations/lapins/issues/1637402456/?project=1811205
le turoblinks before cache hook est executé sur toutes les pages, il faut rajouter un court circuit
> fix turbolinks before cache hook for calendar

- app/models/agent.rb
- app/models/agents_rdv.rb
- app/models/rdv.rb
- app/models/rdvs_user.rb
- app/models/user.rb
- db/migrate/20200505101547_add_id_to_rdvs_users_and_agents_users.rb
- db/schema.rb
this allows adding behaviour to the join tables (`rdvs_users` and `agents_rdvs`) items : 
1. `touch`ing the Rdv when an association is updated or created
2. use `dependent: :destroy` on rdv's `has_many :rdvs_users` and other associations
adding primary keys to the join tables is necessary for point 2.
this PR will help storing RDV's versions for agents and users updates in #598
> explode has_and_belongs_to_many Rdv associations

- app/views/common/_modal_confirmation.html.erb
- app/views/users/rdvs/_rdv.html.slim
- spec/features/users/user_can_manage_rdv_spec.rb
autre facon de faire #616 sans JS additionnel 
On peut déplacer plus ou moins de choses dans le partial `_modal_confirmation.html`. J'y ai mis un peu moins de choses que Carl dans la version JS, car j'anticipe qu'il y aura aussi des confirmations "positives" où on voudra changer les couleurs et les styles des boutons du footer. donc j'ai completement extrait le footer
> [Usager] clarifier les boutons lors de l'annulation

- app/controllers/agents/rdv_wizard_steps_controller.rb
- app/controllers/agents/rdvs_controller.rb
- app/models/motif.rb
- app/models/service.rb
- app/views/agents/rdv_wizard_steps/step3.html.slim
- spec/models/motif_spec.rb
fix https://sentry.io/organizations/lapins/issues/1649997289
c'est cassé quand il y a des erreurs validations car on render la step3 MAIS il manque la variable d'instance `@rdv_wizard` 😨 
j'ai corrigé ca, et j'en ai profité pour déplacer la variable d'instance `@agents_authorize` dans une méthode testée du modèle `Motif`
> fix agents rdv creation validation failure flow

- .rubocop.yml
- app/models/lieu.rb
- app/models/motif.rb
- app/models/plage_ouverture.rb
- lib/tasks/prod/massive_cancel.rake
on etait en `aligned`:
```
variable_name = some_long_call
.method_name_1
.method2    
```
on passe a `indented`:
```
variable_name = some_long_call
.method_name
.method2
```
A est le défaut de rubocop, et c'est ce qu'on a aujourd'hui dans le code.
perso je deteste A : je trouve ça dur à faire, pas pratique car ça dépasse tout le temps des 80cols, et pas pratique parce qu'il faut tout réaligner si tu modifies la première ligne.
on en a discuté, je suis le seul a avoir un avis la dessus a priori https://startups-detat.slack.com/archives/C011EG2GDAT/p1588753650008600
> change rubocop lint rule for indentation : not aligned

- app/controllers/application_controller.rb
- app/views/agents/organisations/stats/index.html.slim
- app/views/stats/_statistics.html.slim
- app/views/stats/index.html.slim
- config/locales/fr.yml
- spec/models/stat_spec.rb
https://trello.com/c/P1Tx7LoI/837-agentvos-statistiques-globales-les-donn%C3%A9es-contenus-dans-les-histogrammes-ne-sont-plus-lisibles
Pour le problème lié au scope de l'organisation:
On passe à la partial "statistic" une variable `rdvs_stats_path` avec le contexte.
Il y a 3 contextes:
- Statistiques globales de l'app
- Statistiques scopés à l'orga (pour les agents admins)
- Statistiques scopés à l'agent (pour chaque agent)
Cette variable était appelé `rdvs_stats_path(by_service: true)` et elle faisait donc appel à la vrai route de rails et nom à la variable passé à la partial.
J’ai renommé la variable en rdvs_statistic_path (qui n'est pas une route rails) pour éviter toute incompréhension.
> [Stats] mauvais groupement sur histo « RDV Créés »

- app/webpacker/packs/application.js
seems to fix `forEach` is not a function on old browsers (chrome 49 and FF 48)
cf https://sentry.io/organizations/lapins/issues/1646162821/?environment=production&project=1811205
it's pretty intricate to me but it seems that polyfills are handled by `@babel/preset-env` which reads the `.browserslistrc` file that says `defaults` option, and Babel will make sure that our `import core-js` will only require the necessary polyfills. 
⚠️ when releasing double check on demo that this doesn't increase bundle size too much
Note: You can check which browsers we currently explicitly target by running `npx browserslist` (this is what the defaults rule currently yields) : 
```
and_chr 75
and_ff 67
and_qq 1.2
and_uc 12.12
android 67
baidu 7.12
chrome 75
chrome 74
chrome 73
edge 18
edge 17
firefox 68 …
```
> add import corejs to application pack for polyfills

- app/mailers/agents/plage_ouverture_mailer.rb
- app/mailers/users/rdv_mailer.rb
cf https://trello.com/c/EoXzM9kK/826-v%C3%A9rifier-la-bonne-gestion-des-accents-dans-les-invitations-ical
the bug only reproduces when sending through SIB's SMTP. I enabled it locally by copying prod's config. This fix seems to be enough.
I really don't understand much to what's happening here, but I think the default is base64 but it's not perfect for plain text files like ICS ... I don't really know 😬 
https://en.wikipedia.org/wiki/MIME#Content-Transfer-Encoding
> fix ICS text encoding using 8bit

- db/seeds.rb
Une partie de la logique de l'application est manquante en l'absence de ce service (RDV Secrétariat par exemple).
> Ajoute le service Secrétariat dans les seeds

- .circleci/config.yml
- Procfile
- app/models/rdv/ics.rb
- app/services/twilio_text_messenger.rb
- config/environments/production.rb
actuellement : 
- en demo : `HOST=demo.rdv-solidarites.fr`
- sur les review apps: `HOST=https://demo-rdv-solidarites-pr653.osc-fr1.scalingo.io`
-> le https est 'en trop' sur les review apps. Cela cause des problemes, dont l'envoi de mails.
On ne peut pas corriger en enlevant le HTTPS du HOST des review apps, car il est mis automatiquement lors de la création des review apps, on n'a pas la main dessus.
On ne peut donc pas faire de fix sûr en une seule PR je pense, car il faudrait déployer le code + changer simultanément la variable d'env `HOST`. 
Solution proposée :
- introduction d'une nouvelle variable d'env `HOST_QUALIFIED` qui contient le HOST **avec** le protocole
- on s'assure qu'elle est bien configurée manuellement sur tous les envs actuels (demo, prod, review apps)
- on deploie …
> fix sending mails from review apps : introduce HOST_QUALIFIED env var

- .circleci/config.yml
- .env.sample
- app/models/rdv/ics.rb
- app/services/twilio_text_messenger.rb
- config/environments/production.rb
Suite de la PR #653
On supprime HOST_QUALIFIED et on utilise HOST a la place.
Avant de deployer on s'assure que HOST est bien configuré avec le protocole sur demo et prod
une fois déployé on supprime HOST_QUALIFIED partout
> stop using temporary HOST_QUALIFIED in favor of HOST

- app/controllers/agents/organisations/stats_controller.rb
- app/views/stats/_statistics.html.slim
Remonté pendant la démo, Il y a un problème de donnée sur `/organisations/1/stats` au niveau du graphique `RDV par type`
> [Stats] Fix les mauvaise données sur les stats agent

- spec/controllers/users/rdv_wizard_steps_controller_spec.rb
Le bug etait super ponctuel : dans 10 jours c'est le 1er juin et c'est férié. Donc impossible de reserver ce jour la. 
J'ai hardcodé les dates pour éviter que ca ne se reproduise
> fix users rdv wizard specs with hardcoded date to avoid holidays

- scripts/get_deployed_changes.rb
`$ ruby scripts/get_deployed_changes.rb --archive`
- prints the list of cards in the deployed column in MD format to be copied in the changelog.
- archives all cards in list.
> added script to fill changelog easily

- .circleci/config.yml
seems like a quick fix for a few seconds on each build
> fix order of yarn cache save in circleci config

- app/controllers/agents/users_controller.rb
- app/controllers/users/registrations_controller.rb
- app/form_models/users/registration_form.rb
- app/models/user.rb
- app/views/users/registrations/new.html.slim
- spec/factories/user.rb
- spec/form_models/users/registration_form_spec.rb
Extraction d'un form object `Users::RegistrationForm` qui est utilisé dans le sign up et le edit des users comme proxy pour le modele User. Cela permet de retirer le booleen `@user.created_or_updated_by_agent` qui met des validations conditionnelles dans le modele User.
sur le principe des Form Objects cf https://culttt.com/2015/11/04/using-form-objects-in-ruby-on-rails/ par ex
refacto préliminaire pour #669
> extract users registration form object

- spec/factories/rdv.rb
- spec/factories/service.rb
- spec/services/twilio_text_messenger_spec.rb
- spec/spec_helper.rb
https://trello.com/c/3kkrW3SI/832-enlever-les-tests-qui-font-des-calls-a-lapi-twilio
- enleve les appels a l'API en mockant le call a `messages.create` 
- rend les expectations plus explicites en les hardcodant et en comparant l'entiereté du body plutot que des sous parties.
> remove actual API calls from SMS specs + make them more explicit

- .rubocop_todo.yml
- app/controllers/agents/rdvs_controller.rb
- app/form_models/agent_rdv_search_form.rb
- app/helpers/application_helper.rb
- app/helpers/rdvs_helper.rb
- app/helpers/users_helper.rb
- app/models/user.rb
- app/views/agents/agents/show.html.slim
- app/views/agents/organisations/rdvs/index.html.slim
- app/views/agents/rdvs/_rdv.html.slim
- app/views/agents/rdvs/_rdv_details.html.slim
- app/views/agents/rdvs/_rdvs_list.html.slim
- app/views/agents/rdvs/index.html.slim
- app/views/agents/users/_relative_information.html.slim
- app/views/agents/users/_responsible_information.html.slim
- app/views/agents/users/_show_relative.html.slim
- app/webpacker/components/calendar.js
- app/webpacker/stylesheets/print.scss
- config/locales/fr.yml
cf https://trello.com/c/uNz3uw6C/222-agent-pouvoir-imprimer-la-liste-et-les-notes-des-rdv-du-jour
⚠️ Disclaimer : cette PR est un peu grosse et pas découpée en commits propres. Si vous le souhaitez, je peux extraire certains refactos dans des commits / PRs indépendantes
- Ajout d'un lien contextuel vers la liste de RDV de la journée en dessous du calendrier (`agents/rdvs#index`). Ce lien est maintenu à jour dynamiquement en JS lorsqu'on change de date / de type de vue.
- Sur `agents/rdvs#index`:
- Support d'un nouveau filtre `date` (jusqu'ici uniquement date range supportés)
- Ajout d'une nouvelle option d'affichage `user_details` qui deplie les coordonnees des users.
- Ajout de delegates dans le modele `User` pour afficher les infos du responsable quand user est un proche
- Rendu plus …
> improve rdvs list view + improve printing options + add filter on date from calendar

- app/views/users/rdv_wizard_steps/step2.html.slim
https://trello.com/c/R7tUmMdh/887-usager-bug-marges-dans-la-selection-usager-dans-la-prise-rdv
avant :
apres :
> fix margins in rdv wizard step 2

- app/mailers/agents/plage_ouverture_mailer.rb
- app/models/rdv/ics.rb
https://trello.com/c/wmYVeX4z/568-agent-outlook-la-plage-douverture-envoy%C3%A9e-de-rdv-solidarit%C3%A9s-vers-outlook-nappara%C3%AEt-pas-dans-loutlook-soit-erreur-%C3%A0-louverture-d
L'évenement ICS est maintenant reconnu par Outlook qui l'affiche en haut du mail avec des boutons pour "répondre" même si ce n'est pas possible et l'ajouter au calendrier facilement.
Les fichiers ICS envoyés avant n'étaient pas "cassés", mais juste pas interprétés par Outlook. Ce n'est pas documenté, mais Outlook interprète les ICS uniquement lorsqu'ils sont envoyés comme une `part` du mail inline, pas comme un `attachment`. 
Je suppose que les agents n'arrivaient pas à ouvrir les fichiers ICS car leurs ordinateurs sont configurés de manière particulière. Je n'ai pas de problème pour ouvrir les fichiers ICS …
> fix plage ouverture ICS opening in Outlook

- app/controllers/lieux_controller.rb
- app/views/lieux/index.html.slim
- app/webpacker/stylesheets/components/_cards.scss
- spec/features/users/user_can_search_rdv_spec.rb
https://trello.com/c/ojjMVtjb/872-usagerprise-de-rdv-toujours-passer-par-la-liste-de-lieux
- on passe toujours par la liste des lieux. avant, on pouvait être redirigé directement vers un lieu quand il n'y avait qu'un résultat
- ca sera plus explicite de passer par ici dans les cas ou il n'y a aucune disponibilité
- il y a maintenant une border qui apparait au hover des cards de lieux disponibles
- le hover est mieux désactivé pour les cards de lieux indisponibles
testable sur la review app: https://demo-rdv-solidarites-pr687.osc-fr1.scalingo.io/lieux?search%5Bdepartement%5D=75&search%5Blatitude%5D=48.8546&search%5Blongitude%5D=2.34771&search%5Bmotif_name%5D=%C3%8Atre+rappel%C3%A9+par+la+PMI&search%5Bservice%5D=1&search%5Bwhere%5D=Paris+75000
- j'ai utilisé les stretched links …
> stop redirecting to unique lieu

- app/mailers/agents/plage_ouverture_mailer.rb
L'absence de ce charset déclenchait un warning lors des specs, par exemple lieux_controller_spec
> fix charset encoding warning in plage ouverture mailer

- .browserslistrc
blind fix attempt for https://trello.com/c/bR6ukPkS/890-reparer-closest-pour-ie-11-18
I could not manage to reproduce bug with closest through browserstack :/
It's very unclear which `closest` is generating this error as we don't have source maps connected on sentry. From looking at the code we only explicitly call the vanilla `closest` (not the jQuery one) at one point in the code : the motif form js (apart from the super admin interface). However the events on sentry are spread among the whole admin so it doesn't seem linked to that one.
> add IE 11 to browserslist

- Gemfile
- Gemfile.lock
- app/webpacker/components/calendar.js
- app/webpacker/packs/application.js
- app/webpacker/routes.js.erb
- babel.config.js
- package.json
- yarn.lock
en travaillant sur le support de IE11 j'ai itéré dans des directions qui m'ont amené à mettre a jour webpacker + mettre a jour notre config de babel. 
Ca ne corrige pas le probleme de IE 11 tel quel mais c'est un pas dans la bonne direction
j'ai vérifié sur la review app que ça n'augmente pas la taille du bundle et que ça n'introduit pas de regression ni sur FF moderne ni sur IE 11
> upgrade to webpacker 5 + remove js-routes gem + minor babel configs

- app/views/agents/rdvs/_rdv_details.html.slim
- app/views/agents/rdvs/show.html.slim
https://trello.com/c/nAhf9nW3/892-lagent-devrait-pouvoir-annuler-un-rdv-qui-a-lieu-dans-tres-peu-de-temps
j'ai aussi corrigé une marge en dessous des notes libres en passant
> fix canceling rdv starting soon for agents

- app/services/notifications/rdv/rdv_updated_service.rb
https://trello.com/c/F2nEwFc9/903-usagernotification-lorsquun-rdv-est-modifi%C3%A9-lusager-re%C3%A7oit-un-mail-de-confirmations-mais-plus-de-sms
j'avais cassé l'envoi de SMS lors de l'update de RDV dans mon refacto pour extraire des services d'envoi de notifs : https://github.com/betagouv/rdv-solidarites.fr/commit/2f39467cbb321e06226c15576d59ccaab1c9bf39
j'avais oublié de copier l'envoi de rdv_created a l'update, ce qui est un peu perturbant
> fix sending SMS on RDV update

- config/environments/development.rb
it's annoying, we ignore them, and it's often for premature optimizations
> prevent window alerts for n+1 queries from bullet in dev

- app/controllers/agents/invitations_controller.rb
- spec/controllers/agents/invitations_controller_spec.rb
https://trello.com/c/ZCoXalEx/902-agent-erreur-invitation-email-diff%C3%A9rence-de-capitalisation
Sur la review app pour verifier que ca marche vous pouvez essayer de vous connecter en tant que martine@demo.rdv-solidarites.fr et inviter MAYA@demo.rdv-solidarites.fr
> fix inviting agent with email capitalized differently

- app/views/agents/rdvs/show.html.slim
https://trello.com/c/fD1aSsjR/899-agenthistorique-des-actions-les-modifications-sur-les-notes-libres-napparaissent-pas
on filtre les attributs affichés dans l'historique de version des RDVs, les notes n'y étaient pas pour l'instant
> [agent] add RDV notes to allowed attributes in versions history

- app/controllers/agents/organisations/rdvs_controller.rb
- app/controllers/agents/stats_controller.rb
- app/views/agents/stats/index.html.slim
- config/initializers/mime_types.rb
https://trello.com/c/MjwC5deL/897-agent-extraction-stats-impossible-douvrir-le-fichier
en fait la gem ne genere que du XLS, pas du ODS https://github.com/zdavatz/spreadsheet
ca marchait sur LibreOffice car il doit pas regarder l'extension pour decider du format, mais pas sur excel
j'ai aussi supprimé le code mort et buggé de stats_controller. l'export se faisait d'abord depuis ce controlleur mais on l'a déplacé pour le mettre dans rdvs_controller pour des raisons sémantiques
> fix export format from ods to xls + remove dead code

- app/controllers/stats_controller.rb
- app/services/monthly_stats_exporter_service.rb
- app/services/rdv_exporter_service.rb
- app/services/xls_exporter.rb
- app/views/stats/_statistics.html.slim
- spec/services/monthly_stats_exporter_service_spec.rb
https://trello.com/c/Zg9300Vj/900-extraction-des-stats-publiques
Export excel du nombre de rendez-vous par mois, par service et par département depuis la page publique de statistique.
Remaniement des deux exporteur pour mutualiser une partie du code commun, basé sur le principe de composition plutôt qu'héritage.
Ça laisse une duplication sur l'initialisation, peut-être du à l'héritage de la classe `BaseService`. Ça sera pour une prochaine fois peut-être.
> exporte des stats mensuels

- app/controllers/agents/plage_ouvertures_controller.rb
- app/mailers/agents/plage_ouverture_mailer.rb
https://trello.com/c/4RIwsw9A/922-r%C3%A9parer-ics-pour-zimbra
base64 n'est pas super adapté vu que ics est un format texte mais ca semble mieux marcher
avec 8bit ou quoted-printable on a des soucis d'encodage et de compatibilité sur zimbra et-ou outlook 
⚠️ en attente de validation d'Aude ou Elodie que ca ne casse rien pour le 62
> fixing ICS for zimbra using base64 encoding instead of 8bit

- app/views/users/registrations/new.html.slim
https://trello.com/c/MDclzKuB/923-bug-usager-inscription
ce n'est pas la meilleure maniere de corriger ce souci, mais je n'ai pas réussi a faire mieux.
dans l'ideal il faudrait que le form helper re-utilise tout seul les clés i18n du modele User. 
Je me suis un peu cassé la tete mais je ne comprends pas le fonctionnement, j'ai préféré abandonner pour l'instant et le faire explicitement simplement
> [user] fix registration form labels translations explicitly

- app/webpacker/components/places-input.js
https://trello.com/c/XnqTAzbl/947-investigation-probl%C3%A8me-distance-recherche-christelle-cufay
La recherche via l'API adresse.data.gouv.fr renvoie les coordonnées sous la forme `[longitude, latitude]` et j'avais pris l'inverse 😨
> [bug][user] fix coordinates order from addresse API 🙀

- app/helpers/welcome_helper.rb
- app/views/common/_search_form.html.slim
- app/views/lieux/index.html.slim
https://trello.com/c/USRqtFtw/946-o%C3%B9-ne-pas-afficher-le-num%C3%A9ro-de-tel-sil-ny-en-a-pas-dans-le-departement
j'avais cassé le comportement en introduisant la fonction intermediaire `urgency_number_raw`, je corrige ici + je rajoute un check dans le bloc "Vous ne trouvez pas votre lieu" meme si ca ne devrait quasiment jamais se produire.
difficile de verifier sur la review app, il faudrait creer une orga et des lieux dans le bon contexte un peu relou.
ce que j'ai fait en local pour verifier c'est commenter dans le welcome helper.
> fix to never display phone instructions when it's absent

- app/views/common/_search_form.html.slim
https://trello.com/c/BwuMXjmA/951-usager-bug-retour-au-service
pour verifier cliquer sur modifier le service depuis https://demo-rdv-solidarites-pr743.osc-fr1.scalingo.io/lieux?search%5Bcity_code%5D=62040&search%5Bdepartement%5D=62&search%5Blatitude%5D=50.732087&search%5Blongitude%5D=2.318718&search%5Bmotif_name%5D=%C3%8Atre+rappel%C3%A9+par+la+PMI&search%5Bservice%5D=1&search%5Bwhere%5D=Arques%2C+62510%2C+62%2C+Pas-de-Calais%2C+Hauts-de-France
(quand je vois cette url je me dis que ca serait cool d'enlever le namespace [search] des parametres get de la search!)
> in user rdv search, fix link back to change service

- app/controllers/agents/organisations/rdvs_controller.rb
- app/controllers/agents/stats_controller.rb
- app/models/rdv.rb
- app/views/agents/stats/index.html.slim
https://trello.com/c/Jf6G6373/927-agent-limiter-les-stats-aux-rdvs-de-lagent-courant
le lien pour telecharger un export depuis la page "Vos Statistiques" renvoyait un export avec TOUS les rdvs du scope, cad ceux de toute l'orga pour les admins et les secretaires, et ceux des autres collegues du service pour les agents classiques.
> Fix RDVs export for current agent scope

- app/models/user.rb
- app/views/agents/users/_form.html.slim
hotfix : suite à la livraison de la séparation des notes et logements pour chaque organisation, la création des proches est cassée.
Ce patch vise à la réparer.
Il y avait, dans le model user, un mécanisme pour s'assurer que l'organisation d'un proche est la même que le parent. Cette vérification à lieu dans le controller, et crée un doublon dans le model.
> revoit l'affectation d'organisation coté controller uniquement

- app/webpacker/components/browser-detection.js
https://trello.com/c/iVY5eZTe/527-home-bandeau-navigateur-obsol%C3%A8te
La version Extended Support Release de firefox est la 68. C'est pas la peine de forcer les personnes à avoir une version plus récente.
> firefox ESR (extended support release) est sur la version 68

- app/views/layouts/_left_menu.html.slim
repond a 2 tickets :
1 bug https://trello.com/c/wQTXdPd0/973-agent-lien-sectorisation-dans-menu-d%C3%A9passe-en-responsive
1 oubli https://trello.com/c/S4oO0Vrh/958-agent-d%C3%A9placer-le-lien-sectorisation-dans-param%C3%A8tres
> move sectorisation link to parametres

- app/controllers/agents/plage_ouvertures_controller.rb
- app/views/agents/plage_ouvertures/_plage_ouverture.html.slim
- app/views/agents/plage_ouvertures/index.html.slim
https://trello.com/c/etIgH5un/957-agent-plages-douverture-permettre-la-cr%C3%A9ation-successive-de-plages-douvertures-pour-une-m%C3%AAme-activit%C3%A9-sans-r%C3%A9currence-de-date
ajout d'un bouton dupliquer a coté des plages d'ouverture.
ouvre le formulaire de creation avec les motifs, la description et le lieu preremplis.
> [agent] add button to duplicate plage ouvertures

- app/controllers/users/passwords_controller.rb
- app/models/user.rb
- app/views/users/registrations/new.html.slim
- config/locales/fr.yml
- config/routes.rb
- spec/services/import_zone_rows_service_spec.rb
https://trello.com/c/6dNrculW/943-usagerinscription-ajouter-lien-mot-de-passe-oubli%C3%A9-lorsque-lemail-est-d%C3%A9j%C3%A0-utilis%C3%A9
J'ai aussi fait en sorte que lorsqu'on clique sur mot de passe oublié ca transmette l'email automatiquement.
> [user] add forgot password link when registering with used email

- app/views/agents/departements/zone_imports/new.html.slim
https://trello.com/c/0g389RKW/976-agentsectorisation-rendre-plus-visible-le-fait-que-cest-un-code-insee-et-pas-un-code-postal
> [agent] add instruction to use INSEE code in sectorisation

- app/webpacker/components/calendar.js
https://trello.com/c/Fpw2RY9R/979-agentcalendrier-lorsquun-onglet-est-laiss%C3%A9-ouvert-longtemps-il-y-a-plein-dalertes-lorsquon-revient
`visibilitychange` seems decently supported 
https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event
https://caniuse.com/#search=visibilitychange
to test : 
- open a calendar page, open the network tab
- clear network requests and switch to another tab
- wait 1m +
- go back to the other tab
- check that there was no request in between BUT that requests re-start
repeat test but staying on the same tab but leaving the agenda (eg by navigating to absences with turbolinks)
> [agent] clear agenda refetch interval on browser tab blur

- app/models/user.rb
- app/services/duplicate_user_finder_service.rb
- db/migrate/20200702132842_add_email_original_to_users.rb
- db/schema.rb
- spec/models/user_spec.rb
- spec/services/duplicate_user_finder_service_spec.rb
https://trello.com/c/MbRWv7GQ/972-impossible-de-recr%C3%A9er-un-usager-supprim%C3%A9
I fixed 2 different issues preventing re-creating a user that was soft-deleted :
- scope to active users in DuplicateUserFinder => pretty obvious
- bypass users.email unicity => more tricky. The email unicity constraint is at the db level so we cannot just change the scope of the validation (and maybe it's best like that). What I did was that now soft deleted users have a dummy email like `user_34@deleted.rdv-solidarites.fr` and their original email is backuped in `users.email_original`. this allows re-creating a new user with the old email.
Also, I couldn't refrain from a little refacto of the `user#soft_delete` method please indulge me.
> [agent] do not consider soft deleted users in uniqueness checks

- app/controllers/users/rdv_wizard_steps_controller.rb
- app/controllers/users/users_controller.rb
- app/views/users/users/_form.html.slim
https://trello.com/c/PpjN4DMc/984-usager-etape-v%C3%A9rifier-mes-informations-le-champ-logement-appara%C3%AEt-2-fois
Du coté Usager, les informations ne sont pas contextualisées à une organisation. Nous affichons donc tout les éléments de chaque profile.
L'ajout consiste à afficher aussi le nom de l'organisation lié au profile pour rendre visible qu'il y a deux organisations qui ont deux informations.
Normalement, ces informations devraient être les même. Peut-être que nous pourrions, par la suite, rendre visible un soucis d'informations décallé entre organisation pour chaque usager. Mais c'est un autre ticket à faire.
> affiche les profiles usager pour chaque organisation

- spec/spec_helper.rb
tiny change that was annoying me when using `save_and_open_screenshot` : the default size is a tiny mobile view and our site is not that responsive especially for agents
before:
after:
> increase viewport size in specs to regular desktop size

- app/webpacker/components/datetimepicker.js
cf https://trello.com/c/vXYTvvDg/1009-creation-de-plage-ouverture-jour-de-fin-pas-pris-en-compte
the bug was introduced when we started using the jQuery datetimepicker instead of the native HTML5 date input. The problem was that the `change` event was not triggered anymore, and thus the associated stimulus action to refresh the `recurrence` input was not being refreshed correctly. 
I've added a somewhat hacky fix to always trigger this change event for such inputs. We may do better when we remove stimulus
> trigger change event for date inputs to fix plage ouverture recurrence creation bug

- app/controllers/agents/users_controller.rb
- app/views/agents/users/compare.html.slim
- app/views/layouts/modal.html.slim
https://trello.com/c/oe7D3fSt/982-agenttunnel-de-prise-de-rdv-pouvoir-cr%C3%A9er-un-usager-existant-dans-une-autre-orga
> [agent] compare existing users from rdv creation flow

- app/mailers/agents/plage_ouverture_mailer.rb
https://trello.com/c/ZuBCaH2U/1014-envoyer-ics-plage-ouverture-depuis-une-autre-adresse
> change sender mail for plage ouverture ICS

- README.md
- app/controllers/admin/mailer_previews_controller.rb
- app/controllers/health_checks_controller.rb
- app/jobs/send_rdv_events_stats_mail_job.rb
- app/mailers/admins/system_mailer.rb
- app/models/file_attente.rb
- app/models/rdv.rb
- app/models/rdv_event.rb
- app/services/notifications/rdv/base_service_concern.rb
- app/services/notifications/rdv/rdv_cancelled_by_agent_service.rb
- app/services/notifications/rdv/rdv_created_service.rb
- app/services/notifications/rdv/rdv_upcoming_reminder_service.rb
- app/services/notifications/rdv/rdv_updated_service.rb
- app/views/mailers/admins/system_mailer/rdv_events_stats.html.slim
- config/routes.rb
- db/migrate/20200730084038_create_rdv_events.rb
- db/schema.rb
- lib/tasks/rdv_events_stats_mail.rake
- spec/mailers/previews/admins/system_mailer_preview.rb
- spec/models/file_attente_spec.rb
- spec/models/rdv_event_spec.rb
- spec/services/notifications/rdv/rdv_cancelled_by_agent_service_spec.rb
- spec/services/notifications/rdv/rdv_created_service_spec.rb
- spec/services/notifications/rdv/rdv_upcoming_reminder_service_spec.rb
https://trello.com/c/FKue0DWU/971-monitor-cron-jobs-reminders-file-attente
- new table `RdvEvents` : `rdv_id event_type event_name`
- store event on each mail + sms notifs
- new public endpoint to expose RdvEvent today stats (to setup an external monitoring alert)
- daily mail sent with RdvEvents stats for manual monitoring in the first days/weeks
> monitor CRON jobs running : RDV reminders and file attente notifs

- app/views/layouts/admin/application.html.erb
- app/webpacker/administrate/index.js
- app/webpacker/stylesheets/administrate/application.scss
- package.json
- yarn.lock
https://trello.com/c/2vDHjGJ5/1024-remove-selectize-js-package-dependency
Les multi-selects deviennent natifs:
> remove selectize JS package dependency used only in admin and deprecated

- spec/factories/agent.rb
- spec/factories/rdv.rb
- spec/factories/user.rb
- spec/models/creneau_spec.rb
- spec/models/lieu_spec.rb
- spec/models/plage_ouverture_spec.rb
- spec/models/rdv_spec.rb
I only dealt with past dates because for the ones in the future it's not as easy (we don't want to have to come back and postpone the dates every so often)
> refactor specs to use more stable determined past dates to avoid flakiness

- app/controllers/agents/users_controller.rb
- app/helpers/rdvs_helper.rb
- app/helpers/users_helper.rb
- app/jobs/reminder_job.rb
- app/models/creneau.rb
- app/models/file_attente.rb
- app/models/rdv.rb
- app/models/user.rb
- app/services/creneaux_builder_service.rb
- app/views/agents/rdvs/_rdv.html.slim
- app/views/agents/users/show.html.slim
- config/locales/users.fr.yml
- spec/mailers/previews/agents/rdv_mailer_preview.rb
- spec/mailers/previews/users/rdv_mailer_preview.rb
- spec/models/rdv_spec.rb
- spec/models/user_spec.rb
https://trello.com/c/aUoAmzuL/986-usersoftdelete-devrait-soccuper-des-rdvs
alternative version for #815
there was actually already a protection to avoid deleting users with RDVs but it was broken (cf commit 5) and incomplete (only dealt with future RDVs)
ℹ️ this PR should be read commit by commit 
remove freeze time and complicated dependencies
the `active` scope means 'not deleted' in most models except `FileAttente` and
`Rdv` where it has a different meaning. This commit changes these 2 scopes names.
`family` feels bad: I don't know what kind of objects it will return, and it's
unclear what it's going to include.
preliminary iso-refactor
The current implementation is half broken: it will only check for RDVs with 
strictly rdv.users == user.family. It will not match RDVs where only one …
> Improve users soft deletion behaviour with RDVs

- app/controllers/agents/merge_users_controller.rb
- app/form_models/merge_users_form.rb
- app/models/agent.rb
- app/models/file_attente.rb
- app/services/merge_users_service.rb
- app/views/agents/merge_users/_user_agents.html.slim
- app/views/agents/merge_users/_user_notes.html.slim
- app/views/agents/merge_users/_user_rdvs.html.slim
- app/views/agents/merge_users/_user_relatives.html.slim
- app/views/agents/merge_users/_user_selection.html.slim
- app/views/agents/merge_users/new.html.slim
- app/views/layouts/_left_menu.html.slim
- app/webpacker/components/merge-users-form.js
- app/webpacker/packs/application_agent.js
- app/webpacker/stylesheets/components/_forms.scss
- config/routes.rb
- spec/factories/user_profile.rb
- spec/features/agents/agent_can_see_users_rdv_spec.rb
- spec/features/agents/relatives/agent_can_create_relative_spec.rb
- spec/features/agents/relatives/agent_can_delete_relative_spec.rb
- spec/features/agents/relatives/agent_can_update_relative_spec.rb
- spec/features/agents/users/agent_can_create_user_spec.rb
- spec/features/agents/users/agent_can_delete_user_spec.rb
- spec/features/agents/users/agent_can_merge_users_spec.rb
- spec/features/agents/users/agent_can_update_user_spec.rb
- spec/services/merge_users_service_spec.rb
https://trello.com/c/Yv0CMWtJ/942-agent-doublon-fusion-des-fiches-usagers
ℹ️ followup to #829 , rebased on master
This PR only includes the merge users interface and service, not the duplicate users list suggestion. This last part may come as a later separate PR.
Features:
- lets you pick 2 active users (relative or responsible or mixed)
- when there are conflicting values for attributes, lets you pick which one to preserve
- merges all associations of the users within the current organisation 
- automatically decides which should be the target and which should be merged into the target
> [agent] merge users interface

- app/helpers/application_helper.rb
- app/models/absence.rb
- app/models/concerns/recurrence_concern.rb
- app/webpacker/components/datetimepicker.js
https://trello.com/c/6JeDpvVn/1036-investiguer-probleme-datepicker-sur-les-absences
- remplace l'utilisation de l'option `mask` du plugin jquery de datepicker par un simple placeholder. le `mask` mettait en fait une valeur dans l'input, donc il etait envoyable tel quel alors qu'il contenait `__/__/____`. ce n'est pas le cas avec le placeholder, l'input est considéré vide.
- ameliore les absences et le RecurrenceConcern pour ne pas exploser mais donner une erreur claire lorsqu'on soumet une valeur incorrecte (ce qui ne devrait pas arriver). L'erreur est en double mais c'est mieux qu'une 500 et je n'ai pas trop envie de hacker pour empecher ca (c'est du au fait que c'est divisé en temps et date)
> [agent] fix placeholder for date format in date inputs, prevent submission of empty dates

- app/controllers/agents/users_controller.rb
- app/models/concerns/user/responsability_concern.rb
PR très discutable ! 
pendant que je bossais sur la fusion des usagers, j'ai fait des manips interdites et me suis retrouvé dans des états incohérents. Ces deux petits changements m'ont paru utiles à ce moment, mais ce sont en fait des sécurités redondantes avec ce qui existe déjà. On peut considérer ça comme du code "en trop", ou des sécurités utiles, je ne suis pas hyper sûr.
1. filtrer sur les usagers `active` (càd pas soft deleted) dans les listes d'usagers coté agent. c'est deja fait indirectement via le filtre du Policy Scope des users qui filtre les usagers appartenant a l'orga courante. ca ne devrait pas se produire qu'un usager soit soft deleted mais continue a appartenir a une orga, donc c'est redondant mais quand meme plus securisant
2. validation sur les users que …
> [agent] fix active users scope in users index

- package.json
- yarn.lock
Le robot de surveillance à suggérer la mise à jour d'un paquet js : serialize-javascript (https://github.com/betagouv/rdv-solidarites.fr/pull/839).
En regardant un peu ce que faisait cette mise à jour et ce paquet, j'ai l'impression que nous ne nous en servons pas.
```bash
grep -ri "serialize" app/webpacker/
```
ne renvoie rien.
> supprimer une lib inutilisé

- app/views/agents/users/_responsible_form_fields.html.slim
- app/webpacker/components/agent-user-form.js
- spec/features/agents/users/agent_can_merge_users_spec.rb
En plus de clarifier le formularie usager, cette PR permet d'avoir des tests qui passent sur la PR https://github.com/betagouv/rdv-solidarites.fr/pull/832.
De plus 
- je pense que la règle 12.14 du RGAA est moyennement respecté (https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-12-14);
- je me dit qu'en plus, ça fait beaucoup de javascript pour un gain UX qui me semble assez discutable;
- le `elsif user.pending_reconfirmation?`, vis à vis du message de  n'est jamais appelé (je n'ai pas reproduit le cas où ça s'affiche;
Moins de code, moins de bug.
> Affiche la proposition invitation

- app/views/agents/rdvs/show.html.slim
découverte d'un caractère `>` dans la fiche RDV. C'est une erreur. Je vais remettre un `&nbsp;` à la place puisque ça ne semble pas être faisable autrement.
> espace-avec-un-blanc

- scripts/full_orga_sql_dump.sh
https://trello.com/c/NVvX8hOR/1030-dump-complet-des-donn%C3%A9es-par-organisation
new version of #822 , pure bash script without gem dependency and ruby script
`./scripts/full_orga_sql_dump.sh 83 postgresql://localhost/rdv-sol-prod-dump` 
- outputs one CSV file per table
- outputs one global `full_dump_organisation_XX.sql` file that contains both the schema and data.
in order to do it, the script creates a temporary postgres db on the local machine, but it's dropped before the end of the script
@guillett this is not my most beautiful looking code , sorry. I'm far from being a bash expert 😨 so it's a lot of hacks.
there are a few tricky workarounds to deal with weird cases in the prod db where there's some incoherent data, and also some twists so that foreign keys constraints are respected …
> bash script to export all data from one organisation

- app/helpers/application_helper.rb
- app/views/admin/organisations/index.html.slim
- app/views/layouts/registration.html.slim
- app/webpacker/stylesheets/structure/_authentication.scss
https://trello.com/c/KXykCVie/1059-agent-am%C3%A9liorer-le-message-affich%C3%A9-sur-la-gauche-des-pages-listes-des-organisations-et-editer-mon-compte
remplace PR #857
- repare detection users ou agents sur la liste des orgas pour le message de gauche
- change message generique par un menu pour les agents connectés (visible sur liste des orgas et sur editer compte donc)
- ajoute max height 100vh
ce n'est pas très beau mais ca me parait quand meme mieux que l'existant
> improve registration layout for connected agents

- app/views/layouts/_degraded_service.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/application_agent.html.slim
https://trello.com/c/s77YlZQG/1060-banni%C3%A8re-pour-service-d%C3%A9grad%C3%A9
messages optionnels indépendants pour agents et usagers définis par des variables d'env
testable sur la review app en togglant les vars d'env sur https://my.osc-fr1.scalingo.com/apps/demo-rdv-solidarites-pr860/variables
`DEGRADED_SERVICE_MESSAGE_AGENTS`
and
`DEGRADED_SERVICE_MESSAGE_USERS`
> add optional banner for degraded service cases

- app/blueprints/rdv_blueprint.rb
- app/controllers/admin/rdv_wizard_steps_controller.rb
- app/controllers/admin/rdvs_controller.rb
- app/controllers/users/rdv_wizard_steps_controller.rb
- app/controllers/users/rdvs_controller.rb
- app/models/rdv.rb
- app/views/admin/rdv_wizard_steps/step2.html.slim
- app/views/admin/rdv_wizard_steps/step3.html.slim
- app/views/admin/rdvs/_form.html.slim
- app/views/admin/rdvs/_rdv_details.html.slim
- app/views/admin/rdvs/show.html.slim
- config/locales/models/rdv.fr.yml
- db/migrate/20200903072742_restore_rdv_context.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/rdv.rb
- spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
https://trello.com/c/bATaTRzd/1046-contexte-du-rendez-vous
- j'ai pris l'initative de modifier l'affichage et l'édition du contexte pour être plus proche du Motif 
- j'ai rajouté le `context` dans le blueprint pour qu'il soit envoyé dans les webhooks outgoing. @guillett est-ce que ca te parait logique ? faut-il prévenir les utilisateurs des webhooks?
- j'ai lancé la migration sur un dump de la prod : `user_note_destroyed=>3509, :context_cleaned=>42` et ca a duré ~1m
> reintroduce RDVs old_notes as context

- app/views/admin/rdvs/_rdvs_list.html.slim
https://trello.com/c/PMmIQ65G/1050-liste-des-rdv-de-la-journ%C3%A9e-tri%C3%A9s-par-ordre-chronologique
Afin d'avoir la liste des rendez-vous de la journée dans le même ordre que le déroulement de la journée, la les des rdvs est trié par ordre chronologique.
> Tri les rdv par ordre chronologique

- app/controllers/admin/rdvs_controller.rb
- spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
- spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
https://trello.com/c/lOBN6DfA/1047-sassurer-que-le-rendez-vous-est-bien-enregistr%C3%A9-dans-lagenda
Maintenant qu'une zone de texte est disponible dans le tunnel de prise de rendez-vous pour préciser l'objet, nous pouvons remettre la redirection vers l'agenda en fin de tunnel.
Ça rassure les agents de voir le rendez-vous positionné.
> Redirige agent vers agenda après la prise d'un RDV

- app/controllers/stats_controller.rb
- app/models/stat.rb
- app/views/stats/index.html.slim
https://trello.com/c/EXxWdesz/1052-ajouter-un-graphique-sur-la-page-stats-avec-les-statuts-des-rdvs
slightly tricky because we're using chartkick + chart.js which doesn't let us use `stacked: :relative` option [cf doc](https://github.com/ankane/chartkick.js?files=1#options), so I used some ruby ninja-fu but it's not incredibly readable 🤷 
thanks for the very precise specs @guillett  👍 I decided to filter out `waiting` rdvs because I think it only makes it harder to read without giving any additional infos as it's a very transient state so they'll ever be a maximum of a few rdvs in that state at a time
> new chart for rdvs by statuses on public stats pages

- app/controllers/admin/creneaux/agent_searches_controller.rb
- app/controllers/admin/lieux_controller.rb
- app/controllers/admin/motifs_controller.rb
- app/models/creneau/agent_search.rb
- app/models/lieu.rb
- app/models/motif.rb
- app/policies/agent/motif_policy.rb
- app/views/admin/plage_ouvertures/_form.html.slim
- app/views/admin/rdv_wizard_steps/step3.html.slim
- config/brakeman.ignore
https://trello.com/c/qYU7hDhW/516-agents-lieux-et-motifs-trop-longue-dans-les-listes-de-recherche-de-cr%C3%A9neaux
- j'en ai profité pour corriger un bug de permissions : on ne filtrait pas du tout les agents ni les motifs proposés dans l'interface trouver un créneau. Un agent non admin et non secretaire ne devrait voir que les agents de son propre service. ce n'était pas le cas avant.
- j'ai essayé d'harmoniser les tris de ces trois ressources Agent Lieux et Motifs sur l'ensembe de l'admin
- j'ai utilisé la fonction pg `unaccent` qui permet de faire des comparaisons en ignorant les accents. utile pour le motif 'Être rappelé par la PMI'
- je n'ai rien fait pour aider à la découverte de l'autocomplete dans les champs sur la vue trouver un créneau car je n'ai pas trop d'idée 
- j'ai tenté …
> order agents, lieux and motifs in trouver un creneau interface

- app/helpers/users_helper.rb
- app/views/admin/rdv_wizard_steps/step3.html.slim
- app/views/admin/rdvs/_rdv_details.html.slim
- app/views/admin/rdvs/show.html.slim
- db/seeds.rb
https://trello.com/c/oz2KGEWU/1065-afficher-linfo-du-responsable-proche-sur-la-fiche-rdv
- en passant j'ai corrigé le tri pour qu'il soit sur le nom de famille et pas le prenom
- dans le code j'ai découpé en deux helpers, un utilisé coté admin et un utilisé coté users. jusqu'ici il y avait un seul helper qui testait la présence de `current_agent` pour distinguer
cf https://demo-rdv-solidarites-pr873.osc-fr1.scalingo.io/admin/organisations/1/rdvs/2
> display user relative tag in rdvs#show and rdvs lists

- app/views/admin/users/_responsible_information.html.slim
https://trello.com/c/DsiOqZ2d/1069-repositionner-message-dattente-confirmation-mail
cf https://demo-rdv-solidarites-pr874.osc-fr1.scalingo.io/admin/organisations/1/users/1
> reposition email confirmation pending message in admin/users#show

- Makefile
Pas de carte Trello.
J'ai découvert que nous avons accès à la gem [Brakeman](https://brakemanscanner.org/) un outil de scan de sécurité.
Je ne sais pas encore m'en servir, mais j'aimerais qu'il soit exécuté le plus souvent possible. Je l'ajoute donc dans le make test.
> ajoute brakemane au make test

- app/services/creneaux_builder_for_date_service.rb
- app/services/creneaux_builder_service.rb
J'ai simplement déplacé le service `CreneauxBuilderForDate` dans un fichier à part et renommé en `CreneauxBuilderForDateService` pour rester cohérent avec les autres Services.
Ça devrait tempérer les erreurs `superclass mismatch for class CreneauxBuilderForDate` que l'on a de manière aléatoire en développement, le live reloading n'a pas l'air d'apprécier d'avoir deux classes dans un seul fichier. C'est plus rails-y aussi.
> isolate CreneauxBuilderForDateService into separate file

- app/controllers/lieux_controller.rb
https://trello.com/c/P07xCD4Q/1081-corriger-bug-pendant-recherche-usager-quand-un-motif-a-disparu-pour-le-lieu-courant
https://sentry.io/organizations/rdv-solidarites/issues/1756911462/?environment=production&project=1811205&query=is%3Aunresolved
testable sur la review app via ce lien : 
https://demo-rdv-solidarites-pr878.osc-fr1.scalingo.io/lieux/5?date=2020-09-14+11%3A00%3A00+%2B0200&search%5Bcity_code%5D=75056&search%5Bdepartement%5D=75&search%5Blatitude%5D=48.845&search%5Blongitude%5D=2.3752&search%5Bmotif_name%5D=Consultation+pr%C3%A9natale&search%5Bservice%5D=1&search%5Bwhere%5D=Paris%2C+75001%2C+75%2C+Paris%2C+%C3%8Ele-de-France
(j'ai accédé a cette recherche puis j'ai supprimé toutes les plages d'ouvertures de l'orga)
> handle error when user searches for a lieu that doesn't have associated motifs

- app/controllers/admin/absences_controller.rb
- app/views/admin/absences/_absence.html.slim
- app/views/admin/absences/_form.html.slim
- app/views/admin/absences/edit.html.slim
- app/views/admin/absences/index.html.slim
- app/views/admin/absences/new.html.slim
- app/views/admin/plage_ouvertures/edit.html.slim
- app/views/admin/plage_ouvertures/index.html.slim
- app/views/admin/plage_ouvertures/new.html.slim
- spec/controllers/admin/absences_controller_spec.rb
- spec/features/agents/agent_can_crud_absences_spec.rb
- spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
https://trello.com/c/gCzhgs3J/1070-pr%C3%A9ciser-agent-cible-dans-les-formulaires-de-plage-douverture-et-dabsences
> better agent context visibility in admin/absences and admin/plage_ouvertures + remove right bar from absences

- app/views/common/_session_form.html.slim
https://trello.com/c/wgO4USIk/1078-rendre-mot-de-passe-oubli%C3%A9-plus-visible
aussi visible sur le formulaire agents
qu'en penses-tu @yaf ?
cf https://demo-rdv-solidarites-pr885.osc-fr1.scalingo.io/users/sign_in
> improve forgotten password visibility for users signin

- app/models/motif.rb
- spec/models/motif_spec.rb
https://trello.com/c/rMGykJTv/1071-tous-les-motifs-de-lorganisation-pour-un-admin
Élargir la liste des motifs quand on est sur la prise d'un rendez-vous par une personne ayant les droit administrateur (et donc une visibilité sur tout les motifs).
> Autorise tous les motifs pour l'admin

- app/controllers/agent_departement_auth_controller.rb
https://trello.com/c/4pdDmnK7/1083-r%C3%A9parer-authentification-partie-sectorisation
broken in https://github.com/betagouv/rdv-solidarites.fr/commit/d087e7a1e73c01a53e4c3857b8ac145ce7196522
it's surprising no tests failed but that part is under-tested. it may be acceptable because sectorisation is almost unused
> fix pundit authentication in departement level controllers

- app/controllers/admin/users_controller.rb
- app/models/user.rb
- app/views/admin/users/_responsible_form_fields.html.slim
- spec/controllers/admin/users_controller_spec.rb
https://trello.com/c/KDZt9wA2/1093-reparer-la-case-%C3%A0-cocher-envoyer-une-invitation-sur-la-fiche-usager
J'ai déplacé l'invitation dans le controller. Ça me semble plus approprié. Nous utilisons devise pour faire le boulot, pas la peine de surcharger nos modèles en plus.
> invite l'usager depuis le controller

- yarn.lock
should fix https://github.com/betagouv/rdv-solidarites.fr/network/alert/yarn.lock/node-forge/open
changement qui impacte uniquement le dev. @yaf tu pourras tester que ca ne perturbe pas ton environnement local sur linux avant d'approuver ? ca ne change rien sur mac os a priori.
> bump webpack-dev-server dev dependency because of security alert

- app/controllers/admin/creneaux/agent_searches_controller.rb
- app/controllers/admin/rdv_wizard_steps_controller.rb
- app/form_models/agent_creneaux_search_form.rb
- app/form_models/agent_rdv_wizard.rb
- app/models/service.rb
- app/views/admin/creneaux/agent_searches/index.html.slim
- app/views/admin/rdv_wizard_steps/step1.html.slim
- app/views/admin/rdv_wizard_steps/step2.html.slim
- app/webpacker/components/service-filter-for-motifs-selects.js
- app/webpacker/packs/application_agent.js
- app/webpacker/stylesheets/components/_select2.scss
https://trello.com/c/dQzWcy1m/597-ajouter-un-filtre-par-service-dans-la-vue-trouver-un-cr%C3%A9neau
J'ai envisagé trois solutions différentes : 
1. a chaque changement de service, faire une requete AJAX JSON sur `/motifs?service_id=x` et rafraichir la liste des options dispos dans le select du motif (comme le `populate-libelle.js` existant) 
2. a chaque changement de service, rafraichir la page automatiquement avec le parametre get `service_id=x` et peupler le select de motifs avec la liste filtrée dans la vue directement
3. a chaque changement de service, filtrer la liste des options dispos dans le select des motifs purement en JS - sans requête AJAX
J'ai fini par choisir **3** pour plusieurs raisons : 
- La requête AJAX est superflue et offre une moins bonne UX (plus lente + plus …
> new service filter for motifs in admin/agent_searches#index and admin/rdv_wizard#step1

- app/views/devise/passwords/edit.html.slim
- spec/features/users/user_can_search_rdv_spec.rb
- spec/features/users/user_signs_up_and_signs_in_spec.rb
https://trello.com/c/VoV38htD/1092-ajouter-oeil-pour-visualiser-mot-de-passe-sur-la-page-de-reset-password
> allow toggling password visibility on password reset page

- app/controllers/users/registrations_controller.rb
- app/views/layouts/user_registration.html.slim
- app/views/users/passwords/edit.html.slim
- app/views/users/passwords/new.html.slim
- app/views/users/registrations/edit.html.slim
- app/views/users/registrations/new.html.slim
- app/views/users/registrations/pending.html.slim
- app/views/users/sessions/new.html.slim
- app/webpacker/stylesheets/structure/_general.scss
https://trello.com/c/l3DQkHUm/1112-am%C3%A9liorations-ui-dans-nouveau-layout-userregistration
harmonisation avec le tunnel de prise de RDV : 
- titre et flash descendus du header (fond bleu) dans le corps (fond blanc)
- colonne md-6 réduite et centrée plutôt que largeur complète car le contenu est court 
Correction : 
- sur la page editer les infos de mon compte (`user_registrations#edit`)  il ne faut pas utiliser le nouveau layout `user_registration` mais plutot le layout normal `application` qui affiche l'info de connexion de l'usager dans le header.
> UI improvements in user_registration layout

- app/views/admin/users/index.html.slim
- app/views/layouts/_left_menu.html.slim
- spec/features/agents/agent_can_see_users_rdv_spec.rb
- spec/features/agents/relatives/agent_can_create_relative_spec.rb
- spec/features/agents/relatives/agent_can_delete_relative_spec.rb
- spec/features/agents/relatives/agent_can_update_relative_spec.rb
- spec/features/agents/users/agent_can_create_user_spec.rb
- spec/features/agents/users/agent_can_delete_user_spec.rb
- spec/features/agents/users/agent_can_merge_users_spec.rb
- spec/features/agents/users/agent_can_update_user_spec.rb
https://trello.com/c/jpQlZ7pV/1106-modifier-menu-usager
Pour simplifier la navigation dans l'application, nous avons déplacé l'entrée de menu « fusionner des fiches usagers » dans la page qui liste les usagers.
Ça nous permet de placer l'accès aux usagers en un click dans le menu de gauche.
> Reorganisation du menu Usager

- app/jobs/webhook_job.rb
- Lien vers Trello Sentry
https://trello.com/c/sgoKsOHT/1119-remonter-les-erreurs-en-cas-de-probl%C3%A8mes-dans-les-notifications
- Des requêtes en direction du SI du Pas de Calais sont en échec. Aujourd'hui nous n'avons pas de visibilité là dessus. Avec ce dev, les notifications ayant échouées, ie celle dont la requête HTTP ne retournant pas un statut sans erreur, seront en erreur dans les _delayed_jobs_ avec la réponse HTTP reçue pour faciliter la résolution du problème.
Dans le cas du Pas de Calais, les requêtes en erreur renvoyaient précédemment un code 200 (ie pas d'erreur). Aujourd'hui, nous recevons une 403 mais celui est pour le moment ignoré.
Je suis preneur de [reformulation de l'erreur remontée](https://github.com/betagouv/rdv-solidarites.fr/compare/feature/clean-webhook-failure …
> Ensure HTTP errors in web hook logic are reported

- app/jobs/webhook_job.rb
followup to #913 @guillett 
we need to fix sentry integration weird encoding pb
Bogus response payload:
> OutgoingWebhookError (Webhook failed with status code 500 and body {"Signature":true,"Erreur":"Une exception a été levée par l'initialiseur de type pour 'Cd62.Fwk.Fondamentaux.Ldap.Dal.ActiveDirectory.Impl.Helpers'."})
> Ensure HTTP errors in web hook logic are reported 

- app/views/common/_footer.html.slim
- app/views/layouts/mailer.html.slim
- app/views/layouts/registration.html.slim
C'est quelque chose par défaut dans un projet RoR je crois. Cela n'a pas de sens dans notre contexte.
https://trello.com/c/uLf2AKId/1122-supprimer-les-copyrights-de-lapplication
> Supprime le symbole Copyright de notre application

- app/models/plage_ouverture.rb
- app/services/creneaux_builder_service.rb
- app/services/search_creneaux_for_agents_service.rb
- app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
- spec/models/plage_ouverture_spec.rb
- spec/services/creneaux_builder_service_spec.rb
https://trello.com/c/rKf95VMz/1121-trouver-un-cr%C3%A9neau-affiche-toutes-les-dispos-dun-m%C3%AAme-motif-par-t%C3%A9l-%C3%A0-domicile-et-sur-place
Le problème vient du fait qu'on utilise le meme service pour la recherche coté usager (seulement sur base du nom du motif) et coté agent (ou le filtre distingue les motifs par types : sur place, a domicile, par tel).
testable sur la review app avec le motif "**Suivi Après Naissance**" : 
- Martine a une plage d'ouverture les lundis pour le motif **Sur place**
- Martine a une plage d'ouverture les mardis pour le motif **Par téléphone**
- Marco a une plage d'ouverture les mercredis pour le motif **Sur place**
https://demo-rdv-solidarites-pr918.osc-secnum-fr1.scalingo.io/admin/organisations/1/agent_searches?service_id=1&motif_id=15&from_date=07%2F1 …
> in agent_searches, filter on motifs.location_type

- app/helpers/agents_helper.rb
- app/views/admin/rdv_wizard_steps/step1.html.slim
- app/views/admin/rdvs/show.html.slim
https://trello.com/c/3cQqvxLA/422-copier-un-rdv-et-son-contexte
simple lien qui renvoie au wizard avec les valeurs pré remplies via les params get.
Il manquait quelques champs cachés dans la step1 car on n'arrivait jamais a la step1 avec ces params pour l'instant.
> add duplicate link on admin/rdvs#show to the wizard prefilled

- app/controllers/admin/rdvs_controller.rb
- app/controllers/users/rdvs_controller.rb
- app/models/rdv.rb
- app/services/cancel_rdv_by_agent_service.rb
- app/views/admin/rdvs/show.html.slim
- config/routes.rb
- spec/controllers/admin/rdvs_controller_spec.rb
- spec/models/rdv_spec.rb
https://trello.com/c/IvGqFbiQ/1118-lib%C3%A9rer-le-cr%C3%A9neau-quand-on-passe-au-statut-absent-excus%C3%A9-sans-annuler
Le changement de status pour une « absence excusée » ne faisait pas le boulot nécessaire d'annulation... Cette PR vise à faire ce qu'il faut.
> annule le rdv en changeant de status

- app/controllers/lieux_controller.rb
- app/controllers/users/creneaux_controller.rb
- app/controllers/users/rdv_wizard_steps_controller.rb
- app/controllers/users/rdvs_controller.rb
- app/form_models/user_rdv_wizard.rb
- app/models/creneau.rb
- app/models/lieu.rb
- app/service_models/concerns/users/creneaux_search_concern.rb
- app/service_models/users/creneau_search.rb
- app/service_models/users/creneaux_search.rb
- app/services/creneaux_builder_for_date_service.rb
- spec/controllers/lieux_controller_spec.rb
- spec/controllers/users/creneaux_controller_spec.rb
- spec/controllers/users/rdv_wizard_steps_controller_spec.rb
- spec/controllers/users/rdvs_controller_spec.rb
- spec/form_models/user_rdv_wizard_spec.rb
- spec/models/creneau_spec.rb
- spec/models/lieu_spec.rb
- spec/service_models/users/creneau_search_spec.rb
- spec/service_models/users/creneaux_search_spec.rb
https://trello.com/c/6ysKq39q/1130-r%C3%A9parer-coh%C3%A9rence-des-filtres-appliqu%C3%A9s-sur-les-cr%C3%A9neaux-propos%C3%A9s-cot%C3%A9-usagers-rdv-suivis-locationtype
- extract `Users::CreneauxSearch` object from `LieuxController` : not 100% necessary here, but it clears the way
- introduce a very close singular `Users::CreneauSearch` to build a single `Crenau` instead of calling directly `Creneau.new` and checking `creneau.available?`. This allows us to remove the some code in the `Creneau` model, that was duplicated with the code in `CreneauxBuilderFordateService`. 
- lieux controller specs refactored to limit testing surface : the used services are stubbed instead of being actually called.
> fix filtering available creneaux in user RDV tunnel

- app/webpacker/components/calendar.js
https://trello.com/c/9pHoLhD0/1132-calendrier-cass%C3%A9-quand-affichage-avec-un-fuseau-horaire-non-francais
> force timezone to Paris in FullCalendar config

- app/webpacker/components/calendar.js
https://trello.com/c/I9NWrip0/1111-bug-probl%C3%A8me-daffichage-lorsque-les-rdvs-sencha%C3%AEnent
simply removing 15px height for now
> remove agent calendar events min height 15px to fix overlap

- config/initializers/content_security_policy.rb
suite au retrait des google fonts, suppression de google et gstatic de nos listes de CSP
> remove content security policies for google fonts

- app/controllers/static_pages_controller.rb
- app/views/common/_footer.html.slim
- app/views/static_pages/contact.html.slim
- config/routes.rb
https://trello.com/c/o9c4bcfq/1142-afficher-une-page-contact-avec-les-num%C3%A9ro-de-tel-des-d%C3%A9partement
Pour commencer, remplacement de l'adresse email dans le footer par une page contact qui reprends simplement les numéros de téléphone des départements qui nous l'ont donnée + l'adresse email de l'équipe.
> ajoute une page contact

- app/controllers/admin/invitations_controller.rb
https://sentry.io/organizations/rdv-solidarites/issues/2018508764/?environment=production&project=1811205&referrer=alert_email
pour reproduire le bug (corrigé dans cette PR ) : inviter deux agents a la suite, sans attendre que le premier ait accepté
la gem devise_token_auth utilisee pour l'auth de l'api a ajouté plusieurs champs a agents, dont `uid` et `provider`. ces deux derniers doivent former une paire unique. pour une raison pas super claire pour moi, l'`uid` lors de l'invitation d'un nouvel agent n'etait pas setté automatiquement a la valeur de l'email. cette PR y remedie de maniere un peu brutale
> when inviting a new agent, set uid to email

- app/controllers/agents/sessions_controller.rb
- app/controllers/users/sessions_controller.rb
https://trello.com/c/jrZ94IC2/1137-corriger-bug-double-connexion-agent-et-usager
le probleme venait en partie du fait que c'etait impossible de se deconnecter lorsqu'on etait connecté aux deux en meme temps. 
Ce commit ne corrige pas le probleme a la source, mais permet de debloquer ce cas. Pour corriger la source du probleme il faudrait reussir a empecher completement devise de logger un agent et un user en meme temps, quelque soit le chemin d'entrée (sign_in, sign_up, confirmations ...). je ne sais pas comment le faire facilement
> restrict before action filter to prevent double sign in to agents/sessions#new

- app/jobs/send_transactional_sms_job.rb
- app/services/send_transactional_sms_service.rb
- app/views/admin/lieux/_form.html.slim
https://trello.com/c/zEMWzaqC/1114-envoyer-le-nom-du-lieu-en-plus-de-ladresse-dans-les-sms-et-mails-envoy%C3%A9s-aux-usagers
- j'ai légèrement modifié le code de l'envoi de SMS pour voir en local les SMS qui auraient été envoyés dans les logs
- j'ai aussi rajouté des indications dans le formulaire de création de lieu pour indiquer que le nom et l'adresse apparaîtront dans les notifs
voir les noms de lieux en production ici : https://pad.incubateur.net/8t63puPHTt2u1iFjSVOs_A#
- il y a des noms longs comme " Maison des Solidarités Départementales Annexe Onet Le Château"
- il y a quelques noms surprenants comme CPEF ou "Visite à domicile"
- il y a des noms qui répètent le nom de la ville comme "MEURCHIN - Centre Multi-accueil"
@yaf je vois plusieurs approches possibles : 
1. on tronque les …
> include lieu name in SMS messages

- app/views/layouts/application.html.slim
- app/views/layouts/user_registration.html.slim
- app/views/lieux/index.html.slim
- app/views/welcome/index.html.slim
- app/views/welcome/welcome_departement.html.slim
- app/views/welcome/welcome_service.html.slim
- app/webpacker/stylesheets/application.scss
- force la navbar a respecter la largeur max du container, ca aligne avec le reste
- enleve les paddings horizontaux sur le hero et le search form de la home et des differentes etapes de recherche, aussi pour aligner avec les limites verticales.
- diminue la font-size des titres du hero pour que ca rentre sur un iPhone 5/SE (~ a peu pres le plus petit smartphone encore pas mal utilisé)
> improve home UI navbar alignment + smaller fonts on small devices

- app/controllers/welcome_controller.rb
- app/models/motif.rb
https://trello.com/c/taHQshk8/1155-trier-la-liste-de-motifs-par-ordre-alphab%C3%A9tique-dans-la-recherche-usager
J'ai du préciser la table `motifs` dans le scope `ordered_by_name` pour éviter la confusion lors de jointure avec une table contenant également un `name`. Un peu comme ici où dans la requête, nous faisons une jointure sur le service du motif.
> tri les motifs coté usagers

- config/locales/models/motif.fr.yml
- db/migrate/20201112164609_remove_disable_notifications_for_users_from_motifs.rb
- db/schema.rb
Supprime le champs `disable_notifications_for_users` de la table `motifs` puisque devenu inutile
Est-ce qu'on attends la semaine prochaine pour passer cette migration ?
> Remove disable notifications for users from motifs 

- app/helpers/agents_helper.rb
- app/views/layouts/_left_menu.html.slim
- spec/features/agents/agent_can_see_his_stats_spec.rb
https://trello.com/c/9VJOUdJ5/1163-ramener-vos-statistiques-dans-votre-espace-de-menu
Dans la ligné des travaux sur le menu, je propos de déplacer « vos statistiques » à coté de « mes organisations » dans la zone de menu personnel
au lieu de
> ramène le vos statistique chez vous

- app/controllers/admin/agents_controller.rb
- app/controllers/admin/permissions_controller.rb
- app/controllers/agents/registrations_controller.rb
- app/models/agent.rb
- app/service_models/agent_removal.rb
- app/views/admin/agents/_agent.html.slim
- app/views/admin/permissions/edit.html.slim
- app/views/agents/registrations/edit.html.slim
- db/migrate/20201118161148_remove_deprecated_absences_and_plages_ouvertures.rb
- db/schema.rb
- spec/controllers/admin/agents_controller_spec.rb
- spec/features/agents/admin_can_configure_the_organisation_spec.rb
- spec/models/agent_spec.rb
- spec/service_models/agent_removal_spec.rb
https://trello.com/c/c728Kj9h/1168-supprimer-les-plages-douvertures-des-agents-lorsquils-sont-retir%C3%A9s-dune-organsiation
refacto préliminaire qui enlève la rightbar de la vue édition agent (en fait nommée permissions 🤷 )
Simplification du `Agent#soft_delete` qui ne fait plus que soft_delete effectivement, jamais destroy, ni remove orga. C'était vraiment perturbant comme méthode
Introduction d'un nouveau service `AgentRemoval` en charge de retirer un agent d'une orga. C'est dans ce service qu'on rajoute le fait de supprimer les plages d'ouvertures et absences associées
Ajout de messages preventifs dans les interfaces pour dire que l'operation de retrait d'une orga est irreversible et supprimera les POs et absences
Lorsqu'un agent veut supprimer son compte maintenant : 
- on l'en …
> Destroy plage ouvertures and absences when removing agent from orga

- Gemfile
- Gemfile.lock
- app/controllers/admin/plage_ouvertures_controller.rb
- app/helpers/plage_ouvertures_helper.rb
- app/models/absence.rb
- app/models/concerns/recurrence_concern.rb
- app/models/plage_ouverture.rb
- app/models/plage_ouverture/ics.rb
- app/models/recurrence/occurrence.rb
- app/policies/agent/plage_ouverture_policy.rb
- app/service_models/plage_ouverture_overlap.rb
- app/views/admin/absences/_absence.html.slim
- app/views/admin/plage_ouvertures/_form.html.slim
- app/views/admin/plage_ouvertures/_overlapping_plage_ouvertures.html.slim
- app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
- app/views/admin/plage_ouvertures/edit.html.slim
- app/views/admin/plage_ouvertures/show.html.slim
- app/views/common/_recurrence.html.slim
- app/views/layouts/_model_errors.html.slim
- app/webpacker/components/recurrence-form.js
- app/webpacker/stylesheets/components/_forms.scss
- config/locales/plage_ouvertures.yml
- config/routes.rb
- spec/controllers/admin/plage_ouvertures_controller_spec.rb
- spec/factories/plage_ouverture.rb
- spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
- spec/models/absence_spec.rb
- spec/models/concerns/recurrence_concern_spec.rb
- spec/service_models/plage_ouverture_overlap_spec.rb
https://trello.com/c/QEzwN6e0/1087-alerter-lors-de-la-cr%C3%A9ation-de-rdvs-ou-de-plages-douvertures-en-conflit-avec-dautres-plages-douvertures-potentiellement-dautres
⚠️ lire les commits un par un
⚠️ Cette PR a été sacrément longue et un peu dure à écrire 😓  elle est longue, mais relativement bien découpée, et il y a peut être la moitié de lignes de test
- renommer le `RecurrenceConcern#ends_at` actuel en `first_occurence_ends_at`. Cette méthode est en effet très perturbante actuellement car elle renvoie le ends_at de la première occurence pour les plages d'ouvertures ou absences récurrentes. On s'attend bien plus à ce qu'elle renvoie la date de fin éventuelle de la récurrence. La nouvelle méthode `ends_at` renvoie donc bien cette valeur de fin d'occurence ou nil s'il n'y a pas de fin …
> Add overlapping Plage Ouvertures warnings 

- app/helpers/rdvs_helper.rb
- app/views/common/_header_user_logged.html.slim
- app/views/users/creneaux/index.html.slim
- app/views/users/rdvs/_rdv.html.slim
- app/views/users/rdvs/index.html.slim
- spec/features/users/user_signs_up_and_signs_in_spec.rb
- spec/features/users/user_views_his_rdvs_spec.rb
https://trello.com/c/hFd6rlQO/1179-reparer-menu-haut-de-la-vue-usager
j'en profite pour 
- retirer le menu dropdown qui ne sert a rien et cassait la vue responsive pour les users
- harmoniser les items de menus en "Vos"
- ameliorer le layout des rdvs sur l'index
- réparer une faute d'orthographe sur le "passés"
> fix user topbar menu layout in users/rdvs#index

- app/blueprints/rdv_blueprint.rb
https://trello.com/c/yEE6L8rj/1180-ajouter-le-nom-du-lieu-pour-linterconnexion
encore plus simple que prévu, mais je n'ai pas ajouté de spec par contre
pour tester sur la review app https://demo-rdv-solidarites-pr978.osc-secnum-fr1.scalingo.io/ : 
- j'ai branché un webhook sur l'orga 1 vers https://webhook.site/#!/bf304f9c-5f15-49a7-b7a9-6b2ca5a90f70
- se connecter en tant que martine
- créer des RDVs de différents location_type
- vérifier : sur webhook.site : lieu est null ou bien présent pour les motifs sur place
> send lieu on RDVs webhooks

- app/controllers/admin/absences_controller.rb
- app/controllers/admin/plage_ouvertures_controller.rb
- app/controllers/admin/rdvs_controller.rb
- app/views/admin/plage_ouvertures/show.html.slim
- app/views/admin/rdvs/_rdv_status_dropdown.html.slim
- app/views/admin/rdvs/edit.html.slim
- app/views/admin/rdvs/index.json.jbuilder
- app/views/admin/rdvs/show.html.slim
- spec/controllers/admin/rdvs_controller_spec.rb
https://trello.com/c/95YCduVA/1164-perte-de-contexte-suite-%C3%A0-suppression-dun-rdv-dans-lagenda
ℹ️ lisible commit par commit
ℹ️ @yaf hésite pas à merger en mon absence, c'est assez safe
ce n'est pas parfaitement trivial de préserver le contexte de l'agent sur toutes les pages, il faut bien s'assurer de le garder partout. 
on peut arriver depuis l'agenda mais aussi depuis la liste des RDVs, ou bien les users show. Il faut donc gérer le cas où on est dans le contexte d'un agent et le contexte sans. J'ai donc passé l'agent en param get `agent_id` et il faut bien faire attention de le passer partout et le retuiliser quand on redirige, par ex apres un create. 
On peut seulement arriver depuis l'agenda (je crois), donc c'est un peu plus simple. La petite complexité réside dans le fait qu'on …
> better preserve agent context in rdvs, plage ouvertures and absences views

- app/views/common/_footer_users.html.slim
- app/views/layouts/application_agent.html.slim
https://trello.com/c/ztA8YAyx/1184-ajouter-un-lien-vers-la-politique-de-confidentialit%C3%A9
Thomas me faisait remarqué qu'il manquait la Politique de Confidentialité dans les documents que nous avions mis en ligne. Ça sera chose réparé avec cette PR.
> ajoute un lien vers la politique de confidentialité

- app/controllers/admin/motifs_controller.rb
- app/helpers/motifs_helper.rb
- app/helpers/sectors_helper.rb
- app/helpers/welcome_helper.rb
- app/models/motif.rb
- app/models/sector.rb
- app/models/sector_attribution.rb
- app/service_models/concerns/users/creneaux_search_concern.rb
- app/service_models/users/geo_search.rb
- app/views/admin/departements/sectors/show.html.slim
- app/views/admin/departements/setup_checklists/show.slim
- app/views/admin/motifs/_form.html.slim
- app/views/admin/motifs/_motif.html.slim
- app/views/admin/motifs/index.html.slim
- app/views/common/_search_form.html.slim
- app/webpacker/components/motif-form.js
- app/webpacker/stylesheets/components/_motifs.scss
- config/locales/models/motif.fr.yml
- config/locales/motifs.yml
- config/locales/sectors.yml
- db/migrate/20201123155850_add_sectorisation_level_to_motifs.rb
- db/schema.rb
- spec/controllers/lieux_controller_spec.rb
- spec/factories/motif.rb
- spec/factories/sector_attribution.rb
- spec/helpers/motifs_helper_spec.rb
- spec/service_models/users/creneaux_search_spec.rb
- spec/service_models/users/geo_search_cases_spec.rb
- spec/service_models/users/geo_search_spec.rb
Cette PR introduit un changement conceptuel assez profond de la sectorisation.
Actuellement la secto est activée ou désactivée à l'échelle d'un département via une variable d'env. Sur les départements activés, les règles d'attribution des secteurs (à l'agent ou à l'orga) s'appliquent à tous les motifs. 
Pour rappel, **un secteur =** 
- un ensemble de communes (ou de rues) 
- attribuées à 
- un ensemble d'organisations entières OU d'agents spécifiques
Dans cette PR on introduit un `sectorisation_level` au niveau des motifs qui peut avoir trois valeurs : 
- `departement` : les créneaux proposés pour ce motif seront dispos pour tout le département
- `organisation`: les créneaux proposés pour ce motif seront dispos uniquement pour les secteurs attribués à des orgas entières
- `agent` : les …
> add motifs.sectorisation_level to allow desectorisation

- app/controllers/admin/plage_ouvertures_controller.rb
- app/controllers/agent_auth_controller.rb
- app/helpers/plage_ouvertures_helper.rb
- app/views/admin/plage_ouvertures/_form.html.slim
- app/views/admin/plage_ouvertures/_overlapping_plage_ouvertures.html.slim
- app/views/admin/plage_ouvertures/show.html.slim
- app/views/layouts/_model_errors.html.slim
preliminary to https://github.com/betagouv/rdv-solidarites.fr/pull/987
- extract logic to filter plage ouvertures on departement scope from the plage_ouvertures controller to a generic view helper
- generize `overlapping_plage_ouvertures` partial so it accepts a random `model` duck-typed to respond to a `overlapping_plage_ouvertures` method
- extract the display overlapping warnings + Confirm or change values view from the specific plage ouverture form to the generic `model_errors` partial
> generize form confirm warnings and overlapping plage ouvertures display

- app/controllers/static_pages_controller.rb
- app/controllers/support_tickets_controller.rb
- app/form_models/support_ticket_form.rb
- app/helpers/application_helper.rb
- app/lib/zammad_api.rb
- app/views/layouts/application_agent.html.slim
- app/views/static_pages/contact.html.slim
- app/views/welcome/welcome_agent.html.slim
- config/routes.rb
- spec/controllers/support_tickets_controller_spec.rb
- spec/form_models/support_ticket_form_spec.rb
https://trello.com/c/L4cNwlGr/1187-mieux-qualifier-les-mails-depuis-la-page-contact
- La liste des sujets possible est : 
"Je suis usager et je n'arrive pas à annuler mon RDV",
"Je suis usager et je n'arrive pas à accéder à mon compte",
"Je suis agent et je n'arrive pas à accéder à mon compte",
"Je suis agent et j'ai une question ou je rencontre un problème",
"Je suis agent ou décideur public et j'aimerais plus d'informations sur RDV-Solidarités",
"Autre",
- J'ai hésité à utiliser le formulaire clé en mains fourni par Zammad mais il y a vraiment peu de config possible et ça rajoutait du JS pas beau. J'ai préferré faire cet effort d'intégrer l'API et avoir un formulaire qu'on gère nous même et qu'on pourra faire évoluer
- je ne remplis pas encore les bonnes infos aux bons endroits dans …
> Zammad contact form, support tickets controller form and model

- app/controllers/admin/rdvs_controller.rb
- app/controllers/users/rdvs_controller.rb
- app/mailers/users/rdv_mailer.rb
- app/models/rdv.rb
- app/service_functions/rdv_updater.rb
- app/services/notifications/rdv/rdv_cancelled_by_agent.rb
- app/services/notifications/rdv/rdv_cancelled_by_user.rb
- app/views/mailers/users/rdv_mailer/rdv_cancelled_by_agent.html.slim
- app/views/mailers/users/rdv_mailer/rdv_cancelled_by_user.html.slim
- spec/controllers/admin/rdvs_controller_spec.rb
- spec/controllers/users/rdvs_controller_spec.rb
- spec/mailers/users/rdv_mailer_spec.rb
- spec/models/rdv_spec.rb
- spec/service_functions/rdv_updater_spec.rb
- spec/services/notifications/rdv/rdv_cancelled_by_agent_spec.rb
- spec/services/notifications/rdv/rdv_cancelled_by_user_spec.rb
https://trello.com/c/YunxOY7K/1185-utilise-partout-la-m%C3%AAme-fa%C3%A7on-dannuler-un-rdv
L'usager ne passait pas par le RdvUpdater. Cette PR vise à corriger cela.
J'en ais profité pour supprimer la méthode `cancel` de la classe Rdv.
> généralise l'usager de RdvUpdater

- app/models/concerns/recurrence_concern.rb
- app/webpacker/components/recurrence-form.js
- db/migrate/20201203112249_add_starts_to_recurrences.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/absence.rb
- spec/factories/plage_ouverture.rb
- spec/jobs/update_plage_ouvertures_expirations_job_spec.rb
- spec/models/concerns/recurrence_concern_spec.rb
- spec/models/plage_ouverture/ics_spec.rb
- spec/models/plage_ouverture_spec.rb
- spec/service_models/plage_ouverture_overlap_spec.rb
- spec/services/creneaux_builder_service_spec.rb
- spec/services/find_availability_service_spec.rb
preliminary to #987 
Montrose accepte une option `starts` optionnelle pour définir le début d'une récurrence. Pour l'instant nous ne la définissons jamais. Or, nos plages d'ouvertures et absences ont **toujours** une date de début.
L'absence du `starts` dans les recurrences ne semblait pas gênante jusqu'ici mais elle le devient lorsqu'on veut utiliser la méthode `recurrence.include?` dans la PR #987 
dans cette PR :
- migration qui sette le `recurrence.starts` sur toutes les POs et absences ou il est manquant 
- before_save qui s'assure que `recurrence.starts = first_day` lorsque `recurrence` n'est pas nil
J'ai testé la migration sur la db de prod, ca passe bien
> migration + before_save hook to set recurrence.starts on absences and plage ouvertures

- app/form_models/agent_rdv_wizard.rb
- app/form_models/user_rdv_wizard.rb
- app/models/rdv.rb
encore un mini refacto preliminaire pour https://github.com/betagouv/rdv-solidarites.fr/pull/987 !
Je m'apprete a rajouter des methodes dans le modèle RDV et ça fait dépasser la taille raisonnable acceptée par le linter. 
Plutôt que déplacer mes nouvelles méthodes dans un concern pour éviter ce problème, je propose de sortir une fonction qui je pense n'a pas sa place dans ce modèle : `to_query`. 
C'est une méthode utilisée pour générer des liens avec des query params correspondant à un RDV. C'est donc plus une méthode de présentation que de modèle. Elle est exclusivement appelée et surchargée depuis les form models user rdv wizard et agent rdv wizard. J'ai inliné et simplifié cette génération de query params, par ex côté user il n'y a pas besoin (et c'est un peu dangereux) de passer les …
> extract rdv#to_query to wizards objects

- app/controllers/admin/permissions_controller.rb
- app/models/agent.rb
- app/views/admin/invitations/new.html.slim
- app/views/admin/permissions/edit.html.slim
- app/views/agents/registrations/edit.html.slim
- config/brakeman.ignore
https://trello.com/c/c3ycMAQT/1144-bug-changer-un-agent-de-service-rend-les-plages-douvertures-incoh%C3%A9rentes
J'ai rajouté des textes explicatifs : 
à l'invitation
dans la page de modification du compte de l'agent courant
sur le agent#edit (en fait permissions#edit, je sais pas trop pq)
> prevent agents from changing service

- app/views/admin/motifs/_motif.html.slim
https://trello.com/c/xxNscEiG/1188-masquer-le-niveau-de-sectorisation-dans-la-liste-pour-les-motifs-non-r%C3%A9servables-en-ligne
> do not show sectorisation_level in motifs#index when not reservable online

- app/controllers/admin/rdvs_controller.rb
- app/form_models/agent_rdv_wizard.rb
- app/helpers/admin_helper.rb
- app/models/concerns/recurrence_concern.rb
- app/models/plage_ouverture.rb
- app/models/rdv.rb
- app/service_models/time_slot.rb
- app/views/admin/plage_ouvertures/_form.html.slim
- app/views/admin/plage_ouvertures/_overlapping_plage_ouvertures.html.slim
- app/views/admin/rdv_wizard_steps/step3.html.slim
- app/views/admin/rdvs/_rdv_details.html.slim
- app/views/admin/rdvs/edit.html.slim
- app/views/admin/rdvs/index.json.jbuilder
- app/views/layouts/_model_errors.html.slim
- app/webpacker/components/calendar.js
- db/seeds.rb
- spec/controllers/admin/rdvs_controller_spec.rb
- spec/models/plage_ouverture_spec.rb
- spec/service_models/time_slot_spec.rb
- spec/services/creneaux_builder_service_spec.rb
- spec/services/find_availability_service_spec.rb
https://trello.com/c/6HOfDMIF/1170-alerter-lors-de-la-cr%C3%A9ation-de-rdvs-en-conflit-avec-des-plages-douvertures
**agent rdv wizard tunnel step 3**
**rdvs show**
(ca apparait de la meme maniere dans la liste des RDVs)
**calendar**
J'ai créé un petit modele hors AR qui represente un créneau temporel : `TimeSlot`. C'est un datetime de début + un datetime de fin. Il a deux comportements : 
- il valide que les datetimes appartiennent à la même journée et sont consécutifs
- on peut calculer si deux time slots se chevauchent ou non avec `#intersects?`
Un `Creneau` peut etre vu comme un `TimeSlot` qualifié car il correspond a une plage d'ouverture + une duree de rdv etc
Dans les specs j'ai essayé de bien découper ce que je teste et de mocker le niveau en dessous a chaque fois pour limiter les …
> warn overlapping plage ouvertures conflicts on RDVs creation

- app/helpers/motifs_helper.rb
- app/views/admin/motifs/_motif.html.slim
https://trello.com/c/U37LFm0b/1189-info-motif-en-ligne-ou-hors-ligne-au-moment-de-cr%C3%A9er-une-plage-douverture
J'avais effectivement cassé le comportement des badges il y a 2 semaines lorsque j'ai modifié `motifs#index`. J'y ai déplacé l'info "réservable en ligne" dans une colonne à part, il ne fallait donc plus afficher ce badge juste à côté du nom mais bien dans sa colonne propre. Je n'ai pas réalisé qu'en changeant ça dans le helper je cassais le comportement attendu sur la plage d'ouverture où ce badge doit bien s'afficher. Ce commit répare le comportement.
> restore displaying motif reservable online badge where appropriate

- app/controllers/admin/users_controller.rb
- app/controllers/users/rdv_wizard_steps_controller.rb
- app/controllers/users/users_controller.rb
- app/helpers/displayable_user.rb
- app/models/concerns/user/responsability_concern.rb
- app/models/file_attente.rb
- app/services/notifications/rdv/base_service_concern.rb
- app/views/admin/rdvs/show.html.slim
- app/views/admin/users/_responsible_form_fields.html.slim
- app/views/admin/users/_responsible_information.html.slim
- app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
- app/views/users/users/_form.html.slim
- app/webpacker/components/agent-user-form.js
- config/locales/models/user.fr.yml
- db/migrate/20201208091156_add_notify_booleans_to_users.rb
- db/schema.rb
- spec/models/user_spec.rb
- spec/services/notifications/rdv/base_service_spec.rb
https://trello.com/c/onN13lua/1175-d%C3%A9sactiver-les-notifications-pour-un-usager
L'admin ne peut pas modifier les prefs de notifs une fois le compte confirmé : 
J'ai du rajouter encore un peu de complexité dans le JS du formulaire des users dans l'admin. ce JS est responsable de basculer du mode "usager responsable" vers le mode "usager proche". Il gère la visibilité des bons champs selon le mod, et maintient à jour les attributs `disabled` sur les différents inputs pour s'assurer que le formulaire soumettra les bons champs.
L'utilisation de champs de types checkbox pour les nouvelles preferences de notifs fait que rails rajoute un hidden input avec la valeur 0 pour quand la checkbox n'est pas coché. Ce input n'a pas les memes classes et attributs que le principal, donc pas …
> add users.notify_by_sms and email settings

- app/models/rdv.rb
- app/models/user.rb
- app/views/admin/rdvs/_short_rdvs_list.html.slim
- app/views/admin/rdvs/show.html.slim
- app/views/admin/users/show.html.slim
- app/webpacker/stylesheets/components/_utilities.scss
- spec/features/agents/agent_can_see_users_rdv_spec.rb
- spec/lib/phonelib_spec.rb
- spec/models/rdv_spec.rb
- spec/models/user_phone_spec.rb
- spec/models/user_spec.rb
https://trello.com/c/pYTq6GJX/1195-afficher-le-bloc-rdvs-precedents-sur-la-vue-usager
Après une discussion en visio avec Élodie du 62, nous avons conclu que le mieux serait d'avoir un encart sur le rendez-vous courant. Pour déterminer ce rendez-vous, 
Le bloc n'apparait pas quand il n'y a pas de rendez-vous courant
Je n'ai pas réussi à trouver une belle requête SQL qui fait sa en une fois... Du coup j'ai:
- récupéré l'ensemble des rdv du jour
- défini un début de période à une heure avant le rendez-vous
- défini une fin de période à une heure après la fin du rendez-vous
- selectionné les rdv dont maintenant tombe dans la période élargie.
J'ai re-utilisé la vue partielle de liste courte de rendez-vous car il peut y avoir plusieurs rdvs en court.
> affiche un bloc de rdvs courant

- app/views/devise/invitations/edit.html.slim
https://trello.com/c/58xrngIl/1194-label-explicite-pour-linscription-agent
> affiche les labels sur les champs d'inscription

- app/form_models/admin/rdv_form_concern.rb
- app/models/rdv.rb
- app/policies/agent/rdv_policy.rb
- app/policies/default_agent_policy.rb
- app/presenters/rdv_ending_shortly_before_presenter.rb
- app/service_models/rdv_start_coherence.rb
- config/brakeman.ignore
- config/locales/models/rdv.fr.yml
- spec/form_models/admin/rdv_form_concern_spec.rb
- spec/models/rdv_spec.rb
- spec/presenters/rdv_ending_shortly_before_presenter_spec.rb
- spec/service_models/rdv_start_coherence_spec.rb
https://trello.com/c/fbebJ0G5/1173-ajuster-lheure-de-d%C3%A9but-du-rdv-avec-la-fin-du-pr%C3%A9c%C3%A9dent
Cette PR est _relativement_ simple après le gros refacto des admin RDV forms.
Pour l'agent courant
Pour un autre agent, dans le scope
Pour un autre agent, hors scope
Un point un peu tricky c'est le multi-agent. Il faut prendre en compte le fait que le RDV qu'on est en train de créer peut avoir plusieurs agents, et que le RDV qui est potentiellement en conflit a une autre liste d'agents et il faut faire l'intersection. 
Aussi, on ne veut pas afficher plusieurs warnings pour des RDVs d'un même agent comme : 
- Attention, Martine a un RDV finissant à 15h30
- Attention, Martine a un RDV finissant à 15h45
- Attention, Martine a un RDV finissant à 16h00 
etc, il faut bien prendre le dernier …
>  in admin RDV forms, warn when agents have other RDVs ending shortly before

- app/views/admin/rdvs/_rdv_status_dropdown.html.slim
- app/views/admin/rdvs/show.html.slim
bug remonté par Elodie : 
- lorsqu'on essaie de modifier le statut d'un RDV, via le bouton annuler OU via le dropdown
- on peut se prendre un avertissement "ca va laisser un trou" et ca ramene au formulaire d'edition
quickfix: skipper les warnings depuis le bouton annuler et le dropdown d'update de statut
> updating RDV statuses should skip warnings

- app/models/plage_ouverture.rb
cc #1027 
sur un dump de prod sur ce cas long : http://localhost:5000/admin/organisations/101/agent_searches?service_id=&motif_id=800&from_date=24%2F12%2F2020&agent_ids%5B%5D=&lieu_ids%5B%5D=&commit=Afficher+les+cr%C3%A9neaux
on passe de : 
- 22s a 5s 
- de 13M d'allocs à  3M
> improve creneaux search perfs by removing extraneous includes

- app/controllers/admin/rdvs_controller.rb
- app/service_functions/rdv_exporter.rb
- app/services/rdv_exporter_service.rb
- spec/service_functions/rdv_exporter_spec.rb
- spec/services/rdv_exporter_service_spec.rb
Ajouter la notion de Mineur ou Majeur pour chaque ligne de RDV dans l'export des statistiques par orgnisation.
Dans le cas d'un rendez-vous avec plusieurs usagers, je suis parti du principe que s'il y avait un mineur, il faut déclarer « mineur » dans l'export.
_Ça me fait me demander si le fait de pouvoir mettre plusieurs usager sur un rdv est utilisé et si oui, pourquoi, par qui ? J'ai l'impression que ça complexifie pas mal de règle metier pour un gain mineur_
#1009
> ajoute mineur/majeur dans l'export stat orga

- app/helpers/motifs_helper.rb
- app/views/admin/rdvs/index.json.jbuilder
- app/webpacker/stylesheets/components/_calendar.scss
- spec/controllers/admin/rdvs_controller_spec.rb
- spec/helpers/motifs_helper_spec.rb
https://trello.com/c/F0LCArHS/1116-probl%C3%A8me-de-contrastes-sur-lagenda-et-les-couleurs-de-motifs
Dans un premier temps, j'ai exploré la possibilité, comme évoqué dans le ticket, de proposer une palette de couleur prédéfini au moment de la configuration d'un motif.
Définition d'une palette à partir du [figma](https://www.figma.com/file/JhZCwwrmaw2NYrITCj8QAK/RDV-Solidarit%C3%A9?node-id=5%3A95), puis déclinaison pour trouver 22 couleurs de fond et de texte en accord avec le [référentiel d'accessibilité](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/) en utilisant le site [a11yrocks/colorPalette](http://www.a11yrocks.com/colorPalette/)
Puis je me suis demandé s'il fallait proposer la palette à la façon de trello
Mais j'ai trouvé que ça faisait un composant très complexe …
> Calcul le contraste du texte dans l'agenda

- app/lib/redirect_to_registration.rb
- config/initializers/devise.rb
- spec/controllers/users/rdv_wizard_steps_controller_spec.rb
- spec/features/users/user_can_search_rdv_spec.rb
https://trello.com/c/23F6PWYU/1129-afficher-le-formulaire-dinscription-usager-par-d%C3%A9faut-plutot-que-celui-de-connexion
Utilisation de la configuration suggéré dans l'article : https://trello.com/c/23F6PWYU/1129-afficher-le-formulaire-dinscription-usager-par-d%C3%A9faut-plutot-que-celui-de-connexion
> redirige vers la page d'inscription

- app/webpacker/components/select2-inputs.js
trying to fix https://sentry.io/organizations/rdv-solidarites/issues/1910972605/?environment=production&project=1811205&query=is%3Aunresolved
le sélecteur que j'ajoute affine juste pour s'assurer de destroy des select ayant bien été initialisés
> narrow down select2 destroy selector to avoid JS errors

- app/models/motif.rb
- config/initializers/css_hex_color_validator.rb
- spec/models/motif_spec.rb
Traitement du ticket #1082 
Valider le format en #RRGGBB de la couleur des motifs.
Je suis passé par un validateur externe (dans le `config/initialize/css_hex_color_validator.rb`) c'est peut-être _overkill_, mais ça me semble le plus élégant, sans avoir un coup extraordinaire
> valide la couleur du motif

- app/controllers/organisations_controller.rb
should fix https://sentry.io/organizations/rdv-solidarites/issues/2037988059/?environment=production&project=1811205&query=is%3Aunresolved
Il me semble que la création d'organisations par des nouveaux agents est cassé, partiellement ou complètement. Le souci vient du fait que le before_save callback `sync_uid` de `devise_token_auth` (gem utilisée pour l'auth par token dans l'API) ne se déclenche pas bien dans le flow de création d'orga + agent. Ca fait que `uid = nil`, ca passe une fois mais la deuxième fois on prend une erreur due à la contrainte d'unicité sur `[uid, provider]`.
C'est ce court-circuit qui semble sauter à tort : https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user_omniauth_callbacks.rb#L26 . Ca s'appuie sur …
> fix creating organisation not setting new agents' uid

- app/controllers/concerns/can_have_rdv_wizard_context.rb
should fix https://sentry.io/organizations/rdv-solidarites/issues/2020843070/?environment=production&project=1811205&query=is%3Aunresolved
Pour reproduire : 
- créer une PO pour un certain motif
- dans un autre onglet faire une recherche usager pour ce motif et aller jusqu'à la page de sign up : les infos du RDV sont affichées (elles sont stockées dans un cookie dans un return_to)
- supprimer la PO ou la modifier
- rafraîchir la page de signup dans l'autre onglet : ça fait une 500 aujourd'hui
La source du problème est que le return_to path peut être valide syntatiquement mais ça ne signifie pas que le créneau est toujours disponible. On ne gère pas le cas où le créneau n'est pas dispo pour l'instant et ça explose.
Dans cette PR, je valide que le créneau associé au rdv wizard est tjs …
> clear session return_to path when creneau is not available anymore

- app/controllers/lieux_controller.rb
should fix https://sentry.io/organizations/rdv-solidarites/issues/2075664820/events/b44c5ad270ff4f83983c3f3582f81a9e/?environment=production&project=1811205
ce changement fait que les usagers qui arrivent sur les routes `/lieux` sans param `search` seront redirigés vers la home avec un message d'erreur plutôt que se prendre une 500. C'est peut etre un poil risqué car ca peut nous cacher des erreurs, mais pour l'instant ces erreurs "ne viennent pas de chez nous", c'est à dire que les gens arrivent avec des liens cassés de l'extérieur
On pourra éventuellement mettre des warning en place sans que ça fasse des 500 pour autant si jamais des usagers nous remontent qu'ils rencontrent ce message d'erreur
> soft handle absent search params in lieux controller

- app/controllers/admin/agents_controller.rb
- app/controllers/admin/permissions_controller.rb
- app/presenters/agent_removal_presenter.rb
- app/service_models/agent_removal.rb
- app/views/admin/permissions/edit.html.slim
- spec/features/agents/admin_can_configure_the_organisation_spec.rb
- spec/service_models/agent_removal_spec.rb
issue #1088
j'en ai profité pour améliorer et contextualiser les textes de : 
- bouton de suppression / retrait de l'agent
- message d'avertissement avant retrait
- flash success après coup
> soft delete agents when removed from last organisation

- config/locales/devise.fr.yml
building up on #1108 
@sylvinus I reverted the change `E-mail` -> `Email` because both seem to be accepted orthographs
> Typo fixes by sylvinus

- app/views/admin/departements/zone_imports/new.html.slim
Pour la secto à la rue, on propose soit la sélection manuelle via un autocomplete BAN ce qui fonctionne bien, soit l'import d'un fichier pour les imports massifs. Dans ce dernier cas on demande une colonne `street_code` qui est un identifiant de rue dans le référentiel de la BAN, par ex `62080_0180`. C'est un identifiant quasi impossible à avoir pour l'instant, puisqu'aucun autre outil ne semble faire référence à ces codes, a contrario du city_code utilisé par la BAN qui est le code commune INSEE.
Cette PR rajoute un lien vers un mini-outil externe développé pour l'occasion qui permet d'entrer une liste de noms de rues et de récupérer les identifiants rue BAN correspondants. Le but est de permettre aux agents ou plutôt aux SI des départements d'agrémenter leurs fichiers d'imports. 
Le …
> link to external page with street ban ids finder tool for sectorisation

- app/models/organisation.rb
cf #1117 
- retire l'association `Organisation.zones` car il n'y a en fait pas de lien entre ces deux objets. Une orga est associée à un ou plusieurs Secteur, et un Secteur a une ou plusieurs zones, mais ça n'a pour autant pas de sens de dire qu'une orga a des zones. 
- ajoute l'organisation `Organisation.plage_ouvertures` utile pour la suppression en cascade.
> improve organisation associations, remove zones, add plage_ouvertures

- app/models/user.rb
- spec/models/user_spec.rb
Pour résoudre ce problème https://sentry.io/organizations/rdv-solidarites/issues/2154627583/?project=1811205&query=is%3Aunresolved
Nous n'avions pas pris en compte le cas où l'usager n'a pas de date de naissance. Nous allons considéré qu'ille n'est pas mineur dans ce cas.
> prend en compte le cas sans date de naissance

- app/models/sector.rb
- db/migrate/20210114143145_delete_corrupt_zones.rb
- db/schema.rb
should fix https://sentry.io/organizations/rdv-solidarites/issues/2149603162/?environment=staging&project=1811205&query=is%3Aunresolved
le probleme était qu'on ne supprimait pas les zones lorsqu'on supprime un secteur (il manquait le dependent).
j'ai fait une migration pour corriger les problèmes existants.
> destroy corrupt zones without sectors

- app/webpacker/components/rdv-status-dropdowns.js
should fix https://sentry.io/organizations/rdv-solidarites/issues/2052301596/?environment=production&project=1811205&query=is%3Aunresolved
Ce bug se produit quand le retour de l'update du statut d'un RDV ne renvoie pas de RDV. Ça peut se produire dans le cas où un agent essaie d'updater un RDV sur lequel il n'a pas les permissions adéquates. UJS + Turbolinks déclenche alors un refresh auto de la page avec un flash "non autorisé", mais il ne détache pas les callbacks attachés à ajax:success, ce qui est surprenant.
J'ai essayé sans succès de comprendre la source du problème : pourquoi est-ce qu'on propose d'updater les status de RDV pour lesquels l'agent courant n'a pas les permissions mais je n'ai pas trouvé. Les scopes m'ont l'air cohérents et bien appliqués. 
On manque un peu d'infos …
> fix js bug when using rdv status dropdown on non authorized RDV

- app/mailers/custom_devise_mailer.rb
- app/models/super_admin.rb
- app/views/agents/mailer/invitation_instructions.html.erb
- app/views/agents/mailer/invitation_instructions.text.erb
- config/application.rb
- config/initializers/devise.rb
- config/locales/devise.fr.yml
- spec/controllers/admin/invitations_controller_spec.rb
- spec/mailers/previews/custom_devise_mailer_preview.rb
- spec/mailers/previews/devise_mailer_preview.rb
J'ai du introduire un DeviseCustomMailer qui hérite de `Devise::Mailer` pour pouvoir modifier le reply_to à la volée. cf https://github.com/heartcombo/devise/wiki/How-To:-Use-custom-mailer
Jusqu'ici on utilisait exactement le meme template de mail pour les invitations usagers et les invitations agents.
J'ai changé ça pour donner plus de détails dans les invitations agents : 
avant :
apres :
> invitations mail reply_to inviter agent with CustomDeviseMailer

- app/jobs/send_transactional_sms_job.rb
- app/service_models/transactional_sms/base_concern.rb
- app/service_models/transactional_sms/builder.rb
- app/service_models/transactional_sms/file_attente.rb
- app/service_models/transactional_sms/rdv_cancelled.rb
- app/service_models/transactional_sms/rdv_created.rb
- app/service_models/transactional_sms/reminder.rb
- app/services/send_transactional_sms_service.rb
- spec/service_models/transactional_sms/base_concern_spec.rb
- spec/service_models/transactional_sms/builder_spec.rb
- spec/service_models/transactional_sms/file_attente_spec.rb
- spec/service_models/transactional_sms/rdv_cancelled_spec.rb
- spec/service_models/transactional_sms/rdv_created_spec.rb
- spec/service_models/transactional_sms/reminder_spec.rb
- spec/services/send_transactional_sms_service_spec.rb
Le but initial était d'isoler plus clairement la partie envoi de SMS, qui va varier selon le provider, de la partie génération du SMS.
Dans la foulée, je suis allé trop loin, mais je n'ai pas pu m'empêcher de refacto la partie génération du SMS qui ne me plaisait vraiment pas avec un `send(@type)` assez bizarre. J'ai séparé chaque événement dans une classe à part comme `TransactionalSms::RdvCancelled` , et elles partagent du comportement via un concern `TransactionalSms::BaseConcern` qui contient par exemple le footer commun, ou la fonction pour éviter les caractères spéciaux.
J'ai laissé le support de SendInBlue pour l'instant, car on va vouloir consommer le crédit restant. J'ai mis le switch sur une variable d'env.
rien de spécial pour le support Netsize; je me suis appuyé sur le script …
> Netsize Support + SMS service refactos

- app/service_models/transactional_sms/base_concern.rb
- app/services/send_transactional_sms_service.rb
don't know how I missed this
il y avait en fait plusieurs problèmes : 
- utilisation de next au lieu de break (mtn return car extrait dans une fonction)
- l'API Netsize renvoie 200 même quand ça marche pas 😬  il faut vérifier le responseCode contenu dans la réponse JSON
- on envoyait des noms de campagne trop longs sur les environnements de demo/prod, la limite est à 50 caractères
> fix netsize : error handling + break from proc + campaign names

- app/controllers/admin/motifs_controller.rb
- app/helpers/motifs_helper.rb
- app/policies/agent/motif_policy.rb
- app/policies/default_agent_policy.rb
- app/views/admin/motifs/_form.html.slim
- app/views/admin/motifs/_motif.html.slim
- app/views/admin/motifs/_motif_attributes.html.slim
- app/views/admin/motifs/index.html.slim
- app/views/admin/motifs/show.html.slim
- app/views/layouts/_left_menu.html.slim
- app/webpacker/stylesheets/components/_motifs.scss
- app/webpacker/stylesheets/components/_utilities.scss
- config/locales/models/motif.fr.yml
- config/routes.rb
- spec/controllers/admin/motifs_controller_spec.rb
- spec/features/agents/admin_can_configure_the_organisation_spec.rb
Ajoute une vue `motifs#show`, et rend la vue `motifs#index` accessible aux non-admins
Vues agent non admin:
Vues agent admin: 
Pour le lien dans le menu de gauche, j'ai fait comme pour la liste des lieux : le lien apparaît au top level pour les agents non admin , et dans paramètres pour les agents admin. A mon avis on pourrait harmoniser en mettant ces deux items top level même pour les admins.
J'ai essayé de génériser au maximum les wordings dans I18n pour éviter que notre vocabulaire ne diverge entre les différentes vues index, show, edit.
J'en ai profité pour génériser un tout petit peu le code du formulaire sur certaines options à valeurs multiples où ça se justifiait bien.
J'ai peut-être un poil trop fait de helpers pour être plus DRY, c'est un peu moins évident à lire que si tout …
> introduce read-only list of motifs for non-admin agents

- app/lib/redirect_to_registration.rb
fix #1135
cf https://github.com/heartcombo/devise/wiki/Redirect-to-new-registration-(sign-up)-path-if-unauthenticated#working-with-multiple-devise-resources
> redirect agents to sign in rather than user sign up

- app/form_models/admin/rdv_form_concern.rb
- app/models/rdv.rb
- app/presenters/rdvs_overlapping_rdv_presenter.rb
- app/service_models/rdvs_overlapping.rb
- config/locales/models/rdv.fr.yml
- spec/form_models/admin/rdv_form_concern_spec.rb
- spec/models/rdv_spec.rb
- spec/service_models/rdvs_overlapping_spec.rb
#1120 
Ajoute la possibilité de retrouver les rendez-vous commençant sur une période donnée.
Je ne suis pas super satisfait d'avoir « dupliqué » l'existant pour faire cette feature, mais je ne me vois pas prendre du temps pour proposer un refactoring pour le moment.
> Alerte en cas de chevauchement avec un autre RDV dans le tunnel RDV agent

- .circleci/config.yml
- lib/tasks/ci.rake
Je viens de découvrir qu'il y a une tache pour exécuter 2 commandes. Je les déplace dans le fichier CI et supprime la tache.
Ça n'a rien à voir avec le souci de Brakeman que j'avais, mais je trouve ça plus clair ainsi.
> Supprime la tache CI

- Makefile
- app/controllers/admin/motifs_controller.rb
- app/models/motif.rb
- app/views/admin/motifs/index.html.slim
- app/webpacker/components/motif-filters.js
- app/webpacker/packs/application_agent.js
- config/brakeman.ignore
- spec/controllers/admin/motifs_controller_spec.rb
fix #1054
Pour faciliter la consultation des motifs (liste longue parfois), ajout
- d'un champ de recherche (basé sur le nom pour le moment)
- de filtres sur les colonnes « Réservable en ligne », « Service » et « Type de rendez-vous »
> Filtre et recherche dans la page des motifs

- app/presenters/displayable_user_presenter.rb
- app/views/admin/merge_users/new.html.slim
- app/views/admin/rdvs/show.html.slim
- app/views/common/_user_attribute.html.slim
- spec/presenters/displayable_user_presenter_spec.rb
#1159
J'en profite pour faire un peu de nettoyage.
- utilisation d'une seul instance de `DisplayableUser` dans le show d'un RDV
- Déplacement du `DisplayableUser` depuis les helpers pour en faire un `DisplayableUserHelper`
- Mise en place de lien `mail_to` et `tel` pour le mail et le téléphone de l'usage sur la fiche RDV
>  rajouter liens mailto sur les emails d'usagers

- app/policies/agent/agent_policy.rb
should fix https://sentry.io/organizations/rdv-solidarites/issues/2206711239/?environment=production&project=1811205&query=is%3Aunresolved
C'est un peu limite comme solution en terme de rigueur des policies, je relache la contrainte, mais je ne comprends pas à quoi elle servait. Je ne suis pas tout à fait sûr de ce que j'ai cassé dans la PR des rôles indépendants par orga, j'ai peut-être rajouté cette contrainte par erreur. Je n'ai pas envie d'y passer trop de temps car on va probablement attaquer l'introduction du niveau département bientôt et que ça va cleaner tout ça.
> fix agent policy for sector attribution agents form

- app/models/user.rb
- db/migrate/20210205140023_add_trackable_fields_to_user.rb
- db/schema.rb
Le modulde [Trackable](https://www.rubydoc.info/github/heartcombo/devise/master/Devise/Models/Trackable) de devis propose d'enregistrer la date et l'heure de la dernière connexion. 
Le hic, c'est que ça enregistre aussi les adresses IP. Est-ce un problème pour nous ? C'est un peu dommage de récolter une information qui ne nous sert à rien.
fix #1156
> active le module Trackable de devise

- app/lib/csv_or_xls_reader.rb
- db/migrate/20210210114138_fix_traling_zeros_in_city_code_in_zones.rb
- db/schema.rb
XLS est un format un peu naze, et apparement supporte mal la distinction entre texte et floats. Quand une colonne ne semble contenir que des données numériques, la gem qu'on utilise considère par défaut que ce sont des floats. Quand on les affiche en strings, ça nous affiche donc un trailing `.0`. Par exemple un code commune INSEE 62002 devient 62002.0. 
Cela casse les imports XLS de zones, cf le pb de christelle cufay.
Il y a une partie des données en prod corrompues, environ 10 zones. 
Cette PR fait un fix de workaround pour gérer ce cas dans le lecteur XLS, et une migration pour corriger les entrées corrompues. 
Il faudrait peut-être rajouter des validations sur le format autorisé des champs city_code et city_ban_id, plus tard.
> better support floats in XLS zones import + migration to fix corrupt values

- app/helpers/user_notifications_helper.rb
- app/models/concerns/user/notificable_concern.rb
- app/models/concerns/user/responsability_concern.rb
- app/models/user.rb
- app/presenters/displayable_user_presenter.rb
- app/service_models/transactional_sms/base_concern.rb
- app/services/notifications/rdv/base_service_concern.rb
- app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
- app/views/users/users/_form.html.slim
- spec/factories/user.rb
- spec/models/concerns/user/notificable_concern_spec.rb
- spec/presenters/displayable_user_presenter_spec.rb
- spec/service_models/transactional_sms/base_concern_spec.rb
- spec/services/notifications/rdv/base_service_spec.rb
#1176 
Avant de complexifier légèrement la règle pour décider de l'envoi d'un SMS je l'ai extraite dans un concern rattaché au User. J'ai déplacé les tests afférents.
j'essaie d'empêcher l'envoi à deux niveaux : 
- en haut dans l'enqueuing des jobs en filtrant sur les users avec des numéros de mobiles - via la complexification de la méthode `notifiable_by_sms?`
- au plus bas en raisant quand on essaie de construire un TransactionalSMS pour un user n'ayant pas un numero de mobile
> prevent trying to send SMS to landlines

- app/models/user.rb
- app/presenters/admin/rdv_user_presenter.rb
- app/views/admin/rdvs/_short_rdvs_list.html.slim
- app/views/admin/rdvs/show.html.slim
- app/views/admin/users/show.html.slim
- spec/features/agents/agent_can_see_users_rdv_spec.rb
- spec/models/user_spec.rb
- spec/presenters/admin/rdv_user_presenter_spec.rb
closes #1031
Le bloc intitulé "rendez-vous précédents" apparaît maintenant dans la carte de l'usager plutôt que dans une carte indépendante, pour exprimer le fait que ce sont les RDVs de cet usager dont on parle (utile si plusieurs usagers).
Jusqu'ici le filtre "rdvs précédents" se faisait sur base de l'heure actuelle, on parlait des RDVs dans le passé de l'usager. Or, si je suis par exemple en train de regarder la page d'un RDV qui a eu lieu il y a un mois, et que je vois un rdv qui a eu lieu il y a 1j dans un bloc "rdvs précédents" ça n'a pas trop de sens à mon avis. J'ai changé ce filtre temporel, pour qu'on n'affiche ici que les RDVs précédents par rapport au RDV regardé. 
Les "RDVs précédents" au sens ceux dans le passé sont toujours visible sur les fiches usagers, mais plus sur les …
> Améliorations du bloc de RDVs précédents sur la vue RDV admin

- app/services/upsert_user_for_franceconnect_service.rb
should fix https://sentry.io/organizations/rdv-solidarites/issues/2244974663/?environment=production&project=1811205&referrer=alert_email
fix rapide sans specs car : 
- je crois qu'il ne faudrait pas tester au niveau du service d'upsert de FC mais plutot au niveau du model User, ce qui est deja fait il me semble
- je crois qu'en fait ce warning de duplicate user ne devrait pas etre dans le modele mais dans un form model specifique a l'admin
- je crois aussi qu'il faudrait refacto ce systeme de warning maison par la gem qu'on utilise maintenant pour les warnings du tunnel RDV admin pour harmoniser
> quickfix to ignore duplicate user warnings on FC upsert

- app/controllers/admin/users_controller.rb
- app/helpers/users_helper.rb
- app/models/service.rb
- app/views/admin/rdv_wizard_steps/step2.html.slim
- app/views/admin/users/_form.html.slim
- spec/factories/service.rb
- spec/factories/user.rb
- spec/helpers/users_spec.rb
- spec/models/service_spec.rb
fix #1184
Pour « orienter » la création d'un usager dans le tunnel de conversion, j'ai ajouté le motif dans l'appel du formulaire usager. L'idée est de pouvoir retrouver le service au moment d'une création. Si nous sommes en PMI, on affiche le proche par défaut. En général, en PMI, c'est l'enfant qui a rendez-vous.
>  Changer le défaut du formulaire de création d'usager (responsable -> proche) dans le tunnel de RDV agent pour le service PMI

- app/policies/application_policy.rb
- app/policies/user/rdv_policy.rb
- app/policies/user/user_policy.rb
preliminary to #1215 
La direction que j'envisage pour les policies est de **limiter le contexte à l'agent ou l'usager connecté**. Le contexte désigne ici le `pundit_user`utilisé comme premier argument d'instanciation des policies.
Aujourd'hui côté agent on utilise comme `pundit_user` un `AgentContext` qui contient l'agent connecté + l'organisation courante si l'agent parcoure des routes scopées à l'organisation. Pour les routes scopées au département entier, pour l'instant on hacke complètement. 
Une direction alternative pourrait être de rajouter dans le contexte le Territoire pour supprimer le hack et faire quelque chose de propre. 
A mon avis, il vaut mieux simplifier au maximum le contexte et donc les policies. La policy devrait être uniquement en charge de dire si, dans l'absolu, un …
> refactor users and ApplicationPolicy

- app/controllers/admin/absences_controller.rb
- app/controllers/api/v1/absences_controller.rb
- app/policies/agent/absence_policy.rb
- spec/policies/agent/absence_policy_spec.rb
suite a #1224 : refacto des policies admin 
- heritage direct de `ApplicationPolicy`
- définition explicite des actions utilisées uniquement
- ajout de specs
> refactor AbsencePolicy to inherit from ApplicationPolicy

- spec/controllers/admin/agent_roles_controller_spec.rb
on utilisait le mauvais id pour generer la route, ca passait la plupart du temps par chance 😅
> fix error in agent_roles_controller_spec that causes flaky specs

- README.md
J'ai supprimé le grand texte. Je crois que ce n'est pas vraiment la peine d'écrire tout cette historique dans le README.
Un axe plutôt « index » de documentation me semble plus intéressant. J'ai donc ajouté quelques liens. Il en manque peut-être.
> simplifie le README

- scripts/scalingo_dump.rb
- execute un dropdb seulement si existe
- améliore la doc en cas de manque de la variable d'environnement SCALINGO_API_TOKEN
> Proposition d'améliorationo du script de dump & restore de la base PostgreSQL de Scalingo

- app/controllers/admin/agents_controller.rb
- config/routes.rb
Avec #1224, `admin/organisations/XXX/agents/YYY` est devenu `admin/organisations/XXX/agent_agendas/YYY`
On a cassé l'API public de RDV-Solidarités :sweat_smile: 
Des agents ont mis en favori le lien vers leur agenda et ces liens sont désormais dysfonctionnels.
Cette PR est une ébauche (peut-être pas fonctionnelle) mais donne une proposition de solution.
En plus de cela, il serait bien d'ajouter un message pour prévenir que les liens ont changés et demander à la création de nouveaux favoris / liens / raccourcis.
> Redirige les URL pointant précédemment vers les agendas

- app/controllers/admin/users_controller.rb
Fix #1247
Lors de la création d'un usager « proche », nous vérifions l'autorisation du responsable s'il est déjà enregistré.
Cette vérification s'assure que toutes les organisations sont autorisé dans le contexte :
```ruby
return false if @record.user_profiles.empty?
(   
@record.user_profiles.map(&:organisation_id) -
(current_organisation.present? ? [current_organisation.id] : current_agent.organisation_ids)
).empty?
```
Je ne suis pas très sûr de pourquoi nous vérifions l'autorisation du responsable. 
Je ne suis pas très sûr de pourquoi nous vérifions toutes les organisations.
J'ai l'impression que les deux éléments pourrait être revu. Pour débloquer la situation rapidement, je supprime la vérification d'autorisation sur l'usager responsable.
> arrête de vérifier l'autorisation d'un responsable

- .github/workflows/stale.yml
Je trouve que c'est un peu court pour réagir. Je modifie le temps avant fermeture de 7 à 42 jours.
Je pense que c'est aussi en gardant ce type d'issue que certaines personnes peuvent venir participer plus facilement.
> Allonge la durée avant fermeture

- spec/services/find_availability_service_spec.rb
should fix https://github.com/betagouv/rdv-solidarites.fr/runs/2165957522?check_suite_focus=true
Le test echoue aujourd'hui specifiquement : 
- https://github.com/betagouv/rdv-solidarites.fr/blob/master/app/services/jours_feries_service.rb/#L20
le 1er mai est férié
- le test verifie que quand il y a une plage d’ouverture avec une recurrence mensuelle mais la premiere occurence couverte par une absence, ca renvoie bien le mois d’apres mais la ca saute un mois
- c’est probablement parce que la premiere occurence est le 1er avril -> bien couverte et deuxieme occurence 1er mai => couverte par le jour férié mais ce n’est pas prevu
le fix consiste a :
- hardcoder une date dans le passé plutot qu'une date future indeterminée (jeudi prochain)
- je dois wrapper la creation de la PlageOuverture …
> fix holiday edge case in find availability service specs

- .env.sample
- app/services/send_transactional_sms_service.rb
- app/views/common/_env.html.slim
J’ai repris les variables déclarées sur scalingo, et fait un peu de tri, mais ça amène plus de questions 😅 
Si je comprends bien, celles-ci sont dépréciées :
- `SECTORISATION_ENABLED_DEPARTMENT_LIST` était utile pour une migration passée
- `MAINTENANCE_PAGE_URL` n’est pas utilisé par scalingo, c’est `SCALINGO_*_PAGE_URL`. 
- `LAPIN_DATABASE_PASSWORD` idem, je présume que l’ancienne configuration de prod?
Par contre, je n’ai pas compris à quoi servaient ces deux variables:
- `MATOMO_AUTH_TOKEN` est utilisé par `matomo.rake` un script qui… anonymise les données sur matomo?
- `APP` est utilisé dans `TransactionalSms::BaseConcern#tags`, mais n’est pas valué en prod. Je présume qu’on peut supprimer le code?
> Nettoyage des variables d’environnement dans .env

- app/service_functions/admin/ics/plage_ouverture.rb
- spec/service_functions/admin/ics/plage_ouverture_spec.rb
fixes #1273 
corrige probleme introduit dans le commit https://github.com/betagouv/rdv-solidarites.fr/commit/3f8b9dd6ef93af3cd28368609fbdf9e9e68813bf
ce commit avait retiré la ligne `event.rrule = payload[:recurrence]`
dans cette PR je fixe le test associé qui ne testait en fait pas la bonne chose
- tous les fichiers ICS qu'on genere, meme non recurrents, contiennent tous deux lignes RRULE qui ressemblent a celle-ci RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
- cette ligne est en fait utilisee pour definir la timezone ou qqch, en tout cas ca ne decrit pas l'evenement
- le payload.merge(recurrence: "FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10") de ce test n'a en fait aucune importance : on peut l'enlever et le test passe. c'est parce que tous les ICS contiennent cette ligne
- par contre si on met quoi …
> fix plage ouverture ICS rrule

- spec/rails_helper.rb
J'ai encore eu le souci de la taille d'un numéro de département qui explose.
Plutôt que de remettre le modulo sur la séquence du numéro de département, je propose de mettre en place la commande `rewind_sequence` disponible sur factory_bot.
> remet à zéro les séquences à la fin de chaque test

- app/helpers/rdvs_helper.rb
J'ai découvert que le badge n'affichais pas la bonne couleur dans la fiche usager et fiche rdv coté admin.
Avant correction :
Après correction :
> corrige les couleurs de badges de la vue usager

- app/views/admin/plage_ouvertures/_form.html.slim
- spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
fixes #1295: une erreur 404 au retour du formulaire de création d’une nouvelle plage d’ouverture. Je présume que c’est liée au chantier sur les contextes agents/organisation.
> Corrige un crash à l’annulation d’une nouvelle plage d’ouverture

- app/controllers/admin/motifs_controller.rb
- app/views/admin/motifs/index.html.slim
- spec/controllers/admin/motifs_controller_spec.rb
link #1174 
- Gardé l'entête du tableau, pour plus de cohérence avec la liste des agents.
- Alignement du bouton (je n'ai pas trouvé de meilleur moyen qu'en le dupliquant dans le code)
- Spécifie pourquoi il n'y a pas de motifs affiché
> Améliorations d'interface de la liste de motifs pour les admins

- app/form_models/admin/rdv_wizard_form/step3.rb
cette redefinition du `save` date probablement de l'introduction du `Admin::RdvFormConcern` qui a du redefinir ce save a a un moment et l'override redevenait necessaire.
Ce n'est plus le cas
> remove extraneous save override in Admin::RdvWizardForm::Step3

- config/initializers/sentry.rb
See this issue: https://sentry.io/organizations/rdv-solidarites/issues/2292048716/events/18b550feebca4468b30f70c011e7d59f/?project=1811205
I think setting `excluded_exceptions` is unneeded with the new sentry ruby gems.
> Use default settings in sentry to ignore 4xx errors

- config/locales/fr.yml
- spec/features/agents/admin_can_configure_the_organisation_spec.rb
- spec/features/agents/agent_can_crud_absences_spec.rb
- spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
- spec/features/agents/relatives/agent_can_update_relative_spec.rb
- spec/features/agents/users/agent_can_create_user_spec.rb
- spec/features/agents/users/agent_can_update_user_spec.rb
- spec/features/users/user_can_search_rdv_spec.rb
Nous avons eu plusieurs retours sur l'aspect perturbant d'appuyer sur un bouton modifier pour enregistrer des informations. Dans le flux, on se retrouve à appuyer sur un bouton modifier pour accéder a un formulaire puis, à appuyer à nouveau sur modifier pour l'enregistrer.
Cette PR propose donc d'utiliser le mot Enregistrer à la place de modifier et créer pour les boutons de submit des formulaires.
> Change le label des boutons

- yarn.lock
should fix https://github.com/betagouv/rdv-solidarites.fr/security/dependabot/yarn.lock/y18n/open
> bump y18n js package to fix security alert

- app/models/plage_ouverture.rb
- app/views/admin/plage_ouvertures/_form.html.slim
Ce code n'est en fait pas utilisé pour afficher le warning actuellement existant: 
Si on souhaitait afficher un message plus riche comme ceux affichés sur le show, le bon fix serait de modifier `PlageOuverture#warn_overlapping_plage_ouvertures` pour faire un `render partial : admin/plage_ouvertures/overlapping_plage_ouvertures`
> remove dead code in plage_ouvertures form partial

- app/models/concerns/has_phone_number_concern.rb
- app/models/user.rb
- app/services/duplicate_user_finder_service.rb
- app/views/common/_user_attribute.html.slim
- app/views/layouts/_model_errors.html.slim
- spec/factories/user.rb
- spec/models/concerns/user/notificable_concern_spec.rb
- spec/service_models/transactional_sms/base_concern_spec.rb
- spec/services/duplicate_user_finder_service_spec.rb
refactos préliminaires extraits de https://github.com/betagouv/rdv-solidarites.fr/pull/1284
Aujourd'hui `User.new(phone_number: "0101010101").phone_number_formatted == nil` ce qui est perturbant et prone a erreurs.
J'override le getter `phone_number_formatted` des records avec le HasPhoneNumberConcern pour s'assurer que la valeur qu'on renvoie est la version formattée de `phone_number`
Par conséquent je retire l'instanciation initiale de `phone_number_formatted` dans la factory des User, qui etait une rustine pour ce sujet coté specs
J'ai aussi du modifier quelques specs comme `spec/service_models/transactional_sms/base_concern_spec.rb` et `spec/models/concerns/user/notificable_concern_spec.rb` pour setter phone_number plutot que phone_number_formatted
Cette méthode était utilisée à un …
> refactos de methodes sur les usagers partageant un numéro de téléphone

- app/views/admin/static_pages/support.html.slim
- app/views/static_pages/contact.html.slim
Le bureau ouvert n'était que peut fréquenter. Plusieurs raisons à cela :
- les agents remonte leurs soucis, questions et demande aux personnes référentes de leur territoire, pas besoin d'un bureau ouvert avec nous, mais plutôt avec leur référente... Et encore.
- nous voyons les personnes référentes toutes les deux semaines pour l'instant. Nous aimerions passer à toutes les semaines. Le rythme semble suffisant pour ne pas avoir en plus un bureau ouvert à tenir.
> supprime les références au bureau ouvert

- app/controllers/admin/invitations_devise_controller.rb
- app/policies/agent/agent_role_policy.rb
- app/views/admin/invitations_devise/new.html.slim
- spec/controllers/admin/invitations_devise_controller_spec.rb
-> issue #1308 
Ça se relit assez bien commit par commit. J’ai fait les deux solutions qu’on a évoquées: 
- on ne prend plus en compte l’organisation passée en paramètre du rôle
- on `authorize` avant d’inviter.
Au passage, j’ai un tout petit peu simplifié InvitationsController, mais c’est toujours un sac de noeuds dans ma tête entre Devise et Pundit 😬.
> Empêche d'inviter des agents à des organisations non-autorisées

- app/models/agent.rb
En fait, c’était déjà en place, mais le fonctionnement de Devise#Invitable et des validations est un peu subtil. Devise peut créer l’Agent et envoyer l‘invitation sans valider du tout, sauf si on validate_on_invite. C’est ce qu’on fait, et jusqu’ici c’est bien. Par contre, `accepted_or_not_invited` est contre intuitif, et en fait il vaut `false` pendant l’acceptation de l’invitation, ce qui fait que le first_name et last_name peuvent être laissés vide en base.
* On a un peu de baddata (15 agents) en prod avec first_name ou last_name vide, mais on peut les corriger à la main.
* Ça n’aiderait à rien de spécifier que les colonnes doivent être nonnull en base: ça n’empêcherait pas des chaines vides, et de toute façon, on veut que le first_name et last_name soient vide quand l’agent est invité …
> Valide (réellement) la présence de Agent#first_name et last_name

- app/helpers/admin_helper.rb
- app/policies/agent/agent_policy.rb
- app/views/admin/agent_roles/edit.html.slim
- app/views/admin/agents/_agent.html.slim
- app/views/admin/agents/index.html.slim
- app/views/admin/lieux/index.html.slim
- app/views/admin/motifs/index.html.slim
- spec/features/agents/admin_can_configure_the_organisation_spec.rb
- spec/policies/agent/agent_policy_spec.rb
fixes #1267
Avec un design plus ou moins inspiré de Lieux#index.
* Ajout d’une colonne Actions, avec les boutons edit et delete
* Redesign pour déplacer les invitations en dessous, plutôt qu’à droite.
* Je n’ai pas réussi à utiliser les policies dans les vues, je me suis résolu à utiliser `current_agent_role.admin?`. C’est probablement faisable, mais je veux bien en parler, j’ai l’impression que c’est lié à des travaux en cours.
Ça permet aussi de répondre à  https://rdv-solidarites.zammad.com/#ticket/zoom/61, puisqu’on peut modifier les agents sans nom (voir aussi #1313)
> Ajout d’une colonne “Actions” à admin/organisations/:id/agents

- app/controllers/admin/users_controller.rb
- app/models/user.rb
- app/services/duplicate_users_finder_service.rb
- app/views/common/_user_attribute.html.slim
- spec/services/duplicate_users_finder_service_spec.rb
encore une PR préliminaire à #1284 
Refacto pur, pas de changement de comportement
désolé @n-b je change un peu de direction par rapport à hier : 
- J'avais introduit un param `only` mais en fait ça ne m'arrange pas par rapport à ce que je veux faire dans la PR successive
- C'est en fait plus pratique que le service renvoie tous les doublons et qu'on les filtre a posteriori si besoin
- C'est un peu moins optimisé pour l'instant puisqu'on utilise le service puis on filtre les résultats pour n'afficher que les doublons sur base du numéro de téléphone dans le users/show. Il n'y a en fait probablement pas de raison de faire ça, on devrait par cohérence afficher tous types de doublons qui se produisent je pense (par ex ceux sur base de l'identité). Je n'ai pas changé ça dans la PR mais on …
> refactor DuplicateUserFinderService to return multiple matches

- app/views/mailers/users/rdv_mailer/rdv_upcoming_reminder.html.slim
- spec/mailers/users/rdv_mailer_spec.rb
#1318 
pas de chance c'était le seul mail pas testé 🤷 
visible sur la demo app via https://demo-rdv-solidarites-pr1319.osc-secnum-fr1.scalingo.io/super_admins/mailer_previews/users%2Frdv_mailer%2Frdv_upcoming_reminder
@n-b sur les review apps l'auth a la super admin se fait via basic auth, le login c'est `rdv-solidarites` et le mot de passe est une var d'env, `scalingo env -a demo-rdv-solidarites-pr1319 --region osc-secnum-fr1 | grep BASIC | sed 's/.*=//' | pbcopy`
> fix rdv upcoming reminder mail rendering

- app/views/layouts/user_registration.html.slim
Fixes #1305, j’ai juste décalé le flash dans le container, et un peu élargi celui-ci.
Avant:
Après:
De fait, ça modifie aussi le message pour l’inscription pour un motif non “suivi” :
> Meilleur affichage des messages de connexion à l’usager

- app/views/admin/absences/index.html.slim
- app/views/admin/plage_ouvertures/index.html.slim
- app/webpacker/stylesheets/components/_tables.scss
Suite à #1333: retire la border en haut des table.table, et les usages de `border-top-0`.
J’ai fait un tour rapide: ça fait plus clair sur certains écrans, en fait j’aime autant comme ça :)
> Retrait (en mieux) de la bordure en haut des tables

- app/models/lieu.rb
- spec/controllers/admin/lieux_controller_spec.rb
- spec/models/lieu_spec.rb
Corrige le souci remonté par Élise (en tout cas une partie).
C'est aussi la correction pour cette entrée Sentry https://sentry.io/organizations/rdv-solidarites/issues/2333945966/?project=1811205&query=is%3Aunresolved
Dans un email du 13 avril 2021, Élise nous signale une erreur 500 au moment de la suppression d'un lieu. Le souci, c'est que le lieu à encore des rendez-vous, nous ne pouvons pas le supprimer.
Cette correction affichera correctement la raison de l'échec de la suppression.
La demande de pouvoir supprimer des lieux inutilisés est déjà posé sur le forum https://forum.rdv-solidarites.fr/t/gestion-des-lieux-inutilises/28
Ça pose la question des rendez-vous passés, des plages d'ouvertures passées, des absences passées.
Mais c'est un autre sujet. Je vais le relancer sur le forum.
> bloque la suppression de lieu avec au moins un RDV

- app/controllers/admin/absences_controller.rb
- app/views/admin/absences/_absence.html.slim
- app/views/admin/absences/index.html.slim
- app/views/admin/lieux/_lieu.html.slim
- app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
- app/views/admin/plage_ouvertures/index.html.slim
- config/locales/fr.yml
fixes #1331
Au passage, quelques petits ajustements sur les lieux et les plages d’ouvertures; je vais peut-être essayer d’utiliser les policies pour afficher les actions de façon conditionnelle, mais ça avait l’air un peu touchy à première vue. 
> Ajouter une colonnes actions (et bouton dupliquer) à Absences#index

- app/views/common/_footer_users.html.slim
Pas d'issue liée.
- Resynchronisé la doc avec le repo github (c'était fait avec le compte d'Adrien, c'était à refaire) ;
- ranger un peu quelques éléments de la doc, dont les informations légales, dans une sous rubrique ;
- modifié les liens ici pour pointer vers les nouveaux (il y a redirection en attendant) ;
- supprimer les icônes de lien externe.
-
> revise les liens vers les informations légales

- app/helpers/paper_trail_helper.rb
Relevé par Élodie, pas d’Issue associée. Ce n’est pas une iframe, mais ça y ressemble un peu: VersionsController#index retourne du html, qui est inclus en ajax dans le layout de Admin::RdvsController#show.
Je n’ai pas rajouté de test, parce que ça demanderait un peu plus de travail : VersionsController n’est actuellement pas testé, et Admin::RdvsController en controller, alors que j’aurais besoin de Capybara. 
Après ce commit, le changement dans l’historique affiche l’id de l’objet supprimé, au lieu de planter en essayant de récupérer les détails:
> Corrige une 404 à l’affichage de l’historique d’un Rdv si un ancien Lieu a été supprimé

- app/controllers/application_controller.rb
- app/controllers/users/invitations_controller.rb
- app/controllers/users/registrations_controller.rb
- app/mailers/custom_devise_mailer.rb
- app/views/devise/mailer/invitation_instructions.html.erb
- app/views/users/invitations/edit.html.slim
- fixes #1328 
Quand un usage se crée un “nouveau” compte alors qu’il avait déjà un compte non-activé créé par un agent, on fait en fait une invitation au compte existante au lieu de créer un nouveau compte. Cette PR permet de passer les paramètres :first_name, :last_name, et :phone_number jusqu’au formulaire de validation de l’invitation, en passant par le lien dans le mail d’invitation.
Je sais pas exactement comment écrire des tests pour ça, je vais voir si j’arrive à un truc pertinent.
> Met à jour les paramètres de l’usager à sa véritable inscription

- app/helpers/agents_helper.rb
- app/models/agent.rb
- app/views/admin/absences/index.html.slim
- app/views/admin/agent_agendas/show.html.slim
- app/views/admin/plage_ouvertures/index.html.slim
- app/views/admin/rdv_wizard_steps/step3.html.slim
- app/views/admin/rdvs/edit.html.slim
- app/views/admin/territories/agent_territorial_roles/index.html.slim
- app/views/admin/territories/agent_territorial_roles/new.html.slim
- app/views/admin/territories/sector_attributions/_form.html.slim
- app/views/admin/territories/sectorisation_tests/_attribution.html.slim
- app/views/admin/territories/sectors/index.html.slim
- app/views/admin/users/show.html.slim
- app/views/layouts/_left_menu.html.slim
- app/views/layouts/registration.html.slim
- spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
- spec/features/agents/agent_can_crud_absences_spec.rb
- spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
Nous avions fait une PR (en fait avec un patch en plus) pour masquer le nom du service auquel un agent appartient. Je crois que c'est mieux de le remettre (en attendant que nous changions les mécanismes autour des services).
Cette PR est un (en fait deux) revert des commits en questions.
> Affiche le service a nouveau

- app/helpers/users_helper.rb
En testant des choses sur RDV-Solidarités cette après midi, j'ai constaté ce problème de liste des usagers.
C'est lié à une correction que j'avais proposé sur une règle rubocop. Je n'avais pas vérifié tous les écrans impactés.
> affiche correctement la liste des usagers d'un rdv

- app/views/admin/rdvs/show.html.slim
Pas de ticket sur ce point, mais une correction de la duplication d'un rdv.
Suite au message d'agent expliquant que la duplication ne fonctionne plus (depuis Zammad)
> corrige la duplication de rendez-vous

- app/mailers/admins/system_mailer.rb
- app/views/mailers/admins/system_mailer/rdv_events_stats.html.slim
- config/locales/mailers.fr.yml
- config/locales/models/rdv_event.fr.yml
refs #1026
Je n’ai pas fait grand chose de plus que traduire, mais c’est plus clair pour moi comme ça. Il y avait aussi un bug: on affichait les `today_stats` pour hier comme pour aujourd’hui.
Avant:
Après:
> Améliorations sur le mail quotidien de stats de mails et SMS

- app/webpacker/components/places-inputs.js
fixes #1363, refs #1285
Pour #1285, je pense qu’on devrait passer l’identifiant BAN complet et l’interpréter _au mieux_ côté serveur.
WIP: 
> Corrige la recherche d‘adresse avec un numéro de rue

- .github/workflows/ci.yml
- spec/services/notifications/rdv/rdv_cancelled_service_spec.rb
Pour faire en sorte que le test soit plus lisible et fonction à chaque heure de le journée
> fige le temps utilisé dans les tests

- app/controllers/admin/absences_controller.rb
- app/mailers/agents/absence_mailer.rb
- app/service_functions/admin/ics/absence.rb
- app/views/mailers/agents/absence_mailer/absence_created.html.slim
- app/views/mailers/agents/absence_mailer/absence_destroyed.html.slim
- app/views/mailers/agents/absence_mailer/absence_updated.html.slim
- spec/controllers/admin/absences_controller_spec.rb
- spec/mailers/previews/agents/absence_mailer_preview.rb
- spec/mailers/previews/agents/plage_ouverture_mailer_preview.rb
- spec/service_functions/admin/ics/absence_spec.rb
close #1051 
Envoie des fichiers ICS pour les créations, suppression et mise à jour d'absence. À la manière des plages d'ouverture.
> Envoie un ics pour le CUD des absences

- Gemfile
- Gemfile.lock
administrate currently crashes in rails 6.0.3.7 and 6.1.3.2 with the error “Please use symbols for polymorphic route arguments.”. A fix is coming in https://github.com/thoughtbot/administrate/pull/1972, but we can’t really wait, and we can’t rollback rails either.
👋 Coucou la team DS https://github.com/betagouv/demarches-simplifiees.fr/pull/6178
close #issue_number
> Fix superadmin after upgrade to rails 6.0.3.7

- app/controllers/admin/agents/rdvs_controller.rb
- spec/controllers/admin/agents/rdvs_controller_spec.rb
followup #1396
A priori, seul `admin/agents/:id/rdvs` est concerné, et pas `plage_ouvertures` ni `absences`.
> Filtre les RDV par date dans le json pour l’agenda

- app/controllers/application_controller.rb
- app/controllers/lieux_controller.rb
- app/controllers/users/rdv_wizard_steps_controller.rb
- app/controllers/users/rdvs_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/welcome_controller.rb
Pour permettre au 62 d'utiliser RDV-Solidarités dans une iframe.
Il y aurait peut-être quelque chose à creuser autour de composant qui s'intègre dans une application existante (pour l'interface usager)
> autorise les iframe

- app/dashboards/agent_dashboard.rb
- app/dashboards/organisation_dashboard.rb
- app/dashboards/user_dashboard.rb
Pour réparer https://sentry.io/organizations/rdv-solidarites/issues/2393361557/?project=1811205&query=is%3Aunresolved
En supprimant des dashboards, j'ai créé des erreurs dans la vue de certains éléments restants. Cette PR les nettoies.
> répare les dashboards restants du superadmin

- Gemfile
- Gemfile.lock
Avec bootsnap, la différence de performance est négligeable, et pour une raison que j’ignore et que je ne veux pas investiguer, ça fait tourner deux cores à 100%. Adrien me disait qu’il avait le même problème. @yaf tu en penses quoi?
> Remove Spring

- app/helpers/date_helper.rb
- app/mailers/agents/rdv_mailer.rb
- app/models/rdv.rb
- app/services/notifications/rdv/base_service_concern.rb
- app/services/notifications/rdv/rdv_cancelled_service.rb
- app/services/notifications/rdv/rdv_created_service.rb
- app/services/notifications/rdv/rdv_date_updated_service.rb
- app/views/mailers/admins/system_mailer/rdv_events_stats.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_starting_soon_cancelled.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_starting_soon_created.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_starting_soon_date_updated.html.slim
- app/views/mailers/common/_rdv_overview.html.slim
- config/locales/fr.yml
- config/locales/mailers.fr.yml
- spec/mailers/agents/rdv_mailer_spec.rb
- spec/mailers/previews/agents/rdv_mailer_preview.rb
- spec/services/notifications/rdv/rdv_date_updated_service_spec.rb
Préliminaire à  #1059, normalement aucun changement fonctionnel
* Ajustements de code style sur le partial rdv overview utilisé dans les mails
* Ajouts de helpers de date `soon?(date)` et `relative_date(date)`
* Déplacé les conditions d’envoi des emails aux agents dans le “base concern”, dans une méthode `should_notify_agent`. C’est là qu’on va prendre en compte les préférences.
> Refactor pour les notifications des agents 

- config/initializers/delayed_worker_class_reloading_patch.rb
Suite de #1447: en fait les soucis de performances sont dûs à delayed_job qui fait du polling sur la base (ce qui est [un peu scandaleux](https://github.com/collectiveidea/delayed_job/issues/584), mais bon) et qui [reload l’app](https://github.com/collectiveidea/delayed_job/issues/821) chaque seconde. Spring n’améliore pas le problème, mais n’était pas la cause principale. Au bout d’un moment, forcément, ça leake un peu.
> Prevent DelayedJob from reloading the app every second in development

- app/helpers/date_helper.rb
- app/mailers/agents/rdv_mailer.rb
- app/services/notifications/rdv/rdv_date_updated_service.rb
- spec/mailers/previews/agents/rdv_mailer_preview.rb
- spec/services/notifications/rdv/rdv_date_updated_service_spec.rb
Introduced in #1449
Of course, we can’t use rdv.attribute_before_last_save in the job. Huh.
> Fix a crash in Agents::RdvMailer#rdv_starting_soon_date_updated 

- app/controllers/admin/territories/sectors_controller.rb
- config/locales/views/admin_territories_sectors.fr.yml
close #1346
* redirige vers admin_territory_sector_path au lieu de admin_territory_sectors_path après un update
* corrige la redirection après création (qui se base sur le nom du bouton. Ce n’est pas idéal…)
* utilise i18n pour les messages
> Correction de la redirection après création/modification d’un secteur

- app/webpacker/components/places-inputs.js
`street_name` is a required param, but it’s not something that exists in the api according to https://geo.api.gouv.fr/adresse
Broken in #1384 🤷 
> Fix street-level sector zone creation

- app/controllers/admin/organisations/stats_controller.rb
- app/views/admin/organisations/stats/index.html.slim
- app/views/layouts/_left_menu.html.slim
- spec/features/agents/admin_can_see_the_organisation_stats_spec.rb
close #1404 
Rend visible les statistiques de l'organisation à tous les agents de l'organisation
> déplace les statistiques de l'organisation

- app/helpers/paper_trail_helper.rb
- spec/helpers/paper_trail_helper_spec.rb
fixes #1474
followup #1470
L’erreur 500 est visible à l’affichage des versions d’un Rdv, dans `admin/organisations/:organisation_id/rdvs/:id`.
> Fix Rdv versions history display

- app/services/send_transactional_sms_service.rb
- config/initializers/sendinblue.rb
- spec/services/send_transactional_sms_service_spec.rb
Deuxième étape, lié au #1408 
Maintenant que la base contient la configuration SMS, nous allons l'utilisé pour l'envoie des notifications.
**PR Clef dans la migration, les notifications doivent continuer à être envoyées après sa livraison :)**
> SMS-Configuration #2 Utilise la configuration sms en db link to 1408

- app/models/rdv.rb
- config/locales/models/rdv.fr.yml
- spec/controllers/admin/agents/rdvs_controller_spec.rb
- spec/controllers/admin/rdvs_controller_spec.rb
- spec/factories/rdv.rb
- spec/features/agents/admin_can_see_the_organisation_stats_spec.rb
- spec/features/agents/agent_can_see_his_stats_spec.rb
- spec/features/anybody/anybody_can_see_stats_spec.rb
- spec/features/users/user_views_his_rdvs_spec.rb
- spec/form_models/admin/edit_rdv_form_spec.rb
- spec/form_models/admin/rdv_search_form_spec.rb
- spec/models/concerns/has_phone_number_concern_spec.rb
- spec/models/file_attente_spec.rb
- spec/models/rdv_spec.rb
- spec/models/user_spec.rb
- spec/presenters/admin/rdv_user_presenter_spec.rb
- spec/rails_helper.rb
- spec/service_functions/rdv_exporter_spec.rb
- spec/service_models/agent_removal_spec.rb
close #1427 
Le problème a été résolu en corrigeant les dates de rendez-vous posé dans le passé (sans doute par erreur de saisie).
Pour limiter (empêcher ?) la reproduction de ce problème, nous ajoutons une limitation sur la création de rendez-vous dans le passé.
> empêche de poser des rendez-vous dans le passé

- app/models/concerns/has_phone_number_concern.rb
- app/models/concerns/user/improved_unicity_error_concern.rb
- config/locales/models/user.fr.yml
- spec/factories/user.rb
- spec/models/concerns/has_phone_number_concern_spec.rb
close #1471
* Validation spéciale pour les numéros de téléphone, avec les DROM concernés. La référence est ce document https://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf sur le site de l’ARCEP. (Il y a plusieurs section, le Plan de Numérotation commence après 16 pages).
* Affichage d’un indice sur les numéros acceptés: <img width="668" alt="Capture d’écran 2021-05-31 à 17 02 11" src="https://user-images.githubusercontent.com/139391/120212593-77dc1f00-c232-11eb-8e34-e44d426b2afa.png">
* Petites corrections au passage sur les erreurs et les numéros de téléphone dans les tests.
> Autorise les numéros de téléphone ultramarins

- scripts/load_absences_csv.rb
- spec/features/agents/agent_can_manage_recurrence_on_plage_ouverture_spec.rb
- spec/form_models/admin/rdv_search_form_spec.rb
Modifie la façon de récupérer les colonnes (qui ont changées de nom).
Je suis obligé aussi de corriger un test (mais pourquoi échoue-t-il maintenant ?).
Et je vois encore la lourdeur de l'usage des organisations.
> utilise le numéro de colonne plutôt que le nom

- app/models/rdv.rb
- spec/models/rdv_spec.rb
Nous bloquons la création de rendez-vous dans le passé. Mais nous pouvons déplacer un rendez-vous dans le passé.
Cette PR permet ajoute le blocage en case de mise à jour également.
Nous considérons qu'il est possible de créer ou modifier un rendez-vous 2 jours dans le passé, pas plus loin.
TODO : traiter le message d'erreur vraiment pas beau « Starts at doit être dans le futur » :confused: 
> Bloque l'enregistrement de rdv dans le passé

- app/mailers/agents/rdv_mailer.rb
- app/mailers/users/rdv_mailer.rb
- app/models/concerns/payloads/rdv.rb
- app/services/notifications/rdv/rdv_cancelled_service.rb
- app/services/notifications/rdv/rdv_created_service.rb
- app/services/notifications/rdv/rdv_date_updated_service.rb
- app/services/notifications/rdv/rdv_upcoming_reminder_service.rb
- app/views/mailers/agents/rdv_mailer/rdv_cancelled.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_created.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_date_updated.html.slim
- app/views/mailers/common/_rdv_overview.html.slim
- app/views/mailers/users/rdv_mailer/rdv_cancelled.html.slim
- db/seeds.rb
- spec/mailers/agents/rdv_mailer_spec.rb
- spec/mailers/previews/agents/rdv_mailer_preview.rb
- spec/mailers/previews/users/rdv_mailer_preview.rb
- spec/mailers/users/rdv_mailer_spec.rb
- spec/services/notifications/rdv/rdv_cancelled_service_spec.rb
- spec/services/notifications/rdv/rdv_created_service_spec.rb
- spec/services/notifications/rdv/rdv_date_updated_service_spec.rb
- spec/services/notifications/rdv/rdv_upcoming_reminder_service_spec.rb
refs #1361
- passe un payload (un hash) des attributs du Rdv au lieu de passer le Rdv en lui-même. Ainsi, le job peut être exécuté même si le Rdv est supprimé entretemps.
> [RDVJobs 3/N] Passe un payload au job d’envoi de mail plutôt qu’un record

- app/controllers/users/creneaux_controller.rb
- app/views/users/creneaux/_creneaux.html.slim
- spec/controllers/users/creneaux_controller_spec.rb
close #1479 
Dans un rendez-vous mis en file d'attente ;
Si un créneau se libère, il est proposé à l'usager ;
Il peut le choisir pour avancer son rendez-vous.
Le hic, c'est que nous ne changions que la date et l'heure. Or les nouveaux créneaux proposés sont calculé à partir du motif du rendez-vous, sur tous les agents qui le proposent donc.
Cette PR prend en compte la mise à jour de l'agent chargé du rendez-vous dans le cas d'une modification de rendez-vous via file d'attente.
L'analyse de ce problème m'a permis de faire une doc sur la file d'attente. C'est peut-être une bonne idée d'y jeter un coup d'œil pour vérifier que c'est clair  https://doc.rdv-solidarites.fr/tutoriels/file-dattente
> prend en compte l'agent du nouveau créneau

- .gitignore
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Puisque nous nous apprêtons à revoir les tests de « feature », je préfère avoir un outil pour vérifier que nous couvrons toujours une bonne partie du code.
> ajoute simplecov

- Gemfile
- Gemfile.lock
- app/views/common/_creneaux.html.slim
- app/views/mailers/common/_rdv_overview.html.slim
- app/views/users/rdvs/_rdv.html.slim
Close #1483 
Ajout de [autolink](https://github.com/tenderlove/rails_autolink), et mise en place aux endroits où l'on affiche les consignes.
_Merci @n-b pour la suggestion_
> ajoute autolink pour avoir des liens clickable

- app/jobs/send_transactional_sms_job.rb
- app/models/concerns/payloads/rdv.rb
- app/models/file_attente.rb
- app/service_models/transactional_sms/base_concern.rb
- app/service_models/transactional_sms/rdv_cancelled.rb
- app/service_models/transactional_sms/rdv_created.rb
- app/service_models/transactional_sms/rdv_updated.rb
- app/service_models/transactional_sms/reminder.rb
- app/services/notifications/rdv/rdv_cancelled_service.rb
- app/services/notifications/rdv/rdv_created_service.rb
- app/services/notifications/rdv/rdv_date_updated_service.rb
- app/services/notifications/rdv/rdv_upcoming_reminder_service.rb
- app/services/send_transactional_sms_service.rb
- app/views/mailers/common/_rdv_overview.html.slim
- app/views/mailers/users/rdv_mailer/rdv_cancelled.html.slim
- spec/service_models/transactional_sms/base_concern_spec.rb
- spec/service_models/transactional_sms/file_attente_spec.rb
- spec/service_models/transactional_sms/rdv_cancelled_spec.rb
- spec/service_models/transactional_sms/rdv_created_spec.rb
- spec/service_models/transactional_sms/rdv_updated_spec.rb
- spec/service_models/transactional_sms/reminder_spec.rb
- spec/services/send_transactional_sms_service_spec.rb
refs #1361
- idem à #1487, mais pour les SMS cette fois-ci: passe un payload (un hash) des attributs du Rdv au lieu de passer le Rdv en lui-même. Ainsi, le job peut être exécuté même si le Rdv est supprimé entretemps.
> [RDVJobs 4/N] Passe un payload au job d’envoi de sms plutôt qu’un record

- app/views/admin/rdvs/show.html.slim
fixes #1439
Je ne sais pas exactement quel était le problème: en gros, j’ai l’impression que mettre un `div` dans un `li` dans le `.breadcrumb` dans `.page-title` ça pose problème. À vue de nez, breadcrumb utilise une flexbox, et ça fait des choses bizarre.
> Corrige l’affichage du titre du Rdv

- .rubocop.yml
- app/mailers/agents/absence_mailer.rb
- app/mailers/agents/plage_ouverture_mailer.rb
- app/mailers/agents/rdv_mailer.rb
- app/mailers/application_mailer.rb
- app/mailers/concerns/ics_multipart_attached.rb
- app/mailers/users/rdv_mailer.rb
- app/models/concerns/ical_helpers/ics.rb
- spec/mailers/agents/plage_ouverture_mailer_spec.rb
- spec/mailers/users/rdv_mailer_spec.rb
- spec/models/concerns/ical_helpers/ics_spec.rb
* use a single helper for all emails
* base64-encode the attached ics file
* properly use PUBLISH/CANCEL methods
refs #1354
> Unify and cleanup icalendar email attachment

- .rubocop.yml
- app/service_functions/rdv_updater.rb
- spec/service_functions/rdv_updater_spec.rb
> Corrige l’envoi de trop de notifications pour les changements de Rdv

- app/controllers/admin/creneaux/agent_searches_controller.rb
- app/models/lieu.rb
- spec/controllers/admin/creneaux/agent_searches_controller_spec.rb
- spec/models/lieu_spec.rb
close #1530 
Nous avions oublié de filtrer les lieux dans le formulaire de recherche de créneaux coté agent. Cette PR corrige cette oublie.
> affiche uniquement les lieux ouverts

- app/webpacker/components/analytic.js
Je crois qu’on envoie pas d’évènement à matomo quand on navigue “via turbolinks”, c’est à dire 99% du temps en usage normal. Si je lis bien le code, on n’envoie de hit que pour la visite de la première page (et pour les modales). On avait le même problème sur PDE et sur DS 😁 
> Send matomo hits even when navigating with turbolinks

- app/mailers/concerns/ics_multipart_attached.rb
- spec/mailers/agents/plage_ouverture_mailer_spec.rb
- spec/mailers/users/rdv_mailer_spec.rb
This is a return to what we used to do before #1531. Fixes #1354
Quoted-printable would make sense, and this is what Google Calendar uses.
However, with quoted-printable, Rails (in quoted-printable.rb) uses “pack("M")” which gives `=OD\n`.
I’m not 100% sure if this is fine by the specs.(See RFC2045) But:
* We know that Zimbra doesn’t like it very much: when the application/ics attachment is encoded as such, zimbra decodes it as CRCRLF and its icalendar parsing library crashes.
* Outlook apparently does not automatically interpret the text/calendar part anymore, since #1531
> Encode the text/calendar part of emails as base64 too

- app/views/admin/users/_responsible_form_fields.html.slim
- app/webpacker/packs/application.js
- app/webpacker/packs/application_agent.js
- config/locales/models/user.fr.yml
- package.json
- spec/factories/user.rb
- yarn.lock
Je suis tombé dessus en essayant de comprendre pourquoi je n’arrivais pas à taper de “+” dans les numéros de téléphone des users: en fait c’était fait exprès dans #336. On a mis PhoneLib depuis, donc c’est globalement inutile, et gênant.
> Permet de saisir des numéros de téléphone au format international

- config/locales/fr.yml
From the docs https://apidock.com/ruby/DateTime/strftime :
>  %d - Day of the month, zero-padded (01..31)
>          %-d  no-padded (1..31)
>  %e - Day of the month, blank-padded ( 1..31)
We probably never should use %e.
> Tweak day padding in date formats

- app/models/concerns/payloads/rdv.rb
- app/service_models/transactional_sms/base_concern.rb
- app/services/notifications/rdv/rdv_cancelled_service.rb
- app/services/notifications/rdv/rdv_created_service.rb
- app/services/notifications/rdv/rdv_date_updated_service.rb
- app/services/notifications/rdv/rdv_upcoming_reminder_service.rb
- app/views/mailers/common/_rdv_overview.html.slim
close #1062
* dans les emails, les usagers concerné par le Rdv sont maintenant systématiquement indiqués
* dans les sms, les usagers sont indiqués si besoin: si le destinataire a des `relatives`.
> Indique les noms des usagers dans les notifications en cas d’ambiguïté

- app/controllers/api/v1/users_controller.rb
- app/controllers/users/invitations_controller.rb
- db/migrate/20210707150348_add_after_accept_path_to_users.rb
- db/schema.rb
Dans cette PR j'ajoute une colonne `after_accept_path` à la table `users` qui, si elle est remplie redirige l'utilisateur vers un chemin spécifique après qu'il ait accepté son invitation.
Je donne également la possibilité de renseigner ce  champ par l'api au moment de la création de l'utilisateur.
> feat(invitations): Redirect user after invitation accepted

- app/views/admin/rdvs/show.html.slim
close #1043 
Le lien supprimer d'un rendez-vous est visible de toutes et tous. Cette PR le rend visible que des profils admin, et il apparait dans un texte qui évoque ce qu'il va se passer en supprimant le rendez-vous de cette manière.
> limite l'accès au bouton de suppression de RDV

- app/blueprints/user_blueprint.rb
Je rajoute l'attribut `phone_number_formatted ` aux utilisateurs renvoyés par l'API.
Cet attribut nous est utile pour envoyer correctement le SMS d'invitation.
> Add phone number formatted to user blueprint

- app/models/concerns/payloads/rdv.rb
- app/views/mailers/common/_rdv_overview.html.slim
- spec/models/concerns/payloads/rdv_spec.rb
Close #1587 
Suppression du nom et prénom de l'usager dans le résumé du RDV du fichier ICS
> retire le nom et prénom usager dans le summary ics

- app/controllers/admin/users_controller.rb
- app/views/admin/rdv_wizard_steps/step2.html.slim
- app/views/admin/users/_duplicate_alert.html.slim
- app/views/admin/users/_form.html.slim
Close #1594 
Après la création d'un usager existant dans une autre organisation, nous devrions pouvoir le choisir puis continuer dans le tunnel. Ce n'est pas le cas avant cette PR.
Maintenant, si l'usager créer existe sur une autre organisation, la proposition de l'utiliser (et l'association à l'orga courante) nous renvoie vers le tunnel de prise de rendez-vous avec cet usager sélectionné.
> Ajoute l'usager d'une autre orga dans l'orga courant et continue le tunnel de prise de rendez-vous

- app/mailers/admins/grc_92_mailer.rb
Après avoir fait des essais en démonstration, nous avons constaté avec les personnes du 92 qu'il y a un problème.
Notre piste nous amène à penser que c'est lié au format du mail. L'outil de mail2sms mis en place n'accepte pas les messages en HTML. Il faut donc l'envoyer en texte brut.
> Intègre les mécanismes d'appel pour le 92

- app/models/user.rb
- spec/models/user_spec.rb
Close #1605 
Réduire le blocage pour la suppression de proche.
Lorsque le proche n'a pas de rendez-vous, pas la peine de le bloquer quand le repsonsable à un rendez-vous
> ajoute de tests sur la possibilité de suppression

- app/views/admin/rdvs/_rdv.html.slim
- app/views/admin/rdvs/_rdv_status_dropdown.html.slim
- app/views/admin/rdvs/show.html.slim
- app/webpacker/stylesheets/components/_dropdown.scss
- config/locales/rdvs.fr.yml
- spec/features/agents/agent_can_see_users_rdv_spec.rb
- spec/features/users/user_views_his_rdvs_spec.rb
- spec/helpers/rdvs_helper_spec.rb
Fait en passant pour #1615
Avant:
Après
Le titre est centré verticalement, capitalisé, et les items du menu sont des items (et pas des headers).
> Ajustements sur les cartes de Rdv

- app/views/admin/rdv_wizard_steps/step2.html.slim
- app/views/admin/users/_form.html.slim
- app/webpacker/components/select2-inputs.js
Close #1604
* Fix select2 with bootstrap modals
* Widen the main user select
* Use the json ajax query for the responsible select, and avoid inlining all the users in the html.
> Corrige les sélecteurs d’usagers dans le tunnel de Rdv

- config/initializers/content_security_policy.rb
See https://docs.mapbox.com/mapbox-gl-js/guides/browsers-and-testing/
This fixes this error in Safari “[Error] Refused to load blob:https://demo.rdv-solidarites.fr/e520bb03-70c7-4eff-a43a-8da69bdb0b94 because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.”
I suspect Safari interprets CSP and blob urls differently, or the default values are different from other browsers.
This makes the sectors map work correctly on Safari.
> Add “blob:” to CSP as per mapbox recommendations

- app/webpacker/components/select2-inputs.js
Followup #1618
`closest()` n’existe pas sur IE11, et si j’en crois sentry c’est encore une bonne part de nos utilisateurs.
Du coup, utilisons jQuery 🥲. J’ai testé sur browserstack, ça a l’air de marcher.
fixes RDV-SOLIDARITES-R9
fixes RDV-SOLIDARITES-RB
fixes RDV-SOLIDARITES-RD
fixes RDV-SOLIDARITES-RE
fixes RDV-SOLIDARITES-QY
fixes RDV-SOLIDARITES-QX
> Fix the select2 dropdown js patch for IE

- config/initializers/content_security_policy.rb
fixes RDV-SOLIDARITES-QM
Manifestement notre CSP n’est pas configuré correctement pour stats.data.gouv.fr, on a pas mal d’erreurs. Je comprends pas trop pourquoi ça semble marcher 🤷 .
> CSP: Add stats.data.gouv.fr to connect-src

- app/views/admin/rdvs/_rdv_status_dropdown.html.slim
At some point we’ll have to get rid of one of these two methods.
> Allow changing to noshow as soon as the Rdv is started

- .rubocop.yml
- app/controllers/admin/absences_controller.rb
- app/helpers/absences_helper.rb
- app/jobs/cron_job.rb
- app/models/absence.rb
- app/models/concerns/expiration.rb
- app/models/plage_ouverture.rb
- db/migrate/20210820115346_add_expire_to_absence.rb
- db/schema.rb
- spec/controllers/admin/absences_controller_spec.rb
- spec/helpers/absences_helper_spec.rb
- spec/models/concerns/expiration_spec.rb
Close #1613 
Affiche dans les présents les absences dont la date de fin est passé, mais pour lesquelles la récurrence est encore valable.
> expire les absences selon la récurrence

- app/models/rdv.rb
- config/locales/models/rdv.fr.yml
- spec/models/rdv_spec.rb
fixes #1600
WIP: Il faut aussi corriger les quelques Rdv en erreur en production:
```
> Rdv.where(starts_at: Time.zone.now + 2.years..).map{ |rdv| [rdv.id, rdv.starts_at.to_date.iso8601, rdv.created_at.to_date.iso8601, rdv.agents.ids] }.sort
```
J’ai prévenu les agents concernés pour les rdv créés cet été, et on peut leur laisser corriger. Concernant les deux plus anciens, je pense qu’on peut les supprimer manuellement.
> Prevent creating Rdv more than two years in advance

- app/webpacker/stylesheets/components/_rdv_status.scss
Close #1650 
Lors d'un petit réusinage, nous avons sans doute ajouté un sélecteur sur un lien, alors que dans la page de statistique public, il n'y a pas de lien, c'est uniquement une div.
> replace couleurs de fonds pour les stats public

- app/webpacker/stylesheets/components/_rdv_status.scss
Ce sont des `.fa.fa-circle`, mais depuis #1652 on leur donnait la même background-color et color:
C’est corrigé:
J’ai vérifié que ça ne cassait pas l’affichage dans les stats publiques et privés, et dans les petits labels de status (les `rdv_status_tag`). Je crois que c’est bon.
> Corrige les icônes arrondies dans le menu des status

- config/initializers/content_security_policy.rb
It uses iframes, so we have to allow self
> Fix CSP for letter_opener

- app/models/stat.rb
- app/views/stats/index.html.slim
- app/webpacker/stylesheets/components/_rdv_status.scss
refs #1678
Also reorder statuses so that excused and revoked are neighbours
> Tweak stats colors for rdv by status

- Gemfile
- Gemfile.lock
- app/controllers/admin/absences_controller.rb
- app/controllers/admin/plage_ouvertures_controller.rb
- app/views/admin/absences/index.html.slim
- app/views/admin/plage_ouvertures/index.html.slim
- app/views/layouts/_left_menu.html.slim
- app/views/layouts/application_agent.html.slim
- app/views/layouts/application_agent_departement.html.slim
- app/webpacker/stylesheets/_variables.scss
Le lien est `active` si le path de la page visitée contient celui du lien. A priori, ça marche à peu près partout, peut-être qu’il reste des endroits où on a fait des choses compliquées avec les routes, mais ça devrait aller. Ça simplifie pas mal certains trucs inutiles.
La prochaine fois je retirerai les `content_for(:menu_item)` :)
> Add active_link_to and use it for all “active” classes in links

- app/sms/application_sms.rb
fixup #1686
PR directement vers `production`: c’est un petit bug qui corrige une évolution déjà en prod.
> Make sure to use the :sms queue for SMSSender jobs

- app/views/welcome/welcome_departement.html.slim
- config/locales/views/welcome.fr.yml
Close #1701 
Affiche uniquement les services disponible (issue de la liste affichée pour les filtres) dans le titre de la page de recherche des usagers.
> Affiche les services disponible sur l'accueil usager

- app/webpacker/stylesheets/components/_rdv_solidarites_instance_name.scss
This broke the banner in emails: the html for the emails are rendered in a job, and the css styles are inlined, which means the media queries are resolved in a weird context. In practice, this meant the banner had a `display: none` style in emails. 🙈
> Always display the instance name banner, regardless of width

- scripts/import_motifs_libelles.rb
Pour corriger l'alerte linter que je n'avais pas vu en forçant le passage la première fois.
> Sécurise l'ouverture du fichier

- app/controllers/super_admins/application_controller.rb
- app/views/admin/motifs/index.html.slim
Close #1726 
Ajoute une zone de pagination en bas de la page des motifs
> Ajoute zone de pagination en bas de page motifs

- app/webpacker/stylesheets/structure/_page-head.scss
fixes #1674
L’alternative serait de garder ce css mais de mettre le bouton “trouver un créneau” ailleurs, mais franchement, quand je peux fixer un bug en supprimant du code… (Je trouve ça vraiment contre-intuitif de mettre des “display: none” pour des portions de l’interface.)
> Remove the “display: none” for the page title on small screens

- app/jobs/cron_job.rb
- spec/jobs/cron_job/reminder_job_spec.rb
Followup ruby 3 #1712
fixes #1749
> Prevent a crash in ReminderJob

- app/controllers/api/v1/rdvs_controller.rb
- config/routes.rb
- spec/requests/api/v1/rdvs_request_spec.rb
J'ajoute ici un endpoint permettant de récupérer les rdvs d'une organisation, endpoint dont on aura besoin de manière sporadique côté RDV Insertion.
À noter que je n'ai pas ajouté la route `GET api/v1/rdvs` non scopée à une organisation pour être homogène car au vu de [la policy actuelle](https://github.com/betagouv/rdv-solidarites.fr/blob/863f217b24a955d4e01d2e7df4c8a8e73a3d2289/app/policies/agent/rdv_policy.rb#L9) ça ne renverrait rien.
> feat(api): Add rdvs index endpoint

- app/views/admin/rdvs/_rdv_search_form.html.slim
- app/views/admin/rdvs/index.html.slim
refs #1754
Utiliser le service de recherche js plutôt que de mettre les milliers d’usagers dans le select.
* Il faut faire la même chose avec les agents, même si en principe c’est moins grave, il y en a moins. C’est le point d’après, parce que ce service de recherche n’existe pas; il faut aussi le créer pour le left_menu.
* Je craignais qu’il faille attendre que les colonnes `tsvector` soit implémentées pour mettre ça en prod, parce que ça pourrait augmenter le nombre de recherches full text. Cependant, `Admin::UsersController#search` limite le nombre de résultats à 10, donc en fait ça va très bien.
Benchmark rapide, meilleur temps sur une quinzaine de rechargements de la page:
Avant:
```
16:29:22 web.1     | Started GET "/admin/organisations/443/rdvs" for 127.0.0.1 at 2021-09-29 16:29:22 …
```
> 🚀 [perf] Faster rdv search form

- app/controllers/admin/agents_controller.rb
- app/controllers/admin/invitations_controller.rb
- app/controllers/admin/motifs_controller.rb
- app/controllers/admin/users_controller.rb
- config/brakeman.ignore
- spec/models/user_spec.rb
fixes #1836
En fait, la recherche pg fonctionne déjà bien; simplement, dans la plupart des cas, on forçait le tri par last_name. 🤷 
(Le nouveau test n’est pas tellement utile: il ne teste que le tri des résultat dans `search_by_text`, mais pas le comportement des controllers.)
> Fix search results ordering in controllers

- app/views/admin/rdvs/index.html.slim
followup #1820
Fix an error 500 when displaying `/admin/organisation/:id/rdvs` when coming from another page and a `:breadcrumb_page` param is passed. The passed `:status` may be a “temporal status” which is not a real valid `status` enum, and it breaks when casting inside `human_attribute_value`.
fixes RDV-SOLIDARITES-WG
> Fix a 500 in /rdvs when coming from another counter

- .env.sample
- config/environments/development.rb
- docs/4-notes-techniques.md
See https://developer.apple.com/forums/thread/682332. The default configuration in macOS 12 (Monterey) runs the Airplay Server on the port 5000. This is unfortunate, but there’s not much we can do about it.
Also, use ENV["HOST"] in relevant places.
Again: this is only for the development environment.
> Change the default puma port for development, because of macOS 12

- scripts/agent_et_motif_changent_de_service.rb
Avec RDV Insertion nous commençons à embarquer des départements utilisant déjà RDV-Solidarités tels que l'Aveyron.
Ces organisations utilisent déjà RDV-Solidarités pour le RSA mais sous le service social au lieu du service RSA (car celui-ci n'existait pas il me semble).
Je modifie donc le script de changement de service des motifs et des agents d'une organisation en:
* ajoutant la possibilité de passer les ids des services et de l'orga concernée au script
* ajoutant un "dry run" mode
* soft deletant les motifs changés pour éviter d'avoir des motifs identiques qui s'affichent dans la liste de motifs
J'ai juste un doute sur l'utilisation de ce script si des agents sont liés au service social n'ont pas **que** des motifs de rdvs liés au RSA: en utilisant ce script des motifs de rdvs non liés …
> feat(script): change service swap script

- app/models/concerns/recurrence_concern.rb
- spec/models/concerns/recurrence_concern_spec.rb
Close #1855 
Ajoute une validation sur la date de fin
> vérifie fin de récurrence après début

- app/controllers/admin/rdvs_controller.rb
- app/models/agent.rb
- app/models/motif.rb
- app/models/user.rb
- app/views/admin/rdvs/_short_rdv.html.slim
- app/views/admin/rdvs/_short_rdvs_list.html.slim
- app/views/admin/rdvs/index.html.slim
refs #1754
Sur skylight, à part la recherche de créneau, les pages les plus coûteuses sont les index et show de Rdv et User. En principe tout ça se garde assez bien en cache, pour peu que les `updated_at` soient tenus à jour proprement. Il y a peut-être quelques pièges sur des objets liés qui sont affichés 🤔. 
Sur rdvs/index, avant :
```
Rendered collection of admin/rdvs/_rdv.html.slim [0 / 25 cache hits] (Duration: 944.2ms | Allocations: 674007)
...
Completed 200 OK in 1090ms (Views: 1025.3ms | ActiveRecord: 48.6ms | Allocations: 756157)
```
Après:
```
Rendered collection of admin/rdvs/_rdv.html.slim [25 / 25 cache hits] (Duration: 2.0ms | Allocations: 1140)
...
Completed 200 OK in 126ms (Views: 100.7ms | ActiveRecord: 14.4ms | Allocations: 81435)
```
> Cache rdvs in index and show

- app/helpers/i18n_cache_helper.rb
- app/views/admin/rdvs/_short_rdvs_list.html.slim
- app/views/admin/rdvs/index.html.slim
Followup #1847. Make sure the fragments cached are invalidated when the translations change.
WIP: Merge #1847 d’abord
> Make fragment caching locale-aware

- app/views/admin/users/index.html.slim
Encore un fix de performances en passant. Je ne sais pas combien de liste complète d’agents et d’usagers on affichait dans l’interface 🙈
J’aimerais bien faire un helper à la place de ce bout de code vraiment pas élégant, mais à chaque fois qu’on le duplique il y a une variante quelque part, je ne vois pas trop comment faire bien. En attendant, je duplique…
> Ne pas afficher la liste complète des agents dans le formulaire de recherche des Users

- app/blueprints/motif_blueprint.rb
- app/controllers/api/v1/motifs_controller.rb
- spec/requests/api/v1/motifs_request_spec.rb
Dans cette PR j'ajoute la possibilité de filtrer les motifs par service quand on récupère les motifs par l'API. 
En effet nous nous ne voulons récupérer que les motifs liés aux RSA.
J'ajoute également le `service_id` au blueprint qui pourrait nous être utile.
> feat(api): Filter motifs on services

- .env.sample
- app/jobs/cron_job.rb
- app/services/scalingo_app_restarter.rb
- docs/4-notes-techniques.md
fixes #1866
🧹 Ne pas oublier de mettre les variables d’environnement avant de déployer en prod. Il faut créer un token d’api sur l’un de nos comptes.
> 🧹 Self-restart all Scalingo containers everynight at 2AM

- app/views/layouts/_rdv_a_renseigner.html.slim
- app/views/layouts/application_agent.html.slim
Correction d'un petit pépin lié au bandeau pour les RDV à renseigner.
Tel que c'est fait, nous ne pouvons plus aller sur la page d'administration d'un territoire.
Ceci est un patch rapide où j'ajoute à la condition d'affichage du bandeau une vérification sur le fait que `current_organisation` est définie. Quand je vois le code des layouts, je me dis qu'il y a un sacré remaniement à y faire. Mais là, je n'ai pas l'énergie pour ça. Trop d'autres trucs sur le feu.
> affiche la page sans current_orga

- config/initializers/content_security_policy.rb
- docs/5-decisions-techniques.md
Close #1877 
En vue de rendre RDV-Solidarité accessible, le script ANDI a été ajouté au content security policy afin que les personnes qui travaillent, ou participent de manière ponctuelle, sur le projet puisse utiliser l'outil ANDI. Il n'est cependant accessible que depuis l'environnement de développement.
> Ajoute script andi

- Gemfile
- Gemfile.lock
- app/views/admin/rdvs/index.html.slim
En cliquant sur “à renseigner” depuis “Mes statistiques”. On devrait retirer ce concept de breadcrumb, je pense.
fixes [RDV-SOLIDARITES-WG](https://sentry.io/organizations/rdv-solidarites/issues/2762864691/?environment=production&project=1811205&query=is%3Aunresolved).
> Fix a crash in /rdvs from stats

- app/models/rdv.rb
Close #1896 
C'est en fait plus large qu'évoqué sur le ticket.
Le problème vient du callback utilisé : `after_commit`. À ce stade, l'objet n'est plus considéré comme un `new_record` (et peut-être pas comme un `destroyed` mais je n'ai pas vérifié).
J'ai l'impression qu'au niveau performance, c'est à peu près correct de refaire le calcul chaque fois qu'un RDV du passé est modifié, créé ou supprimé.
> Recompte les « à renseigner » pour un RDV passé

- app/webpacker/stylesheets/components/_breadcrumb.scss
> Fix links color in breadcrumbs

- app/models/concerns/expiration.rb
- spec/models/absence_spec.rb
- spec/models/concerns/expiration_spec.rb
Les absences, contrairement aux plages d'ouverture, ont une date de fin en dehors de la récurrence. Il faut la prendre en compte dans le calcul d'expiration.
Pour être plus cohérent, nous pourrions la supprimer. Cela dit, il faudra prévoir un script pour créer les récurrences correspondantes aux absences que nous modifierions ainsi... À voir plus tard. Peut-être que nous pourrions aussi simplement supprimer les absences ? :smiling_imp: 
> :rocket: Prend en compte le cas de la date de fin d'absence or récurrence

- app/views/admin/creneaux/agent_searches/index.js.erb
- app/views/admin/rdvs/update.js.erb
- app/views/lieux/show.js.erb
- app/views/users/creneaux/index.js.erb
It can happen if we have concurrent queries. This leads to many noisy errors in sentry.
> Mute errors in sentry when the search element is not found

- app/dashboards/organisation_dashboard.rb
- app/dashboards/service_dashboard.rb
- app/dashboards/user_dashboard.rb
Et éviter les consommations dramatyiques de mémoire. Ça semble être une cause de #1912 et d’autres problèmes de performance: lors du chargement d’un formulaire d’usager dans Administrate, on voit un pic mémoire de 1 go (!!!), parce que Administrate charge l’intégralité des objets pour le champ “HasMany”.
C’est a priori un problème existant: https://github.com/thoughtbot/administrate/issues/1464
Le symptôme chez nous était donc: quand un superadmin affiche le formulaire d’un User ou d’une Organisation avec beaucoup d’agents dans superadmin, la consommation mémoire du container qui a répondu double et le container commence à swapper, et les performances tombent.
Cette PR supprime les champ HasMany vers des User ou des Agents dans les dashboards correspondants.
😩😩😩😩😩 
> Améliorer les performances dans superadmin

- app/helpers/creneaux_helper.rb
- app/views/admin/creneaux/agent_searches/_creneaux.html.slim
- app/webpacker/stylesheets/components/_creneaux.scss
Close #1848
Ajoute couleurs sur les créneaux disponibles afin de distinguer les différents agents dispos.
Avant : 
Après: 
> distingue agents lors proposition creneaux

- app/controllers/admin/organisations_controller.rb
- app/helpers/organisations_helper.rb
- app/models/organisation.rb
- app/views/layouts/_left_menu.html.slim
- app/views/layouts/application_agent_departement.html.slim
- spec/features/users/user_signs_up_and_signs_in_spec.rb
- spec/helpers/organisations_helper_spec.rb
Pour faire suite au message d'Irène (83), et à des réflexions dans l'équipe, cette PR permet d'afficher la page de checklist que pour les agents admin (et toujours uniquement la première semaine)
Avant, un agent non admin avait la page de checklist 
> affiche la checklist que pour les agents admin

- app/views/admin/organisations/index.html.slim
refs #1922 
Il manque un paramètre sur un appel au helper de lien pour l'accueil agent sur les organisations.
> ajoute l'agent sur le lien pour l'accueil agent

- app/controllers/api/v1/organisations_controller.rb
- app/views/search/_banner.html.slim
- spec/requests/api/v1/organisations_request_spec.rb
Sur RDV-Insertion, on veut permettre à un agent qui appartiendrait à toutes les organisations d'un territoire de pouvoir créer/inviter une personne au niveau du territoire.
Pour cela on cherche à identifier l'organisation lié au secteur dans lequel se trouve l'allocataire, afin de le créer/inviter sur cette organisation.
Pour se faire, nous géolocalisons l'adresse de l'allocataire côté RDV-I, et on aimerait donc savoir quels secteurs sont attribués à cet allocataire sur RDV-Solidarités (en supposant bien entendu que des secteurs ait été attribué à des organisations au préalable). 
Cette PR rajoute cette possibilité de filtrer les organisations sur l'endpoint `GET api/v1/organisations`.
Je profite de cette PR pour glisser un fix sur le texte d'invitation dans les nouvelles vues 👀 .
> feat(api): Retrieve geolocated organisations

- app/views/admin/slots/_slots.html.slim
refs #1891 
Corrige la recherche d'index pour que le numéro de couleur soit différent d'un agent à l'autre
> Affiche des couleurs différentes

- app/models/agent.rb
- spec/models/agent_spec.rb
Close #1893 
Ajout d'un `has_many` et de la suppression des attributions dans le `soft_delete`. Les attributions n'ont pas d'intérêt à être gardées.
> Supprime les attributions de secteur avec l'agent

- app/form_models/concerns/admin/rdv_wizard_form_concern.rb
When a rdv was being created for a “phone” motif, with a user without a phone number.
followup #1932
fixes RDV-SOLIDARITES-ZG
> 🚀  Fix errors not being displayed properly in step2 of rdv wizard

- app/services/creneaux_builder_service.rb
- app/services/search_creneaux_for_agents_service.rb
- app/views/admin/creneaux/agent_searches/index.html.slim
- app/views/admin/slots/index.html.slim
- spec/services/creneaux_builder_service_spec.rb
~~J'imagine que c'est mieux direct en prod, mais ce n'est pas si urgent que ça non plus. Ce n'est pas un bug à proprement parlé, plutôt un inconfort.~~
Nous affichions la page des créneaux avec les dates alors qu'il n'y a aucune disponibilité (dans certains cas). Autant faire en sorte de ne pas afficher cette page.
> :rocket: Affiche les pages de créneaux seulement s'il y en a

- app/controllers/application_controller.rb
- app/models/agent.rb
- app/models/user.rb
- spec/requests/api_authentication_spec.rb
Côté RDV-Insertion il faudrait que l'on puisse à certains moments vérifier que les identifiants de session RDV-Solidarités sont valides.
Pour cela on veut utiliser l'endpoint généré par `devise_token_auth` `GET api/v1/auth/validate_token`.
Cependant le controller responsable de cette action hérite de `DeviseController`, ce qu'il fait que la requête passe par l'`ApplicationController` et la méthode `sentry_user` raise à l'appel de l'expression `current_agent || current_user` (voir https://github.com/lynndylanhurley/devise_token_auth/issues/1286).
Du coup je `rescue` cette méthode en cas d'erreur et j'ai ajouté un test à cet endpoint.
> fix(api): Use validate token endpoint

- app/views/layouts/mailer.html.slim
- app/views/mailers/admins/organisation_mailer/organisation_created.html.slim
- app/views/mailers/agents/absence_mailer/absence_created.html.slim
- app/views/mailers/agents/absence_mailer/absence_destroyed.html.slim
- app/views/mailers/agents/absence_mailer/absence_updated.html.slim
- app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_created.html.slim
- app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_destroyed.html.slim
- app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_updated.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_cancelled.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_created.html.slim
- app/views/mailers/agents/rdv_mailer/rdv_date_updated.html.slim
- app/views/mailers/common/_rdv_cancellable.html.slim
- app/views/mailers/users/file_attente_mailer/new_creneau_available.html.slim
- app/views/mailers/users/rdv_mailer/rdv_cancelled.html.slim
- app/views/mailers/users/rdv_mailer/rdv_created.html.slim
- app/views/mailers/users/rdv_mailer/rdv_date_updated.html.slim
- app/views/mailers/users/rdv_mailer/rdv_upcoming_reminder.html.slim
- config/locales/mailers.fr.yml
- db/schema.rb
Il est surprenant d'avoir un morceau du corps de message dans le layout. Cette PR propose de placer la fin du message dans le corps des messages, comme pour le bonjour.
Cela fait de la duplication, mais il faut sans doute avoir une autre approche que celle de mettre les morceaux dans le layout
> Harmonise la fin du message de template

- spec/lib/phone_number_validation_spec.rb
- spec/models/concerns/expiration_spec.rb
- spec/models/concerns/recurrence_concern_spec.rb
⚠️ Merge #1966 first. It’s not directly related, but it would conflict. The first commit is the same; it’s better to only review the other two commits.
We sometimes used shared_examples wrongly in rspec, along with `it_behaves_like`. `it_behaves_like` doesn't support multiple contexts in one call; it needs to be called once for each class. `RecurrenceConcernSpec` did run the multiple contexte internally, but `ExpirationSpec` and `PhoneNumberValidationSpec` only ran the tests for the first class. Additionally ExpirationSpec did fail for PlageOuverture.
> Fix uses of shared examples in specs

- app/blueprints/organisation_blueprint.rb
- app/models/organisation.rb
- app/models/webhook_endpoint.rb
Pour le bon fonctionnement de RDV-Insertion nous avons besoin des infos relatives aux organisations, notamment le numéro de téléphone et l'adresse email.
Cette PR configure l'envoi de webhooks au moment des changements sur une organisation (sur `/admin/organisations/:id/edit`) pour que l'on puisse mettre à jour instantanément les infos de l'organisations sur RDV-Insertion.
> feat(webhooks): send webhook on organisations updates

- bin/setup
We use foreman for `make run` but it’s not installed by default.
We _could_ add it to the :development section of the Gemfile and it probably would work, however the foreman developers [explicitly advise against it](https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman).
> Install foreman in bin/setup

- app/services/slot_builder.rb
@yaf est-ce que tu sais pourquoi ligne 75 on utilisait `include?`, mais lignes 76 et 77 on utilisait `cover?`?
----
```
DEPRECATION WARNING: Using `Range#include?` to check the inclusion of a value in a date time range is deprecated. It is recommended to use `Range#cover?` instead of `Range#include?` to check the inclusion of a value in a date time range. (called from first_range at /Users/nicolas/Documents/rdv-solidarites.fr/app/services/slot_builder.rb:69)
DEPRECATION WARNING: Using `Range#include?` to check the inclusion of a value in a date time range is deprecated. It is recommended to use `Range#cover?` instead of `Range#include?` to check the inclusion of a value in a date time range. (called from remaining_range at /Users/nicolas/Documents/rdv-solidarites.fr/app/services/slot_build …
```
> Fix Range#include? being deprecated for date time ranges

- app/views/search/_creneaux.html.slim
Limite l'affichage des noms d'agents dans l'affichage de créneau coté usager.
> Fix dont display agent name

- Makefile
Pour créer un point visuel de reprise dans l'arbre Git. Mon espoir, c'est de simplifier les retours en arrière.
> crée un tag au moment de merge recette sur prod

- app/webpacker/stylesheets/_variables.scss
- app/webpacker/stylesheets/administrate/base/_forms.scss
- app/webpacker/stylesheets/administrate/components/_flashes.scss
- app/webpacker/stylesheets/administrate/library/_variables.scss
- babel.config.js
Corrige des warnings lors de la précompilation js et css:
Sass:
```
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($fa-li-width * 5, 4) or calc($fa-li-width * 5 / 4)
More info and automated migrator: https://sass-lang.com/d/slash-div
```
Il en reste une partie dans FontAwesome, qui sera corrigée dans une mise à jour future
Babel:
```
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config. …
```
> Corrige des warnings de rake assets:precompile

- app/helpers/paper_trail_helper.rb
- app/models/rdv.rb
- app/views/admin/rdvs/show.html.slim
- app/views/admin/versions/_version.html.slim
- config/locales/models/rdv.fr.yml
- config/locales/models/rdvs_user.fr.yml
fixes #1970
Je suis assez mal à l’aise avec `paper_trail_helper` (et dans une moindre mesure `PaperTrailAugmentedVersion`). Je ne suis pas certain de ce qui me dérange, j’ai l’impression que c’est un peu un hack.
Ça ressemble à ça:
> Save notifications changes in rdv paper_trail versions

- app/models/rdv.rb
- app/models/user.rb
- app/services/rdv_start_coherence.rb
- app/services/rdvs_overlapping.rb
- spec/form_models/admin/rdv_search_form_spec.rb
Encore du nettoyage, mais sujet à débat. En gros, la plupart de ces scopes (il y en a d’autres un peu partout, par exemple `User#within_organisation`) peuvent être remplacés par un `join/where` ou un `merge` à l’appel. Je pense qu’ils n’apportent pas grand chose, sinon du bruit et des bugs.
> Remove useless scopes

- Procfile.dev
J'avais des soucis avec le `./bin/webpack-dev-server`, j'ai lu quelque part que l'on pouvait aussi utiliser la commande `./bin/webpack --watch`. En essayant, mes problèmes ont disparu...  C'est un peu magique, et ça me fait bizarre de pas savoir pourquoi, et je n'ai pas envie de passer plus de temps sur le sujet pour l'instant...
> essaie une autre façon de faire tourne le webpack

- app/models/absence.rb
- app/models/plage_ouverture.rb
- spec/models/concerns/recurrence_concern_spec.rb
Close https://sentry.io/organizations/rdv-solidarites/issues/2872600804/?project=1811205&query=is%3Aunresolved
Il y avait un fonctionnement en erreur : 
- affichage d'un créneau disponible dans plusieurs mois
- erreur 500 en cliquant dessus
Lorsque l'on cherche un créneau avec comme date de début de _range_ la date de fin d'une récurrence sur une plage d'ouverture, cette plage n'est pas prise en compte.
Cette PR inclue la plage pour le calcul de créneau.
Directement en production, car ça crée des difficultés pour certains agents pour la prise de RDV.
Nous aurions sans doute gagné à mieux lire [la doc sur la gestion des bordures dans les requêtes de TSRange](https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-IO)
> :rocket: Inclut la fin de récurrence

- app/views/admin/creneaux/agent_searches/index.html.slim
Corrige un des retours du 18 janvier à propos de l'affichage du filtre des équipes lorsqu'il n'y en a aucune de configurée
https://doc.rdv-solidarites.fr/guide-utilisation/pour-un-referent/reunions-referentes/reunion-referentes-du-18-janvier-2022#en-production-jeudi-20
> masque le filtre équipe si aucune équipe

- app/controllers/api/v1/organisations_controller.rb
- app/models/organisation.rb
- app/services/users/geo_search.rb
- spec/requests/api/v1/organisations_request_spec.rb
- spec/services/users/geo_search_spec.rb
Lorsque l'on passe une adresse (département, ville et/ou rue) au service `GeoSearch`, on pouvait jusqu'à présent récupérer [les organisations attribués aux secteurs](https://github.com/betagouv/rdv-solidarites.fr/blob/0c2de800b23162f4149677eaa82c51ebcb130a10/app/services/users/geo_search.rb#L10) qui comprennent la zone de l'adresse. 
Cependant on récupère toutes les organisations attribués à tous les secteurs qui comprennent cette zone, sans distinction de pertinence sur ces organisations.  Cette PR ajoute cette distinction.
(NB: cette feature n'est pas en lien avec [les nouveaux problèmes rencontrés par le 64 sur la sectorisation](https://mattermost.incubateur.net/betagouv/pl/igicn7zn57n58jn7ifrqo6mgbh))
Un exemple concret est plus parlant, ici nous prenons le cas du 64 (ce cas est …
> feat(geosearch): Retrieve most relevant organisations

- app/controllers/admin/territories/agents_controller.rb
- spec/controllers/admin/territories/agents_controller_spec.rb
Corrige un des retours du 18 janvier à propos de doublon dans la liste des agents sur le formulaire de création d'équipe.
https://doc.rdv-solidarites.fr/guide-utilisation/pour-un-referent/reunions-referentes/reunion-referentes-du-18-janvier-2022#en-production-jeudi-20
> search territory agents without duplicate

- app/form_models/agent_creneaux_search_form.rb
- db/schema.rb
- spec/form_models/agent_creneaux_search_form_spec.rb
Corrige un des retours du 18 janvier à propos de la recherche de créneau en combinant les agents et les équipes dans les filtres
https://doc.rdv-solidarites.fr/guide-utilisation/pour-un-referent/reunions-referentes/reunion-referentes-du-18-janvier-2022#en-production-jeudi-20
> combine agents et équipes pour la recherche

- app/controllers/search_controller.rb
- app/services/search_context.rb
- app/views/search/_banner.html.slim
- app/views/search/_creneau_selection.html.slim
- app/views/search/_creneaux.html.slim
- app/views/search/_lieu_selection.html.slim
- app/views/search/_motif_selection.html.slim
- spec/controllers/search_controller_spec.rb
- spec/features/users/user_can_be_invited_spec.rb
- spec/services/search_context_spec.rb
Dans cette PR je change le fonctionnement du `SearchContext` pour me rapprocher de ce qui se fait actuellement sur la search "native" de RDV-Solidarités.
Lorsqu'on est invité, on récupère les motifs disponibles pour les coordonnées géographiques présentes dans l'url (lorsque celles-ci sont présentes). Lorsqu'aucun motif n'est disponible (ce qui peut notamment arriver lorsque les coordonnées géographiques n'ont pas pu être retrouvées et placées dans l'url), on fallback sur tous les motifs de toutes les organisations sur lesquelles on a invité l'utilisateur (un array d'organisation ids est passé en ce sens dans l'URL).
J'ajoute également la possibilité de filtrer les motifs en envoyant un paramètre `motif_search_terms` qui cherchera ce terme dans les motifs disponibles (dans le but de …
> refactor(invitations): Update search context logic

- app/form_models/admin/edit_rdv_form.rb
refs #2028
La bonne façon de faire nécessite d’ajouter une validation d’unicité sur RdvsUsers (et sur AgentsRdvs, tant qu’à faire), d’abord dans ActiveRecord, et surtout en base. Par contre:
* la validation d’unicité dans ActiveRecord ne fonctionne pas de façon satisfaisante, c’est un problème connu de Rails. En gros, il faut se baser sur la contrainte en base et faire du code autour :)
* il faut nettoyer la baddata en base avant de rajouter la contrainte
* mais vu ce bug, on a quelques centaines d’erreurs en base, et ça continue d’arriver; je ne peux donc pas nettoyer à la main puis mettre le fix et la migration en prod en même temps. Cette PR consiste donc à fermer le robinet à baddata.
> 🚀 Prevent duplicate assignment in rdv edit form

- config/locales/models/rdvs_user.fr.yml
Corrige un petit loupé dans le label des notifications
avant :
après : 
> affiche correctement le label

- app/helpers/rdvs_helper.rb
- spec/helpers/rdvs_helper_spec.rb
À l'annulation d'un RDV passé, nous affichons aujourd'hui un message de confirmation. Ce n'est pas nécessaire
Cette PR permet de modifier un RDV passé sans avoir de message de confirmation.
> annule un RDV passé sans message de confirmation

- app/controllers/admin/creneaux/agent_searches_controller.rb
Close #2020 
Lors de la modification sur l'affichage des créneaux coté agent, nous avons cassé la duplication de RDV. Cette PR répare cette duplication pour qu'elle copie aussi le contexte.
> :rocket: Duplique le contexte d'un RDV

- app/models/agents_rdv.rb
- app/models/rdvs_user.rb
- db/migrate/20220124110241_make_rdvs_users_unique.rb
- db/schema.rb
followup #2034, fixes #2028
Concrètement, la validation en ruby ne sert pas à grand chose: Rails ne gère par correctement la validation d’unicité avec les `nested_attributes`. L’intérêt de faire passer cette PR en 🚀 est surtout de faire passer la migration (et de s’assurer qu’elle n’échoue pas) indépendamment du reste de la recette.
Vu que la validation est sur une contrainte de DB, s’il y a une erreur, ce sera une 500; cependant côté frontend, en principe, on ne peut pas envoyer ce genre de données. C’est acceptable pour le moment. J’ai bien envie d’améliorer le formulaire de modification (et un jour de création) de Rdv, de toute façon.
> 🚀 Prevent RdvsUsers and AgentsRdvs duplicates with DB constraints

- app/controllers/admin/territories/agents_controller.rb
- app/models/territory.rb
- app/views/admin/territories/agents/index.html.slim
- spec/controllers/admin/territories/agents_controller_spec.rb
fixes #2021
Also make sure Admin::Territories::AgentsController#index and #search are consistent.
ℹ️ I’m starting to use `q` instead of `term` or `search_term`; it’s the [same thing in select2](https://select2.org/data-sources/ajax), and I find it looks better when using #index.
> Fix duplicates in admin/territories/:id/agents

- app/services/search_context.rb
- app/views/search/_banner.html.slim
- app/views/search/_creneau_selection.html.slim
- app/views/search/_lieu_selection.html.slim
- app/views/search/_motif_selection.html.slim
Je précise le type de motif (sur place ou par téléphone) quand un motif est choisi.
Pour l'instant si la personne est redirigé vers la sélection du lieu directement et que le motif est `RSA Orientation`, elle n'a aucun moyen de savoir s'il s'agit d'un RDV sur place ou téléphonique.
> feat(invitations): Precise location type when a motif is selected

- app/models/concerns/text_search.rb
- spec/models/concerns/text_search_spec.rb
fixes #2047. On ne peut pas combiner la recherche sur la colonne `:email` avec la recherche full-text, puisque ça perd le `ranking`.
Par ailleurs, ce changement signifie qu’on ne peut plus rechercher un `@` qui serait dans un champ autre que l’email.
#2047 was introduced in 120ce67a95358d82a623d814921601e66f57ce03
Avant:
Après:
AVANT LA REVUE
REVUE
> Respecter le tri de la recherche texte dans les résultats

- app/models/lieu.rb
- app/models/motif.rb
- app/services/search_context.rb
On va laisser la possibilité de passer un `lieu_id` dans l'url d'invitation d'un usager.
Lorsque celui-ci est présent, les motifs disponibles ne doivent correspondre qu'aux motifs qui sont rattachés à ce lieu par des plages d'ouvertures. Cette PR fait ce lien, qui était jusqu'à présent fait seulement sur l'organisation du lieu.
> refactor(invitations): Link invitation matching motifs to lieu

- app/models/concerns/recurrence_concern.rb
- spec/models/concerns/recurrence_concern_spec.rb
Close #2055 
La dernière occurrence d'une absence récurrente n'était pas prise en compte dans le calcul de créneau. La méthode `in_range` prend un format `DateTime` et la fin d'occurrence était calculé sur le début de la dernière journée.
Cette PR précise qu'il la fin de journée, pour inclure cette journée dans la liste des occurrences.
AVANT LA REVUE
REVUE
> :rocket: Précise la fin de journée pour la fin de récursion

- app/controllers/admin/slots_controller.rb
- app/services/search_creneaux_for_agents_service.rb
- app/views/admin/creneaux/agent_searches/index.html.slim
- app/views/admin/slots/_slots.html.slim
- app/views/admin/slots/index.html.slim
- spec/controllers/admin/slots_controller_spec.rb
fix https://sentry.io/organizations/rdv-solidarites/issues/2872600804/?project=1811205&query=is%3Aunresolved
Dans cette PR, je commence à modifier la notion de `next_availability` pour que ça corresponde au prochain créneau après la période analysée.
J'ai également ajouté quelques commentaires pour expliquer ce qu'il se passe à certains endroits et suggéré des évolutions.
AVANT LA REVUE
REVUE
> :rocket: fix le bug du créneau suivant

- app/views/admin/creneaux/agent_searches/index.html.slim
Avec les changements apportés par #2103 , il y a des cas où les prochains créneaux ne sont plus affichés
Les modifications nous font utiliser uniquement les créneaux calculés sur la semaine commençant à la date saisie. Parfois, le prochain créneau est plus éloigné.
Ce bug n'est pas visible s'il n'y a qu'un lieu qui propose ce motif. C'est visible seulement dans cette page où on liste les lieux.
Après la correction : 
AVANT LA REVUE
REVUE
> :rocket: Affiche le premier prochain créneau

- app/views/admin/territories/agents/index.html.slim
- app/views/admin/territories/teams/index.html.slim
It’s used in motif filters, not anywhere else
AVANT LA REVUE
REVUE
> 🚀 Remove unneeded css class js-search-and-filter-form

- app/helpers/application_helper.rb
- config/locales/models/rdvs_user.fr.yml
Suite de #2039:
Dans `paper_trail_helper.rb`, on utilise pour les `rdv_users` `human_attribute_value`, qui a besoin que la clé de localisation (dans le `.yml`) soit au pluriel. Par cohérence, autant utiliser `human_attribute_value` aussi dans `boolean_attribute_tag`.
`boolean_attribute_tag` n’est utilisé que dans _notification_overrides.html.slim, ça ne devrait donc rien casser ailleurs.
Demande de C. Beauvois, 1 févr. 2022 à 09:46
Avant:
Après:
AVANT LA REVUE
REVUE
> 🚀 Corrige l’affichage des notifications par usager dans l’historique Rdv

- app/models/concerns/text_search.rb
followup #2051
Fixes https://sentry.io/organizations/rdv-solidarites/issues/2975968713/events/881dd3d7c8d840bd9df3e8fe1de07570/?project=1811205&query=is%3Aunresolved
In Admin::UsersController#index, we merge the text search query with the policy scope, that joins with organisations. Organisations have an email, and then the column is ambiguous 💥
AVANT LA REVUE
REVUE
> 🚀 Fix user search by email

- app/policies/agent/agent_policy.rb
- spec/policies/agent/agent_policy_spec.rb
Les policies des agents des services secrétariats sont gérés différemment des autres.
J’ai hésité à faire une subquery de la query telle qu’elle était écrite précédemment, je trouve ça dommage de référencer la table de jointure. Idéalement, je voudrais écrire quelque chose du genre `Agents.where(organisations: current_agent.organisations)`.
D’un autre côté, c’est plus performant comme ça, et comme c’est une policy utilisée à beaucoup d’endroits par tous les agents de secrétariat, on y gagne. Je crois.
Close #1998
AVANT LA REVUE
REVUE
> Empêche les doublons dans les listes d’agents pour les secrétaires

- config/environments/development.rb
Ça ressemble à ça:
Par contre! Ça ne fonctionne qu’avec les templates `.erb`. Il y a une PR en cours pour les `.slim`, mais manifestement ce n’est pas urgent. Cela dit, ça ne coûte rien.
AVANT LA REVUE
REVUE
> Rails 6.1: Activer annotate_rendered_view_with_filenames en development

- Gemfile
- Gemfile.lock
- Makefile
- config/environments/test.rb
On peut maintenant faire `bundle exec spring rspec` pour que les specs démarrent plus vite. Sur ma machine, le temps pour lancer un test passe d'environ 3s à 0.4s. ⚡ 
Dans certains cas très rares (ça fait quelques années que j'ai pas vu ça), il se peut que le rechargement se passe mal, et que les specs se mettent à se comporter de manière bizarre. Dans ce cas il faut faire un `spring stop` pour que les choses redeviennent normales. Dans la pratique, ça arrive surtout si on modifie des objets globaux (classes, constantes) de manière inhabituelle dans le code.
REVUE
> Accélération du lancement des specs

- app/models/concerns/human_attribute_value.rb
- spec/models/concerns/human_attribute_value_spec.rb
fixes #2135
broken in 511d05d26c6959af23c9434c93703520f3d1e3a8 (#2114)
AVANT LA REVUE
REVUE
> Corrige l’affichage des notifications désactivées sur un Rdv

- app/helpers/paper_trail_helper.rb
- app/models/absence.rb
- app/models/agent.rb
- app/models/lieu.rb
- app/models/organisation.rb
- app/models/plage_ouverture.rb
- app/models/rdv.rb
- app/models/team.rb
- app/models/user.rb
- app/policies/agent/absence_policy.rb
- app/policies/agent/admin_policy.rb
- app/policies/agent/motif_policy.rb
- app/policies/agent/rdv_policy.rb
- app/policies/default_agent_policy.rb
- app/presenters/paper_trail_augmented_version.rb
- app/views/admin/absences/edit.html.slim
- app/views/admin/agent_roles/edit.html.slim
- app/views/admin/lieux/edit.html.slim
- app/views/admin/plage_ouvertures/show.html.slim
- app/views/admin/rdvs/show.html.slim
- app/views/admin/territories/teams/edit.html.slim
- app/views/admin/users/show.html.slim
- app/views/admin/versions/_resource_versions_row.html.slim
- spec/presenters/paper_trail_augmented_version_spec.rb
Il n’y a pas d’issue! C’est suite à une discussion d’hier, et un peu de nettoyage en passant. Cela dit, ça touche du doigt les réécritures des policies (argh) et la suite de #2114 pour les retouches de design sur la page de détail des Usagers.
fixes #2144
AVANT LA REVUE
REVUE
> Gestion de l’historique pour Absence, Lieu, PlageOuverture

- app/models/concerns/benign_errors.rb
- app/views/application/_model_errors.html.slim
Il y a un problème d'affichage actuellement lorsque l'on cré un usager avec le même prénom, nom et date de naissance ET avec la même adresse email. L'email est un élément discriminant, il est unique. Ce n'est pas nécessaire d'afficher le warning en même temps. De plus, il manquait un `html_safe` sur l'affichage du warning.
Avant :
Après (avec uniquement l'alerte sur le mail existant, même si le nom, prénom et date de naissance sont aussi identitque) 
Après (avec uniquement le warning sur le nom, prénom et date de naissance)
AVANT LA REVUE
REVUE
> affiche les warnings et erreur correctement

- app/webpacker/stylesheets/components/_lieux.scss
Les derniers déploiements en production ont échoué (`rake assets:precompile` en RAILS_ENV=production, je ne sais pas trop pourquoi ça passe en développement.)
Followup #2125
AVANT LA REVUE
REVUE
> Fix asset-precompile in production

- yarn.lock
En faisant la mise à jour de patch de webpack-dev-server, ça permet de mettre à jour node-forge, pour lequel on a 3 warnings de sécurité en ce moment.
REVUE
> Nettoyage de certains warnings de sécurité dependabot

- app/services/slot_builder.rb
- spec/services/slot_builder_spec.rb
Les délais de réservations sont à prendre en compte uniquement coté
usager.
AVANT LA REVUE
REVUE
> calcul les créneaux sans min booking delay

- app/controllers/lieux_controller.rb
- app/lib/lapin/range.rb
- app/models/rdv.rb
- app/services/concerns/users/creneaux_search_concern.rb
- app/services/off_days.rb
- app/services/search_context.rb
- app/services/slot_builder.rb
- spec/controllers/lieux_controller_spec.rb
- spec/controllers/search_controller_spec.rb
- spec/factories/motif.rb
- spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
- spec/lib/lapin/range_spec.rb
- spec/models/file_attente_spec.rb
- spec/services/next_availability_service_spec.rb
- spec/services/off_days_spec.rb
- spec/services/slot_builder_spec.rb
- spec/services/users/creneau_search_spec.rb
- spec/services/users/creneaux_search_spec.rb
- spec/spec_helper.rb
Close #2005 
Nous ne prenions pas en compte les délais min et max configuré dans le motif au moment du calcul de créneau.
Il y a plusieurs façons de le prendre en compte. J'ai opté pour la modification de la période de recherche de créneau (déplacement des bornes en fonction de la configuration du motif). C'es ce qui me semble le plus optimum.
Nous pourrions imaginer que cette opération soit réalisé avant, en dehors du calcul de créneau, mais je crois le code pas assez nettoyer encre... et ça permet d'avoir une vue d'ensemble comme ça.
AVANT LA REVUE
REVUE
> Considère le délai min et max du motif

- spec/features/agents/agent_can_create_rdv_collectif_spec.rb
J'avais un test rouge, peut-être à cause de l'heure ?... Je me prenais une erreur sur le fait de ne pas pouvoir créer un RDV dans le passé. Là, au moins, c'est figé :)
AVANT LA REVUE
REVUE
> précise la date et l'heure pour le test du RDV-Collectif

- scripts/migrate_cnfs_to_different_organisations.rb
Il y a un besoin assez fort pour l'expérimentation des cnfs de segmenter les données : c'est ressorti dans quasiment tous les entretiens que les cnfs n'étaient pas à l'aise que les données personnelles des usagers soient accessibles pour tous les cnfs de l'expérimentation. Par ailleurs, ça nous a confirmé que pour le vrai lancement, on voudra une organisation rdv solidarité par structure cnfs (qui sont généralement des petites équipes, et souvent un seul cnfs).
Pour que l'expérience se passe bien, on a aussi besoin de continuité des données : certaines cnfs ont entré de nombreux lieux, et veulent pouvoir continuer à les utiliser, d'autres ont des plages d'ouvertures très détaillées, et elles veulent aussi garder leur historique de rdev
J'ai manuellement créé les nouvelles organisations, …
> Segmentation des cnfs dans des organisations différentes

- app/views/welcome/welcome_agent.html.slim
- spec/features/accessibility/accueil_mds_spec.rb
- spec/features/accessibility/user_pages_spec.rb
- spec/spec_helper.rb
Je crois que ce bouton ne sert à rien en production, à part nous envoyer quelques emails à traiter, en plus des autres...
Avant
après
J'en ai profité pour ajouter un test sur l'accessibilité de cette page.
AVANT LA REVUE
REVUE
> empêche la création de la première orga en autonome

- config/initializers/devise.rb
This fixes this warning at launch:
```
DEPRECATION WARNING: Initialization autoloaded the constant CustomDeviseTokenGenerator.
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload CustomDeviseTokenGenerator, for example,
the expected changes won't be reflected in that stale Class object.
This autoloaded constant has been unloaded.
In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:
Rails.application.reloader.to_prepare do
end
That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run …
```
> Fixup CustomDeviseTokenGenerator initialization for zeitwerk autoloading

- spec/spec_helper.rb
- spec/support/select2_spec_helper.rb
Cette spec échouait aléatoirement sur la CI. Le fix utilise le fait que si on fait un expect sur un élément, capybara attendra et réessayera si l'élément n'est pas trouvé tout de suite, ce qui est plus fiable que d'ajouter des sleep et de croiser les doigts pour qu'ils durent assez longtemps.
La suppression de la ligne sur chromedriver n'est pas directement liée à cette spec, mais elle empêche de faire tourner les specs en local si on n'a pas chrome 97. J'espère que ça va passer sur la CI, si ce n'est pas le cas il faudra peut-être faire une manip.
REVUE
> Rendre une spec plus fiable

- Gemfile
- Gemfile.lock
En creusant un peu après avoir fait passer la pr pour la faille de sécurité de cette gem, je me suis rendu compte qu'elle est inutilisée. Moins de code, c'est moins de problèmes.
REVUE
> Supprimer une gem inutilisée

- app/form_models/merge_users_form.rb
- spec/features/agents/users/agent_can_merge_users_spec.rb
Fix pour https://sentry.io/organizations/rdv-solidarites/issues/3069215539/?environment=production&project=1811205&query=is%3Aunresolved
Pour les attr_accessors qui sont définis de manière statique, il vaut mieux rendre tous les champs accessibles. Les champs qui ne sont pas activés seront ensuite filtrés par `#available_attributes`, et n'apparaitront pas dans le formulaire.
REVUE
> Fix pour la fusion d'usagers

- app/mailers/application_mailer.rb
- app/mailers/custom_devise_mailer.rb
- app/services/notifiers/rdv_upcoming_reminder.rb
- app/sms/application_sms.rb
- config/initializers/delayed_job.rb
refs #2154
~~à tester sur la review app: ~~
~~* est-ce que les jobs sont bien dépilés en parallèle?~~
~~* est-ce que ça consomme plus de mémoire?~~
Par ailleurs, il y a de mémoire un problème pour l’accès au dashboard de super_admin/delayed_jobs sur les review apps, il va peut-être falloir régler ça en premier.
Edit: je n’ai pas réussi à faire marcher delayed_job avec plusieurs workers; une autre piste sera de faire tourner plusieurs instances scalingo, chacune par queue. En attendant, on peut aussi faire tourner plusieurs instances de `jobs`, tout simplement.
Ce n’est pas (plus) ce que tente de faire cette PR: j’ajoute simplement deux autres noms de queues, `:sms_low` et `:mailers_low`, avec une moindre priorité. En principe, ça devrait permettre aux autres jobs de ne pas attendre 20 …
> Add job workers

- app/views/admin/stats/index.html.slim
Close #2218 
Suppression du lien de téléchargement du fichier de stats individuel. Nous avons vocation à réduire la possibilité de sortie des données. Dans quelque temps cet export ne sera possible pour certains profiles. Autant le supprimer (surtout s'il n'était plus à jour et ne fonctionnait pas :))
avant
après
AVANT LA REVUE
REVUE
> Supprime le lien de téléchargement de statistique personnel

- app/models/agent.rb
- app/views/admin/motifs/_form.html.slim
- app/views/admin/motifs/show.html.slim
- app/views/admin/organisations/setup_checklists/show.slim
- db/seeds.rb
Voir #2243 
- le premier commit ajoute des CNFS au seed pour faciliter les tests
- le deuxième commit est un nettoyage de #2206 pour continuer dans cette direction, et indiquer que ce genre de toggles devra être modifié à long terme. Il est probable qu'ils soient supprimés lorsqu'on ouvre le deuxième palier cnfs (voir l'issue). J'espère que d'ici là on aura un assez bon onboarding pour les cnfs pour que la complexité supplémentaire ne soit pas un problème.
- le troisième commit fait les modifications de l'interface
> Cacher la réservation en ligne pour les CNFS

- app/models/rdv.rb
- spec/factories/rdv.rb
- spec/models/rdv_spec.rb
Le Var nous a signalé qu'un usager a pu prendre un RDV sur un motif non ouvert à la réservation en ligne.
Après enquête, il se trouve que c'est l'agent qui a créé le RDV, mais que l'usager l'a « modifié ».
C'est en fait le mécanisme de file d'attente qui a proposé à l'usager un créneau plus tôt (mais avec une autre agent).
Cette PR propose de restreindre le mécanisme de file d'attente au RDV dont le motif est ouvert à la réservation en ligne.
AVANT LA REVUE
REVUE
> Empeche acces file attente pour motif non reservable en ligne

- app/views/admin/users/_responsible_form_fields.html.slim
Le tel est souvent l'élément de communication le plus utilisé et
renseigné.
avant
après
AVANT LA REVUE
REVUE
> Renseigne le tel avant le mail dans la fiche usager

- app/models/plage_ouverture.rb
- app/models/rdv.rb
- spec/models/plage_ouverture_spec.rb
- spec/models/rdv_spec.rb
Nous avions mis en place un système où nous regardions le recouvrement
d'occurrence et non uniquement les plages d'ouvertures (voir
https://github.com/betagouv/rdv-solidarites.fr/commit/9411317abf4f86ed0e58278a15b8c10bbd512dcd).
L'idée, c'était de ramener la vérification qui se faisait au niveau de
l'affichage dans le RDV, au moment de la validation.
Mais nous n'avions pas vérifié l'usage qui était fait des plages
d'ouvertures qui recouvre. Or, elles sont utilisées pour construire le
message d'erreur et vérifier si c'est dans le scope (pourquoi ?)...
Nous reprenons ici pour utiliser les occurrences pour filtrer les plages
d'ouvertures et continuons à envoyer des plages d'ouvertures.
Close https://sentry.io/organizations/rdv-solidarites/issues/3098486121/?project=1811205&query=is%3Aunresolv …
> Selectionne les plages d'ouvertures et non des occurrences

- app/presenters/displayable_user_presenter.rb
- spec/presenters/displayable_user_presenter_spec.rb
En ajoutant le `case_number` et `address_details` nous avons oublié de
les ajouter au `DisplayableUserPresenter`. Cette classe est
principalement (uniquement ?) utilisé dans l'outil de fusion d'usager.
Close https://sentry.io/organizations/rdv-solidarites/issues/3107074499/?project=1811205&query=is%3Aunresolved
AVANT LA REVUE
REVUE
> Ajout le dossier et détail adresse a DisplayableUser

- app/controllers/admin/territories/rdv_fields_controller.rb
- app/models/territory.rb
- app/policies/configuration/territory_policy.rb
- app/views/admin/rdv_wizard_steps/step2.html.slim
- app/views/admin/rdvs/_rdv.html.slim
- app/views/admin/rdvs/_rdv_details.html.slim
- app/views/admin/rdvs/_short_rdv.html.slim
- app/views/admin/territories/rdv_fields/edit.html.slim
- app/views/admin/territories/show.html.slim
- config/locales/views/configuration.yml
- config/locales/views/rdv.fr.yml
- config/routes.rb
- db/migrate/20220317141436_add_enable_context_field_to_territory.rb
- db/schema.rb
- spec/controllers/admin/territories/rdv_fields_controller_spec.rb
- spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
Je suis parti sur une nouvelle interface pour la gestion de l'interface RDV. J'aurais peut-être pu l'ajouter à l'interface de configuration de la fiche usager :thinking:. J'ai hésité, et ça me parait plus simple comme ça. Si nous voulons les fusionner, ça sera toujours faisable plus tard.
Le contexte est affiché à 4 endroits : 
- le formulaire de création d'un RDV ;
- la fiche RDV (le show) ;
- la liste des RDV (avec détails) ;
- l'historique des RDV d'un usager.
Close #2233 
AVANT LA REVUE
REVUE
> Paramètre l'affichage du contexte d'un RDV

- app/views/admin/rdvs/show.html.slim
Dans la fiche d'un RDV, nous affichions pour chaque usager du RDV une
liste des 5 derniers RDV en mode raccourcis.
Nous n'avons pas vraiment besoin de cette liste, et elle va nous gêner
pour les RDV collectif.
C'est aussi une source de problème de performance.
close #2234
AVANT LA REVUE
REVUE
> Arrête d'afficher l'historique des RDV d'un usager

- app/controllers/admin/territories/zones_controller.rb
- app/models/territory.rb
- app/models/zone.rb
- app/policies/configuration/zone_policy.rb
- spec/services/export_zones_service_spec.rb
Signalé par Claire de Data.insertion, il y a une erreur sur l'export des secteurs dans la configuration de la sectorisation.
AVANT LA REVUE
REVUE
> Pose un scope pour l'accès aux secteurs / zones

- app/helpers/motifs_helper.rb
Les agents traitant du RSA souhaitent pouvoir configurer les motifs avec
un délai max de 3 semaines.
Les options de délais passaient de 2 semaines à 1 mois. Cette PR ajoute
l'option à 3 semaines.
close #2302
AVANT LA REVUE
REVUE
> Ajoute une option de délai de motif pour 3 semaines

- app/views/admin/agents/rdvs/index.json.jbuilder
- app/webpacker/components/calendar.js
~~Pour discussion: les problèmes de performance dans l’agenda sont dûs à l’affichage des warning d’overlap avec une plage d’ouverture.~~
---
On n’affiche plus ces warnings dans l’agenda; ils restent visible dans la vue de détail de chaque rdv.
AVANT LA REVUE
REVUE
> Ne pas afficher les warnings d’overlap avec les plages d’ouverture dans l’agenda

- app/views/admin/creneaux/agent_searches/index.html.slim
- config/locales/views/agent_searches.fr.yml
La structure de la page ne permettait pas de voir le message comme quoi
aucuns créneaux ne sont disponibles pour les critères sélectionnés.
Nous affichons maintenant un message.
Avant 
Après
close #2119
AVANT LA REVUE
REVUE
> Précise qu'aucun résultat n'a été trouvé pour les critères dans la recherche de créneau

- app/services/search_context.rb
- app/views/search/_lieu_selection.html.slim
- spec/controllers/search_controller_spec.rb
Comme pour #2298, il manquait un report de correction. Ici, c'est sur la navigation vers les créneaux suivants quand il n'y en a plus.
avant :
après :
Close #2297 
AVANT LA REVUE
REVUE
> Bloque la navigation s'il n'y a plus de créneau

- app/models/absence.rb
- spec/models/absence_spec.rb
Il y a une situtation un peu étrange où l'on peut définir une absence
sur plusieurs jours et qui se répète, ce qui cause le chevauchement de
l'absence sur elle même.
D'une manire un peu direct / radical, suggéré par Clarisse (92) lors de
la dernière réunion référente, cette PR ajoute une validation pour
empêcher la création d'une indisponibilité récurrente si elle est sur
plusieurs jours.
Close #2165
AVANT LA REVUE
REVUE
> Valide une absence sans chevauchement

- app/views/organisations/new.html.slim
- config/locales/fr.yml
- config/locales/models/organisation.fr.yml
- spec/features/accessibility/welcome_pages_spec.rb
Close #2075 
Ajoute test d'accessibilité sur la route `new_organisation_path`.
Corrige les erreurs renvoyées.
Bouton 
AVANT LA REVUE
REVUE
> Améliore accessibilité new_organisation_path

- app/mailers/custom_devise_mailer.rb
- app/views/devise/mailer/invitation_instructions_cnfs.html.erb
- app/views/devise/mailer/invitation_instructions_cnfs.text.erb
- config/locales/devise.fr.yml
- scripts/import_conseillers_numeriques.rb
Close #2311
Oooh, le joli mail d'invitation (d'après une [création originale de Matis Alves](https://docs.google.com/presentation/d/120rOre1wm_4wqHvlP61e4QnhT6snwQUilUPL-V9Lxys/edit?pli=1#slide=id.g1208040ce53_1_0) )
Mettre les 200 cnfs concernés dans le fichier `tmp/export-cnfs.csv` puis lancer :
```
scalingo run "rails runner scripts/import_conseillers_numeriques.rb" --app demo-rdv-solidarites --region osc-secnum-fr1 --file tmp/export-cnfs.csv
```
Il faudra que je mette à jour le lien pour la vidéo quand on sortira la v3.
REVUE
> Script d'import des cnfs pour la phase 4

- app/controllers/admin/rdvs_collectifs_controller.rb
- app/controllers/admin/rdvs_controller.rb
- app/form_models/admin/rdv_collectif_search_form.rb
- app/models/rdv.rb
- app/models/rdvs_user.rb
- app/views/admin/rdvs/edit.html.slim
- app/views/admin/rdvs_collectifs/_rdv.html.slim
- app/views/admin/rdvs_collectifs/edit.html.slim
- app/views/admin/rdvs_collectifs/index.html.slim
- app/views/admin/rdvs_collectifs/new.html.slim
- config/locales/models/rdv.fr.yml
- config/locales/rdvs.fr.yml
- config/routes.rb
- db/migrate/20220321103957_add_rdvs_max_participants_count_and_users_count.rb
- db/schema.rb
- spec/features/agents/agent_can_organize_rdv_collectif_spec.rb
- spec/support/select2_spec_helper.rb
Close #2188
Cette PR ajoute la possibilité de gérer les participants à un rdv collectif.
Dans l'index des rdv collectifs, on a un aperçu du nombre de participants
Comme montré lors de la réunion référente il y a quelques semaines, il est possible de faire de la sur-réservation.
Pour éviter de surcharger la base, cette PR ajoute un counter cache sur le nombre de participants. Pour éviter de faire trop d'écritures, ce counter cache n'est activé que pour les rdv collectifs (il n'est pas mis à jour pour les autres rdvs). Cette option n'étant pas disponible avec les counter-cache classiques de rails, ça a motivé l'ajout de la gem counter-culture.
Pour clarifier que ce counter cache n'est que pour les rdv collectifs, j'ai préfixé son nom, mais je ne suis pas sûr que ça soit l'option la plus …
> RDV Collectifs : limite du nombre de participants

- app/controllers/admin/invitations_devise_controller.rb
- app/policies/agent/service_policy.rb
- app/views/admin/invitations_devise/new.html.slim
- spec/controllers/admin/invitations_devise_controller_spec.rb
close #2312
Cette PR cache les services du médico-social aux cnfs au moment de l'invitation d'un nouvel agent, et évite que les cnfs puissent inviter des nouveaux agents qui pourraient avoir des rdvs.
Avant :
Après :
Pour le moment, c'est une implémentation très simpliste. On en a discuté avec Yannick, et ce fonctionnement va sans doute avoir vocation à évoluer au fur et à mesure du redécoupage des droits d'accès.
REVUE
> Restriction des invitations pour les cnfs

- app/lib/lapin/range.rb
- app/models/motif.rb
- spec/lib/lapin/range_spec.rb
- spec/models/motif_spec.rb
Un bug remonté par Data.insertion depuis la manche. La recherche de
créneau coté usager propose une date, mais en cliquant dessus, on obtient
une erreur 500. C'est au moment de retailler la période de recherche
pour la faire correspondre avec la période de réservation autorisée dans
le motif, que nous nous retrouvons à faire une période où le début et
après la fin :-/
En contrôlant sur les deux bornes, nous évitons cette situation.
Il reste que nous proposons une date alors qu'il n'y a pas de dispo car
nous passons toujours par un autre chemin pour calculer « la prochaine
disponibilité ». Une PR suivante pourrait rassembler le code de ces
services pour uniformiser le mode de calcul.
Ferme le ticket [#3036616730](https://sentry.io/organizations/rdv-solidarites/issues/3036616730/?project=181 …
> Vérifie la période de recherche de créneau l'ensemble de la période de réservation

- app/models/motif.rb
- app/models/service.rb
- app/policies/agent/service_policy.rb
- spec/controllers/admin/invitations_devise_controller_spec.rb
Fix pour https://sentry.io/organizations/rdv-solidarites/issues/3162256671
Cette erreur a été introduite dans https://github.com/betagouv/rdv-solidarites.fr/pull/2321
Le fix est de faire que le scope renvoie une relation activerecord plutôt qu'un tableau, pour qu'on puisse chaîner des appels AR normalement.
D'après mes recherches, il n'était utilisé que dans `Motifs#authorized_services`
REVUE
> Fix pour les invitations d'agents existants par des cnfs

- app/blueprints/rdv_blueprint.rb
- app/models/rdv.rb
- spec/blueprint/rdv_blueprint_spec.rb
Close #2331
Suite à la demande des reférentes ce matin (et même avant ça), on ajoute les infos relatives aux rdvs dans l'api.
Je n'ai pas trouvé dans la doc de page sur l'api des rdvs en eux mêmes. Est-ce que j'ai loupé quelque chose ?
REVUE
> Ajout des infos de rdv collectifs à l'api

- app/helpers/rdvs_helper.rb
- app/models/motif.rb
- app/models/rdv.rb
- app/views/admin/agents/rdvs/index.json.jbuilder
- app/views/admin/rdvs/_rdv_status_dropdown.html.slim
- app/views/admin/rdvs/_rdv_status_dropdown_item.html.slim
- spec/features/agents/agent_can_see_rdv_in_calendar_spec.rb
Close #2333
Avant :
Après : 
En plus de l'intitulé, et en préparation de la sortie des rdv collectifs, on affiche le nombre de participants dans l'agenda
REVUE
> Ajout du nombre de participants dans l'agenda

- app/models/lieu.rb
- config/locales/models/lieu.fr.yml
- spec/models/lieu_spec.rb
C'est sans doute pas le mieux. Je crois que nous pourrions questionner,
dans le cadre de la sectorisation, l'intérêt de récupérer la latitude et
la longitude, et donc l'intérêt de dépendre de la base adresse
nationale.
Cette PR propose simplement d'avoir un message d'erreur qui parle d'un
champ visible à l'écran plutôt que de champs cachés.
Close #2277
AVANT LA REVUE
REVUE
> Clarifie l'erreur sur la validation d'un lieu

- app/webpacker/stylesheets/components/_settings.scss
Mon œil a un peu saigné à votre de me balader sur le module de configuration.
Le `hover` est vraiment violent (inverse des couleurs) car sur un trop gros morceau, je pense et sur presque toute la zone de l'écran.
Cette PR propose de passer à un simple souligné. Je pense que c'est plus simple et tout aussi efficace.
AVANT LA REVUE
REVUE
> réduit le bruit sur le hover du module de config

- app/models/zone.rb
Aujourd'hui, si on ajoute une commune à un secteur, on ne peut pas ajouter une rue de cette commune à ce même secteur.
Je pense que  la logique derrière ça est de dire que si je sectorise un quartier en mettant les rues de ce quartier, il est normal que je ne mette pas la ville entière.
Seulement ça peut poser problème dans les cas où chaque quartier d'une ville a son secteur et la ville entière a son secteur aussi (cas du 64 avec la ville de Pau).
En effet aujourd'hui que si une personne de Pau rentre son adresse, on veut que le secteur "Pau entier" soit retrouvé dans tous les cas. 
Pour cela, il faut que ce secteur contienne: 
* Toutes les rues de Pau, parce que si la rue de l'utilisateur est retrouvée dans un des autres secteurs/quartiers de Pau, [cette …
> feat(sector): Remove existing city restriction when adding a street zone

- Gemfile
- Gemfile.lock
- app/jobs/webhook_job.rb
- spec/jobs/webhook_job_spec.rb
- spec/spec_helper.rb
Dans la liste des erreurs qui nous sont remonté lors de des envoies de
données via les webhooks, ils y en a certaines qui sont liées à une
implémentation particulière du serveur (voir [delayed_job/failed](https://www.rdv-solidarites.fr/super_admins/delayed_job/failed))
C'est le cas dans la Drôme.
En attendant une correction de leur part, nous devons faire en sorte de
réduire le bruit.
Cette PR écarte certaines erreurs. Elle devrait permettre de réduire le
nombre de ticket sentry
[#2447517267](https://sentry.io/organizations/rdv-solidarites/issues/2447517267/?project=1811205&query=is%3Aunresolved)
J'en profite pour introduire une gem pour stubber les appels externes.
AVANT LA REVUE
REVUE
> Écarte certaines erreurs d'envoie de webhook
